package migrations

import (
	"github.com/agambondan/islamic-explorer/app/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

func SeedLessons(db *gorm.DB) {
	modules := []model.LessonModule{
		{Slug: "wudhu", Title: "Tata Cara Wudhu", Description: "Belajar wudhu tahap demi tahap, lengkap dengan bacaan Arab, dalil, dan adab yang disunnahkan.", Category: "Fiqh Ibadah", Level: "Pemula", EstimatedMinutes: 8, Icon: "wudhu", Order: 1},
		{Slug: "sholat", Title: "Tata Cara Sholat", Description: "Panduan gerakan, bacaan rukun dan sunnah, lengkap dengan dalil Quran-Hadis.", Category: "Fiqh Ibadah", Level: "Pemula", EstimatedMinutes: 15, Icon: "sholat", Order: 2},
		{Slug: "adzan-iqomah", Title: "Mengenal Adzan & Iqomah", Description: "Makna, lafaz lengkap, urutan rukun, dan adab muadzin.", Category: "Fiqh Ibadah", Level: "Pemula", EstimatedMinutes: 10, Icon: "adzan", Order: 3},
		{Slug: "puasa", Title: "Fikih Puasa Ramadan", Description: "Syarat, rukun, pembatal, dan sunnah puasa, lengkap dengan contoh aplikatif.", Category: "Fiqh Ibadah", Level: "Menengah", EstimatedMinutes: 12, Icon: "puasa", Order: 4},
		{Slug: "zakat", Title: "Zakat Fitrah & Mal", Description: "Nisab, haul, dan 8 asnaf penerima zakat.", Category: "Fiqh Ibadah", Level: "Menengah", EstimatedMinutes: 12, Icon: "zakat", Order: 5},
		{Slug: "tajwid", Title: "Tajwid Dasar", Description: "Hukum nun mati/tanwin, mim mati, dan mad dengan contoh ayat.", Category: "Al-Quran", Level: "Menengah", EstimatedMinutes: 18, Icon: "tajwid", Order: 6},
		{Slug: "rukun-iman", Title: "Rukun Iman", Description: "Enam pilar keimanan dengan dalil Quran-Hadis.", Category: "Aqidah", Level: "Pemula", EstimatedMinutes: 10, Icon: "iman", Order: 7},
		{Slug: "adab-talab-ilmu", Title: "Adab Menuntut Ilmu", Description: "Etika menuntut ilmu, niat yang benar, dan keutamaan tholabul 'ilmi.", Category: "Adab", Level: "Pemula", EstimatedMinutes: 8, Icon: "book", Order: 8},
		{Slug: "tahsin-tajwid", Title: "Tahsin & Tajwid Dasar", Description: "Memperbaiki bacaan Al-Quran: makhraj, sifat huruf, hukum tajwid, dan latihan praktis.", Category: "Al-Quran", Level: "Pemula", EstimatedMinutes: 20, Icon: "quran", Order: 9},
		{Slug: "aqidah-salaf", Title: "Aqidah Salaf & Rukun Iman", Description: "Pemahaman mendalam enam rukun iman mengikuti metodologi salafus shalih.", Category: "Aqidah", Level: "Menengah", EstimatedMinutes: 15, Icon: "aqidah", Order: 10},
		{Slug: "sholat-sifat-nabi", Title: "Panduan Shalat Sesuai Sifat Nabi ﷺ", Description: "Rinci gerakan, bacaan, dan adab shalat sesuai hadis Sifat Shalat Nabi ﷺ.", Category: "Fiqh Ibadah", Level: "Menengah", EstimatedMinutes: 18, Icon: "sholat", Order: 11},
		{Slug: "dzikir-doa-harian", Title: "Dzikir & Doa Harian", Description: "Dzikir pagi-petang, doa setelah shalat, doa sehari-hari, dan wirid istiqamah.", Category: "Ibadah Harian", Level: "Pemula", EstimatedMinutes: 12, Icon: "dzikir", Order: 12},
		{Slug: "sujud-tilawah", Title: "Panduan Sujud Tilawah", Description: "Hukum, 15 ayat sajdah, tata cara di dalam & luar sholat, serta doa-doa Nabi ﷺ.", Category: "Fiqh Ibadah", Level: "Pemula", EstimatedMinutes: 10, Icon: "sholat", Order: 13},
	}
	for i := range modules {
		db.Clauses(clause.OnConflict{
			Columns: []clause.Column{{Name: "slug"}},
			DoUpdates: clause.AssignmentColumns([]string{
				"title", "description", "category", "level", "estimated_minutes", "icon", "order", "updated_at",
			}),
		}).Create(&modules[i])
	}

	var stored []model.LessonModule
	db.Find(&stored)
	bySlug := map[string]int{}
	for _, m := range stored {
		if m.ID != nil {
			bySlug[m.Slug] = *m.ID
		}
	}

	steps := []model.LessonStep{
		// ===== WUDHU =====
		{
			ModuleID:  bySlug["wudhu"],
			StepOrder: 1,
			Kind:      "rukun",
			Title:     "Niat di Hati & Membaca Bismillah",
			Body:      "**Niat wudhu** bertempat di dalam hati dan tidak dilafazkan secara lisan, karena tidak ada riwayat shahih bahwa Rasulullah ﷺ melafazkan niat saat berwudhu.\n\nHal-hal yang disunnahkan saat mengawali wudhu:\n- **Membasuh kedua telapak tangan** sebanyak tiga kali sebelum memulai.\n- **Membaca basmalah** (`Bismillah`) dengan lisan.\n- **Bersiwak** atau membersihkan gigi sebelum berwudhu.",
			Arabic:    "بِسْمِ اللَّهِ",
			Latin:     "Bismillah",
			Translation: "Dengan menyebut nama Allah.",
			Dalil:     "HR. Abu Dawud No. 101, Tirmidzi No. 25, Ibnu Majah No. 399 (Shahih): \"Tidak ada wudhu bagi orang yang tidak menyebut nama Allah padanya.\"",
			Tip:       "Hadirkan niat di dalam hati untuk bersuci dari hadas kecil, lalu ucapkan basmalah sebelum mulai membasuh.",
		},
		{
			ModuleID:  bySlug["wudhu"],
			StepOrder: 2,
			Kind:      "rukun",
			Title:     "Membasuh Wajah",
			Body:      "**Membasuh seluruh area wajah** merupakan rukun wudhu yang pertama kali dibasuh setelah berkumur dan istinsyaq.\n\nBatasan wajah yang wajib dibasuh:\n- **Secara vertikal:** Dari tempat tumbuhnya rambut kepala bagian atas hingga ujung dagu bawah.\n- **Secara horizontal:** Dari batas daun telinga kanan hingga daun telinga kiri.\n- Membasuh jenggot yang tipis hingga ke kulit, dan menyela-nyela (*takhlil*) jenggot yang lebat.",
			Dalil:     "QS. Al-Maidah: 6: \"...فَاغْسِلُوا وُجُوهَكُمْ...\" (Maka basuhlah wajahmu).",
			Tip:       "Pastikan seluruh bagian wajah dan jenggot/rambut tipis basah merata.",
		},
		{
			ModuleID:  bySlug["wudhu"],
			StepOrder: 3,
			Kind:      "rukun",
			Title:     "Membasuh Kedua Tangan hingga Siku",
			Body:      "**Membasuh kedua tangan** mulai dari ujung jari jemari hingga melewati kedua siku (*al-marafiq*).\n\nTata cara yang disyariatkan:\n- Memulai dari **tangan kanan terlebih dahulu** sebanyak 3 kali, kemudian tangan kiri 3 kali.\n- Meratakan air hingga melewati siku secara sempurna.\n- **Menyela-nyela jari jemari** (*takhlilul ashobi'*) agar air meresap ke seluruh celah jari.",
			Dalil:     "QS. Al-Maidah: 6: \"...وَأَيْدِيَكُمْ إِلَى الْمَرَافِقِ...\" (Dan tanganmu sampai ke siku); HR. Bukhari No. 159 (wudhu Utsman bin Affan).",
			Tip:       "Jangan ada doa khusus per-anggota wudhu karena tidak ada riwayat shahih dari Nabi ﷺ.",
		},
		{
			ModuleID:  bySlug["wudhu"],
			StepOrder: 4,
			Kind:      "rukun",
			Title:     "Mengusap Kepala",
			Body:      "**Mengusap seluruh kepala** satu kali usapan sesuai sifat wudhu Rasulullah ﷺ.\n\nTata cara mengusap kepala:\n- Membasahi kedua telapak tangan dengan air baru (bukan sisa membasuh tangan).\n- Menjalankan kedua telapak tangan mulai dari **bagian depan kepala (pangkal rambut) menuju tengkuk**.\n- Mengembalikan kedua telapak tangan dari tengkuk **kembali ke tempat semula** di bagian depan kepala.",
			Dalil:     "QS. Al-Maidah: 6: \"...وَامْسَحُوا بِرُءُوسِكُمْ...\" (Dan usaplah kepalamu); HR. Bukhari No. 185.",
		},
		{
			ModuleID:  bySlug["wudhu"],
			StepOrder: 5,
			Kind:      "sunnah",
			Title:     "Mengusap Kedua Telinga",
			Body:      "**Mengusap kedua telinga** dilakukan langsung setelah mengusap kepala menggunakan sisa air yang masih ada di jari jemari.\n\nTata cara mengusap telinga:\n- Memasukkan **kedua jari telunjuk** ke dalam lubang dan lekukan telinga bagian dalam.\n- Mengusap **daun telinga bagian luar** menggunakan kedua ibu jari dari bawah ke atas.",
			Dalil:     "HR. Abu Dawud No. 135, Tirmidzi No. 36 (Shahih): \"Kedua telinga termasuk bagian dari kepala.\"",
		},
		{
			ModuleID:  bySlug["wudhu"],
			StepOrder: 6,
			Kind:      "rukun",
			Title:     "Membasuh Kedua Kaki hingga Mata Kaki",
			Body:      "**Membasuh kedua kaki** hingga melewati kedua mata kaki (*al-ka'bain*).\n\nTata cara membasuh kaki:\n- Memulai dari **kaki kanan** sebanyak tiga kali, lalu dilanjutkan kaki kiri tiga kali.\n- **Menyela-nyela jari-jemari kaki** dengan jari kelingking tangan kiri.\n- Memperhatikan **bagian tumit dan lekukan mata kaki** agar tidak ada bagian yang terlewat atau kering.",
			Dalil:     "QS. Al-Maidah: 6: \"...وَأَرْجُلَكُمْ إِلَى الْكَعْبَيْنِ...\" (Dan kakimu sampai ke kedua mata kaki); HR. Bukhari No. 165: \"Celakalah tumit-tumit (yang tidak basah) dari api neraka.\"",
			Tip:       "Pastikan tumit dan lipatan mata kaki terkena air secara sempurna.",
		},
		{
			ModuleID:  bySlug["wudhu"],
			StepOrder: 7,
			Kind:      "sunnah",
			Title:     "Membaca Doa Setelah Wudhu",
			Body:      "Setelah selesai berwudhu secara sempurna dan tertib, disunnahkan menghadap kiblat lalu membaca doa **syahadat tauhid dan permohonan kesucian**.\n\nKeutamaan membaca doa setelah wudhu:\n- Dibukakan baginya **delapan pintu surga**, dan ia dapat masuk dari pintu mana saja yang ia kehendaki (HR. Muslim No. 234).",
			Arabic:    "أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ، اللَّهُمَّ اجْعَلْنِي مِنَ التَّوَّابِينَ وَاجْعَلْنِي مِنَ الْمُتَطَهِّرِينَ",
			Latin:     "Asyhadu allaa ilaaha illallaah wahdahu laa syariika lah, wa asyhadu anna Muhammadan 'abduhu wa rasuuluh. Allaahummaj'alnii minat tawwaabiina waj'alnii minal mutathahhiriin",
			Translation: "Aku bersaksi bahwa tidak ada sesembahan yang berhak disembah selain Allah semata, tidak ada sekutu bagi-Nya. Dan aku bersaksi bahwa Muhammad adalah hamba dan utusan-Nya. Ya Allah, jadikanlah aku termasuk orang-orang yang bertaubat dan jadikanlah aku termasuk orang-orang yang menyucikan diri.",
			Dalil:     "HR. Muslim No. 234 & HR. Tirmidzi No. 55 (Shahih): Dibukakan baginya delapan pintu surga.",
		},

		// ===== SHOLAT =====
		{
			ModuleID:  bySlug["sholat"],
			StepOrder: 1,
			Kind:      "rukun",
			Title:     "Takbiratul Ihram",
			Body:      "**Takbiratul Ihram** adalah rukun pembuka shalat yang menandai dimulainya shalat dan diharamkannya seluruh perbuatan di luar shalat.\n\nTata cara pelaksanaan:\n- Berdiri tegak (*qiyam*) bagi yang mampu menghadap kiblat dengan pandangan ke arah tempat sujud.\n- Mengangkat kedua tangan sejajar **pundak/bahu** atau sejajar **daun telinga** dengan jari-jemari merapat dan telapak tangan menghadap kiblat.\n- Melafazkan takbir: `Allahu Akbar` bersamaan dengan mengangkat tangan atau sesudahnya.",
			Arabic:    "اللَّهُ أَكْبَرُ",
			Latin:     "Allahu Akbar",
			Translation: "Allah Maha Besar.",
			Dalil:     "HR. Bukhari No. 735: Panduan posisi tangan dan takbir pembuka shalat.",
			Tip:       "Pastikan tumit rapat, pandangan ke tempat sujud, dan sudah berniat di hati untuk shalat tertentu.",
		},
		{
			ModuleID:  bySlug["sholat"],
			StepOrder: 2,
			Kind:      "rukun",
			Title:     "Membaca Al-Fatihah",
			Body:      "Membaca **Surah Al-Fatihah** merupakan rukun wajib pada setiap rakaat shalat, baik bagi imam, makmum, maupun shalat sendirian (*munfarid*).\n\nPetunjuk membaca Al-Fatihah:\n- Membaca doa istiftah/iftitah terlebih dahulu secara perlahan (sunnah).\n- Membaca *ta'awwudz* dan basmalah.\n- Membaca Al-Fatihah **ayat demi ayat dengan tartil**, berhenti di setiap akhir ayat.\n- Mengucapkan `Aamiin` setelah selesai membaca ayat terakhir.",
			Arabic:    "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ ۝ الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ ۝ الرَّحْمَٰنِ الرَّحِيمِ ۝ مَالِكِ يَوْمِ الدِّينِ ۝ إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ ۝ اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ ۝ صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ",
			Latin:     "Bismillahirrahmanirrahim. Alhamdu lillahi rabbil 'aalamin. Arrahmanirrahim. Maaliki yawmid diin. Iyyaaka na'budu wa iyyaaka nasta'iin. Ihdinash shirathal mustaqiim. Shirathal ladziina an'amta 'alaihim ghairil maghdhuubi 'alaihim wa ladhdhaalliin",
			Translation: "Dengan nama Allah Yang Maha Pengasih lagi Maha Penyayang. Segala puji bagi Allah, Tuhan semesta alam. Yang Maha Pengasih lagi Maha Penyayang. Yang menguasai Hari Pembalasan. Hanya kepada Engkaulah kami menyembah dan hanya kepada Engkaulah kami memohon pertolongan. Tunjukilah kami jalan yang lurus. (Yaitu) jalan orang-orang yang telah Engkau beri nikmat, bukan (jalan) mereka yang dimurkai dan bukan (pula jalan) mereka yang sesat.",
			Dalil:     "HR. Bukhari No. 756; HR. Muslim No. 395: \"Tidak sah shalatnya orang yang tidak membaca Al-Fatihah.\"",
		},
		{
			ModuleID:  bySlug["sholat"],
			StepOrder: 3,
			Kind:      "sunnah",
			Title:     "Membaca Surat Pendamping",
			Body:      "Setelah selesai Al-Fatihah pada rakaat pertama dan kedua, disunnahkan membaca **surat atau ayat Al-Quran** lainnya.\n\nAdab dan sunnah membaca surat:\n- Disunnahkan membaca surat yang lebih panjang pada shalat Shubuh dan Zhuhur, serta lebih pendek pada shalat Maghrib.\n- Membaca dengan tartil dan merenungi (*tadabbur*) makna ayat yang dibaca.",
			Tip:       "Untuk pemula, surat pendek seperti Al-Ikhlas, Al-Falaq, dan An-Nas cukup mudah untuk diamalkan.",
		},
		{
			ModuleID:  bySlug["sholat"],
			StepOrder: 4,
			Kind:      "rukun",
			Title:     "Ruku' dengan Tuma'ninah",
			Body:      "**Ruku'** dilakukan dengan membungkukkan badan hingga punggung lurus mendatar dan disertai **tuma'ninah** (diam tenang sejenak).\n\nSifat ruku' yang sempurna:\n- Mengangkat kedua tangan bertakbir saat hendak ruku'.\n- Meletakkan kedua telapak tangan di atas lutut dengan jari-jemari direnggangkan seperti mencengkeram lutut.\n- **Punggung dan kepala lurus sejajar**, tidak terlalu menunduk dan tidak mendongak.\n- Membaca tasbih ruku' minimal 3 kali.",
			Arabic:    "سُبْحَانَ رَبِّيَ الْعَظِيمِ",
			Latin:     "Subhaana Rabbiyal 'Adziim",
			Translation: "Maha Suci Tuhanku Yang Maha Agung.",
			Dalil:     "HR. Bukhari No. 816: \"Lalu ruku'lah dan tuma'ninahlah ketika ruku'.\"",
			Tip:       "Tuma'ninah berarti diam sejenak (sekitar satu kali bacaan Subhanallah) di setiap perpindahan gerakan.",
		},
		{
			ModuleID:  bySlug["sholat"],
			StepOrder: 5,
			Kind:      "rukun",
			Title:     "Iktidal dengan Tuma'ninah",
			Body:      "**Iktidal** adalah bangkit dari ruku' menuju posisi berdiri tegak kembali dengan tuma'ninah.\n\nTata cara iktidal:\n- Mengangkat kedua tangan sejajar bahu/telinga sambil mengucapkan: `Sami'allahu liman hamidah`.\n- Berdiri tegak lurus hingga seluruh persendian kembali ke tempatnya.\n- Membaca doa pujian iktidal: `Rabbana wa lakal hamd...`.",
			Arabic:    "سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ، رَبَّنَا لَكَ الْحَمْدُ",
			Latin:     "Sami'allaahu liman hamidah, Rabbanaa lakal hamdu",
			Translation: "Allah mendengar orang yang memuji-Nya. Ya Tuhan kami, bagi-Mu segala puji.",
			Dalil:     "HR. Bukhari No. 789: Bacaan imam dan makmum.",
		},
		{
			ModuleID:  bySlug["sholat"],
			StepOrder: 6,
			Kind:      "rukun",
			Title:     "Sujud dengan Tuma'ninah",
			Body:      "**Sujud** dilakukan dengan menempelkan **7 anggota sujud** ke lantai secara kokoh disertai ketenangan (tuma'ninah).\n\nTujuh anggota badan yang wajib menyentuh lantai:\n1. **Dahi sekaligus hidung**\n2. **Kedua telapak tangan** (menghadap kiblat di samping bahu/telinga)\n3. **Kedua lutut**\n4. **Ujung jari-jemari kedua kaki** (ditekuk menghadap kiblat dan tumit dirapatkan)",
			Arabic:    "سُبْحَانَ رَبِّيَ الْأَعْلَى",
			Latin:     "Subhaana Rabbiyal A'laa",
			Translation: "Maha Suci Tuhanku Yang Maha Tinggi.",
			Dalil:     "HR. Muslim No. 497: \"Tujuh anggota badan bersujud: dahi (termasuk hidung), dua telapak tangan, dua lutut, dan ujung dua kaki.\"",
		},
		{
			ModuleID:  bySlug["sholat"],
			StepOrder: 7,
			Kind:      "rukun",
			Title:     "Duduk di Antara Dua Sujud",
			Body:      "Bangkit dari sujud pertama menuju posisi **duduk iftirasy** dengan tuma'ninah sebelum melakukan sujud kedua.\n\nTata cara duduk iftirasy:\n- Bertakbir saat bangkit dari sujud.\n- Menduduki **telapak kaki kiri** yang dibentangkan, sedangkan **telapak kaki kanan ditegakkan** dengan jari-jemari ditekuk menghadap kiblat.\n- Meletakkan kedua telapak tangan di atas paha atau lutut.\n- Membaca doa permohonan ampunan dan rahmat.",
			Arabic:    "رَبِّ اغْفِرْ لِي، رَبِّ اغْفِرْ لِي",
			Latin:     "Rabbighfir lii, Rabbighfir lii",
			Translation: "Ya Tuhanku, ampunilah aku. Ya Tuhanku, ampunilah aku.",
			Dalil:     "HR. Abu Dawud No. 874 (Hasan): Bacaan duduk di antara dua sujud.",
		},
		{
			ModuleID:  bySlug["sholat"],
			StepOrder: 8,
			Kind:      "rukun",
			Title:     "Tasyahud Akhir",
			Body:      "**Tasyahud akhir** merupakan rukun shalat yang dilakukan sebelum salam pada rakaat terakhir.\n\nTata cara pelaksanaan:\n- Duduk dengan posisi **tawarruk** (pada shalat yang memiliki dua tasyahud): menjulurkan kaki kiri ke bawah betis kanan dan mendudukkan pantat di lantai.\n- Meletakkan telapak tangan kiri di lutut kiri dan tangan kanan di paha kanan dengan menggenggam jari lalu **mengisyaratkan jari telunjuk** ke arah kiblat.\n- Membaca lafaz bacaan tahiyat tasyahud.",
			Arabic:    "التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ، السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ، السَّلَامُ عَلَيْنَا وَعَلَى عِبَادِ اللَّهِ الصَّالِحِينَ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا رَسُولُ اللَّهِ",
			Latin:     "Attahiyyaatu lillaahi wash shalawaatu wat thayyibaat. Assalaamu 'alaika ayyuhan nabiyyu wa rahmatullaahi wa barakaatuh. Assalaamu 'alainaa wa 'alaa 'ibaadillaahish shaalihiin. Asyhadu allaa ilaaha illallah wa asyhadu anna Muhammadan rasuulullah",
			Translation: "Segala penghormatan, shalat, dan kebaikan hanya milik Allah. Semoga keselamatan, rahmat, dan keberkahan Allah tercurah kepadamu wahai Nabi. Keselamatan tercurah kepada kami dan kepada hamba-hamba Allah yang shalih. Aku bersaksi bahwa tiada ilah yang berhak disembah selain Allah, dan aku bersaksi bahwa Muhammad adalah utusan Allah.",
			Dalil:     "HR. Muslim No. 402: \"Jika kamu duduk (tasyahud), bacalah tahiyat.\"",
		},
		{
			ModuleID:  bySlug["sholat"],
			StepOrder: 9,
			Kind:      "rukun",
			Title:     "Shalawat Nabi",
			Body:      "Setelah menyelesaikan bacaan tasyahud, dilanjutkan dengan membaca **Shalawat Ibrahimiyah** atas Nabi Muhammad ﷺ dan keluarganya.\n\nKeutamaan Shalawat Ibrahimiyah:\n- Lafaz shalawat yang paling afdhal dan diajarkan langsung oleh Rasulullah ﷺ kepada para sahabat saat mereka bertanya bagaimana cara bershalawat kepada beliau.",
			Arabic:    "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ. اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ",
			Latin:     "Allahumma shalli 'ala Muhammad wa 'ala aali Muhammad, kama shallayta 'ala Ibraahiim wa 'ala aali Ibraahiim, innaka hamiidum majiid. Allahumma baarik 'ala Muhammad wa 'ala aali Muhammad, kama baarakta 'ala Ibraahiim wa 'ala aali Ibraahiim, innaka hamiidum majiid",
			Translation: "Ya Allah, berilah shalawat kepada Muhammad dan keluarga Muhammad, sebagaimana Engkau memberi shalawat kepada Ibrahim dan keluarga Ibrahim. Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia. Ya Allah, berilah berkah kepada Muhammad dan keluarga Muhammad, sebagaimana Engkau memberi berkah kepada Ibrahim dan keluarga Ibrahim. Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia.",
			Dalil:     "HR. Muslim No. 405: \"Bacalah shalawat atas aku, karena shalawatmu sampai kepadaku.\"",
		},
		{
			ModuleID:  bySlug["sholat"],
			StepOrder: 10,
			Kind:      "rukun",
			Title:     "Salam Penutup",
			Body:      "**Salam** adalah rukun penutup yang membebaskan mushalli dari ikatan dan larangan shalat.\n\nTata cara salam:\n- Menoleh ke arah **kanan** hingga pipi putih terlihat dari belakang sambil mengucapkan salam pertama: `Assalamu'alaikum warahmatullah`.\n- Menoleh ke arah **kiri** sambil mengucapkan salam kedua.",
			Arabic:    "السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ",
			Latin:     "Assalaamu 'alaikum wa rahmatullah",
			Translation: "Semoga keselamatan dan rahmat Allah tercurah kepada kalian.",
			Dalil:     "HR. Muslim No. 582: Panduan salam penutup shalat.",
		},

		// ===== ADZAN & IQOMAH =====
		{
			ModuleID:  bySlug["adzan-iqomah"],
			StepOrder: 1,
			Kind:      "teori",
			Title:     "Pengertian & Keutamaan Adzan",
			Body:      "**Adzan** secara bahasa bermakna pemberitahuan (*al-i'lam*). Secara syariat, adzan adalah pemberitahuan masuknya waktu shalat fardhu dengan lafaz-lafaz khusus yang telah ditentukan oleh syariat Islam.\n\nKeutamaan adzan:\n- Menjadi syiar Islam yang paling agung untuk mengumandangkan tauhid.\n- Para muadzin memiliki **leher yang paling panjang (kemuliaan paling tinggi)** pada hari kiamat (HR. Muslim No. 387).\n- Setan lari terbirit-birit saat mendengar kumandang adzan (HR. Bukhari No. 608).",
			Arabic:    "الْأَذَانُ",
			Latin:     "Al-adzaan",
			Translation: "Adzan (panggilan shalat).",
			Dalil:     "HR. Bukhari No. 604: Awal pensyariatan adzan adalah pada tahun pertama hijriah setelah Rasulullah ﷺ bermusyawarah dengan para sahabat.",
		},
		{
			ModuleID:  bySlug["adzan-iqomah"],
			StepOrder: 2,
			Kind:      "teori",
			Title:     "Syarat & Adab Muadzin",
			Body:      "Muadzin yang mengumandangkan panggilan shalat hendaknya memperhatikan syarat dan adab yang disunnahkan.\n\nSyarat dan adab muadzin:\n- **Muslim, berakal, dan laki-laki**.\n- Memahami masuknya waktu shalat secara tepat dan amanah.\n- Disunnahkan memiliki **suara yang lantang, merdu, dan fasih** (HR. Abu Dawud No. 499).\n- Berdiri menghadap kiblat dalam keadaan suci (berwudhu).\n- Meletakkan kedua jari telunjuk di lubang telinga saat mengumandangkan adzan.",
			Dalil:     "HR. Abu Dawud No. 5148 (Hasan): Disunnahkan agar muadzin adalah orang yang paling memahami waktu dan paling bagus suaranya.",
		},
		{
			ModuleID:  bySlug["adzan-iqomah"],
			StepOrder: 3,
			Kind:      "praktik",
			Title:     "Lafaz Adzan Lengkap",
			Body:      "Kumandang adzan terdiri dari **15 kalimat** yang diucapkan secara tartil dan jelas:\n\n1. Takbir 4 kali: `Allahu Akbar, Allahu Akbar (2x)`\n2. Syahadat Tauhid 2 kali: `Asyhadu allaa ilaaha illallah`\n3. Syahadat Rasul 2 kali: `Asyhadu anna Muhammadar Rasulullah`\n4. Seruan Shalat 2 kali: `Hayya 'alash Shalah` (menoleh ke kanan)\n5. Seruan Kemenangan 2 kali: `Hayya 'alal Falah` (menoleh ke kiri)\n6. Takbir 2 kali: `Allahu Akbar, Allahu Akbar`\n7. Penutup Tauhid: `Laa ilaaha illallah`",
			AudioURL:  "/audio/adzan.mp3",
			Arabic:    "اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ. أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ. أَشْهَدُ أَنَّ مُحَمَّدًا رَسُولُ اللَّهِ، أَشْهَدُ أَنَّ مُحَمَّدًا رَسُولُ اللَّهِ. حَيَّ عَلَى الصَّلَاةِ، حَيَّ عَلَى الصَّلَاةِ. حَيَّ عَلَى الْفَلَاحِ، حَيَّ عَلَى الْفَلَاحِ. اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ. لَا إِلَهَ إِلَّا اللَّهُ",
			Latin:     "Allahu Akbar Allahu Akbar, Allahu Akbar Allahu Akbar. Asyhadu allaa ilaaha illallah, asyhadu allaa ilaaha illallah. Asyhadu anna Muhammadan rasuulullah, asyhadu anna Muhammadan rasuulullah. Hayya 'alash shalah, hayya 'alash shalah. Hayya 'alal falah, hayya 'alal falah. Allahu Akbar Allahu Akbar. Laa ilaaha illallah",
			Translation: "Allah Maha Besar (4x). Aku bersaksi bahwa tiada ilah selain Allah (2x). Aku bersaksi bahwa Muhammad utusan Allah (2x). Marilah menuju shalat (2x). Marilah menuju kejayaan (2x). Allah Maha Besar (2x). Tiada ilah selain Allah.",
			Dalil:     "HR. Muslim No. 379: Lafaz adzan sesuai sunnah.",
		},
		{
			ModuleID:  bySlug["adzan-iqomah"],
			StepOrder: 4,
			Kind:      "praktik",
			Title:     "Doa dan Shalawat Setelah Adzan",
			Body:      "Bagi orang yang mendengar adzan, disunnahkan:\n- **Menirukan setiap lafaz adzan** yang diucapkan muadzin, kecuali pada `Hayya 'alash shalah` dan `Hayya 'alal falah` diganti dengan `Laa hawla wa laa quwwata illaa billaah`.\n- Bershalawat kepada Nabi Muhammad ﷺ setelah adzan selesai.\n- Membaca **doa wasilah** memohonkan kedudukan tertinggi di surga bagi Rasulullah ﷺ.\n- Berdoa memohon hajat kebaikan, karena waktu antara adzan dan iqomah adalah waktu mustajab.",
			Arabic:    "اللَّهُمَّ رَبَّ هَذِهِ الدَّعْوَةِ التَّامَّةِ وَالصَّلَاةِ الْقَائِمَةِ آتِ مُحَمَّدًا الْوَسِيلَةَ وَالْفَضِيلَةَ وَابْعَثْهُ مَقَامًا مَحْمُودًا الَّذِي وَعَدْتَهُ",
			Latin:     "Allahumma Rabba hadzihid da'watit taammah wash shalaatil qaa'imah, aati Muhammadanil wasiilata wal fadhilah, wab'atshu maqaamam mahmuudanil ladzii wa'adtah",
			Translation: "Ya Allah, Tuhan pemilik seruan yang sempurna ini dan shalat yang akan didirikan, berikanlah kepada Muhammad wasilah (kedudukan tinggi) dan keutamaan, dan bangkitkanlah beliau ke tempat yang terpuji yang telah Engkau janjikan.",
			Dalil:     "HR. Bukhari No. 614: Doa setelah adzan.",
			Tip:       "Wasilah adalah kedudukan tertinggi di surga yang hanya dianugerahkan kepada seorang hamba pilihan Allah, yaitu Rasulullah ﷺ.",
		},
		{
			ModuleID:  bySlug["adzan-iqomah"],
			StepOrder: 5,
			Kind:      "praktik",
			Title:     "Iqomah",
			Body:      "**Iqomah** adalah seruan pemberitahuan bahwa shalat berjamaah akan segera didirikan.\n\nPerbedaan iqomah dengan adzan:\n- Lafaz iqomah diucapkan lebih cepat (*hadar*) dibanding adzan yang bertartil.\n- Kalimat syahadat, takbir, dan seruan diucapkan satu kali (kecuali takbir awal 2x, takbir akhir 2x).\n- Ditambahkan kalimat `Qad qaamatish shalah` sebanyak dua kali setelah `Hayya 'alal falah`.",
			Arabic:    "قَدْ قَامَتِ الصَّلَاةُ، قَدْ قَامَتِ الصَّلَاةُ",
			Latin:     "Qad qaamatish shalah, qad qaamatish shalah",
			Translation: "Sungguh shalat telah berdiri, sungguh shalat telah berdiri.",
			Dalil:     "HR. Ahmad No. 19312 (Shahih): Lafaz iqomah.",
		},

		// ===== PUASA =====
		{
			ModuleID:  bySlug["puasa"],
			StepOrder: 1,
			Kind:      "teori",
			Title:     "Pengertian & Keutamaan Puasa",
			Body:      "**Puasa (Ash-Shiyam)** secara syariat adalah menahan diri dari segala hal yang membatalkan (makan, minum, jima', dan semisalnya) mulai dari **terbit fajar shadiq (waktu Shubuh) hingga terbenam matahari (waktu Maghrib)** dengan niat ibadah mengharap ridha Allah semata.\n\nKeutamaan puasa Ramadan:\n- Menjadi rukun Islam yang keempat dan sarana utama meraih derajat **takwa**.\n- Penghapus dosa-dosa yang telah lalu bagi yang berpuasa dengan dasar iman dan mengharap pahala (*ihtisaban*).\n- Bau mulut orang yang berpuasa lebih harum di sisi Allah daripada minyak kasturi.",
			Arabic:    "الصَّوْمُ",
			Latin:     "Ash-shiyaam",
			Translation: "Puasa.",
			Dalil:     "QS. Al-Baqarah: 183: \"Wahai orang-orang yang beriman, diwajibkan atas kamu berpuasa sebagaimana diwajibkan atas orang-orang sebelum kamu agar kamu bertakwa.\"",
		},
		{
			ModuleID:  bySlug["puasa"],
			StepOrder: 2,
			Kind:      "rukun",
			Title:     "Rukun & Syarat Sah Puasa",
			Body:      "Puasa memiliki dua rukun pokok yang wajib dipenuhi agar puasa sah:\n\n1. **Niat di dalam hati:**\n   - Untuk puasa wajib (Ramadan, qadha, nazar), niat wajib dihadirkan **pada malam hari sebelum fajar shadiq** (*tabyit an-niyyah*).\n2. **Imsak (menahan diri):**\n   - Menahan diri dari makan, minum, syahwat, dan seluruh pembatal puasa sejak fajar hingga Maghrib.",
			Dalil:     "HR. Bukhari No. 1901; HR. Muslim No. 1153: \"Barangsiapa yang tidak berniat puasa sebelum fajar, maka tidak ada puasa baginya.\"",
		},
		{
			ModuleID:  bySlug["puasa"],
			StepOrder: 3,
			Kind:      "praktik",
			Title:     "Hal-hal yang Membatalkan Puasa",
			Body:      "Perkara yang membatalkan puasa dan mewajibkan qadha atau kaffarah:\n\n- **Makan dan minum secara sengaja.**\n- **Muntah dengan sengaja** (jika tidak sengaja/terpaksa, puasa tetap sah).\n- **Keluarnya darah haid atau nifas**, meskipun sesaat sebelum matahari terbenam.\n- **Jima' (hubungan suami-istri)** di siang hari Ramadan (membatalkan puasa dan mewajibkan kaffarah berat).\n- Memasukkan sesuatu ke dalam rongga tubuh yang bermakna makanan/nutrisi (seperti infus gizi).",
			Tip:       "Jika lupa makan atau minum dan langsung sadar, lanjutkan puasa. Peristiwa tersebut tidak membatalkan puasa menurut hadis.",
			Dalil:     "HR. Abu Dawud No. 2340 (Hasan): \"Jika salah seorang di antara kamu lupa dan makan atau minum, maka hendaklah ia menyempurnakan puasanya, karena sesungguhnya Allahlah yang telah memberinya makan dan minum.\"",
		},
		{
			ModuleID:  bySlug["puasa"],
			StepOrder: 4,
			Kind:      "sunnah",
			Title:     "Sunnah-sunnah Puasa",
			Body:      "Amalan sunnah yang sangat dianjurkan untuk menyempurnakan pahala puasa:\n\n- **Mengakhirkan sahur** mendekati waktu fajar dan **menyegerakan berbuka** saat matahari terbenam.\n- Berbuka dengan **ruthab (kurma basah)**, tamr (kurma kering), atau air putih sebelum shalat Maghrib.\n- Membaca doa saat berbuka puasa.\n- Menjaga lisan dari ghibah, dusta, adu domba, dan perkataan sia-sia.\n- Memperbanyak sedekah, tilawah Al-Quran, dan shalat malam (Tarawih).",
			Arabic:    "ذَهَبَ الظَّمَأُ وَابْتَلَّتِ الْعُرُوقُ وَثَبَتَ الْأَجْرُ إِنْ شَاءَ اللَّهُ",
			Latin:     "Dzahabazh zhama'u wabtallatil 'uruuqu wa tsabatal ajru insyaa Allah",
			Translation: "Telah hilang dahaga, telah basah urat-urat, dan telah tetap pahala insya Allah.",
			Dalil:     "HR. Abu Dawud No. 2356 (Hasan): Doa berbuka puasa.",
			Tip:       "Utamakan berbuka dengan kurma atau air putih, lalu shalat Maghrib.",
		},
		{
			ModuleID:  bySlug["puasa"],
			StepOrder: 5,
			Kind:      "teori",
			Title:     "Hikmah & Manfaat Puasa",
			Body:      "Ibadah puasa mengandung hikmah agung bagi jiwa, akal, dan raga:\n\n- **Tarbiyah ruhiyah:** Melatih kesabaran, kejujuran batin, dan keikhlasan karena puasa adalah rahasia antara hamba dengan Rabb-nya.\n- **Kepedulian sosial:** Menumbuhkan rasa empati dan kasih sayang terhadap kaum fakir miskin yang menahan lapar.\n- **Kesehatan fisik:** Mengistirahatkan organ pencernaan dan membersihkan racun tubuh.",
			Dalil:     "QS. Al-Baqarah: 183: \"...agar kamu bertakwa.\"",
		},

		// ===== ZAKAT =====
		{
			ModuleID:  bySlug["zakat"],
			StepOrder: 1,
			Kind:      "teori",
			Title:     "Zakat Fitrah",
			Body:      "**Zakat Fitrah** adalah zakat badan yang wajib dikeluarkan oleh setiap muslim (laki-laki, perempuan, dewasa, anak-anak, bahkan bayi yang lahir sebelum terbenam matahari akhir Ramadan) yang memiliki kelebihan makanan pokok untuk malam dan hari raya Idul Fitri.\n\nKetentuan Zakat Fitrah:\n- **Kadar zakat:** Satu sha' makanan pokok daerah setempat (setara kurleb 2,5 kg hingga 3 kg beras/gandum).\n- **Waktu pembayaran:** Boleh dibayarkan 1-2 hari sebelum Idul Fitri, dan waktu paling utama adalah di pagi hari sebelum pelaksanaan shalat Idul Fitri.\n- **Tujuan:** Membersihkan orang yang berpuasa dari perbuatan sia-sia dan memberi makan kaum miskin di hari raya.",
			Dalil:     "HR. Abu Dawud No. 1609 (Shahih): \"Rasulullah ﷺ mewajibkan zakat fitrah satu sha' kurma atau satu sha' gandum, atas budak dan orang merdeka, laki-laki dan perempuan, kecil dan besar dari kaum muslimin.\"",
		},
		{
			ModuleID:  bySlug["zakat"],
			StepOrder: 2,
			Kind:      "teori",
			Title:     "Zakat Mal (Harta)",
			Body:      "**Zakat Mal** adalah zakat yang dikenakan atas harta benda tertentu yang telah memenuhi kriteria syariat.\n\nSyarat wajib zakat mal:\n- **Kepemilikan penuh:** Harta berada dalam kekuasaan mutlak pemiliknya.\n- **Mencapai Nishab:** Batas minimal kepemilikan harta (emas senilai 85 gram emas murni).\n- **Mencapai Haul:** Telah berlalu masa kepemilikan selama satu tahun hijriah penuh.\n- **Kadar zakat:** Umumnya 2,5% untuk emas, perak, uang simpanan, dan perniagaan.",
			Tip:       "Nisab emas zakat mal setara 85 gram emas, sedangkan nisab perak 595 gram perak.",
		},
		{
			ModuleID:  bySlug["zakat"],
			StepOrder: 3,
			Kind:      "praktik",
			Title:     "8 Golongan Penerima (Asnaf)",
			Body:      "Penyaluran zakat telah diatur secara tegas dalam **QS. At-Taubah ayat 60** kepada delapan golongan (*asnaf*):\n\n1. **Fakir:** Orang yang tidak memiliki harta dan penghasilan cukup untuk memenuhi kebutuhan pokok.\n2. **Miskin:** Orang yang memiliki penghasilan tetapi tidak mencukupi kebutuhan dasarnya.\n3. **Amil:** Petugas yang ditunjuk mengumpulkan dan mendistribusikan zakat.\n4. **Muallaf:** Orang yang baru masuk Islam atau yang dilunakkan hatinya kepada Islam.\n5. **Riqab:** Pembebasan budak muslim dari perbudakan.\n6. **Gharim:** Orang yang terlilit utang demi kemaslahatan mubah dan tidak mampu melunasinya.\n7. **Fisabilillah:** Pejuang dakwah dan jihad di jalan Allah.\n8. **Ibnu Sabil:** Musafir yang kehabisan bekal dalam perjalanan ketaatan.",
			Arabic:    "إِنَّمَا الصَّدَقَاتُ لِلْفُقَرَاءِ وَالْمَسَاكِينِ وَالْعَامِلِينَ عَلَيْهَا وَالْمُؤَلَّفَةِ قُلُوبُهُمْ وَفِي الرِّقَابِ وَالْغَارِمِينَ وَفِي سَبِيلِ اللَّهِ وَابْنِ السَّبِيلِ",
			Latin:     "Innama ash shadaqaatu lilfuqaraa'i wal masaakiini wal 'aamiliina 'alaihaa wal mu'allafati quluubuhum wa fir riqaabi wal ghaarimiina wa fii sabiilillaahi wabnis sabiil",
			Translation: "Sesungguhnya zakat-zakat itu hanyalah untuk orang-orang fakir, orang-orang miskin, para amil zakat, para muallaf yang dibujuk hatinya, untuk (memerdekakan) budak, orang-orang yang berutang, untuk jalan Allah, dan orang-orang yang sedang dalam perjalanan.",
			Dalil:     "QS. At-Taubah: 60.",
		},

		// ===== TAJWID =====
		{
			ModuleID:  bySlug["tajwid"],
			StepOrder: 1,
			Kind:      "teori",
			Title:     "Hukum Nun Mati & Tanwin",
			Body:      "Nun sukun (`نْ`) dan tanwin (`ـً`, `ـٍ`, `ـٌ`) apabila bertemu dengan salah satu dari 28 huruf hijaiyah terbagi menjadi **empat hukum bacaan**:\n\n1. **Izhar Halqi:** Dibaca jelas tanpa dengung.\n2. **Idgham (Bighunnah & Bilaghunnah):** Dilebur ke huruf berikutnya.\n3. **Iqlab:** Mengganti bunyi nun menjadi mim sukun.\n4. **Ikhfa Haqiqi:** Dibaca samar antara izhar dan idgham disertai dengung.",
			Dalil:     "QS. Al-An'am: 73: \"...وَقَدْ فَصَّلَ لَكُم مَّا حَرَّمَ عَلَيْكُمْ...\" - contoh Ikhfa karena nun mati bertemu fa'.",
		},
		{
			ModuleID:  bySlug["tajwid"],
			StepOrder: 2,
			Kind:      "praktik",
			Title:     "Idzhar Halqi",
			Body:      "**Idzhar Halqi** terjadi apabila nun sukun atau tanwin bertemu salah satu dari **6 huruf tenggorokan (halq)**:\n\n- Huruf-huruf Idzhar: `ء` (Hamzah), `هـ` (Ha'), `ع` ('Ain), `غ` (Ghain), `ح` (Ha), `خ` (Kha').\n- **Cara membaca:** Nun sukun atau tanwin diucapkan secara **jelas, tegas, dan tidak mendengung**.",
			Arabic:    "مَنْ ءَامَنَ",
			Latin:     "Man aamana",
			Translation: "Barangsiapa yang beriman.",
			Dalil:     "QS. Al-Baqarah: 62.",
		},
		{
			ModuleID:  bySlug["tajwid"],
			StepOrder: 3,
			Kind:      "praktik",
			Title:     "Idgham Bighunnah & Bilaghunnah",
			Body:      "**Idgham** adalah memasukkan bunyi nun sukun/tanwin ke dalam huruf berikutnya:\n\n- **Idgham Bighunnah (dengan dengung):** Jika bertemu 4 huruf (`ي`, `ن`, `م`, `و` - disingkat *YANMU*). Dibaca lebur disertai dengung 2 harakat.\n- **Idgham Bilaghunnah (tanpa dengung):** Jika bertemu 2 huruf (`ل`, `ر`). Dibaca lebur sempurna tanpa dengung sama sekali.",
			Arabic:    "مَن يَعْمَلْ سُوءًا",
			Latin:     "May ya'mal suu-an",
			Translation: "Barangsiapa yang mengerjakan kejahatan.",
			Dalil:     "QS. An-Nisa: 123.",
		},
		{
			ModuleID:  bySlug["tajwid"],
			StepOrder: 4,
			Kind:      "praktik",
			Title:     "Iqlab",
			Body:      "**Iqlab** terjadi jika nun sukun atau tanwin bertemu dengan huruf **Ba (`ب`)**:\n\n- **Cara membaca:** Mengubah bunyi huruf nun/tanwin menjadi bunyi huruf **Mim sukun (`مْ`)**, disertai dengung (*ghunnah*) 2 harakat dan sedikit merapatkan kedua bibir tanpa menekan terlalu keras.\n- Pada mushaf standar Madinah dan Indonesia, hukum ini ditandai dengan huruf mim kecil (`ۭ`) di atas nun sukun atau tanwin.",
			Arabic:    "أَنۢبِئُوهُم",
			Latin:     "Anbii-uhum",
			Translation: "Kabarkanlah kepada mereka.",
			Dalil:     "QS. Al-Baqarah: 33.",
		},
		{
			ModuleID:  bySlug["tajwid"],
			StepOrder: 5,
			Kind:      "praktik",
			Title:     "Ikhfa Haqiqi",
			Body:      "**Ikhfa Haqiqi** terjadi apabila nun sukun atau tanwin bertemu dengan **15 huruf** hijaiyah selain huruf izhar, idgham, dan iqlab.\n\n- Huruf-huruf Ikhfa: `ت`, `ث`, `ج`, `د`, `ذ`, `ز`, `س`, `ش`, `ص`, `ض`, `ط`, `ظ`, `ف`, `ق`, `ك`.\n- **Cara membaca:** Mengucapkan nun sukun/tanwin secara **samar di rongga hidung** dengan suara mendekati makhraj huruf di depannya disertai ghunnah (dengung) 2 harakat.",
			Arabic:    "مِن وَرَائِهِمْ",
			Latin:     "Min waraa'ihim",
			Translation: "Dari belakang mereka.",
			Dalil:     "QS. Al-Buruj: 20.",
		},
		{
			ModuleID:  bySlug["tajwid"],
			StepOrder: 6,
			Kind:      "praktik",
			Title:     "Hukum Mim Mati",
			Body:      "Mim sukun (`مْ`) apabila bertemu dengan huruf hijaiyah memiliki **tiga hukum bacaan**:\n\n1. **Ikhfa Syafawi:** Mim sukun bertemu huruf `ب` (Ba), dibaca samar dengan dengung.\n2. **Idgham Mimi (Mutamatsilain):** Mim sukun bertemu sesama huruf `م` (Mim), dibaca lebur dengan dengung.\n3. **Idzhar Syafawi:** Mim sukun bertemu selain huruf `ب` dan `م`, dibaca jelas tanpa dengung sama sekali (terutama saat bertemu `و` dan `ف` agar tidak tertukar ikhfa).",
			Arabic:    "تَرْمِيهِم بِحِجَارَةٍ",
			Latin:     "Tarmihim bihijaaratin",
			Translation: "Melempari mereka dengan batu.",
			Dalil:     "QS. Al-Fil: 4.",
		},
		{
			ModuleID:  bySlug["tajwid"],
			StepOrder: 7,
			Kind:      "praktik",
			Title:     "Mad (Panjang Bacaan)",
			Body:      "**Mad** secara bahasa berarti memanjangkan suara huruf. Terbagi menjadi dua kategori besar:\n\n- **Mad Thabi'i (Asli):** Panjang 2 harakat apabila ada Alif setelah fathah, Wawu sukun setelah dhammah, atau Ya' sukun setelah kasrah.\n- **Mad Far'i (Cabang):** Mad yang bertambah panjangnya (4 hingga 6 harakat) karena adanya sebab pertemuan dengan hamzah (seperti *Mad Wajib Muttashil*, *Mad Jaiz Munfashil*) atau sebab sukun/tasydid (seperti *Mad Lazim*, *Mad 'Aridh lissukun*).",
			Arabic:    "قَالَ رَبِّ",
			Latin:     "Qaala Rabbi",
			Translation: "Dia berkata, \"Ya Tuhanku.\"",
			Dalil:     "QS. Maryam: 4.",
			Tip:       "Berlatih dengan qari terkenal untuk mendengar langsung panjang-pendek bacaan.",
		},

		// ===== RUKUN IMAN =====
		{
			ModuleID:  bySlug["rukun-iman"],
			StepOrder: 1,
			Kind:      "teori",
			Title:     "Iman kepada Allah",
			Body:      "**Iman kepada Allah** adalah fondasi seluruh ajaran Islam. Mengesakan Allah mencakup empat pilar utama:\n\n- **Iman terhadap keberadaan Allah ﷻ.**\n- **Tauhid Rububiyah:** Mengesakan Allah dalam penciptaan, kerajaan, dan pemeliharaan seluruh alam semesta.\n- **Tauhid Uluhiyah:** Mengikhlaskan seluruh bentuk ibadah (shalat, doa, sembelihan, nazar, tawakkal) hanya kepada Allah semata.\n- **Tauhid Asma' wa Sifat:** Menetapkan nama-nama dan sifat-sifat Allah yang mulia sesuai Al-Quran dan As-Sunnah yang shahih.",
			Dalil:     "QS. Al-Ikhlas: 1-4: \"Katakanlah, Dialah Allah Yang Maha Esa. Allah tempat bergantung. Tidak beranak dan tidak dilahirkan. Dan tiada seorangpun setara dengan-Nya.\"",
		},
		{
			ModuleID:  bySlug["rukun-iman"],
			StepOrder: 2,
			Kind:      "teori",
			Title:     "Iman kepada Malaikat",
			Body:      "Meyakini dengan pasti keberadaan **para malaikat** sebagai hamba-hamba Allah yang mulia:\n\n- Diciptakan dari **cahaya (*nuur*)**, tidak makan, tidak minum, tidak berjenis kelamin, dan tidak pernah bermaksiat kepada Allah.\n- Memiliki tugas-tugas khusus, seperti:\n  - **Jibril:** Menyampaikan wahyu kepada para rasul.\n  - **Mikail:** Mengatur hujan dan rezeki.\n  - **Israfil:** Meniup sangkakala hari kiamat dan kebangkitan.\n  - **Malakul Maut:** Mencabut nyawa.",
			Arabic:    "الْمَلَائِكَةُ",
			Latin:     "Al-malaa'ikah",
			Translation: "Para malaikat.",
			Dalil:     "QS. Al-Baqarah: 285: \"...mereka (para rasul) beriman kepada-Nya, dan mereka semua tunduk kepada-Nya.\"",
		},
		{
			ModuleID:  bySlug["rukun-iman"],
			StepOrder: 3,
			Kind:      "teori",
			Title:     "Iman kepada Kitab-kitab",
			Body:      "Meyakini bahwa Allah telah menurunkan **kitab-kitab suci** kepada para rasul sebagai petunjuk dan pedoman hidup manusia:\n\n- **Suhuf** yang diturunkan kepada Nabi Ibrahim dan Nabi Musa 'alaihimassalam.\n- **Taurat** diturunkan kepada Nabi Musa 'alaihissalam.\n- **Zabur** diturunkan kepada Nabi Daud 'alaihissalam.\n- **Injil** diturunkan kepada Nabi Isa 'alaihissalam.\n- **Al-Quran Al-Karim** diturunkan kepada Nabi Muhammad ﷺ sebagai penyempurna dan penghapus hukum kitab-kitab sebelumnya (*muhaiminan 'alaihi*).",
			Dalil:     "QS. Al-Baqarah: 285: \"Rasul (Muhammad) beriman kepada apa yang diturunkan kepadanya dari Tuhannya...\"",
		},
		{
			ModuleID:  bySlug["rukun-iman"],
			StepOrder: 4,
			Kind:      "teori",
			Title:     "Iman kepada Para Rasul",
			Body:      "Meyakini bahwa Allah telah memilih para manusia pilihan terbaik sebagai **Nabi dan Rasul** untuk membimbing umat manusia menuju tauhid:\n\n- Wajib mengimani seluruh nabi dan rasul tanpa membeda-bedakan satu sama lain dalam risalah tauhid.\n- Mengenal 25 Nabi dan Rasul yang disebutkan dalam Al-Quran, dimulai dari Nabi Adam 'alaihissalam hingga Nabi Muhammad ﷺ sebagai penutup seluruh nabi dan rasul (*Khatamun Nabiyyin*).",
			Dalil:     "QS. Al-Ahzab: 40: \"Muhammad itu sekali-kali bukanlah (bapak) dari seorang laki-laki di antara kamu, tetapi dia adalah Rasulullah dan penutup para nabi.\"",
		},
		{
			ModuleID:  bySlug["rukun-iman"],
			StepOrder: 5,
			Kind:      "teori",
			Title:     "Iman kepada Hari Akhir",
			Body:      "Meyakini kepastian datangnya **Hari Kiamat** dan segala rangkaian peristiwa setelah kematian:\n\n- **Fitnah kubur:** Pertanyaan malaikat Munkar dan Nakir di alam barzakh serta adanya nikmat dan azab kubur.\n- **Kebangkitan (*Al-Ba'ats*):** Dibangkitkannya seluruh manusia dari kubur.\n- **Padang Mahsyar, Hisab, & Mizan:** Pengumpulan manusia dan penimbangan amal perbuatan.\n- **As-Shirath:** Jembatan yang dibentangkan di atas neraka jahannam menuju surga.\n- **Surga (*Jannah*)** sebagai balasan abadi bagi orang beriman, dan **Neraka (*Naar*)** bagi orang kafir.",
			Dalil:     "QS. Al-Qiyamah: 1-3: \"Aku bersumpah dengan hari kiamat, dan aku bersumpah dengan jiwa yang selalu menyesal (dirinya sendiri). Apakah manusia mengira bahwa Kami tidak akan mengumpulkan (kembali) tulang belulangnya?\"",
		},
		{
			ModuleID:  bySlug["rukun-iman"],
			StepOrder: 6,
			Kind:      "teori",
			Title:     "Iman kepada Qada & Qadar",
			Body:      "Meyakini bahwa segala kebaikan dan keburukan yang terjadi di alam semesta telah ditetapkan oleh Allah berdasarkan hikmah-Nya yang sempurna.\n\nEmpat tingkatan (*maratib*) iman kepada takdir:\n1. **Al-'Ilm:** Ilmu Allah yang meliputi segala sesuatu sejak azali.\n2. **Al-Kitabah:** Pencatatan seluruh takdir makhluk di Lauhul Mahfuz 50.000 tahun sebelum penciptaan langit dan bumi.\n3. **Al-Masyi'ah:** Kehendak Allah yang pasti terlaksana atas segala sesuatu.\n4. **Al-Khalq:** Penciptaan Allah terhadap segala makhluk dan perbuatannya.",
			Dalil:     "HR. Tirmidzi No. 2515 (Shahih): \"Berimanlah kamu kepada qada dan qadar, bahwa seluruh perkara itu telah ditetapkan dari Allah.\"",
		},

		// ===== ADAB MENUNTUT ILMU =====
		{
			ModuleID:  bySlug["adab-talab-ilmu"],
			StepOrder: 1,
			Kind:      "sunnah",
			Title:     "Meniatkan Ilmu untuk Mencapai Ridha Allah",
			Body:      "**Ikhlas niat** adalah syarat mutlak diterimanya amalan menuntut ilmu syar'i:\n\n- Niatkan menuntut ilmu untuk **mengangkat kebodohan dari diri sendiri dan orang lain**, mengagungkan syariat Allah, dan mengharap pahala akhirat.\n- Hindari menuntut ilmu demi popularitas, pujian manusia, membanggakan diri di hadapan ulama, atau mendebat orang bodoh.",
			Arabic:    "رَبِّ زِدْنِي عِلْمًا",
			Latin:     "Rabbi zidnii 'ilmaa",
			Translation: "Ya Tuhanku, tambahkanlah aku ilmu.",
			Dalil:     "QS. Thaha: 114.",
			Tip:       "Tiap kali mulai belajar, bisikkan niat ini di hati. Niat adalah fondasi yang membedakan ilmu yang bermanfaat dan yang sia-sia.",
		},
		{
			ModuleID:  bySlug["adab-talab-ilmu"],
			StepOrder: 2,
			Kind:      "sunnah",
			Title:     "Membersihkan Hati Sebelum Menuntut Ilmu",
			Body:      "Ilmu syar'i adalah **cahaya Ilahi** yang hanya akan bersemayam di dalam hati yang bersih:\n\n- Sucikan hati dari penyakit hasad (dengki), kibr (sombong), riya', dan ujub.\n- Hati yang penuh dengan kotoran maksiat akan terhalang dari kelezatan memahami kalam Allah dan sabda Rasulullah ﷺ.",
			Dalil:     "HR. Muslim No. 2701: \"Tidak akan masuk surga orang yang di dalam hatinya terdapat kesombongan sebesar biji sawi.\"",
		},
		{
			ModuleID:  bySlug["adab-talab-ilmu"],
			StepOrder: 3,
			Kind:      "sunnah",
			Title:     "Memulai dengan Bismillah dan Memperhatikan Wudhu",
			Body:      "Di antara kebiasaan para salafus shalih saat menghadiri majelis ilmu:\n\n- Berwudhu terlebih dahulu, mengenakan pakaian yang bersih dan rapi, serta memakai wewangian.\n- Duduk dengan tenang, penuh ketawadhu'an, dan memusatkan pandangan serta pendengaran kepada guru.\n- Mencatat faidah ilmu yang berharga agar tidak hilang (*Iqtidha'ul 'ilmil 'amal*).",
			Tip:       "Menghadap guru secara langsung (tatap muka) akan lebih melekat dalam hati dibanding belajar dari layar.",
		},
		{
			ModuleID:  bySlug["adab-talab-ilmu"],
			StepOrder: 4,
			Kind:      "sunnah",
			Title:     "Senantiasa Rendah Hati terhadap Guru",
			Body:      "Penuntut ilmu wajib menghormati dan memuliakan para ulama dan guru yang mengajarkannya:\n\n- Bertutur kata dengan lemah lembut dan sopan saat bertanya.\n- Mendoakan kebaikan, ampunan, dan keberkahan bagi guru.\n- Tidak memotong pembicaraan guru dan berlapang dada menerima koreksi atau teguran.",
			Dalil:     "HR. Tirmidzi No. 2671 (Hasan): \"Tidak termasuk golongan kami orang yang tidak memuliakan yang tua di antara kami, dan tidak menyayangi yang muda di antara kami.\"",
		},
		{
			ModuleID:  bySlug["adab-talab-ilmu"],
			StepOrder: 5,
			Kind:      "sunnah",
			Title:     "Mengamalkan Ilmu yang Dipelajari",
			Body:      "Buah termanis dari menuntut ilmu adalah **mengamalkannya dalam kehidupan sehari-hari**:\n\n- Para salaf mempelajari 10 ayat Al-Quran, lalu tidak berpindah ke ayat lain sebelum memahami makna dan mengamalkan kandungannya.\n- Menyebarkan ilmu kepada keluarga dan masyarakat dengan hikmah dan teladan yang baik.",
			Dalil:     "HR. Ath-Thabrani: \"Sungguh akan datang kepada suatu kaum yang mencari ilmu, namun tidak dicari melainkan untuk berhias dengannya, dan mereka tidak dituntut dengan ilmu melainkan untuk berdebat.\"",
		},

		// ===== TAHSIN & TAJWID DASAR =====
		{
			ModuleID:  bySlug["tahsin-tajwid"],
			StepOrder: 1,
			Kind:      "teori",
			Title:     "Makharijul Huruf (Tempat Keluarnya Huruf)",
			Body:      "**Makharijul Huruf** adalah tempat keluarnya huruf hijaiyah saat dibunyikan. Mengetahui makhraj huruf mencegah tertukarnya huruf yang mirip bunyinya.\n\nLima kelompok makhraj utama:\n1. **Al-Jauf (Rongga Mulut & Tenggorokan):** Tempat keluarnya huruf-huruf mad (`ا`, `و`, `ي`).\n2. **Al-Halq (Tenggorokan):** Terbagi menjadi pangkal (`ء`, `هـ`), tengah (`ع`, `ح`), dan ujung tenggorokan (`غ`, `خ`).\n3. **Al-Lisan (Lidah):** 10 makhraj untuk 18 huruf (termasuk huruf `ق`, `ك`, `ج`, `ش`, `ي`, `ض`, `ل`, `ن`, `ر`, `ط`, `د`, `ت`, `ص`, `ز`, `س`, `ظ`, `ذ`, `ث`).\n4. **Asy-Syafatain (Kedua Bibir):** Huruf `ف`, `و`, `ب`, `م`.\n5. **Al-Khaisyum (Rongga Hidung):** Tempat keluarnya dengung (*ghunnah*).",
			Arabic:    "مَخَارِجُ الْحُرُوفِ",
			Latin:     "Makhaarijul Huruuf",
			Translation: "Tempat-tempat keluarnya huruf.",
			Dalil:     "QS. Al-Muzzammil: 4: \"...وَرَتِّلِ الْقُرْآنَ تَرْتِيلًا\" (Dan bacalah Al-Quran itu dengan perlahan/tartil).",
			Tip:       "Latih pengucapan huruf tenggorokan (ء ه ع غ ح خ) dan lidah (ق ك ج ش ي ض ل ن ر ط د ت ص ز س ظ ذ ث) di hadapan guru tahsin.",
		},
		{
			ModuleID:  bySlug["tahsin-tajwid"],
			StepOrder: 2,
			Kind:      "teori",
			Title:     "Sifatul Huruf (Sifat-sifat Huruf)",
			Body:      "**Sifatul Huruf** adalah karakter bunyi yang menyertai huruf saat keluar dari makhrajnya.\n\nSifat-sifat pokok yang penting diperhatikan:\n- **Hams vs Jahr:** Hams adalah mengalirnya nafas pada 10 huruf (*Fahatstsahu syakhshun sakat*), sedangkan Jahr tertahannya nafas.\n- **Syiddah vs Rakhawah:** Syiddah adalah tertahannya suara, sedangkan Rakhawah mengalirnya suara.\n- **Isti'la vs Istifal:** Huruf Isti'la (`خ`, `ص`, `ض`, `غ`, `ط`, `ق`, `ظ`) wajib dibaca tebal (*tafkhim*) karena terangkatnya pangkal lidah ke langit-langit.\n- **Qalqalah:** Pantulan suara pada huruf `ق`, `ط`, `ب`, `ج`, `د` saat sukun atau waqaf.",
			Arabic:    "صِفَاتُ الْحُرُوفِ",
			Latin:     "Shifaatul Huruuf",
			Translation: "Sifat-sifat huruf.",
			Tip:       "Huruf Isti'la (خ ص ض غ ط ق ظ) selalu dibaca tebal (tafkhim) dalam segala kondisi harakat.",
		},
		{
			ModuleID:  bySlug["tahsin-tajwid"],
			StepOrder: 3,
			Kind:      "praktik",
			Title:     "Hukum Mad Thabi'i & Mad Far'i",
			Body:      "Hukum pemanjangan suara huruf pada Al-Quran:\n\n- **Mad Asli (Thabi'i):** Dibaca sepanjang 2 harakat (1 alif) secara konsisten.\n- **Mad Far'i:** Mad cabang yang bertambah durasinya:\n  - **Mad Wajib Muttashil:** Mad bertemu hamzah dalam satu kata (panjang 4-5 harakat).\n  - **Mad Jaiz Munfashil:** Mad bertemu hamzah di kata terpisah (panjang 4-5 harakat pada riwayat Hafsh 'an 'Ashim).\n  - **Mad Lazim:** Mad bertemu sukun asli atau tasydid (wajib 6 harakat).",
			Arabic:    "الْمَدُّ الطَّبِيعِيُّ وَالْمَدُّ الْفَرْعِيُّ",
			Latin:     "Al-madduth thabi'iyyu wal maddul far'iyyu",
			Translation: "Mad Thabi'i dan Mad Cabang.",
			Dalil:     "Atsar Ibnu Mas'ud radhiyallahu 'anhu saat menegur seseorang yang membaca ayat zakat tanpa memanjangkan lafaz mad (HR. Sa'id bin Manshur dalam Sunan-nya, sanad shahih).",
		},
		{
			ModuleID:  bySlug["tahsin-tajwid"],
			StepOrder: 4,
			Kind:      "teori",
			Title:     "Waqaf & Ibtida' (Berhenti & Memulai)",
			Body:      "Mengetahui tata cara berhenti (*waqaf*) dan memulai (*ibtida'*) bacaan sangat penting agar tidak merusak makna ayat:\n\n- **Waqaf Taam (Sempurna):** Berhenti pada ayat atau kalimat yang maknanya sudah tuntas dan tidak berkaitan dengan kalimat setelahnya.\n- **Waqaf Kaafi (Cukup):** Berhenti pada kalimat yang maknanya sudah sempurna, namun maknanya masih berkait dengan setelahnya.\n- **Waqaf Hasan (Baik):** Berhenti pada kalimat yang berfaidah, tetapi tidak disarankan memulai langsung dari kata setelahnya kecuali pada akhir ayat.\n- **Waqaf Qabih (Buruk):** Berhenti pada kalimat yang belum lengkap sehingga menimbulkan makna rancu atau rusak (seperti berhenti di `Laa ilaaha` tanpa lanjut `illallaah`).",
			Arabic:    "الْوَقْفُ وَالِابْتِدَاءُ",
			Latin:     "Al-waqfu wal ibtidaa'",
			Translation: "Berhenti dan memulai bacaan.",
			Tip:       "Jangan berhenti pada kata yang memutus hubungan makna tauhid atau makna larangan (seperti berhenti di 'Fawailul lil mushalliin' tanpa lanjut).",
		},
		{
			ModuleID:  bySlug["tahsin-tajwid"],
			StepOrder: 5,
			Kind:      "praktik",
			Title:     "Penerapan Praktis pada Surah Al-Fatihah",
			Body:      "Surah Al-Fatihah adalah rukun shalat yang wajib dibaca dengan tajwid dan makhraj yang benar.\n\nPoin-poin penting saat membaca Al-Fatihah:\n- Menyempurnakan harakat kasrah dan dhammah agar tidak terdengar miring (*imalah*).\n- Menekan tasydid pada lafaz `Iyyaaka` (agar tidak hilang huruf ya' tasydid).\n- Membedakan pengucapan huruf **Dhad (`ض`)** pada `Al-Maghdhubi` dan `Adh-Dhaalliin` dari huruf **Zha (`ظ`)** atau **Dhal (`ذ`)**.\n- Memanjangkan `Adh-Dhaalliin` 6 harakat penuh sebelum memasukkan ke lam bertasydid (*Mad Lazim Kilmi Mutsaqqal*).",
			Arabic:    "غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ",
			Latin:     "Ghairil maghdhuubi 'alaihim waladh-dhaalliin",
			Translation: "Bukan (jalan) mereka yang dimurkai dan bukan (pula jalan) mereka yang sesat.",
			Dalil:     "HR. Bukhari No. 756: \"Tidak sah shalat seseorang yang tidak membaca Fatihatul Kitab (Al-Fatihah).\"",
			Tip:       "Pastikan memanjangkan 'Adh-Dhaalliin' selama 6 harakat (Mad Lazim Kilmi Mutsaqqal) sebelum melafalkan tasydid lam.",
		},

		// ===== AQIDAH SALAF & RUKUN IMAN =====
		{
			ModuleID:  bySlug["aqidah-salaf"],
			StepOrder: 1,
			Kind:      "teori",
			Title:     "Pembagian Tauhid: Rububiyah, Uluhiyah, Asma' wa Sifat",
			Body:      "Intisari dakwah para rasul adalah menegakkan tauhid kepada Allah ﷻ dalam tiga sendi utama:\n\n1. **Tauhid Rububiyah:**\n   - Mengesakan Allah dalam segala perbuatan-Nya: Pencipta, Pemilik, Pengatur rezeki, dan Penguasa seluruh alam semesta.\n2. **Tauhid Uluhiyah:**\n   - Mengesakan Allah dalam segala perbuatan hamba: Hanya menyembah Allah semata dan tidak mempersekutukan-Nya dengan apapun dalam doa, shalat, tawakkal, dan cinta.\n3. **Tauhid Asma' wa Sifat:**\n   - Menetapkan seluruh nama dan sifat yang Allah tetapkan bagi diri-Nya dalam Al-Quran dan As-Sunnah yang shahih, **tanpa Tahrif** (mengubah makna), **tanpa Ta'thil** (menolak sifat), **tanpa Takyif** (menanyakan hakikat caranya), dan **tanpa Tamsyil** (menyerupakan dengan makhluk).",
			Arabic:    "تَوْحِيدُ الرُّبُوبِيَّةِ وَالْأُلُوهِيَّةِ وَالْأَسْمَاءِ وَالصِّفَاتِ",
			Latin:     "Tawhiidur rubuubiyyati wal uluuhiyyati wal asmaa'i wash shifaat",
			Translation: "Tauhid Rububiyah, Uluhiyah, serta Asma' dan Sifat.",
			Dalil:     "QS. Maryam: 65: \"Rabb (Tuhan) langit dan bumi dan apa yang ada di antara keduanya, maka sembahlah Dia dan berteguh hatilah dalam beribadah kepada-Nya. Apakah kamu mengetahui ada seseorang yang sama dengan Dia?\"",
		},
		{
			ModuleID:  bySlug["aqidah-salaf"],
			StepOrder: 2,
			Kind:      "teori",
			Title:     "Hakikat Iman: Perkataan, Keyakinan, dan Amal Perbuatan",
			Body:      "Aqidah Ahlus Sunnah wal Jama'ah merumuskan bahwa iman mencakup tiga pilar tak terpisahkan:\n\n- **Keyakinan di dalam hati (*i'tiqad bil qalb*).**\n- **Pengucapan dengan lisan (*iqrar bil lisan*).**\n- **Pengamalan dengan anggota badan (*'amal bil jawarih*).**\n\nIman memiliki sifat dinamis: **bertambah dengan ketaatan** kepada Allah dan **berkurang dengan kemaksiatan**.",
			Arabic:    "الْإِيمَانُ قَوْلٌ وَعَمَلٌ يَزِيدُ وَيَنْقُصُ",
			Latin:     "Al-iimaanu qawlun wa 'amalun yaziidu wa yanqush",
			Translation: "Iman adalah ucapan dan perbuatan, bertambah dan berkurang.",
			Dalil:     "QS. Al-Anfal: 2: \"Sesungguhnya orang-orang yang beriman adalah mereka yang apabila disebut nama Allah gemetarlah hati mereka dan apabila dibacakan ayat-ayat-Nya bertambahlah iman mereka...\"",
			Tip:       "Jauhi pemahaman Murji'ah yang mengeluarkan amal dari hakikat iman dan pemahaman Khawarij yang mengkafirkan pelaku dosa besar.",
		},
		{
			ModuleID:  bySlug["aqidah-salaf"],
			StepOrder: 3,
			Kind:      "teori",
			Title:     "Bahaya Syirik Akbar dan Syirik Ashghar",
			Body:      "Syirik adalah dosa terbesar yang paling dibenci oleh Allah karena merampas hak mutlak peribadatan kepada-Nya:\n\n- **Syirik Akbar (Besar):**\n  - Memalingkan ibadah kepada selain Allah (menyembelih untuk jin, meminta pertolongan kuburan keramat, sihir).\n  - Menghapuskan seluruh amal saleh dan menyebabkan pelakunya kekal di dalam neraka jika meninggal tanpa taubat.\n- **Syirik Ashghar (Kecil):**\n  - Perkara yang menjadi perantara menuju syirik besar, seperti **Riya'** (beramal saleh agar dilihat dan dipuji manusia), sum'ah, dan bersumpah dengan selain nama Allah.",
			Arabic:    "إِنَّ الشِّرْكَ لَظُلْمٌ عَظِيمٌ",
			Latin:     "Innasysyirka ladhulmun 'azhiim",
			Translation: "Sesungguhnya mempersekutukan (Allah) adalah benar-benar kezhaliman yang besar.",
			Dalil:     "QS. Luqman: 13 & QS. An-Nisa: 48: \"Sesungguhnya Allah tidak akan mengampuni dosa syirik, dan Dia mengampuni segala dosa yang selain dari (syirik) itu, bagi siapa yang dikehendaki-Nya.\"",
		},
		{
			ModuleID:  bySlug["aqidah-salaf"],
			StepOrder: 4,
			Kind:      "teori",
			Title:     "Mengenal Tiga Landasan Utama (Al-Ushul Ats-Tsalatsah)",
			Body:      "Tiga perkara pokok yang wajib dipelajari dan diyakini setiap muslim, yang kelak menjadi materi pertanyaan di alam kubur:\n\n1. **Mengenal Allah (Ma'rifatullah):** Mengenal Rabb Pencipta dengan ayat-ayat kauniyah dan wahyu-Nya.\n2. **Mengenal Agama Islam beserta dalil-dalilnya (Ma'rifatu Dinil Islam bil Adillah):** Mencakup tiga tingkatan: Islam, Iman, dan Ihsan.\n3. **Mengenal Nabi Muhammad ﷺ (Ma'rifatu Nabiyyina Muhammad):** Mengenal nasab, kenabian, hijrah, dan risalah yang beliau bawa.",
			Arabic:    "الْأُصُولُ الثَّلَاثَةُ",
			Latin:     "Al-Ushuuluts Tsalaatsah",
			Translation: "Tiga Prinsip Pokok.",
			Dalil:     "HR. Abu Dawud No. 4753 (Shahih): Hadis panjang Barra' bin 'Azib tentang fitnah dan pertanyaan malaikat Munkar dan Nakir di alam barzakh.",
		},

		// ===== PANDUAN SHALAT SESUAI SIFAT NABI =====
		{
			ModuleID:  bySlug["sholat-sifat-nabi"],
			StepOrder: 1,
			Kind:      "sunnah",
			Title:     "Menghadap Kiblat & Mengambil Sutrah",
			Body:      "Panduan awal shalat sesuai tuntunan hadis Shahih:\n\n- Menghadap ke arah kiblat (Ka'bah) dengan seluruh badan.\n- **Mengambil sutrah:** Mendekat ke pembatas di depan tempat shalat (dinding, tiang, tas, atau tongkat) setinggi pelana kuda (kurleb 30-40 cm).\n- Menghalangi siapa pun yang hendak melintas di antara diri mushalli dan sutrahnya.",
			Arabic:    "إِذَا صَلَّى أَحَدُكُمْ فَلْيُصَلِّ إِلَى سُتْرَةٍ وَلْيَدْنُ مِنْهَا",
			Latin:     "Idzaa shallaa ahadukum falyushalli ilaa sutratin walyadnu minhaa",
			Translation: "Jika salah seorang di antara kalian shalat, hendaklah ia shalat menghadap sutrah dan mendekat kepadanya.",
			Dalil:     "HR. Abu Dawud No. 698 (Shahih); HR. Ibnu Majah No. 954.",
		},
		{
			ModuleID:  bySlug["sholat-sifat-nabi"],
			StepOrder: 2,
			Kind:      "praktik",
			Title:     "Posisi Sedekap yang Shahih",
			Body:      "Tata cara meletakkan tangan saat berdiri membaca Al-Fatihah:\n\n- Meletakkan telapak tangan kanan di atas punggung telapak tangan kiri, pergelangan tangan, atau lengan bawah kiri.\n- Menempatkan kedua tangan **di atas dada / bagian dada** dengan posisi yang wajar dan tenang tanpa memaksakan ditarik ke leher atau diturunkan ke bawah pusar.",
			Dalil:     "HR. Abu Dawud No. 759 & An-Nasa'i No. 889 (Shahih dari Wail bin Hujr): \"Kemudian beliau meletakkan tangan kanannya di atas punggung telapak tangan kirinya, pergelangan dan lengannya.\"",
		},
		{
			ModuleID:  bySlug["sholat-sifat-nabi"],
			StepOrder: 3,
			Kind:      "praktik",
			Title:     "Sifat Ruku' yang Rata & Thuma'ninah",
			Body:      "Sifat ruku' Nabi ﷺ yang sempurna:\n\n- Membungkukkan badan hingga **punggung lurus rata**, tidak condong ke atas dan tidak terlalu menunduk ke bawah.\n- Menempatkan kedua telapak tangan di atas lutut seraya **merenggangkan jari-jemari** seakan mencengkeram lutut.\n- Merenggangkan kedua siku menjauh dari lambung.\n- Berdiam sejenak dengan tenang (*thuma'ninah*) seraya membaca tasbih dan doa ruku'.",
			Arabic:    "سُبْحَانَكَ اللَّهُمَّ رَبَّنَا وَبِحَمْدِكَ اللَّهُمَّ اغْفِرْ لِي",
			Latin:     "Subhaanakallaahumma Rabbanaa wa bihamdika Allaahummaghfir lii",
			Translation: "Maha Suci Engkau ya Allah, Rabb kami, dan dengan memuji-Mu ya Allah ampunilah aku.",
			Dalil:     "HR. Bukhari No. 828 & Muslim No. 484; HR. Abu Dawud No. 863 tentang kelurusan punggung Rasulullah ﷺ.",
		},
		{
			ModuleID:  bySlug["sholat-sifat-nabi"],
			StepOrder: 4,
			Kind:      "praktik",
			Title:     "Sifat Sujud, Duduk Iftirasy & Duduk Tawarruk",
			Body:      "Rincian posisi sujud dan duduk dalam shalat:\n\n- **Sujud:** Menempelkan 7 anggota sujud ke lantai, mengangkat siku dari lantai, merapatkan jari-jemari tangan menghadap kiblat sejajar bahu/telinga, dan merapatkan kedua tumit kaki.\n- **Duduk Iftirasy:** Menduduki kaki kiri dan menegakkan kaki kanan (dilakukan saat duduk antara dua sujud dan duduk tasyahud awal).\n- **Duduk Tawarruk:** Menjulurkan kaki kiri di bawah betis kanan dan mendudukkan pantat di lantai (dilakukan saat duduk tasyahud akhir pada shalat 3 atau 4 rakaat).",
			Dalil:     "HR. Bukhari No. 828 (Sifat Shalat Nabi ﷺ dari Abu Humaid As-Sa'idi).",
			Tip:       "Jauhkan lengan dari lantai dan jangan menghamparkan tangan seperti anjing menghamparkan kakinya.",
		},
		{
			ModuleID:  bySlug["sholat-sifat-nabi"],
			StepOrder: 5,
			Kind:      "sunnah",
			Title:     "Dzikir Shahih Setelah Salam",
			Body:      "Rangkaian dzikir ma'tsur yang dibaca seusai shalat fardhu:\n\n1. Membaca istighfar 3 kali: `Astaghfirullah`.\n2. Membaca doa keselamatan: `Allahumma Antas Salam wa minkas salam tabaarakta yaa Dzal Jalaali wal Ikraam`.\n3. Membaca kalimat tauhid dan pujian syukur.\n4. Bertasbih (*Subhanallah* 33x), bertahmid (*Alhamdulillah* 33x), dan bertakbir (*Allahu Akbar* 33x), lalu menggenapkan ke-100 dengan tahlil.\n5. Membaca **Ayat Kursi** dan surah Al-Ikhlas, Al-Falaq, An-Nas.",
			Arabic:    "أَسْتَغْفِرُ اللَّهَ (٣x)، اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ",
			Latin:     "Astaghfirullah (3x), Allahumma antas salaamu wa minkas salaam, tabaarakta yaa dzal jalaali wal ikraam",
			Translation: "Aku memohon ampunan kepada Allah (3x). Ya Allah, Engkaulah As-Salam (Yang Maha Menyelamatkan), dan dari-Mulah keselamatan. Maha Berkah Engkau wahai Rabb Pemilik keagungan dan kemuliaan.",
			Dalil:     "HR. Muslim No. 591, 597 & HR. An-Nasa'i dalam 'Amalul Yaumi wal Lailah No. 100.",
		},

		// ===== DZIKIR & DOA HARIAN =====
		{
			ModuleID:  bySlug["dzikir-doa-harian"],
			StepOrder: 1,
			Kind:      "teori",
			Title:     "Keutamaan Dzikir & Adab Berdoa",
			Body:      "**Dzikirullah** adalah amalan harian paling ringan dengan pahala timbangan paling berat:\n\nAdab berdoa yang mustajab:\n- Ikhlas semata-mata mengharap ridha Allah.\n- Memulai doa dengan memuji dan menyanjung Allah (*tahmid* & *tasbih*), lalu membaca shalawat atas Nabi ﷺ.\n- Menghadap kiblat dan mengangkat kedua telapak tangan setinggi dada.\n- Memohon dengan penuh harap (*raghab*) dan cemas (*rahab*), serta berbaik sangka bahwa doa pasti dikabulkan.",
			Arabic:    "أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ",
			Latin:     "Alaa bidzikrillaahi tathma'innul quluub",
			Translation: "Ingatlah, hanya dengan mengingat Allah hati menjadi tenteram.",
			Dalil:     "QS. Ar-Ra'd: 28; HR. Tirmidzi No. 3477 (Shahih).",
		},
		{
			ModuleID:  bySlug["dzikir-doa-harian"],
			StepOrder: 2,
			Kind:      "praktik",
			Title:     "Sayyidul Istighfar & Dzikir Pagi Petang",
			Body:      "**Sayyidul Istighfar** adalah puncak doa permohonan ampunan yang memuat pengakuan tauhid, nikmat, dan kelemahan hamba:\n\nWaktu pelaksanaan dzikir pagi & petang:\n- **Dzikir pagi:** Dibaca sejak terbit fajar shadiq (Shubuh) hingga terbit matahari atau menjelang siang.\n- **Dzikir petang:** Dibaca sejak masuk waktu Ashar hingga matahari tenggelam atau awal malam.\n- Keutamaan: Menjadi benteng perlindungan dari marabahaya, sihir, dan godaan setan sepanjang hari.",
			Arabic:    "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ",
			Latin:     "Allaahumma Anta Rabbii laa ilaaha illaa Anta khalaqtanii wa ana 'abduka wa ana 'alaa 'ahdika wa wa'dika mastatha'tu, a'uudzu bika min syarri maa shana'tu, abuu'u laka bini'matika 'alayya wa abuu'u bidzanbii faghfir lii fa-innahu laa yaghfirudz dzunuuba illaa Anta",
			Translation: "Ya Allah, Engkau adalah Rabbku, tiada ilah yang berhak disembah selain Engkau. Engkaulah yang menciptakanku dan aku adalah hamba-Mu. Aku akan setia pada janji-Mu semampuku. Aku berlindung kepada-Mu dari keburukan yang telah kuperbuat. Aku mengakui nikmat-Mu kepadaku dan aku mengakui dosaku, maka ampunilah aku. Sesungguhnya tiada yang mengampuni dosa-dosa selain Engkau.",
			Dalil:     "HR. Bukhari No. 6306.",
			Tip:       "Baca dzikir pagi setelah shalat Shubuh hingga terbit matahari, dan dzikir petang setelah shalat Ashar hingga matahari tenggelam.",
		},
		{
			ModuleID:  bySlug["dzikir-doa-harian"],
			StepOrder: 3,
			Kind:      "praktik",
			Title:     "Doa Keluar & Masuk Rumah",
			Body:      "Menjaga sunnah dzikir saat beraktivitas keluar dan masuk rumah:\n\n- **Saat keluar rumah:** Membaca `Bismillahi tawakkaltu 'alallah laa hawla wa laa quwwata illaa billaah` agar senantiasa dipandu, dicukupi, dan dilindungi dari gangguan setan.\n- **Saat masuk rumah:** Mengucapkan salam dan basmalah agar setan tidak ikut bermalam dan makan di dalam rumah.",
			Arabic:    "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
			Latin:     "Bismillaahi tawakkaltu 'alallaahi wa laa hawla wa laa quwwata illaa billaah",
			Translation: "Dengan nama Allah, aku bertawakkal kepada Allah, tiada daya dan kekuatan kecuali dengan pertolongan Allah.",
			Dalil:     "HR. Abu Dawud No. 5095, Tirmidzi No. 3426 (Shahih): \"Dikatakan kepadanya: Kamu telah diberi petunjuk, dicukupi, dan dilindungi, lalu setan menyingkir darinya.\"",
		},
		{
			ModuleID:  bySlug["dzikir-doa-harian"],
			StepOrder: 4,
			Kind:      "praktik",
			Title:     "Doa Masuk & Keluar Masjid",
			Body:      "Adab dan doa saat mendatangi rumah Allah (masjid):\n\n- **Masuk masjid:** Mendahulukan kaki kanan seraya bershalawat dan memohon dibukakan **pintu-pintu rahmat Allah**.\n- Melakukan shalat sunnah **Tahiyyatul Masjid** 2 rakaat sebelum duduk.\n- **Keluar masjid:** Mendahulukan kaki kiri seraya memohon **limpahan karunia (*fadhl*) Allah**.",
			Arabic:    "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ - اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ",
			Latin:     "Allaahummaftah lii abwaaba rahmatik - Allaahumma innii as-aluka min fadhlik",
			Translation: "Ya Allah, bukakanlah untukku pintu-pintu rahmat-Mu (masuk) - Ya Allah, sesungguhnya aku memohon sebagian dari karunia-Mu (keluar).",
			Dalil:     "HR. Muslim No. 713.",
		},
		{
			ModuleID:  bySlug["dzikir-doa-harian"],
			StepOrder: 5,
			Kind:      "praktik",
			Title:     "Adab & Doa Sebelum Tidur dan Bangun Tidur",
			Body:      "Sunnah Rasulullah ﷺ sebelum dan sesudah tidur:\n\n- Berwudhu seperti hendak shalat sebelum naik ke tempat tidur.\n- Mengibaskan sprei/tempat tidur sebanyak tiga kali.\n- Mengumpulkan kedua telapak tangan, membaca Surah **Al-Ikhlas, Al-Falaq, An-Nas**, lalu meniupkannya dan mengusapkan ke seluruh tubuh yang terjangkau (dilakukan 3 kali).\n- Membaca **Ayat Kursi** dan dua ayat terakhir Surah Al-Baqarah.\n- Berbaring miring di atas **sisi tubuh sebelah kanan** menghadap kiblat seraya membaca doa tidur.",
			Arabic:    "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا - الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
			Latin:     "Bismika Allaahumma amuutu wa ahyaa - Alhamdulillaahil ladzii ahyaanaa ba'da maa amaatanaa wa ilaihin nusyuur",
			Translation: "Dengan nama-Mu ya Allah aku mati dan aku hidup - Segala puji bagi Allah yang menghidupkan kami setelah mematikan kami dan kepada-Nya kami kembali.",
			Dalil:     "HR. Bukhari No. 6312 & 6314.",
		},

		// ===== SUJUD TILAWAH =====
		{
			ModuleID:  bySlug["sujud-tilawah"],
			StepOrder: 1,
			Kind:      "rukun",
			Title:     "Pengertian, Hukum & Keutamaan",
			Body:      "**Sujud Tilawah** adalah sujud satu kali saat membaca atau mendengar ayat sajdah dari Al-Qur'an.\n\n- **Hukum (Jumhur Ulama):** Sunnah Mu'akkadah (sangat dianjurkan), bukan wajib.\n- **Keutamaan:** Setan menangis tersingkir ketika anak Adam bersujud saat membaca ayat sajdah.",
			Arabic:    "إِذَا قَرَأَ ابْنُ آدَمَ السَّجْدَةَ فَسَجَدَ اعْتَزَلَ الشَّيْطَانُ يَبْكِي يَقُولُ يَا وَيْلَهُ أُمِرَ ابْنُ آدَمَ بِالسُّجُودِ فَسَجَدَ فَلَهُ الْجَنَّةُ وَأُمِرْتُ بِالسُّجُودِ فَأَبَيْتُ فَلِيَ النَّارُ",
			Latin:     "Idzaa qara'abnu Aadamas sajdata fasajada 'tazalasy syaithaanu yabkii yaquulu yaa wailahu, umirabnu Aadama bis sujuudi fasajada falahul jannah, wa umirtu bis sujuudi fa-abaitu faliyan naar",
			Translation: "Jika anak Adam membaca ayat sajdah lalu bersujud, setan menyingkir sambil menangis seraya berkata: 'Celakalah aku! Anak Adam diperintahkan bersujud lalu ia sujud maka baginya surga, sedangkan aku diperintahkan bersujud namun aku membangkang maka bagiku neraka.'",
			Dalil:     "HR. Bukhari No. 1073; HR. Muslim No. 81 & 577.",
			Tip:       "Hadirkan kerendahan hati saat mendengar ayat-ayat keagungan Allah.",
		},
		{
			ModuleID:  bySlug["sujud-tilawah"],
			StepOrder: 2,
			Kind:      "rukun",
			Title:     "Mengenal 15 Ayat Sajdah Al-Qur'an",
			Body:      "Terdapat **15 ayat sajdah** yang disepakati oleh jumhur ulama:\n\n1. Al-A'raf (7:206)\n2. Ar-Ra'd (13:15)\n3. An-Nahl (16:50)\n4. Al-Isra' (17:109)\n5. Maryam (19:58)\n6. Al-Hajj ayat pertama (22:18)\n7. Al-Hajj ayat kedua (22:77)\n8. Al-Furqan (25:60)\n9. An-Naml (27:26)\n10. As-Sajdah (32:15)\n11. Shad (38:24)\n12. Fushshilat (41:38)\n13. An-Najm (53:62)\n14. Al-Insyiqaq (84:21)\n15. Al-'Alaq (96:19)",
			Dalil:     "Kutubus Sittah (Bukhari, Muslim, Abu Dawud, Tirmidzi, An-Nasa'i, Ibnu Majah).",
			Tip:       "Perhatikan simbol kubah/sajdah di mushaf standar Madinah dan Kemenag RI.",
		},
		{
			ModuleID:  bySlug["sujud-tilawah"],
			StepOrder: 3,
			Kind:      "praktik",
			Title:     "Kaifiyah di Dalam Sholat",
			Body:      "Tata cara sujud tilawah ketika sedang sholat:\n\n1. Selesai membaca ayat sajdah, langsung **bertakbir intiqal (Allahu Akbar)** menuju sujud tanpa ruku'.\n2. Melakukan sujud 1 kali dengan thuma'ninah.\n3. Membaca tasbih sujud atau doa sujud tilawah.\n4. **Bertakbir intiqal saat bangkit** berdiri kembali ke posisi berdiri.\n5. Melanjutkan bacaan surah atau langsung ruku'.\n\n*Kaidah Makmum:* Wajib mengikuti imam (mutaba'ah). Jika imam tidak sujud, makmum tidak boleh sujud sendiri.",
			Dalil:     "HR. Bukhari No. 1070; HR. Muslim No. 575; Fatwa Lajnah Daimah No. 10214.",
			Tip:       "Jika sholat berjamaah, imam dianjurkan memberi isyarat atau memilih ayat yang makruf agar makmum tidak bingung mengira ruku'.",
		},
		{
			ModuleID:  bySlug["sujud-tilawah"],
			StepOrder: 4,
			Kind:      "praktik",
			Title:     "Kaifiyah di Luar Sholat & Doa",
			Body:      "Tata cara sujud tilawah di luar sholat:\n\n1. Memenuhi syarat bersuci (wudhu), menutup aurat, dan menghadap kiblat.\n2. Berniat sujud tilawah di dalam hati.\n3. **Bertakbir lalu langsung sujud satu kali** (tidak disyariatkan takbiratul ihram pembuka dan tidak ada salam).\n4. Membaca doa yang diajarkan Rasulullah ﷺ:\n\n*Sajada wajhiya lilladzii khalaqahu wa syaqqa sam'ahu wa basharahu bihawlihi wa quwwatih, fatabaarakallaahu ahsanul khaaliqiin.*\n\n5. Bangkit dari sujud tanpa takbir dan tanpa salam.",
			Arabic:    "سَجَدَ وَجْهِي لِلَّذِي خَلَقَهُ وَشَقَّ سَمْعَهُ وَبَصَرَهُ بِحَوْلِهِ وَقُوَّتِهِ فَتَبَارَكَ اللَّهُ أَحْسَنُ الْخَالِقِينَ",
			Latin:     "Sajada wajhiya lilladzii khalaqahu wa syaqqa sam'ahu wa basharahu bihawlihi wa quwwatih, fatabaarakallaahu ahsanul khaaliqiin",
			Translation: "Wajahku bersujud kepada Dzat yang menciptakannya, membukakan pendengaran dan penglihatannya dengan daya dan kekuatan-Nya. Maka Maha Suci Allah sebaik-baik Pencipta.",
			Dalil:     "HR. Abu Dawud No. 1406 & 1414; HR. Tirmidzi No. 580 (Shahih).",
			Tip:       "Boleh juga membaca doa catatan pahala Nabi Dawud (HR. Tirmidzi No. 579).",
		},
	}

	for i := range steps {
		if steps[i].ModuleID == 0 {
			continue
		}
		var existing model.LessonStep
		if err := db.Where("module_id = ? AND step_order = ?", steps[i].ModuleID, steps[i].StepOrder).First(&existing).Error; err == nil {
			db.Model(&existing).Updates(map[string]interface{}{
				"kind":        steps[i].Kind,
				"title":       steps[i].Title,
				"body":        steps[i].Body,
				"arabic":      steps[i].Arabic,
				"latin":       steps[i].Latin,
				"translation": steps[i].Translation,
				"dalil":       steps[i].Dalil,
				"tip":         steps[i].Tip,
			})
		} else {
			db.Create(&steps[i])
		}
	}
}
