package migrations

import (
	"github.com/agambondan/islamic-explorer/app/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

func SeedLessons(db *gorm.DB) {
	modules := []model.LessonModule{
		{Slug: "wudhu", Title: "Tata Cara Wudhu", Description: "Belajar wudhu tahap demi tahap, lengkap dengan bacaan Arab, dalil, dan adab yang disunnahkan.", Category: "Fiqh Ibadah", Level: "Pemula", EstimatedMinutes: 8, Icon: "wudhu", Order: 1},
		{Slug: "sholat", Title: "Tata Cara Sholat", Description: "Panduan gerakan, bacaan rukun dan sunnah, lengkap dengan dalil Quran-Hadis.", Category: "Fiqh Ibadah", Level: "Pemula", EstimatedMinutes: 15, Icon: "sholat", Order: 2},
		{Slug: "adzan-iqomah", Title: "Mengenal Adzan & Iqomah", Description: "Makna, lafaz lengkap, urutan rukun, dan adab muadzin.", Category: "Fiqh Ibadah", Level: "Pemula", EstimatedMinutes: 10, Icon: "adzan", Order: 3},
		{Slug: "puasa", Title: "Fikih Puasa Ramadan", Description: "Syarat, rukun, pembatal, dan sunnah puasa, lengkap dengan contoh aplikatif.", Category: "Fiqh Ibadah", Level: "Menengah", EstimatedMinutes: 12, Icon: "puasa", Order: 4},
		{Slug: "zakat", Title: "Zakat Fitrah & Mal", Description: "Nisab, haul, dan 8 asnaf penerima zakat.", Category: "Fiqh Ibadah", Level: "Menengah", EstimatedMinutes: 12, Icon: "zakat", Order: 5},
		{Slug: "tajwid", Title: "Tajwid Dasar", Description: "Hukum nun mati/tanwin, mim mati, dan mad dengan contoh ayat.", Category: "Al-Quran", Level: "Menengah", EstimatedMinutes: 18, Icon: "tajwid", Order: 6},
		{Slug: "rukun-iman", Title: "Rukun Iman", Description: "Enam pilar keimanan dengan dalil Quran-Hadis.", Category: "Aqidah", Level: "Pemula", EstimatedMinutes: 10, Icon: "iman", Order: 7},
		{Slug: "adab-talab-ilmu", Title: "Adab Menuntut Ilmu", Description: "Etika menuntut ilmu, niat yang benar, dan keutamaan tholabul 'ilmi.", Category: "Adab", Level: "Pemula", EstimatedMinutes: 8, Icon: "book", Order: 8},
		{Slug: "tahsin-tajwid", Title: "Tahsin & Tajwid Dasar", Description: "Memperbaiki bacaan Al-Quran: makhraj, sifat huruf, hukum tajwid, dan latihan praktis.", Category: "Al-Quran", Level: "Pemula", EstimatedMinutes: 20, Icon: "quran", Order: 9},
		{Slug: "aqidah-salaf", Title: "Aqidah Salaf & Rukun Iman", Description: "Pemahaman mendalam enam rukun iman mengikuti metodologi salafus shalih.", Category: "Aqidah", Level: "Menengah", EstimatedMinutes: 15, Icon: "aqidah", Order: 10},
		{Slug: "sholat-sifat-nabi", Title: "Panduan Shalat Sesuai Sifat Nabi ﷺ", Description: "Rinci gerakan, bacaan, dan adab shalat sesuai hadis Sifat Shalat Nabi ﷺ.", Category: "Fiqh Ibadah", Level: "Menengah", EstimatedMinutes: 18, Icon: "sholat", Order: 11},
		{Slug: "dzikir-doa-harian", Title: "Dzikir & Doa Harian", Description: "Dzikir pagi-petang, doa setelah shalat, doa sehari-hari, dan wirid istiqamah.", Category: "Ibadah Harian", Level: "Pemula", EstimatedMinutes: 12, Icon: "dzikir", Order: 12},
	}
	for i := range modules {
		db.Clauses(clause.OnConflict{
			Columns: []clause.Column{{Name: "slug"}},
			DoUpdates: clause.AssignmentColumns([]string{
				"title", "description", "category", "level", "estimated_minutes", "icon", "order", "updated_at",
			}),
		}).Create(&modules[i])
	}

	var stored []model.LessonModule
	db.Find(&stored)
	bySlug := map[string]int{}
	for _, m := range stored {
		if m.ID != nil {
			bySlug[m.Slug] = *m.ID
		}
	}

	steps := []model.LessonStep{
		// ===== WUDHU =====
		{ModuleID: bySlug["wudhu"], StepOrder: 1, Kind: "rukun", Title: "Niat di Hati & Membaca Bismillah", Body: "Niat wudhu letaknya di dalam hati tanpa dilafazkan lisan, karena tidak ada dalil shahih bahwa Rasulullah ﷺ melafazkan niat wudhu. Disunnahkan mengawali wudhu dengan membaca basmalah.", Arabic: "بِسْمِ اللَّهِ", Latin: "Bismillah", Translation: "Dengan menyebut nama Allah.", Dalil: "HR. Abu Dawud No. 101, Tirmidzi No. 25, Ibnu Majah No. 399 (Shahih): \"Tidak ada wudhu bagi orang yang tidak menyebut nama Allah padanya.\"", Tip: "Hadirkan niat di dalam hati untuk bersuci dari hadas kecil, lalu ucapkan basmalah sebelum mulai membasuh."},
		{ModuleID: bySlug["wudhu"], StepOrder: 2, Kind: "rukun", Title: "Membasuh Wajah", Body: "Siramkan air ke seluruh wajah: dari dahi tempat tumbuhnya rambut sampai dagu, dan dari telinga kanan ke telinga kiri. Wajah adalah anggota wudhu pertama yang wajib dibasuh.", Dalil: "QS. Al-Maidah: 6: \"...فَاغْسِلُوا وُجُوهَكُمْ...\" (Maka basuhlah wajahmu).", Tip: "Pastikan seluruh bagian wajah dan jenggot/rambut tipis basah merata."},
		{ModuleID: bySlug["wudhu"], StepOrder: 3, Kind: "rukun", Title: "Membasuh Kedua Tangan hingga Siku", Body: "Membasuh tangan mulai ujung jari hingga melewati siku. Dimulai dari tangan kanan terlebih dahulu sebanyak tiga kali, lalu tangan kiri dengan cara yang sama, sambil menyela-nyela jari jemari.", Dalil: "QS. Al-Maidah: 6: \"...وَأَيْدِيَكُمْ إِلَى الْمَرَافِقِ...\" (Dan tanganmu sampai ke siku); HR. Bukhari No. 159 (wudhu Utsman bin Affan).", Tip: "Jangan ada doa khusus per-anggota wudhu karena tidak ada riwayat shahih dari Nabi ﷺ."},
		{ModuleID: bySlug["wudhu"], StepOrder: 4, Kind: "rukun", Title: "Mengusap Kepala", Body: "Mengusap seluruh kepala sekali: menjalankan kedua telapak tangan dari depan kepala hingga ke tengkuk, lalu mengembalikannya ke tempat semula.", Dalil: "QS. Al-Maidah: 6: \"...وَامْسَحُوا بِرُءُوسِكُمْ...\" (Dan usaplah kepalamu); HR. Bukhari No. 185."},
		{ModuleID: bySlug["wudhu"], StepOrder: 5, Kind: "sunnah", Title: "Mengusap Kedua Telinga", Body: "Mengusap kedua telinga bersamaan setelah mengusap kepala dengan sisa air kepala: jari telunjuk membersihkan bagian dalam telinga, dan ibu jari membersihkan daun telinga bagian luar.", Dalil: "HR. Abu Dawud No. 135, Tirmidzi No. 36 (Shahih): \"Kedua telinga termasuk bagian dari kepala.\""},
		{ModuleID: bySlug["wudhu"], StepOrder: 6, Kind: "rukun", Title: "Membasuh Kedua Kaki hingga Mata Kaki", Body: "Membasuh kedua kaki hingga mata kaki, dimulai dari kaki kanan sebanyak tiga kali lalu kaki kiri, serta menyela-nyela jari kaki dengan jari kelingking.", Dalil: "QS. Al-Maidah: 6: \"...وَأَرْجُلَكُمْ إِلَى الْكَعْبَيْنِ...\" (Dan kakimu sampai ke kedua mata kaki); HR. Bukhari No. 165: \"Celakalah tumit-tumit (yang tidak basah) dari api neraka.\"", Tip: "Pastikan tumit dan lipatan mata kaki terkena air secara sempurna."},
		{ModuleID: bySlug["wudhu"], StepOrder: 7, Kind: "sunnah", Title: "Membaca Doa Setelah Wudhu", Body: "Setelah selesai wudhu, disunnahkan membaca doa persaksian tauhid dan permohonan ampunan serta kesucian.", Arabic: "أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ، اللَّهُمَّ اجْعَلْنِي مِنَ التَّوَّابِينَ وَاجْعَلْنِي مِنَ الْمُتَطَهِّرِينَ", Latin: "Asyhadu allaa ilaaha illallaah wahdahu laa syariika lah, wa asyhadu anna Muhammadan 'abduhu wa rasuuluh. Allaahummaj'alnii minat tawwaabiina waj'alnii minal mutathahhiriin", Translation: "Aku bersaksi bahwa tidak ada sesembahan yang berhak disembah selain Allah semata, tidak ada sekutu bagi-Nya. Dan aku bersaksi bahwa Muhammad adalah hamba dan utusan-Nya. Ya Allah, jadikanlah aku termasuk orang-orang yang bertaubat dan jadikanlah aku termasuk orang-orang yang menyucikan diri.", Dalil: "HR. Muslim No. 234 & HR. Tirmidzi No. 55 (Shahih): Dibukakan baginya delapan pintu surga."},

		{ModuleID: bySlug["sholat"], StepOrder: 1, Kind: "rukun", Title: "Takbiratul Ihram", Body: "Berdiri tegak menghadap kiblat, angkat kedua tangan sejajar telinga (laki-laki) atau sejajar bahu (perempuan), lalu bertakbir.", Arabic: "اللَّهُ أَكْبَرُ", Latin: "Allahu Akbar", Translation: "Allah Maha Besar.", Dalil: "HR. Bukhari No. 735: Panduan posisi tangan dan takbir pembuka shalat.", Tip: "Pastikan tumit rapat, pandangan ke tempat sujud, dan sudah berniat di hati untuk shalat tertentu."},
		{ModuleID: bySlug["sholat"], StepOrder: 2, Kind: "rukun", Title: "Membaca Al-Fatihah", Body: "Surat wajib dalam tiap rakaat setelah takbiratul ihram dan berdiri. Tidak sah shalat tanpa membacanya bagi imam maupun munfarid.", Arabic: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ ۝ الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ ۝ الرَّحْمَٰنِ الرَّحِيمِ ۝ مَالِكِ يَوْمِ الدِّينِ ۝ إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ ۝ اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ ۝ صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ", Latin: "Bismillahirrahmanirrahim. Alhamdu lillahi rabbil 'aalamin. Arrahmanirrahim. Maaliki yawmid diin. Iyyaaka na'budu wa iyyaaka nasta'iin. Ihdinash shirathal mustaqiim. Shirathal ladziina an'amta 'alaihim ghairil maghdhuubi 'alaihim wa ladhdhaalliin", Translation: "Dengan nama Allah Yang Maha Pengasih lagi Maha Penyayang. Segala puji bagi Allah, Tuhan semesta alam. Yang Maha Pengasih lagi Maha Penyayang. Yang menguasai Hari Pembalasan. Hanya kepada Engkaulah kami menyembah dan hanya kepada Engkaulah kami memohon pertolongan. Tunjukilah kami jalan yang lurus. (Yaitu) jalan orang-orang yang telah Engkau beri nikmat, bukan (jalan) mereka yang dimurkai dan bukan (pula jalan) mereka yang sesat.", Dalil: "HR. Bukhari No. 756; HR. Muslim No. 395: \"Tidak sah shalatnya orang yang tidak membaca Al-Fatihah.\""},
		{ModuleID: bySlug["sholat"], StepOrder: 3, Kind: "sunnah", Title: "Membaca Surat Pendamping", Body: "Setelah Al-Fatihah, disunnahkan membaca ayat atau surat lain. Bacaan diselingi dengan jeda yang cukup agar bisa bernapas.", Tip: "Untuk pemula, surat pendek seperti Al-Ikhlas, Al-Falaq, dan An-Nas cukup mudah untuk diamalkan."},
		{ModuleID: bySlug["sholat"], StepOrder: 4, Kind: "rukun", Title: "Ruku' dengan Tuma'ninah", Body: "Bungkukkan badan, tangan di lutut, punggung rata (tidak bengkok), dan kepala sejajar punggung. Saat ruku' membaca tasbih minimal tiga kali.", Arabic: "سُبْحَانَ رَبِّيَ الْعَظِيمِ", Latin: "Subhaana Rabbiyal 'Adziim", Translation: "Maha Suci Tuhanku Yang Maha Agung.", Dalil: "HR. Bukhari No. 816: \"Lalu ruku'lah dan tuma'ninahlah ketika ruku'.\"", Tip: "Tuma'ninah berarti diam sejenak (sekitar satu kali bacaan Subhanallah) di setiap perpindahan gerakan."},
		{ModuleID: bySlug["sholat"], StepOrder: 5, Kind: "rukun", Title: "Iktidal dengan Tuma'ninah", Body: "Bangun dari ruku' hingga berdiri tegak kembali. Membaca doa iktidal.", Arabic: "سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ، رَبَّنَا لَكَ الْحَمْدُ", Latin: "Sami'allaahu liman hamidah, Rabbanaa lakal hamdu", Translation: "Allah mendengar orang yang memuji-Nya. Ya Tuhan kami, bagi-Mu segala puji.", Dalil: "HR. Bukhari No. 789: Bacaan imam dan makmum."},
		{ModuleID: bySlug["sholat"], StepOrder: 6, Kind: "rukun", Title: "Sujud dengan Tuma'ninah", Body: "Turun hingga tujuh anggota sujud menyentuh lantai: dahi (termasuk hidung), telapak tangan, lutut, dan kaki. Saat sujud membaca tasbih minimal tiga kali.", Arabic: "سُبْحَانَ رَبِّيَ الْأَعْلَى", Latin: "Subhaana Rabbiyal A'laa", Translation: "Maha Suci Tuhanku Yang Maha Tinggi.", Dalil: "HR. Muslim No. 497: \"Tujuh anggota badan bersujud: dahi (termasuk hidung), dua telapak tangan, dua lutut, dan ujung dua kaki.\""},
		{ModuleID: bySlug["sholat"], StepOrder: 7, Kind: "rukun", Title: "Duduk di Antara Dua Sujud", Body: "Setelah sujud, duduk iftirasy (dengan kaki kiri di bawah, kanan tegak) sejenak. Membaca doa antara dua sujud.", Arabic: "رَبِّ اغْفِرْ لِي، رَبِّ اغْفِرْ لِي", Latin: "Rabbighfir lii, Rabbighfir lii", Translation: "Ya Tuhanku, ampunilah aku. Ya Tuhanku, ampunilah aku.", Dalil: "HR. Abu Dawud No. 874 (Hasan): Bacaan duduk di antara dua sujud."},
		{ModuleID: bySlug["sholat"], StepOrder: 8, Kind: "rukun", Title: "Tasyahud Akhir", Body: "Duduk dengan posisi tawarruk (pantat kiri di atas kaki kiri, kanan tegak) dan membaca tahiyat. Ini rukun yang tidak boleh ditinggalkan.", Arabic: "التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ، السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ، السَّلَامُ عَلَيْنَا وَعَلَى عِبَادِ اللَّهِ الصَّالِحِينَ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا رَسُولُ اللَّهِ", Latin: "Attahiyyaatu lillaahi wash shalawaatu wat thayyibaat. Assalaamu 'alaika ayyuhan nabiyyu wa rahmatullaahi wa barakaatuh. Assalaamu 'alainaa wa 'alaa 'ibaadillaahish shaalihiin. Asyhadu allaa ilaaha illallah wa asyhadu anna Muhammadan rasuulullah", Translation: "Segala penghormatan, shalat, dan kebaikan hanya milik Allah. Semoga keselamatan, rahmat, dan keberkahan Allah tercurah kepadamu wahai Nabi. Keselamatan tercurah kepada kami dan kepada hamba-hamba Allah yang shalih. Aku bersaksi bahwa tiada ilah yang berhak disembah selain Allah, dan aku bersaksi bahwa Muhammad adalah utusan Allah.", Dalil: "HR. Muslim No. 402: \"Jika kamu duduk (tasyahud), bacalah tahiyat.\""},
		{ModuleID: bySlug["sholat"], StepOrder: 9, Kind: "rukun", Title: "Shalawat Nabi", Body: "Setelah tahiyat, lanjutkan dengan shalawat atas Nabi ﷺ. Ini bagian dari rukun menurut sebagian ulama.", Arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ. اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ", Latin: "Allahumma shalli 'ala Muhammad wa 'ala aali Muhammad, kama shallayta 'ala Ibraahiim wa 'ala aali Ibraahiim, innaka hamiidum majiid. Allahumma baarik 'ala Muhammad wa 'ala aali Muhammad, kama baarakta 'ala Ibraahiim wa 'ala aali Ibraahiim, innaka hamiidum majiid", Translation: "Ya Allah, berilah shalawat kepada Muhammad dan keluarga Muhammad, sebagaimana Engkau memberi shalawat kepada Ibrahim dan keluarga Ibrahim. Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia. Ya Allah, berilah berkah kepada Muhammad dan keluarga Muhammad, sebagaimana Engkau memberi berkah kepada Ibrahim dan keluarga Ibrahim. Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia.", Dalil: "HR. Muslim No. 405: \"Bacalah shalawat atas aku, karena shalawatmu sampai kepadaku.\""},
		{ModuleID: bySlug["sholat"], StepOrder: 10, Kind: "rukun", Title: "Salam Penutup", Body: "Akhiri shalat dengan menoleh ke kanan dan ke kiri sambil mengucapkan salam.", Arabic: "السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ", Latin: "Assalaamu 'alaikum wa rahmatullah", Translation: "Semoga keselamatan dan rahmat Allah tercurah kepada kalian.", Dalil: "HR. Muslim No. 582: Panduan salam penutup shalat."},

		{ModuleID: bySlug["adzan-iqomah"], StepOrder: 1, Kind: "teori", Title: "Pengertian Adzan", Body: "Adzan adalah panggilan untuk menunaikan shalat fardhu, berisi kalimat-kalimat yang disyariatkan untuk mengingatkan waktu shalat.", Arabic: "الْأَذَانُ", Latin: "Al-adzaan", Translation: "Adzan (panggilan shalat).", Dalil: "HR. Bukhari No. 604: Awal pensyariatan adzan adalah pada tahun pertama hijriah setelah Rasulullah ﷺ bermusyawarah dengan para sahabat."},
		{ModuleID: bySlug["adzan-iqomah"], StepOrder: 2, Kind: "teori", Title: "Syarat-syarat Muadzin", Body: "Disunnahkan muadzin adalah muslim yang baligh, berakal, laki-laki, dan memahami hukum adzan. Dianjurkan pula memiliki suara yang merdu.", Dalil: "HR. Abu Dawud No. 5148 (Hasan): Disunnahkan agar muadzin adalah orang yang paling memahami waktu dan paling bagus suaranya."},
		{ModuleID: bySlug["adzan-iqomah"], StepOrder: 3, Kind: "praktik", Title: "Lafaz Adzan Lengkap", Body: "Adzan terdiri dari 15 kalimat dengan susunan berikut, dibaca dua kali untuk kalimat Hayya 'alas shalah dan Hayya 'alal falah.", AudioURL: "/audio/adzan.mp3", Arabic: "اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ. أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ. أَشْهَدُ أَنَّ مُحَمَّدًا رَسُولُ اللَّهِ، أَشْهَدُ أَنَّ مُحَمَّدًا رَسُولُ اللَّهِ. حَيَّ عَلَى الصَّلَاةِ، حَيَّ عَلَى الصَّلَاةِ. حَيَّ عَلَى الْفَلَاحِ، حَيَّ عَلَى الْفَلَاحِ. اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ. لَا إِلَهَ إِلَّا اللَّهُ", Latin: "Allahu Akbar Allahu Akbar, Allahu Akbar Allahu Akbar. Asyhadu allaa ilaaha illallah, asyhadu allaa ilaaha illallah. Asyhadu anna Muhammadan rasuulullah, asyhadu anna Muhammadan rasuulullah. Hayya 'alash shalah, hayya 'alash shalah. Hayya 'alal falah, hayya 'alal falah. Allahu Akbar Allahu Akbar. Laa ilaaha illallah", Translation: "Allah Maha Besar (4x). Aku bersaksi bahwa tiada ilah selain Allah (2x). Aku bersaksi bahwa Muhammad utusan Allah (2x). Marilah menuju shalat (2x). Marilah menuju kejayaan (2x). Allah Maha Besar (2x). Tiada ilah selain Allah.", Dalil: "HR. Muslim No. 379: Lafaz adzan sesuai sunnah."},
		{ModuleID: bySlug["adzan-iqomah"], StepOrder: 4, Kind: "praktik", Title: "Shalawat Setelah Adzan", Body: "Setelah muadzin selesai, disunnahkan bagi yang mendengar untuk membaca shalawat atas Nabi ﷺ, lalu memohon syafaat.", Arabic: "اللَّهُمَّ رَبَّ هَذِهِ الدَّعْوَةِ التَّامَّةِ وَالصَّلَاةِ الْقَائِمَةِ آتِ مُحَمَّدًا الْوَسِيلَةَ وَالْفَضِيلَةَ وَابْعَثْهُ مَقَامًا مَحْمُودًا الَّذِي وَعَدْتَهُ", Latin: "Allahumma Rabba hadzihid da'watit taammah wash shalaatil qaa'imah, aati Muhammadanil wasiilata wal fadhilah, wab'atshu maqaamam mahmuudanil ladzii wa'adtah", Translation: "Ya Allah, Tuhan pemilik seruan yang sempurna ini dan shalat yang akan didirikan, berikanlah kepada Muhammad wasilah (kedudukan tinggi) dan keutamaan, dan bangkitkanlah beliau ke tempat yang terpuji yang telah Engkau janjikan.", Dalil: "HR. Bukhari No. 614: Doa setelah adzan.", Tip: "Wassilah adalah tempat yang tinggi di surga. Rasulullah ﷺ sendiri bersabda bahwa wasilah hanya akan diberikan kepada satu hamba, dan beliau berharap itu adalah dirinya."},
		{ModuleID: bySlug["adzan-iqomah"], StepOrder: 5, Kind: "praktik", Title: "Iqomah", Body: "Iqomah mirip adzan, hanya ada beberapa perbedaan: dibaca lebih pelan, shahadat hanya satu kali, ditambah 'Qad qaamatish shalah' dua kali di antara Hayya 'alal falah dan takbir penutup.", Arabic: "قَدْ قَامَتِ الصَّلَاةُ، قَدْ قَامَتِ الصَّلَاةُ", Latin: "Qad qaamatish shalah, qad qaamatish shalah", Translation: "Sungguh shalat telah berdiri, sungguh shalat telah berdiri.", Dalil: "HR. Ahmad No. 19312 (Shahih): Lafaz iqomah."},

		{ModuleID: bySlug["puasa"], StepOrder: 1, Kind: "teori", Title: "Pengertian Puasa", Body: "Menahan diri dari makan, minum, dan segala hal yang membatalkan dari terbit fajar (shubuh) hingga terbenam matahari, dengan niat karena Allah.", Arabic: "الصَّوْمُ", Latin: "Ash-shiyaam", Translation: "Puasa.", Dalil: "QS. Al-Baqarah: 183: \"Wahai orang-orang yang beriman, diwajibkan atas kamu berpuasa sebagaimana diwajibkan atas orang-orang sebelum kamu agar kamu bertakwa.\""},
		{ModuleID: bySlug["puasa"], StepOrder: 2, Kind: "rukun", Title: "Rukun Puasa", Body: "Rukun puasa ada dua: (1) Niat, yaitu membedaakan puasa wajib dari sekadar menahan lapar. (2) Menahan diri dari segala pembatal dari terbit fajar hingga terbenam matahari.", Dalil: "HR. Bukhari No. 1901; HR. Muslim No. 1153: \"Barangsiapa yang tidak berniat puasa sebelum fajar, maka tidak ada puasa baginya.\""},
		{ModuleID: bySlug["puasa"], StepOrder: 3, Kind: "praktik", Title: "Hal-hal yang Membatalkan Puasa", Body: "Makan dan minum sengaja, muntah sengaja, haid dan nifas, serta hal lain yang masuk ke lubang terbuka (qubul/dubur).", Tip: "Jika lupa makan atau minum dan langsung sadar, lanjutkan puasa. Peristiwa tersebut tidak membatalkan puasa menurut hadis.", Dalil: "HR. Abu Dawud No. 2340 (Hasan): \"Jika salah seorang di antara kamu lupa dan makan atau minum, maka hendaklah ia menyempurnakan puasanya, karena sesungguhnya Allahlah yang telah memberinya makan dan minum.\""},
		{ModuleID: bySlug["puasa"], StepOrder: 4, Kind: "sunnah", Title: "Sunnah-sunnah Puasa", Body: "Menyegerakan berbuka, mengakhirkan sahur, memperbanyak doa terutama di 10 hari terakhir Ramadan, bersedekah, dan membaca Al-Quran.", Arabic: "ذَهَبَ الظَّمَأُ وَابْتَلَّتِ الْعُرُوقُ وَثَبَتَ الْأَجْرُ إِنْ شَاءَ اللَّهُ", Latin: "Dzahabazh zhama'u wabtallatil 'uruuqu wa tsabatal ajru insyaa Allah", Translation: "Telah hilang dahaga, telah basah urat-urat, dan telah tetap pahala insya Allah.", Dalil: "HR. Abu Dawud No. 2356 (Hasan): Doa berbuka puasa.", Tip: "Utamakan berbuka dengan kurma atau air putih, lalu shalat Maghrib."},
		{ModuleID: bySlug["puasa"], StepOrder: 5, Kind: "teori", Title: "Hikmah Puasa", Body: "Puasa melatih kesabaran, mengendalikan hawa nafsu, menumbuhkan rasa empati kepada yang kurang mampu, dan menjadi sarana taqarrub kepada Allah.", Dalil: "QS. Al-Baqarah: 183: \"...agar kamu bertakwa.\""},

		{ModuleID: bySlug["zakat"], StepOrder: 1, Kind: "teori", Title: "Zakat Fitrah", Body: "Zakat fitrah wajib bagi setiap muslim yang memiliki kelebihan makanan untuk dirinya dan keluarganya pada malam dan hari Idul Fitri. Besarannya 2.5 kg makanan pokok atau senilai 3.5 liter makanan pokok.", Dalil: "HR. Abu Dawud No. 1609 (Shahih): \"Rasulullah ﷺ mewajibkan zakat fitrah satu sha' kurma atau satu sha' gandum, atas budak dan orang merdeka, laki-laki dan perempuan, kecil dan besar dari kaum muslimin.\""},
		{ModuleID: bySlug["zakat"], StepOrder: 2, Kind: "teori", Title: "Zakat Mal (Harta)", Body: "Zakat mal wajib atas harta yang memenuhi syarat: milik penuh, mencapai nisab (batas minimum), sudah haul (genap satu tahun), dan lebih dari kebutuhan pokok. Kadar umumnya 2.5%.", Tip: "Nisab emas zakat mal setara 85 gram emas, sedangkan nisab perak 595 gram perak."},
		{ModuleID: bySlug["zakat"], StepOrder: 3, Kind: "praktik", Title: "8 Golongan Penerima (Asnaf)", Body: "Penerima zakat ada 8: (1) Fakir, (2) Miskin, (3) Amil, (4) Muallaf, (5) Memerdekakan budak, (6) Gharim, (7) Fisabilillah, (8) Ibnu Sabil.", Arabic: "إِنَّمَا الصَّدَقَاتُ لِلْفُقَرَاءِ وَالْمَسَاكِينِ وَالْعَامِلِينَ عَلَيْهَا وَالْمُؤَلَّفَةِ قُلُوبُهُمْ وَفِي الرِّقَابِ وَالْغَارِمِينَ وَفِي سَبِيلِ اللَّهِ وَابْنِ السَّبِيلِ", Latin: "Innama ash shadaqaatu lilfuqaraa'i wal masaakiini wal 'aamiliina 'alaihaa wal mu'allafati quluubuhum wa fir riqaabi wal ghaarimiina wa fii sabiilillaahi wabnis sabiil", Translation: "Sesungguhnya zakat-zakat itu hanyalah untuk orang-orang fakir, orang-orang miskin, para amil zakat, para muallaf yang dibujuk hatinya, untuk (memerdekakan) budak, orang-orang yang berutang, untuk jalan Allah, dan orang-orang yang sedang dalam perjalanan.", Dalil: "QS. At-Taubah: 60."},

		{ModuleID: bySlug["tajwid"], StepOrder: 1, Kind: "teori", Title: "Hukum Nun Mati & Tanwin", Body: "Nun mati (نْ) dan tanwin (ـً ـٍ ـٌ) apabila bertemu huruf hijaiyah tertentu memiliki empat hukum: Izhar, Idgham, Iqlab, dan Ikhfa.", Dalil: "QS. Al-An'am: 73: \"...وَقَدْ فَصَّلَ لَكُم مَّا حَرَّمَ عَلَيْكُمْ...\" - contoh Ikhfa karena nun mati bertemu fa'."},
		{ModuleID: bySlug["tajwid"], StepOrder: 2, Kind: "praktik", Title: "Idzhar Halqi", Body: "Nun mati/tanwin dibaca jelas apabila bertemu huruf halq (tenggorokan): ء ه ع غ ح خ.", Arabic: "مَنْ ءَامَنَ", Latin: "Man aamana", Translation: "Barangsiapa yang beriman.", Dalil: "QS. Al-Baqarah: 62."},
		{ModuleID: bySlug["tajwid"], StepOrder: 3, Kind: "praktik", Title: "Idgham Bighunnah", Body: "Nun mati/tanwin bertemu ي ن م و ل ر dilebur menjadi satu dengan dengung (nunnasal terdengar di akhir).", Arabic: "مَن يَعْمَلْ سُوءًا", Latin: "May ya'mal suu-an", Translation: "Barangsiapa yang mengerjakan kejahatan.", Dalil: "QS. An-Nisa: 123."},
		{ModuleID: bySlug["tajwid"], StepOrder: 4, Kind: "praktik", Title: "Iqlab", Body: "Nun mati/tanwin bertemu ب (ba) diganti menjadi bunyi م (mim) dengan dengung. Tanda: terdapat nun mati/tanwin berbunyi seperti 'mb'.", Arabic: "أَنۢبِئُوهُم", Latin: "Anbii-uhum", Translation: "Kabarkanlah kepada mereka.", Dalil: "QS. Al-Baqarah: 33."},
		{ModuleID: bySlug["tajwid"], StepOrder: 5, Kind: "praktik", Title: "Ikhfa Haqiqi", Body: "Nun mati/tanwin bertemu 15 huruf (selain Idzhar, Idgham, Iqlab) dibaca samar-samar dengan dengung.", Arabic: "مِن وَرَائِهِمْ", Latin: "Min waraa'ihim", Translation: "Dari belakang mereka.", Dalil: "QS. Al-Buruj: 20."},
		{ModuleID: bySlug["tajwid"], StepOrder: 6, Kind: "praktik", Title: "Hukum Mim Mati", Body: "Mim mati (مْ) terbagi tiga: Ikhfa Syafawi (bertemu ب), Idgham Mimi (bertemu م), dan Idzhar Syafawi (bertemu semua huruf selain mim dan ba).", Arabic: "تَرْمِيهِم بِحِجَارَةٍ", Latin: "Tarmihim bihijaaratin", Translation: "Melempari mereka dengan batu.", Dalil: "QS. Al-Fil: 4."},
		{ModuleID: bySlug["tajwid"], StepOrder: 7, Kind: "praktik", Title: "Mad (Panjang Bacaan)", Body: "Mad Thabi'i dibaca 2 harakat. Mad Far'i (cabang) seperti Mad Layyin, Mad 'Aridh, Mad Wajib Muttashil, dan lain-lain.", Arabic: "قَالَ رَبِّ", Latin: "Qaala Rabbi", Translation: "Dia berkata, \"Ya Tuhanku.\"", Dalil: "QS. Maryam: 4.", Tip: "Berlatih dengan qari terkenal untuk mendengar langsung panjang-pendek bacaan."},

		{ModuleID: bySlug["rukun-iman"], StepOrder: 1, Kind: "teori", Title: "Iman kepada Allah", Body: "Meyakini dengan sebenar-benar keyakinan bahwa Allah ﷻ ada, Esa dalam Rububiyah (penciptaan), Uluhiyah (penyembahan), dan Asma' wa Sifat (nama dan sifat).", Dalil: "QS. Al-Ikhlas: 1-4: \"Katakanlah, Dialah Allah Yang Maha Esa. Allah tempat bergantung. Tidak beranak dan tidak dilahirkan. Dan tiada seorangpun setara dengan-Nya.\""},
		{ModuleID: bySlug["rukun-iman"], StepOrder: 2, Kind: "teori", Title: "Iman kepada Malaikat", Body: "Meyakini bahwa malaikat adalah makhluk gaib yang diciptakan dari cahaya, patuh pada perintah Allah, dan tidak pernah durhaka.", Arabic: "الْمَلَائِكَةُ", Latin: "Al-malaa'ikah", Translation: "Para malaikat.", Dalil: "QS. Al-Baqarah: 285: \"...mereka (para rasul) beriman kepada-Nya, dan mereka semua tunduk kepada-Nya.\""},
		{ModuleID: bySlug["rukun-iman"], StepOrder: 3, Kind: "teori", Title: "Iman kepada Kitab-kitab", Body: "Meyakini bahwa Allah menurunkan kitab-kitab kepada para rasul: Suhuf (Ibrahim & Musa), Taurat (Musa), Zabur (Daud), Injil (Isa), dan Al-Quran (Muhammad ﷺ).", Dalil: "QS. Al-Baqarah: 285: \"Rasul (Muhammad) beriman kepada apa yang diturunkan kepadanya dari Tuhannya...\"."},
		{ModuleID: bySlug["rukun-iman"], StepOrder: 4, Kind: "teori", Title: "Iman kepada Rasul", Body: "Meyakini para rasul yang wajib diketahui secara umum ada 25, dimulai dari Nuh hingga Muhammad ﷺ sebagai penutup para nabi.", Dalil: "QS. Al-Ahzab: 40: \"Muhammad itu sekali-kali bukanlah (bapak) dari seorang laki-laki di antara kamu, tetapi dia adalah Rasulullah dan penutup para nabi.\""},
		{ModuleID: bySlug["rukun-iman"], StepOrder: 5, Kind: "teori", Title: "Iman kepada Hari Akhir", Body: "Meyakini bahwa kehidupan dunia akan berakhir. Setelahnya ada kebangkitan, hisab (penghitungan amal), shirat (jembatan), surga, dan neraka.", Dalil: "QS. Al-Qiyamah: 1-3: \"Aku bersumpah dengan hari kiamat, dan aku bersumpah dengan jiwa yang selalu menyesal (dirinya sendiri). Apakah manusia mengira bahwa Kami tidak akan mengumpulkan (kembali) tulang belulangnya?\"."},
		{ModuleID: bySlug["rukun-iman"], StepOrder: 6, Kind: "teori", Title: "Iman kepada Qada & Qadar", Body: "Meyakini bahwa semua yang terjadi di alam semesta ini merupakan ketetapan Allah ﷻ yang sudah tercatat di Lauhul Mahfuz, baik maupun buruk.", Dalil: "HR. Tirmidzi No. 2515 (Shahih): \"Berimanlah kamu kepada qada dan qadar, bahwa seluruh perkara itu telah ditetapkan dari Allah.\""},

		{ModuleID: bySlug["adab-talab-ilmu"], StepOrder: 1, Kind: "sunnah", Title: "Meniatkan Ilmu untuk Mencapai Ridha Allah", Body: "Langkah pertama tholabul 'ilmi adalah meluruskan niat: menuntut ilmu bukan karena gengsi, pujian, atau kedudukan, melainkan karena Allah ﷻ.", Arabic: "رَبِّ زِدْنِي عِلْمًا", Latin: "Rabbi zidnii 'ilmaa", Translation: "Ya Tuhanku, tambahkanlah aku ilmu.", Dalil: "QS. Thaha: 114.", Tip: "Tiap kali mulai belajar, bisikkan niat ini di hati. Niat adalah fondasi yang membedakan ilmu yang bermanfaat dan yang sia-sia."},
		{ModuleID: bySlug["adab-talab-ilmu"], StepOrder: 2, Kind: "sunnah", Title: "Membersihkan Hati Sebelum Menuntut Ilmu", Body: "Membersihkan hati dari penyakit seperti hasad, sombong, dan ujub. Karena ilmu adalah cahaya, dan cahaya tidak masuk dalam hati yang gelap.", Dalil: "HR. Muslim No. 2701: \"Tidak akan masuk surga orang yang di dalam hatinya terdapat kesombongan sebesar biji sawi.\""},
		{ModuleID: bySlug["adab-talab-ilmu"], StepOrder: 3, Kind: "sunnah", Title: "Memulai dengan Bismillah dan Memperhatikan Wudhu", Body: "Disunnahkan memulai belajar dalam keadaan suci, berpakaian rapi, dan duduk dengan sopan menghadap guru.", Tip: "Menghadap guru secara langsung (tatap muka) akan lebih melekat dalam hati dibanding belajar dari layar."},
		{ModuleID: bySlug["adab-talab-ilmu"], StepOrder: 4, Kind: "sunnah", Title: "Senantiasa Rendah Hati terhadap Guru", Body: "Memuliakan guru adalah bagian dari memuliakan ilmu itu sendiri. Jangan membantah, jangan mencela, dan jagalah adab saat bertanya.", Dalil: "HR. Tirmidzi No. 2671 (Hasan): \"Tidak termasuk golongan kami orang yang tidak memuliakan yang tua di antara kami, dan tidak menyayangi yang muda di antara kami.\""},
		{ModuleID: bySlug["adab-talab-ilmu"], StepOrder: 5, Kind: "sunnah", Title: "Mengamalkan Ilmu yang Dipelajari", Body: "Ilmu tanpa amal bagaikan pohon tanpa buah. Tujuan akhir tholabul 'ilmi adalah diamalkan agar menjadi penerang di dunia dan akhirat.", Dalil: "HR. Ath-Thabrani: \"Sungguh akan datang kepada suatu kaum yang mencari ilmu, namun tidak dicari melainkan untuk berhias dengan-nya, dan mereka tidak dituntut dengan ilmu melainkan untuk berdebat.\""},

		// ===== TAHSIN & TAJWID DASAR =====
		{ModuleID: bySlug["tahsin-tajwid"], StepOrder: 1, Kind: "teori", Title: "Makharijul Huruf (Tempat Keluarnya Huruf)", Body: "Makhraj huruf adalah tempat keluarnya huruf saat dibunyikan. Terdapat 5 kelompok utama: Al-Jauf (rongga mulut & tenggorokan), Al-Halq (tenggorokan), Al-Lisan (lidah), Asy-Syafatain (kedua bibir), dan Al-Khaisyum (rongga hidung/ghunnah).", Arabic: "مَخَارِجُ الْحُرُوفِ", Latin: "Makhaarijul Huruuf", Translation: "Tempat-tempat keluarnya huruf.", Dalil: "QS. Al-Muzzammil: 4: \"...وَرَتِّلِ الْقُرْآنَ تَرْتِيلًا\" (Dan bacalah Al-Quran itu dengan perlahan/tartil).", Tip: "Latih pengucapan huruf tenggorokan (ء ه ع غ ح خ) dan lidah (ق ك ج ش ي ض ل ن ر ط د ت ص ز س ظ ذ ث) di hadapan guru tahsin."},
		{ModuleID: bySlug["tahsin-tajwid"], StepOrder: 2, Kind: "teori", Title: "Sifatul Huruf (Sifat-sifat Huruf)", Body: "Karakteristik yang melekat pada huruf saat diucapkan, seperti Hams (mengalirnya nafas) lawan Jahr, Syiddah (tertahannya suara) lawan Rakhawah, Isti'la (terangkatnya pangkal lidah/tebal) lawan Istifal (tipis), serta Qalqalah (pantulan suara pada ق ط ب ج د).", Arabic: "صِفَاتُ الْحُرُوفِ", Latin: "Shifaatul Huruuf", Translation: "Sifat-sifat huruf.", Tip: "Huruf Isti'la (خ ص ض غ ط ق ظ) selalu dibaca tebal (tafkhim) dalam segala kondisi harakat."},
		{ModuleID: bySlug["tahsin-tajwid"], StepOrder: 3, Kind: "praktik", Title: "Hukum Mad Thabi'i & Mad Far'i", Body: "Mad Thabi'i (asli) berpanjang 2 harakat bila ada alif setelah fathah, ya sukun setelah kasrah, atau wawu sukun setelah dhammah. Mad Far'i adalah cabang mad yang bertambah panjangnya (4-6 harakat) karena sebab hamzah atau sukun/tasydid.", Arabic: "الْمَدُّ الطَّبِيعِيُّ وَالْمَدُّ الْفَرْعِيُّ", Latin: "Al-madduth thabi'iyyu wal maddul far'iyyu", Translation: "Mad Thabi'i dan Mad Cabang.", Dalil: "Atsar Ibnu Mas'ud radhiyallahu 'anhu saat menegur seseorang yang membaca ayat zakat tanpa memanjangkan lafaz mad (HR. Sa'id bin Manshur dalam Sunan-nya, sanad shahih)."},
		{ModuleID: bySlug["tahsin-tajwid"], StepOrder: 4, Kind: "teori", Title: "Waqaf & Ibtida' (Berhenti & Memulai)", Body: "Waqaf adalah menghentikan bacaan sejenak untuk bernafas dengan niat melanjutkan kembali. Terbagi menjadi Waqaf Taam (sempurna), Kaafi (cukup), Hasan (baik), dan Qabih (buruk/merusak makna). Ibtida' adalah memulai kembali bacaan dari kata yang tepat maknanya.", Arabic: "الْوَقْفُ وَالِابْتِدَاءُ", Latin: "Al-waqfu wal ibtidaa'", Translation: "Berhenti dan memulai bacaan.", Tip: "Jangan berhenti pada kata yang memutus hubungan makna tauhid atau makna larangan (seperti berhenti di 'Fawailul lil mushalliin' tanpa lanjut)."},
		{ModuleID: bySlug["tahsin-tajwid"], StepOrder: 5, Kind: "praktik", Title: "Penerapan Praktis pada Surah Al-Fatihah", Body: "Surah Al-Fatihah wajib dibaca dengan tajwid yang lurus karena merupakan rukun shalat. Perhatikan tasydid pada 'Iyyaka', pengucapan huruf 'Dad' (ض) pada 'Al-Maghdhubi' dan 'Adh-Dhaalliin' agar tidak tertukar dengan 'Zha' (ظ).", Arabic: "غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ", Latin: "Ghairil maghdhuubi 'alaihim waladh-dhaalliin", Translation: "Bukan (jalan) mereka yang dimurkai dan bukan (pula jalan) mereka yang sesat.", Dalil: "HR. Bukhari No. 756: \"Tidak sah shalat seseorang yang tidak membaca Fatihatul Kitab (Al-Fatihah).\"", Tip: "Pastikan memanjangkan 'Adh-Dhaalliin' selama 6 harakat (Mad Lazim Kilmi Mutsaqqal) sebelum melafalkan tasydid lam."},

		// ===== AQIDAH SALAF & RUKUN IMAN =====
		{ModuleID: bySlug["aqidah-salaf"], StepOrder: 1, Kind: "teori", Title: "Pembagian Tauhid: Rububiyah, Uluhiyah, Asma' wa Sifat", Body: "Tauhid menurut Al-Quran dan pemahaman Salaful Ummah mencakup tiga bagian: Rububiyah (mengesakan Allah dalam penciptaan, kepemilikan, dan pengaturan), Uluhiyah (mengesakan Allah dalam segala jenis ibadah), dan Asma' wa Sifat (menetapkan nama dan sifat Allah sesuai Quran-Sunnah tanpa tamsyil, takyif, tahrif, atau ta'thil).", Arabic: "تَوْحِيدُ الرُّبُوبِيَّةِ وَالْأُلُوهِيَّةِ وَالْأَسْمَاءِ وَالصِّفَاتِ", Latin: "Tawhiidur rubuubiyyati wal uluuhiyyati wal asmaa'i wash shifaat", Translation: "Tauhid Rububiyah, Uluhiyah, serta Asma' dan Sifat.", Dalil: "QS. Maryam: 65: \"Rabb (Tuhan) langit dan bumi dan apa yang ada di antara keduanya, maka sembahlah Dia dan berteguh hatilah dalam beribadah kepada-Nya. Apakah kamu mengetahui ada seseorang yang sama dengan Dia?\""},
		{ModuleID: bySlug["aqidah-salaf"], StepOrder: 2, Kind: "teori", Title: "Hakikat Iman: Perkataan, Keyakinan, dan Amal Perbuatan", Body: "Aqidah Ahlus Sunnah wal Jama'ah menetapkan bahwa iman terdiri dari keyakinan di dalam hati, perkataan dengan lisan, dan perbuatan dengan anggota badan. Iman dapat bertambah dengan ketaatan kepada Allah dan berkurang dengan perbuatan maksiat.", Arabic: "الْإِيمَانُ قَوْلٌ وَعَمَلٌ يَزِيدُ وَيَنْقُصُ", Latin: "Al-iimaanu qawlun wa 'amalun yaziidu wa yanqush", Translation: "Iman adalah ucapan dan perbuatan, bertambah dan berkurang.", Dalil: "QS. Al-Anfal: 2: \"Sesungguhnya orang-orang yang beriman adalah mereka yang apabila disebut nama Allah gemetarlah hati mereka dan apabila dibacakan ayat-ayat-Nya bertambahlah iman mereka...\"", Tip: "Jauhi pemahaman Murji'ah yang mengeluarkan amal dari hakikat iman dan pemahaman Khawarij yang mengkafirkan pelaku dosa besar."},
		{ModuleID: bySlug["aqidah-salaf"], StepOrder: 3, Kind: "teori", Title: "Bahaya Syirik Akbar dan Syirik Ashghar", Body: "Syirik adalah memalingkan hak ibadah kepada selain Allah atau menyamakan makhluk dengan Allah. Syirik akbar menggugurkan seluruh amal dan pelakunya kekal di neraka jika mati sebelum bertaubat. Syirik ashghar (seperti riya' dan sum'ah) merusak pahala amalan tertentu.", Arabic: "إِنَّ الشِّرْكَ لَظُلْمٌ عَظِيمٌ", Latin: "Innasysyirka ladhulmun 'azhiim", Translation: "Sesungguhnya mempersekutukan (Allah) adalah benar-benar kezhaliman yang besar.", Dalil: "QS. Luqman: 13 & QS. An-Nisa: 48: \"Sesungguhnya Allah tidak akan mengampuni dosa syirik, dan Dia mengampuni segala dosa yang selain dari (syirik) itu, bagi siapa yang dikehendaki-Nya.\""},
		{ModuleID: bySlug["aqidah-salaf"], StepOrder: 4, Kind: "teori", Title: "Mengenal Tiga Landasan Utama (Al-Ushul Ats-Tsalatsah)", Body: "Tiga pertanyaan kubur yang wajib diketahui setiap mukmin: Mengenal Allah ﷻ (Rabb kita), Mengenal Agama Islam beserta dalil-dalilnya, dan Mengenal Nabi Muhammad ﷺ.", Arabic: "الْأُصُولُ الثَّلَاثَةُ", Latin: "Al-Ushuuluts Tsalaatsah", Translation: "Tiga Prinsip Pokok.", Dalil: "HR. Abu Dawud No. 4753 (Shahih): Hadis panjang Barra' bin 'Azib tentang fitnah dan pertanyaan malaikat Munkar dan Nakir di alam barzakh."},

		// ===== PANDUAN SHALAT SESUAI SIFAT NABI =====
		{ModuleID: bySlug["sholat-sifat-nabi"], StepOrder: 1, Kind: "sunnah", Title: "Menghadap Kiblat & Mengambil Sutrah", Body: "Disunnahkan shalat mendekat ke sutrah (pembatas di depan mushalli seperti dinding, tiang, atau benda setinggi pelana kuda) guna menjaga pandangan dan mencegah orang lewat melintas persis di hadapannya.", Arabic: "إِذَا صَلَّى أَحَدُكُمْ فَلْيُصَلِّ إِلَى سُتْرَةٍ وَلْيَدْنُ مِنْهَا", Latin: "Idzaa shallaa ahadukum falyushalli ilaa sutratin walyadnu minhaa", Translation: "Jika salah seorang di antara kalian shalat, hendaklah ia shalat menghadap sutrah dan mendekat kepadanya.", Dalil: "HR. Abu Dawud No. 698 (Shahih); HR. Ibnu Majah No. 954."},
		{ModuleID: bySlug["sholat-sifat-nabi"], StepOrder: 2, Kind: "praktik", Title: "Posisi Sedekap yang Shahih", Body: "Meletakkan telapak tangan kanan di atas punggung telapak tangan kiri, pergelangan tangan, atau lengan bawah kiri di atas dada/posisi dada tanpa berlebihan ke leher atau perut bawah.", Dalil: "HR. Abu Dawud No. 759 & An-Nasa'i No. 889 (Shahih dari Wail bin Hujr): \"Kemudian beliau meletakkan tangan kanannya di atas punggung telapak tangan kirinya, pergelangan dan lengannya.\""},
		{ModuleID: bySlug["sholat-sifat-nabi"], StepOrder: 3, Kind: "praktik", Title: "Sifat Ruku' yang Rata & Thuma'ninah", Body: "Membungkuk hingga punggung lurus mendatar; jika diletakkan segelas air di atas punggung tidak akan tumpah. Merenggangkan jari-jemari tangan di atas lutut dan menjauhkan siku dari lambung.", Arabic: "سُبْحَانَكَ اللَّهُمَّ رَبَّنَا وَبِحَمْدِكَ اللَّهُمَّ اغْفِرْ لِي", Latin: "Subhaanakallaahumma Rabbanaa wa bihamdika Allaahummaghfir lii", Translation: "Maha Suci Engkau ya Allah, Rabb kami, dan dengan memuji-Mu ya Allah ampunilah aku.", Dalil: "HR. Bukhari No. 828 & Muslim No. 484; HR. Abu Dawud No. 863 tentang kelurusan punggung Rasulullah ﷺ."},
		{ModuleID: bySlug["sholat-sifat-nabi"], StepOrder: 4, Kind: "praktik", Title: "Sifat Sujud, Duduk Iftirasy & Duduk Tawarruk", Body: "Menempelkan dahi, hidung, dua telapak tangan, dua lutut, dan ujung jari-jari kaki ke lantai menghadap kiblat. Duduk di antara dua sujud dan tasyahud awal dengan posisi Iftirasy (menduduki kaki kiri, kaki kanan ditegakkan). Duduk tasyahud akhir shalat rakaat lebih dari dua dengan posisi Tawarruk (menjulurkan kaki kiri di bawah betis kanan, pantat menempel ke lantai).", Dalil: "HR. Bukhari No. 828 (Sifat Shalat Nabi ﷺ dari Abu Humaid As-Sa'idi).", Tip: "Jauhkan lengan dari lantai dan jangan menghamparkan tangan seperti anjing menghamparkan kakinya."},
		{ModuleID: bySlug["sholat-sifat-nabi"], StepOrder: 5, Kind: "sunnah", Title: "Dzikir Shahih Setelah Salam", Body: "Membaca istighfar 3 kali, dilanjutkan doa 'Allahumma antas salaam...', membaca tahlil, tasbih (33x), tahmid (33x), takbir (33x), digenapkan ke-100 dengan kalimat tauhid, membaca Ayat Kursi, dan surah Al-Mu'awwidzat.", Arabic: "أَسْتَغْفِرُ اللَّهَ (٣x)، اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ", Latin: "Astaghfirullah (3x), Allahumma antas salaamu wa minkas salaam, tabaarakta yaa dzal jalaali wal ikraam", Translation: "Aku memohon ampunan kepada Allah (3x). Ya Allah, Engkaulah As-Salam (Yang Maha Menyelamatkan), dan dari-Mulah keselamatan. Maha Berkah Engkau wahai Rabb Pemilik keagungan dan kemuliaan.", Dalil: "HR. Muslim No. 591, 597 & HR. An-Nasa'i dalam 'Amalul Yaumi wal Lailah No. 100."},

		// ===== DZIKIR & DOA HARIAN =====
		{ModuleID: bySlug["dzikir-doa-harian"], StepOrder: 1, Kind: "teori", Title: "Keutamaan Dzikir & Adab Berdoa", Body: "Dzikir adalah penentram jiwa dan benteng terkuat dari godaan setan. Adab berdoa: ikhlas karena Allah, memulai dengan memuji Allah dan shalawat atas Nabi ﷺ, menghadap kiblat, mengangkat tangan, dan yakin doa akan dikabulkan.", Arabic: "أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ", Latin: "Alaa bidzikrillaahi tathma'innul quluub", Translation: "Ingatlah, hanya dengan mengingat Allah hati menjadi tenteram.", Dalil: "QS. Ar-Ra'd: 28; HR. Tirmidzi No. 3477 (Shahih)."},
		{ModuleID: bySlug["dzikir-doa-harian"], StepOrder: 2, Kind: "praktik", Title: "Sayyidul Istighfar & Dzikir Pagi Petang", Body: "Sayyidul Istighfar adalah doa permohonan ampunan paling utama. Barangsiapa membacanya di pagi hari dengan penuh keyakinan lalu meninggal sebelum sore, ia termasuk penghuni surga; demikian pula bila dibaca di sore hari.", Arabic: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ", Latin: "Allaahumma Anta Rabbii laa ilaaha illaa Anta khalaqtanii wa ana 'abduka wa ana 'alaa 'ahdika wa wa'dika mastatha'tu, a'uudzu bika min syarri maa shana'tu, abuu'u laka bini'matika 'alayya wa abuu'u bidzanbii faghfir lii fa-innahu laa yaghfirudz dzunuuba illaa Anta", Translation: "Ya Allah, Engkau adalah Rabbku, tiada ilah yang berhak disembah selain Engkau. Engkaulah yang menciptakanku dan aku adalah hamba-Mu. Aku akan setia pada janji-Mu semampuku. Aku berlindung kepada-Mu dari keburukan yang telah kuperbuat. Aku mengakui nikmat-Mu kepadaku dan aku mengakui dosaku, maka ampunilah aku. Sesungguhnya tiada yang mengampuni dosa-dosa selain Engkau.", Dalil: "HR. Bukhari No. 6306.", Tip: "Baca dzikir pagi setelah shalat Shubuh hingga terbit matahari, dan dzikir petang setelah shalat Ashar hingga matahari tenggelam."},
		{ModuleID: bySlug["dzikir-doa-harian"], StepOrder: 3, Kind: "praktik", Title: "Doa Keluar & Masuk Rumah", Body: "Saat keluar rumah disunnahkan bertawakkal kepada Allah agar diberi petunjuk, kecukupan, dan perlindungan dari godaan setan. Saat masuk rumah membaca salam dan bismillah.", Arabic: "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ", Latin: "Bismillaahi tawakkaltu 'alallaahi wa laa hawla wa laa quwwata illaa billaah", Translation: "Dengan nama Allah, aku bertawakkal kepada Allah, tiada daya dan kekuatan kecuali dengan pertolongan Allah.", Dalil: "HR. Abu Dawud No. 5095, Tirmidzi No. 3426 (Shahih): \"Dikatakan kepadanya: Kamu telah diberi petunjuk, dicukupi, dan dilindungi, lalu setan menyingkir darinya.\""},
		{ModuleID: bySlug["dzikir-doa-harian"], StepOrder: 4, Kind: "praktik", Title: "Doa Masuk & Keluar Masjid", Body: "Masuk masjid mendahulukan kaki kanan seraya memohon dibukakan pintu rahmat. Keluar masjid mendahulukan kaki kiri seraya memohon limpahan karunia Allah.", Arabic: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ - اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ", Latin: "Allaahummaftah lii abwaaba rahmatik - Allaahumma innii as-aluka min fadhlik", Translation: "Ya Allah, bukakanlah untukku pintu-pintu rahmat-Mu (masuk) - Ya Allah, sesungguhnya aku memohon sebagian dari karunia-Mu (keluar).", Dalil: "HR. Muslim No. 713."},
		{ModuleID: bySlug["dzikir-doa-harian"], StepOrder: 5, Kind: "praktik", Title: "Adab & Doa Sebelum Tidur dan Bangun Tidur", Body: "Berwudhu sebelum tidur, mengibaskan tempat tidur, tidur miring ke sisi kanan menghadap kiblat, membaca Ayat Kursi, 3 Qul (Al-Ikhlas, Al-Falaq, An-Nas) lalu ditiupkan ke telapak tangan dan diusapkan ke seluruh badan (3x), lalu membaca doa tidur.", Arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا - الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ", Latin: "Bismika Allaahumma amuutu wa ahyaa - Alhamdulillaahil ladzii ahyaanaa ba'da maa amaatanaa wa ilaihin nusyuur", Translation: "Dengan nama-Mu ya Allah aku mati dan aku hidup - Segala puji bagi Allah yang menghidupkan kami setelah mematikan kami dan kepada-Nya kami kembali.", Dalil: "HR. Bukhari No. 6312 & 6314."},
	}

	for i := range steps {
		if steps[i].ModuleID == 0 {
			continue
		}
		var existing model.LessonStep
		if err := db.Where("module_id = ? AND step_order = ?", steps[i].ModuleID, steps[i].StepOrder).First(&existing).Error; err == nil {
			db.Model(&existing).Updates(map[string]interface{}{
				"kind":        steps[i].Kind,
				"title":       steps[i].Title,
				"body":        steps[i].Body,
				"arabic":      steps[i].Arabic,
				"latin":       steps[i].Latin,
				"translation": steps[i].Translation,
				"dalil":       steps[i].Dalil,
				"tip":         steps[i].Tip,
			})
		} else {
			db.Create(&steps[i])
		}
	}
}
