package migrations

import "github.com/agambondan/islamic-explorer/app/model"

func seedDailyReminders() []model.DailyReminder {
	return []model.DailyReminder{
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Ilmu dan Adab",
			Text:         "Adab yang sedikit namun kokoh sering menjadi pintu bagi ilmu yang banyak.",
			Author:       "Abdullah bin Al-Mubarak",
			Source:       "Siyar A'lam An-Nubala",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 10,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Kebutuhan Ilmu",
			Text:         "Manusia lebih membutuhkan ilmu daripada makan dan minum, karena ilmu dibutuhkan di setiap keadaan.",
			Author:       "Imam Ahmad bin Hanbal",
			Source:       "Madarij As-Salikin",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 20,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Menjaga Waktu",
			Text:         "Waktu adalah modal perjalanan seorang hamba; siapa yang menjaganya, ia menjaga jalan pulangnya.",
			Author:       "Ibnul Qayyim Al-Jauziyyah",
			Source:       "Al-Fawa'id",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 30,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Ilmu Bermanfaat",
			Text:         "Tanda ilmu yang bermanfaat adalah bertambahnya rasa takut kepada Allah dan baiknya amal.",
			Author:       "Ibnu Rajab Al-Hanbali",
			Source:       "Jami' Al-'Ulum wal Hikam",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 40,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Keikhlasan Amal",
			Text:         "Keikhlasan adalah ruh amal; dengannya amal kecil dapat menjadi besar di sisi Allah.",
			Author:       "Imam An-Nawawi",
			Source:       "Riyadhus Shalihin",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 50,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Hati yang Hidup",
			Text:         "Hati menjadi hidup dengan nasihat, dzikir, rasa takut kepada Allah, dan amal yang dijaga.",
			Author:       "Hasan Al-Bashri",
			Source:       "Hilyatul Auliya",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 60,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Amal Kecil",
			Text:         "Mulai dari amal yang kecil, lalu jaga agar tetap hidup setiap hari.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 70,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Ilmu yang Menundukkan",
			Text:         "Ilmu yang bermanfaat adalah ilmu yang membuat hati semakin tunduk dan amal semakin terarah.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 80,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Niat yang Lurus",
			Text:         "Sesungguhnya amal tergantung pada niat, dan setiap orang hanya mendapat apa yang ia niatkan.",
			Author:       "Nabi Muhammad ﷺ",
			Source:       "HR. Bukhari 1 & Muslim 1907",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 90,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Bertahap dalam Ilmu",
			Text:         "Sesungguhnya ilmu itu diperoleh secara bertahap, maka janganlah terburu-buru menuntut hasil yang instan.",
			Author:       "Imam As-Syafi'i",
			Source:       "Diwan As-Syafi'i",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 100,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Menahan Lisan",
			Text:         "Barangsiapa beriman kepada Allah dan hari akhir, hendaklah ia berkata baik atau diam.",
			Author:       "Nabi Muhammad ﷺ",
			Source:       "HR. Bukhari 6018 & Muslim 47",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 110,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Cahaya di Atas Cahaya",
			Text:         "Allah (Pemberi) cahaya (kepada) langit dan bumi. Perumpamaan cahaya-Nya seperti lubang yang tidak tembus, di dalamnya ada pelita besar.",
			Author:       "Al-Quran",
			Source:       "QS. An-Nur: 35",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 120,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Jangan Berputus Asa",
			Text:         "Katakanlah, wahai hamba-hamba-Ku yang melampaui batas terhadap diri mereka sendiri, janganlah kamu berputus asa dari rahmat Allah. Sesungguhnya Allah mengampuni dosa-dosa semuanya.",
			Author:       "Al-Quran",
			Source:       "QS. Az-Zumar: 53",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 130,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Bersama Kesulitan Ada Kemudahan",
			Text:         "Karena sesungguhnya sesudah kesulitan itu ada kemudahan, sesungguhnya sesudah kesulitan itu ada kemudahan.",
			Author:       "Al-Quran",
			Source:       "QS. Asy-Syarh: 5-6",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 140,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Sabar dalam Menuntut Ilmu",
			Text:         "Jadikan menuntut ilmu sebagai kebiasaan harian, walau hanya satu halaman; konsistensi lebih berat daripada kecepatan.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 150,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Mulai dari yang Dekat",
			Text:         "Mulailah belajar dari hal yang paling dekat dengan kehidupanmu, karena ilmu yang diamalkan lebih utama dari yang hanya dikumpulkan.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 160,
		},
	}
}
