package migrations

import "github.com/agambondan/islamic-explorer/app/model"

func seedDailyReminders() []model.DailyReminder {
	return []model.DailyReminder{
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Ilmu dan Adab",
			Text:         "Adab yang sedikit namun kokoh sering menjadi pintu bagi ilmu yang banyak.",
			Author:       "Abdullah bin Al-Mubarak",
			Source:       "Siyar A'lam An-Nubala",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 10,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Kebutuhan Ilmu",
			Text:         "Manusia lebih membutuhkan ilmu daripada makan dan minum, karena ilmu dibutuhkan di setiap keadaan.",
			Author:       "Imam Ahmad bin Hanbal",
			Source:       "Madarij As-Salikin",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 20,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Menjaga Waktu",
			Text:         "Waktu adalah modal perjalanan seorang hamba; siapa yang menjaganya, ia menjaga jalan pulangnya.",
			Author:       "Ibnul Qayyim Al-Jauziyyah",
			Source:       "Al-Fawa'id",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 30,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Ilmu Bermanfaat",
			Text:         "Tanda ilmu yang bermanfaat adalah bertambahnya rasa takut kepada Allah dan baiknya amal.",
			Author:       "Ibnu Rajab Al-Hanbali",
			Source:       "Jami' Al-'Ulum wal Hikam",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 40,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Keikhlasan Amal",
			Text:         "Keikhlasan adalah ruh amal; dengannya amal kecil dapat menjadi besar di sisi Allah.",
			Author:       "Imam An-Nawawi",
			Source:       "Riyadhus Shalihin",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 50,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Hati yang Hidup",
			Text:         "Hati menjadi hidup dengan nasihat, dzikir, rasa takut kepada Allah, dan amal yang dijaga.",
			Author:       "Hasan Al-Bashri",
			Source:       "Hilyatul Auliya",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 60,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Amal Kecil",
			Text:         "Mulai dari amal yang kecil, lalu jaga agar tetap hidup setiap hari.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 70,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Ilmu yang Menundukkan",
			Text:         "Ilmu yang bermanfaat adalah ilmu yang membuat hati semakin tunduk dan amal semakin terarah.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 80,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Niat yang Lurus",
			Text:         "Sesungguhnya amal tergantung pada niat, dan setiap orang hanya mendapat apa yang ia niatkan.",
			Author:       "Nabi Muhammad ﷺ",
			Source:       "HR. Bukhari 1 & Muslim 1907",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 90,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Bertahap dalam Ilmu",
			Text:         "Sesungguhnya ilmu itu diperoleh secara bertahap, maka janganlah terburu-buru menuntut hasil yang instan.",
			Author:       "Imam As-Syafi'i",
			Source:       "Diwan As-Syafi'i",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 100,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Menahan Lisan",
			Text:         "Barangsiapa beriman kepada Allah dan hari akhir, hendaklah ia berkata baik atau diam.",
			Author:       "Nabi Muhammad ﷺ",
			Source:       "HR. Bukhari 6018 & Muslim 47",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 110,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Cahaya di Atas Cahaya",
			Text:         "Allah (Pemberi) cahaya (kepada) langit dan bumi. Perumpamaan cahaya-Nya seperti lubang yang tidak tembus, di dalamnya ada pelita besar.",
			Author:       "Al-Quran",
			Source:       "QS. An-Nur: 35",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 120,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Jangan Berputus Asa",
			Text:         "Katakanlah, wahai hamba-hamba-Ku yang melampaui batas terhadap diri mereka sendiri, janganlah kamu berputus asa dari rahmat Allah. Sesungguhnya Allah mengampuni dosa-dosa semuanya.",
			Author:       "Al-Quran",
			Source:       "QS. Az-Zumar: 53",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 130,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Bersama Kesulitan Ada Kemudahan",
			Text:         "Karena sesungguhnya sesudah kesulitan itu ada kemudahan, sesungguhnya sesudah kesulitan itu ada kemudahan.",
			Author:       "Al-Quran",
			Source:       "QS. Asy-Syarh: 5-6",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 140,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Sabar dalam Menuntut Ilmu",
			Text:         "Jadikan menuntut ilmu sebagai kebiasaan harian, walau hanya satu halaman; konsistensi lebih berat daripada kecepatan.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 150,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Mulai dari yang Dekat",
			Text:         "Mulailah belajar dari hal yang paling dekat dengan kehidupanmu, karena ilmu yang diamalkan lebih utama dari yang hanya dikumpulkan.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 160,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Jalan Menuju Surga",
			Text:         "Siapa yang menempuh jalan menuntut ilmu, Allah akan memudahkan baginya jalan menuju surga.",
			Author:       "Nabi Muhammad ﷺ",
			Source:       "HR. Muslim 2699",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 170,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Warisan Para Nabi",
			Text:         "Ulama adalah warisan para nabi; para nabi tidak mewariskan dinar dan dirham, tetapi mewariskan ilmu.",
			Author:       "Nabi Muhammad ﷺ",
			Source:       "HR. Abu Dawud 3641; Tirmidzi 2682",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 180,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Ilmu Tanpa Amal",
			Text:         "Seperti pohon tanpa buah, demikianlah ilmu tanpa amal; ia menambah dosa, bukan pahala.",
			Author:       "Al-Hasan Al-Bashri",
			Source:       "Hilyatul Auliya",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 190,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Sabar dan Istiqamah",
			Text:         "Kebaikan tidak akan didapat kecuali dengan sabar, dan amal tidak akan sempurna kecuali dengan istiqamah.",
			Author:       "Ibnul Qayyim Al-Jauziyyah",
			Source:       "Madarij As-Salikin",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 200,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Hati yang Tenang",
			Text:         "Hati yang tenang adalah hati yang hanya berpegang kepada Allah; siapa yang berpegang kepada selain-Nya, hatinya guncang.",
			Author:       "Ibnul Qayyim Al-Jauziyyah",
			Source:       "Al-Fawa'id",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 210,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Keutamaan Sholat",
			Text:         "Sholat adalah tiang agama; siapa yang mendirikannya, dia telah mendirikan agama, dan siapa yang merusaknya, dia telah merusak agama.",
			Author:       "Nabi Muhammad ﷺ",
			Source:       "HR. Baihaqi; Al-Musannaf",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 220,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Baca dan Renung",
			Text:         "Bacalah Al-Quran dengan tadabbur (merenung), jangan hanya lisan; sesungguhnya Al-Quran diturunkan untuk ditadabburi.",
			Author:       "Imam Al-Ghazali",
			Source:       "Ihya Ulumuddin",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 230,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Hikmah Kesabaran",
			Text:         "Kesabaran adalah menahan diri dari keluh, melukis senyum di wajah kesulitan, dan yakin bahwa setelah kesulitan pasti ada kemudahan.",
			Author:       "Syekh Abdul Qadir Al-Jailani",
			Source:       "Al-Fath Ar-Rabbani",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 240,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Menjaga Amanah",
			Text:         "Amanah adalah ciri orang mukmin; khianat adalah ciri orang munafik. Jagalah amanah, baik dalam perkara besar maupun kecil.",
			Author:       "Nabi Muhammad ﷺ",
			Source:       "HR. Bukhari 33; Muslim 58",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 250,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Allah Beserta Orang Sabar",
			Text:         "Dan bersabarlah kamu, sesungguhnya Allah beserta orang-orang yang sabar.",
			Author:       "Al-Quran",
			Source:       "QS. Al-Anfal: 46",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 260,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Manusia Diciptakan dalam Kesengsaraan",
			Text:         "Sesungguhnya Kami telah menciptakan manusia dalam kesengsaraan.",
			Author:       "Al-Quran",
			Source:       "QS. Al-Balad: 4",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 270,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Membaca dengan Nama Rabb",
			Text:         "Bacalah dengan (menyebut) nama Rabbmu yang menciptakan. Dia telah menciptakan manusia dari segumpal darah.",
			Author:       "Al-Quran",
			Source:       "QS. Al-Alaq: 1-2",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 280,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Sesungguhnya Manusia dalam Kerugian",
			Text:         "Demi masa. Sesungguhnya manusia benar-benar dalam kerugian, kecuali orang-orang yang beriman dan mengerjakan amal saleh.",
			Author:       "Al-Quran",
			Source:       "QS. Al-Ashr: 1-3",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 290,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Janganlah Kamu Bersedih",
			Text:         "Janganlah kamu bersedih, sesungguhnya Allah bersama kami. Maka Allah menurunkan ketenangan ke dalam hatinya.",
			Author:       "Al-Quran",
			Source:       "QS. At-Taubah: 40",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 300,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Dan Kami Mudahkan Al-Quran",
			Text:         "Dan sesungguhnya Kami telah memudahkan Al-Quran untuk pelajaran, maka adakah yang mau mengambil pelajaran?",
			Author:       "Al-Quran",
			Source:       "QS. Al-Qamar: 17",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 310,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Konsisten Setiap Hari",
			Text:         "Lebih baik mengerjakan amal sedikit tapi terus-menerus, daripada banyak tapi terputus-putus.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 320,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Renungkan Nikmat",
			Text:         "Luangkan waktu sejenak setiap hari untuk merenung nikmat Allah; syukur adalah kunci bertambahnya nikmat.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 330,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Jaga Sholat Waktu",
			Text:         "Sholat tepat waktu adalah amal paling dicintai Allah; jangan biarkan dunia melalaikanmu dari waktu sholat.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 340,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Minta Ilmu yang Bermanfaat",
			Text:         "Doakan: 'Ya Allah, berikanlah aku ilmu yang bermanfaat, rezeki yang halal, dan amal yang diterima.'",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 350,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Taubat Setiap Malam",
			Text:         "Sebelum tidur, periksa amal seharian; taubatlah dari dosa, dan niatkan kebaikan untuk esok hari.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 360,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Hati yang Bersih",
			Text:         "Hati itu berkarat sebagaimana besi berkarat, dan pembersihnya adalah dzikrullah serta membaca Al-Quran.",
			Author:       "Abdullah bin Mas'ud",
			Source:       "Az-Zuhd karya Imam Ahmad",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 370,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Menghitung Diri Sendiri",
			Text:         "Hisablah diri kalian sebelum kalian dihisab, dan timbanglah amal kalian sebelum kalian ditimbang.",
			Author:       "Umar bin Khattab",
			Source:       "Hilyatul Auliya (1/52)",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 380,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Dua Kenikmatan yang Tertipu",
			Text:         "Dua kenikmatan yang banyak manusia tertipu padanya: kesehatan dan waktu luang.",
			Author:       "Nabi Muhammad ﷺ",
			Source:       "HR. Bukhari 6412",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 390,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Harta yang Sebenarnya",
			Text:         "Hartamu yang hakiki adalah apa yang telah engkau sedekahkan untuk akhiratmu; bukan yang engkau timbun untuk ahli warismu.",
			Author:       "Ali bin Abi Thalib",
			Source:       "Nahjul Balaghah / Siyar A'lam An-Nubala",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 400,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Hakikat Kezuhudan",
			Text:         "Zuhud di dunia bukanlah mengharamkan yang halal atau menyia-nyiakan harta, melainkan engkau lebih percaya pada apa yang ada di tangan Allah daripada apa yang ada di tanganmu.",
			Author:       "Al-Hasan Al-Bashri",
			Source:       "Jami' Al-'Ulum wal Hikam",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 410,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Manisnya Ibadah",
			Text:         "Barangsiapa ridha kepada Allah sebagai Rabb, Islam sebagai agama, dan Muhammad sebagai Rasul, ia pasti merasakan manisnya iman.",
			Author:       "Nabi Muhammad ﷺ",
			Source:       "HR. Muslim 34",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 420,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Ujian dan Dosa",
			Text:         "Tidaklah suatu musibah turun melainkan karena dosa, dan tidaklah musibah itu diangkat melainkan dengan taubat.",
			Author:       "Ali bin Abi Thalib",
			Source:       "Al-Jawab Al-Kafi karya Ibnul Qayyim",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 430,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Ilmu adalah Cahaya",
			Text:         "Ilmu bukanlah sekadar banyaknya riwayat atau hafalan, melainkan cahaya ketakwaan yang Allah letakkan di dalam hati.",
			Author:       "Imam Malik bin Anas",
			Source:       "Tartib Al-Madarik",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 440,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Tawakal yang Hakiki",
			Text:         "Seandainya kalian bertawakal kepada Allah dengan sebenar-benarnya tawakal, niscaya Dia akan memberi rezeki sebagaimana Dia memberi rezeki kepada burung.",
			Author:       "Nabi Muhammad ﷺ",
			Source:       "HR. Tirmidzi 2344; Ahmad 1/30",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 450,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Bahaya Kesombongan",
			Text:         "Sombong adalah menolak kebenaran dan merendahkan manusia.",
			Author:       "Nabi Muhammad ﷺ",
			Source:       "HR. Muslim 91",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 460,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Obat Hati yang Gelisah",
			Text:         "Jika engkau mendapati kekerasan di dalam hatimu, dekatilah orang miskin dan usaplah kepala anak yatim.",
			Author:       "Nabi Muhammad ﷺ",
			Source:       "HR. Ahmad 2/263; Shahih At-Targhib",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 470,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Tanda Cinta kepada Allah",
			Text:         "Tanda kecintaan seorang hamba kepada Rabbnya adalah ia senantiasa merindukan firman-Nya dan gemar bermunajat kepada-Nya di kegelapan malam.",
			Author:       "Fudhail bin Iyadh",
			Source:       "Sifatush Shafwah",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 480,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Menjaga Prasangka Baik",
			Text:         "Jauhilah prasangka buruk, karena prasangka buruk itu adalah sedusta-dusta perkataan.",
			Author:       "Nabi Muhammad ﷺ",
			Source:       "HR. Bukhari 5143 & Muslim 2563",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 490,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Harta Terbaik",
			Text:         "Sebaik-baik harta adalah harta yang berada di tangan orang saleh yang memanfaatkannya di jalan Allah.",
			Author:       "Nabi Muhammad ﷺ",
			Source:       "HR. Ahmad 4/197; Al-Adab Al-Mufrad",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 500,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Malu Sebagian dari Iman",
			Text:         "Rasa malu itu tidak mendatangkan sesuatu kecuali kebaikan.",
			Author:       "Nabi Muhammad ﷺ",
			Source:       "HR. Bukhari 6117 & Muslim 37",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 510,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Meraih Keridhaan Orang Tua",
			Text:         "Keridhaan Allah ada pada keridhaan orang tua, dan kemurkaan Allah ada pada kemurkaan orang tua.",
			Author:       "Nabi Muhammad ﷺ",
			Source:       "HR. Tirmidzi 1899; Shahih Ibnu Hibban",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 520,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Ciri Kebaikan Islam Seseorang",
			Text:         "Di antara tanda kebaikan Islam seseorang adalah ia meninggalkan apa yang tidak bermanfaat baginya.",
			Author:       "Nabi Muhammad ﷺ",
			Source:       "HR. Tirmidzi 2317; Ibnu Majah 3976",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 530,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Kekayaan Jiwa",
			Text:         "Bukanlah kekayaan itu dengan banyaknya harta benda, tetapi kekayaan yang sejati adalah kekayaan jiwa.",
			Author:       "Nabi Muhammad ﷺ",
			Source:       "HR. Bukhari 6446 & Muslim 1051",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 540,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Ujian Kesabaran",
			Text:         "Besarnya balasan sebanding dengan besarnya ujian; dan bila Allah mencintai suatu kaum, Dia menguji mereka.",
			Author:       "Nabi Muhammad ﷺ",
			Source:       "HR. Tirmidzi 2396; Ibnu Majah 4031",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 550,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Kebaikan yang Menyebar",
			Text:         "Tersenyummu di depan saudaramu adalah sedekah bagimu.",
			Author:       "Nabi Muhammad ﷺ",
			Source:       "HR. Tirmidzi 1956",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 560,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Penyesalan adalah Taubat",
			Text:         "Penyesalan yang tulus di dalam hati adalah inti dari taubat nasuha.",
			Author:       "Nabi Muhammad ﷺ",
			Source:       "HR. Ibnu Majah 4252; Ahmad 1/376",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 570,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Dunia seperti Bayangan",
			Text:         "Dunia ini laksana bayangan; jika engkau mengejarnya, engkau tidak akan menangkapnya, namun jika engkau membelakanginya, ia akan mengikutimu.",
			Author:       "Ibnul Qayyim Al-Jauziyyah",
			Source:       "Ighatsatul Lahafan",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 580,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Tanda Cinta Akhirat",
			Text:         "Siapa yang menjadikan akhirat sebagai tujuannya, Allah akan menjadikan kekayaan di dalam hatinya dan menyatukan urusannya.",
			Author:       "Nabi Muhammad ﷺ",
			Source:       "HR. Tirmidzi 2465",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 590,
		},
		{
			Type:         model.DailyReminderTypeUlama,
			Title:        "Menjaga Pandangan",
			Text:         "Pandangan mata adalah salah satu panah beracun dari panah-panah Iblis. Siapa yang menahannya karena takut kepada Allah, Allah gantikan dengan manisnya iman di hatinya.",
			Author:       "Hudzaifah bin Al-Yaman",
			Source:       "Az-Zuhd karya Abu Dawud",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 600,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Mengingat Allah Menenangkan Hati",
			Text:         "Ingatlah, hanya dengan mengingat Allah hati menjadi tenteram.",
			Author:       "Al-Quran",
			Source:       "QS. Ar-Ra'd: 28",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 610,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Berdoa dan Dikabulkan",
			Text:         "Dan Rabbmu berfirman: 'Berdoalah kepada-Ku, niscaya akan Kuperkenankan bagimu.'",
			Author:       "Al-Quran",
			Source:       "QS. Ghafir: 60",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 620,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Allah Dekat",
			Text:         "Dan apabila hamba-hamba-Ku bertanya kepadamu tentang Aku, maka sesungguhnya Aku adalah dekat. Aku mengabulkan permohonan orang yang berdoa apabila ia memohon kepada-Ku.",
			Author:       "Al-Quran",
			Source:       "QS. Al-Baqarah: 186",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 630,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Janji Tambahan Nikmat",
			Text:         "Dan (ingatlah juga), tatkala Rabbmu memaklumkan; 'Sesungguhnya jika kamu bersyukur, pasti Kami akan menambah (nikmat) kepadamu.'",
			Author:       "Al-Quran",
			Source:       "QS. Ibrahim: 7",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 640,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Beban Sesuai Kesanggupan",
			Text:         "Allah tidak membebani seseorang melainkan sesuai dengan kesanggupannya.",
			Author:       "Al-Quran",
			Source:       "QS. Al-Baqarah: 286",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 650,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Jalan Keluar bagi yang Bertakwa",
			Text:         "Barangsiapa bertakwa kepada Allah niscaya Dia akan mengadakan baginya jalan keluar, dan memberinya rezeki dari arah yang tiada disangka-sangkanya.",
			Author:       "Al-Quran",
			Source:       "QS. At-Talaq: 2-3",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 660,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Cukuplah Allah sebagai Penolong",
			Text:         "Dan barangsiapa yang bertawakal kepada Allah niscaya Allah akan mencukupkan (keperluan)nya.",
			Author:       "Al-Quran",
			Source:       "QS. At-Talaq: 3",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 670,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Keluasan Rahmat Allah",
			Text:         "Rahmat-Ku meliputi segala sesuatu.",
			Author:       "Al-Quran",
			Source:       "QS. Al-A'raf: 156",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 680,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Berlomba dalam Kebaikan",
			Text:         "Maka berlomba-lombalah kamu (dalam berbuat) kebaikan. Di mana saja kamu berada pasti Allah akan mengumpulkan kamu sekalian.",
			Author:       "Al-Quran",
			Source:       "QS. Al-Baqarah: 148",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 690,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Balasan Kebaikan",
			Text:         "Tidak ada balasan kebaikan kecuali kebaikan (pula).",
			Author:       "Al-Quran",
			Source:       "QS. Ar-Rahman: 60",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 700,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Perniagaan yang Tidak Merugi",
			Text:         "Sesungguhnya orang-orang yang selalu membaca kitab Allah dan mendirikan shalat dan menafkahkan sebahagian dari rezeki yang Kami anugerahkan kepada mereka secara diam-diam dan terang-terangan, mereka itu mengharapkan perniagaan yang tidak akan merugi.",
			Author:       "Al-Quran",
			Source:       "QS. Fatir: 29",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 710,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Perhiasan Kehidupan Dunia",
			Text:         "Harta dan anak-anak adalah perhiasan kehidupan dunia, tetapi amalan-amalan yang kekal lagi saleh adalah lebih baik pahalanya di sisi Rabbmu serta lebih baik untuk menjadi harapan.",
			Author:       "Al-Quran",
			Source:       "QS. Al-Kahfi: 46",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 720,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Hari Ditampakkan Amal",
			Text:         "Barangsiapa yang mengerjakan kebaikan seberat dzarrah pun, niscaya dia akan melihat (balasan)nya. Dan barangsiapa yang mengerjakan kejahatan seberat dzarrah pun, niscaya dia akan melihat (balasan)nya pula.",
			Author:       "Al-Quran",
			Source:       "QS. Az-Zalzalah: 7-8",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 730,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Jangan Menghinakan Diri Sendiri",
			Text:         "Wahai orang-orang yang beriman, bertakwalah kepada Allah dan hendaklah setiap diri memperhatikan apa yang telah diperbuatnya untuk hari esok (akhirat).",
			Author:       "Al-Quran",
			Source:       "QS. Al-Hasyr: 18",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 740,
		},
		{
			Type:         model.DailyReminderTypeQuote,
			Title:        "Cahaya Petunjuk",
			Text:         "Kitab (Al-Quran) ini tidak ada keraguan padanya; petunjuk bagi mereka yang bertakwa.",
			Author:       "Al-Quran",
			Source:       "QS. Al-Baqarah: 2",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 750,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Sedekah Subuh",
			Text:         "Mulailah pagimu dengan bersedekah walau hanya sedikit uang atau doa kebaikan; dua malaikat berdoa untuk orang yang berinfak setiap pagi.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 760,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Menjaga Wudhu",
			Text:         "Biasakan memperbarui wudhu ketika batal; keadaan suci menjaga ketenangan hati dan menjauhkan godaan setan.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 770,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Catat Faedah Ilmu",
			Text:         "Ikatlah ilmu dengan menuliskannya. Faedah yang tidak dicatat akan mudah hilang terbawa kesibukan dunia.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 780,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Menghidupkan Sepertiga Malam",
			Text:         "Sempatkan dua rakaat sholat tahajud di akhir malam, ketika Allah turun ke langit dunia dan mengabulkan setiap doa hamba-Nya.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 790,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Menjaga Silaturahmi",
			Text:         "Sapa orang tua, keluarga, atau saudaramu hari ini; silaturahmi melapangkan rezeki dan memanjangkan umur dalam keberkahan.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 800,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Dzikir Pagi dan Petang",
			Text:         "Jangan lewatkan wirid pagi dan petang; keduanya adalah benteng kokoh dari marabahaya, kegelisahan, dan gangguan makhluk halus.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 810,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Memaafkan Sebelum Tidur",
			Text:         "Lapangkan dada dan maafkan semua orang yang pernah berbuat salah kepadamu sebelum memejamkan mata; raih malam yang tenang tanpa dendam.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 820,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Menghindari Perdebatan Kusir",
			Text:         "Tinggalkan debat kusir meskipun engkau merasa benar; menjaga kebersihan hati dan kehangatan persaudaraan jauh lebih berharga.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 830,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Menjaga Amanah Waktu Kerja",
			Text:         "Tunaikan tugas dan pekerjaanmu dengan penuh amanah; rezeki yang berkah berawal dari ketulusan dan kejujuran dalam bekerja.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 840,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Adab Bertutur Kata di Media Sosial",
			Text:         "Sebelum memposting atau berkomentar, tanyakan pada diri sendiri: apakah perkataan ini bernilai pahala atau justru memberatkan timbangan dosa?",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 850,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Satu Hari Satu Kebaikan Tersembunyi",
			Text:         "Lakukan minimal satu amalan rahasia setiap hari yang hanya diketahui oleh Allah semata; ia menjadi penolong di saat sulit.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 860,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Menjaga Pandangan dari Hal Haram",
			Text:         "Tundukkan pandangan dari hal-hal yang diharamkan Allah; manisnya rasa iman hanya akan masuk ke hati yang bersih dari racun maksiat mata.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 870,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Syukuri Makanan yang Ada",
			Text:         "Jangan pernah mencela makanan; jika menyukainya makanlah, dan jika tidak berselera tinggalkanlah dengan baik tanpa keluhan.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 880,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Menuntut Ilmu Bersama Guru",
			Text:         "Ambillah ilmu dari para guru dan asatidz yang terpercaya sanad dan manhajnya; jangan hanya bersandar pada lembaran tanpa bimbingan.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 890,
		},
		{
			Type:         model.DailyReminderTypeAdvice,
			Title:        "Menyebarkan Salam",
			Text:         "Tebarkan salam kepada orang yang engkau kenal maupun yang tidak engkau kenal; ia menumbuhkan cinta dan meruntuhkan rasa angkuh.",
			Author:       "Thullaabul 'Ilmi",
			Source:       "Pengingat harian",
			Lang:         "idn",
			IsActive:     true,
			DisplayOrder: 900,
		},
	}
}
