package migrations

import (
	"github.com/agambondan/islamic-explorer/app/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

func getMasjidData() []model.Masjid {
	return []model.Masjid{
		{
			Name:        "Masjid Jami' Al-Barkah (Rodja)",
			Description: "Masjid utama sekaligus pusat Radio Rodja 756 AM. Siaran kajian ilmiah Islam berlandaskan Al-Qur'an dan As-Sunnah pemahaman Salafush Shalih.",
			Address:     "Jl. Pahlawan, Kp. Tengah RT 03/03, Cileungsi, Kabupaten Bogor, Jawa Barat 16820",
			District:    "Cileungsi",
			City:        "Bogor",
			Province:    "Jawa Barat",
			Latitude:    -6.3952078,
			Longitude:   106.9588901,
			Phone:       "021-22887131",
			Capacity:    2500,
			Facilities:  "Kajian sunnah rutin, live streaming Rodja, perpustakaan kitab, ruang wudhu, parkir",
			ImageURL:    "",
			Website:     "https://radiorodja.com",
			IsActive:    true,
		},
		{
			Name:        "Masjid Nur-Salma",
			Description: "Masjid yayasan Nur-Salma yang diasuh Ustadz Dr. Erwandi Tarmizi, MA. Fokus kajian tauhid, jual-beli riba, dan hadits arbain.",
			Address:     "Centennial Tower Lt. 22, Jl. Jenderal Gatot Subroto Kav. 24-25, Karet Semanggi, Setiabudi, Kota Jakarta Selatan, DKI Jakarta 12950",
			District:    "Setiabudi",
			City:        "Jakarta Selatan",
			Province:    "DKI Jakarta",
			Latitude:    -6.2301492,
			Longitude:   106.8208588,
			Phone:       "021-52901234",
			Capacity:    1500,
			Facilities:  "Kajian sunnah, perpustakaan kitab kuning, ruang wudhu, kelas tahsin & tahfizh",
			ImageURL:    "",
			Website:     "https://nursalma.or.id",
			IsActive:    true,
		},
		{
			Name:        "Masjid Nurim Blok M",
			Description: "Masjid di pusat Blok M, pengajian rutin ahlussunnah waljama'ah yang ramai dikunjungi karyawan & mahasiswa sekitar Kebayoran.",
			Address:     "Jl. Wolter Monginsidi No.71, Kebayoran Baru, Kota Jakarta Selatan, DKI Jakarta 12180",
			District:    "Kebayoran Baru",
			City:        "Jakarta Selatan",
			Province:    "DKI Jakarta",
			Latitude:    -6.2397,
			Longitude:   106.8058,
			Phone:       "021-7206123",
			Capacity:    1800,
			Facilities:  "Kajian sunnah pekanan, kelas bahasa Arab, wudhu & parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Sunda Kelapa",
			Description: "Pusat dakwah dan kajian sunnah di kawasan Menteng. Dipimpin Ustadz Dudi Muttaqien dan asatidzah salaf lainnya.",
			Address:     "Jl. Taman Sunda Kelapa No.16, Menteng, Kota Jakarta Pusat, DKI Jakarta 10310",
			District:    "Menteng",
			City:        "Jakarta Pusat",
			Province:    "DKI Jakarta",
			Latitude:    -6.2012984,
			Longitude:   106.8322571,
			Phone:       "021-31934261",
			Capacity:    4000,
			Facilities:  "Kajian rutin, perpustakaan, aula, klinik dhuafa, parkir",
			ImageURL:    "",
			Website:     "https://masjidsundakelapa.id",
			IsActive:    true,
		},
		{
			Name:        "Masjid Al-Ikhlas Cipete",
			Description: "Salah satu pusat kajian ilmiah dan tadabbur Qur'an teraktif di Cipete-Cilandak, salaf-affiliated.",
			Address:     "Jl. Cipete III No.3, Cipete Selatan, Cilandak, Kota Jakarta Selatan, DKI Jakarta 12410",
			District:    "Cilandak",
			City:        "Jakarta Selatan",
			Province:    "DKI Jakarta",
			Latitude:    -6.2789206,
			Longitude:   106.7997904,
			Phone:       "021-7690123",
			Capacity:    2500,
			Facilities:  "Kajian sunnah rutin, streaming YouTube/Audio, perpustakaan, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Baitussalam Billy Moon",
			Description: "Masjid kajian sunnah tematik di kawasan Duren Sawit dengan pengajian keluarga dan pemuda aktif.",
			Address:     "Komplek Billy Moon, Pondok Kelapa, Duren Sawit, Kota Jakarta Timur, DKI Jakarta 13450",
			District:    "Duren Sawit",
			City:        "Jakarta Timur",
			Province:    "DKI Jakarta",
			Latitude:    -6.2480321,
			Longitude:   106.9291752,
			Phone:       "021-8645123",
			Capacity:    3000,
			Facilities:  "Kajian sunnah tematik, AC, perpustakaan, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Jami' Imam Asy-Syafi'i BSD",
			Description: "Masjid jami ahlussunnah di kawasan BSD City, dikenal dengan kajian hadits arbain dan fikih perbandingan madzhab.",
			Address:     "Jl. Kalimantan, BSD City, Serpong, Kota Tangerang Selatan, Banten 15310",
			District:    "Serpong",
			City:        "Tangerang Selatan",
			Province:    "Banten",
			Latitude:    -6.3006,
			Longitude:   106.6854,
			Phone:       "021-5371234",
			Capacity:    2000,
			Facilities:  "Kajian sunnah, perpustakaan, ruang wudhu, parkir luas",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Ar-Rohmah Cibubur",
			Description: "Masjid ahlussunnah di Cibubur, pengajian keluarga dan remaja aktif dengan tema tarbiyah dan aqidah.",
			Address:     "Komp. Kota Wisata Cibubur, Nagrak, Gunung Putri, Kabupaten Bogor, Jawa Barat 16968",
			District:    "Gunung Putri",
			City:        "Bogor",
			Province:    "Jawa Barat",
			Latitude:    -6.3851121,
			Longitude:   106.9543061,
			Phone:       "021-84934567",
			Capacity:    1500,
			Facilities:  "Kajian keluarga, kelas tahfizh, wudhu, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Istiqlal",
			Description: "Masjid nasional Indonesia dan salah satu masjid terbesar di Asia Tenggara. Peletakan batu pertama oleh Presiden Soekarno pada 24 Agustus 1961, dirancang arsitek Frederich Silaban, dan diresmikan sebagai masjid nasional oleh Presiden Soeharto pada 22 Februari 1978.",
			Address:     "Jl. Taman Wijaya Kusuma, Ps. Baru, Kec. Sawah Besar, Kota Jakarta Pusat, DKI Jakarta 10710",
			District:    "Sawah Besar",
			City:        "Jakarta Pusat",
			Province:    "DKI Jakarta",
			Latitude:    -6.1697,
			Longitude:   106.8308,
			Phone:       "",
			Capacity:    200000,
			Facilities:  "Ruang shalat utama, plaza, perpustakaan, museum, parkir luas",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Raya Baiturrahman Banda Aceh",
			Description: "Masjid agung ikon Provinsi Aceh, dibangun pemerintah kolonial Belanda pada 1879-1881 menggantikan masjid lama yang terbakar saat Perang Aceh. Dikenal karena menjadi salah satu bangunan yang selamat dari gempa dan tsunami Aceh 2004.",
			Address:     "Jl. Moh. Jam No.1, Kampung Baru, Kec. Baiturrahman, Kota Banda Aceh, Aceh",
			District:    "Baiturrahman",
			City:        "Banda Aceh",
			Province:    "Aceh",
			Latitude:    5.55361,
			Longitude:   95.317194,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Halaman luas, perpustakaan, museum tsunami, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Raya Al-Mashun Medan",
			Description: "Masjid utama peninggalan Kesultanan Deli, dibangun 1906-1909 di kompleks Istana Maimun. Memadukan gaya arsitektur Timur Tengah, India, dan Spanyol, dibiayai antara lain oleh Kesultanan Deli dan pengusaha Tjong A Fie.",
			Address:     "Jl. Masjid Raya, Kelurahan Aur, Kec. Medan Maimun, Kota Medan, Sumatera Utara",
			District:    "Medan Maimun",
			City:        "Medan",
			Province:    "Sumatera Utara",
			Latitude:    3.575111,
			Longitude:   98.687321,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Halaman kompleks Istana Maimun, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Raya Sumatera Barat",
			Description: "Masjid raya Provinsi Sumatera Barat, dikenal sebagai Masjid Mahligai Minang karena atapnya berbentuk gonjong khas arsitektur Minangkabau. Dibangun 2007-2019 melalui sayembara desain yang dimenangkan arsitek Rizal Muslimin.",
			Address:     "Jl. Khatib Sulaiman, Alai Parak Kopi, Padang Utara, Kota Padang, Sumatera Barat 25173",
			District:    "Padang Utara",
			City:        "Padang",
			Province:    "Sumatera Barat",
			Latitude:    -0.924306,
			Longitude:   100.362611,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Halaman luas, area parkir, ukiran kaligrafi khas Minang",
			ImageURL:    "",
			Website:     "https://masjidraya.sumbarprov.go.id",
			IsActive:    true,
		},
		{
			Name:        "Masjid Raya An-Nur Pekanbaru",
			Description: "Masjid raya Provinsi Riau, dibangun 1963 dan diresmikan 1968, lalu direnovasi besar pada masa Gubernur Saleh Djasit hingga menjadi salah satu masjid termegah di Sumatera.",
			Address:     "Jl. Hangtuah, Sumahilang, Kec. Pekanbaru Kota, Kota Pekanbaru, Riau 28156",
			District:    "Pekanbaru Kota",
			City:        "Pekanbaru",
			Province:    "Riau",
			Latitude:    0.537800,
			Longitude:   101.437040,
			Phone:       "",
			Capacity:    4500,
			Facilities:  "Halaman luas, perpustakaan, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Raya Sultan Riau Penyengat",
			Description: "Masjid bersejarah peninggalan Kesultanan Riau-Lingga di Pulau Penyengat, mulai dibangun sekitar 1803 dan direnovasi 1832. Memiliki 13 kubah dan 17 menara-kubah kecil, dan berstatus cagar budaya nasional.",
			Address:     "Pulau Penyengat, Kota Tanjungpinang, Kepulauan Riau",
			District:    "Tanjungpinang Kota",
			City:        "Tanjungpinang",
			Province:    "Kepulauan Riau",
			Latitude:    0.929440,
			Longitude:   104.420390,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Situs cagar budaya, halaman masjid, dermaga penyeberangan",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Agung Al-Falah Jambi",
			Description: "Masjid agung Kota Jambi yang dikenal sebagai Masjid Seribu Tiang, dibangun 1971-1980 dan diresmikan Presiden Soeharto pada 29 September 1980.",
			Address:     "Jl. Sultan Thaha, Legok, Telanaipura, Kota Jambi, Jambi 36124",
			District:    "Telanaipura",
			City:        "Jambi",
			Province:    "Jambi",
			Latitude:    -1.594178,
			Longitude:   103.608285,
			Phone:       "",
			Capacity:    10000,
			Facilities:  "Halaman luas, perpustakaan, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Agung Sultan Mahmud Badaruddin I Jayo Wikramo Palembang",
			Description: "Masjid tertua dan terbesar di Palembang, dibangun Sultan Mahmud Badaruddin I sejak 1738-1748 di kawasan permukiman Melayu-Arab 19 Ilir. Arsitekturnya memadukan unsur Melayu, Tionghoa, dan Eropa.",
			Address:     "Jl. Jenderal Sudirman, 19 Ilir, Bukit Kecil, Kota Palembang, Sumatera Selatan",
			District:    "Bukit Kecil",
			City:        "Palembang",
			Province:    "Sumatera Selatan",
			Latitude:    -2.987480,
			Longitude:   104.759970,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Halaman kompleks bersejarah, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Jamik Pangkalpinang",
			Description: "Masjid tertua dan terbesar di Pangkalpinang, dibangun para penambang timah keturunan Melayu, Tionghoa, dan Arab pada 1936. Ornamennya memadukan ukiran kayu, keramik porselen, dan kubah berlapis emas.",
			Address:     "Jl. Masjid Jamik, Kec. Rangkui, Kota Pangkalpinang, Kepulauan Bangka Belitung 33684",
			District:    "Rangkui",
			City:        "Pangkal Pinang",
			Province:    "Kepulauan Bangka Belitung",
			Latitude:    -2.130821,
			Longitude:   106.109828,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Halaman masjid, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Jamik Bengkulu",
			Description: "Masjid bersejarah yang rekonstruksinya dirancang Ir. Soekarno saat menjalani masa pengasingan di Bengkulu, memadukan gaya arsitektur Jawa dan Sumatra. Ditetapkan sebagai cagar budaya nasional pada 2004.",
			Address:     "Jl. Jenderal Suprapto, Kel. Penggantungan, Kec. Gading Cempaka, Kota Bengkulu, Bengkulu",
			District:    "Gading Cempaka",
			City:        "Bengkulu",
			Province:    "Bengkulu",
			Latitude:    -3.792340,
			Longitude:   102.262240,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Situs cagar budaya, halaman masjid, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Agung Al-Furqon Bandar Lampung",
			Description: "Masjid agung Kota Bandar Lampung yang dibangun atas prakarsa Presiden Soekarno sejak 1951 dan diresmikan 1961, dengan menara setinggi 114 meter yang menjadi salah satu ikon kota.",
			Address:     "Jl. Diponegoro, Gulak Galik, Kec. Tlk. Betung Utara, Kota Bandar Lampung, Lampung 35212",
			District:    "Teluk Betung Utara",
			City:        "Bandar Lampung",
			Province:    "Lampung",
			Latitude:    -5.435162,
			Longitude:   105.246967,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Halaman luas, menara ikon kota, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Agung Jawa Tengah",
			Description: "Masjid agung Provinsi Jawa Tengah, dibangun 2001-2006 dan diresmikan Presiden Susilo Bambang Yudhoyono. Arsitekturnya memadukan gaya Jawa, Islam, dan Yunani, dengan ciri khas enam payung elektrik raksasa terinspirasi Masjid Nabawi Madinah.",
			Address:     "Jl. Gajah Raya, Sambirejo, Kec. Gayamsari, Kota Semarang, Jawa Tengah 50166",
			District:    "Gayamsari",
			City:        "Semarang",
			Province:    "Jawa Tengah",
			Latitude:    -6.983900,
			Longitude:   110.445800,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Payung elektrik raksasa, halaman luas, menara pandang, parkir",
			ImageURL:    "",
			Website:     "https://majt.or.id",
			IsActive:    true,
		},
		{
			Name:        "Masjid Gedhe Kauman Yogyakarta",
			Description: "Masjid utama Kesultanan Ngayogyakarta, dibangun Sri Sultan Hamengku Buwono I bersama Kyai Faqih Ibrahim Diponingrat pada 1773, terletak di sisi barat kompleks Alun-Alun Utara Yogyakarta.",
			Address:     "Jl. Kauman, Kampung Kauman, Ngupasan, Gondomanan, Kota Yogyakarta, DI Yogyakarta",
			District:    "Gondomanan",
			City:        "Yogyakarta",
			Province:    "DI Yogyakarta",
			Latitude:    -7.802415,
			Longitude:   110.362297,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Halaman kompleks keraton, pagongan, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Nasional Al-Akbar Surabaya",
			Description: "Masjid nasional dan masjid terbesar kedua di Indonesia setelah Istiqlal, peletakan batu pertamanya pada 4 Agustus 1995. Berdiri di lahan 11,2 hektare dengan kapasitas puluhan ribu jamaah.",
			Address:     "Jl. Masjid Al-Akbar Timur No.1, Pagesangan, Kec. Jambangan, Kota Surabaya, Jawa Timur 60233",
			District:    "Jambangan",
			City:        "Surabaya",
			Province:    "Jawa Timur",
			Latitude:    -7.336294,
			Longitude:   112.715330,
			Phone:       "",
			Capacity:    36000,
			Facilities:  "Menara pandang, perpustakaan, halaman luas, parkir",
			ImageURL:    "",
			Website:     "https://www.masjidalakbar.or.id",
			IsActive:    true,
		},
		{
			Name:        "Masjid Agung Sudirman Denpasar",
			Description: "Masjid agung utama Kota Denpasar, berdiri sejak 1974 di dalam kawasan Kodam IX/Udayana namun tetap terbuka untuk umum. Dikenal karena memadukan unsur arsitektur Bali pada bangunannya.",
			Address:     "Jl. Slamet Riyadi No.1, Dauh Puri, Denpasar Barat, Kota Denpasar, Bali",
			District:    "Denpasar Barat",
			City:        "Denpasar",
			Province:    "Bali",
			Latitude:    -8.667030,
			Longitude:   115.219610,
			Phone:       "0361-264595",
			Capacity:    0,
			Facilities:  "Halaman masjid, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Raya Hubbul Wathan Islamic Center NTB",
			Description: "Masjid raya sekaligus Islamic Center Provinsi Nusa Tenggara Barat, dibangun 2010-2013. Memiliki 4 lantai, 5 kubah, dan 5 menara, salah satunya setinggi 99 meter melambangkan asmaul husna.",
			Address:     "Jl. Udayana No.1, Kelurahan Gomong, Kec. Selaparang, Kota Mataram, Nusa Tenggara Barat",
			District:    "Selaparang",
			City:        "Mataram",
			Province:    "Nusa Tenggara Barat",
			Latitude:    -8.579965,
			Longitude:   116.100609,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Halaman luas, menara pandang, perpustakaan, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Agung Al-Baitul Qadim Kupang",
			Description: "Masjid tertua di Pulau Timor, telah berdiri lebih dari dua abad di kawasan Kampung Airmata, Kota Kupang, dan menjadi salah satu pusat sejarah masuknya Islam di Nusa Tenggara Timur.",
			Address:     "Kelurahan Airmata, Kec. Kota Lama, Kota Kupang, Nusa Tenggara Timur",
			District:    "Kota Lama",
			City:        "Kupang",
			Province:    "Nusa Tenggara Timur",
			Latitude:    -10.165516,
			Longitude:   123.578035,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Situs bersejarah, halaman masjid, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Jami' Sultan Syarif Abdurrahman Pontianak",
			Description: "Masjid tertua dan terbesar di Pontianak, didirikan bersamaan dengan berdirinya Kota Pontianak pada 1771 oleh Sultan Syarif Abdurrahman Alkadrie.",
			Address:     "Kampung Dalam Bugis, Kec. Pontianak Timur, Kota Pontianak, Kalimantan Barat",
			District:    "Pontianak Timur",
			City:        "Pontianak",
			Province:    "Kalimantan Barat",
			Latitude:    -0.026738,
			Longitude:   109.347678,
			Phone:       "",
			Capacity:    1500,
			Facilities:  "Situs bersejarah, halaman tepi Sungai Kapuas, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Raya Darussalam Palangka Raya",
			Description: "Masjid raya Provinsi Kalimantan Tengah, awalnya didirikan 1984 lalu direnovasi 2011-2014. Arsitekturnya memadukan gaya modern dan Arab dengan ornamen khas suku Dayak.",
			Address:     "Jl. George Obos, Menteng, Kec. Jekan Raya, Kota Palangka Raya, Kalimantan Tengah 73112",
			District:    "Jekan Raya",
			City:        "Palangka Raya",
			Province:    "Kalimantan Tengah",
			Latitude:    -2.230718,
			Longitude:   113.890220,
			Phone:       "",
			Capacity:    20000,
			Facilities:  "Halaman luas, ornamen khas Dayak, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Raya Sabilal Muhtadin Banjarmasin",
			Description: "Masjid raya Provinsi Kalimantan Selatan, dibangun 1974 dan diresmikan 1981 untuk menghormati ulama besar Syekh Muhammad Arsyad al-Banjari. Berdiri di bekas lokasi benteng kolonial Fort Van Tatas.",
			Address:     "Jl. Jenderal Sudirman, Antasan Besar, Kec. Banjarmasin Tengah, Kota Banjarmasin, Kalimantan Selatan 70114",
			District:    "Banjarmasin Tengah",
			City:        "Banjarmasin",
			Province:    "Kalimantan Selatan",
			Latitude:    -3.319012,
			Longitude:   114.591256,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Halaman luas di tengah kota, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Islamic Center Samarinda (Baitul Muttaqien)",
			Description: "Masjid raya Provinsi Kalimantan Timur di tepi Sungai Mahakam, salah satu masjid terbesar di Asia Tenggara dengan tujuh menara dan satu kubah besar.",
			Address:     "Jl. Slamet Riyadi No.1, Teluk Lerong Ulu, Kec. Sungai Kunjang, Kota Samarinda, Kalimantan Timur 75243",
			District:    "Sungai Kunjang",
			City:        "Samarinda",
			Province:    "Kalimantan Timur",
			Latitude:    -0.502440,
			Longitude:   117.119810,
			Phone:       "",
			Capacity:    10000,
			Facilities:  "Halaman tepi Sungai Mahakam, tujuh menara, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Baitul Izzah Islamic Center Tarakan",
			Description: "Masjid raya sekaligus Islamic Center terbesar di Provinsi Kalimantan Utara, diresmikan 2012 dan berdiri di atas lahan sekitar 30 hektare.",
			Address:     "Jl. Sei Sesayap, Kampung Empat, Kec. Tarakan Timur, Kota Tarakan, Kalimantan Utara 77112",
			District:    "Tarakan Timur",
			City:        "Tarakan",
			Province:    "Kalimantan Utara",
			Latitude:    3.298636,
			Longitude:   117.624100,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Lahan luas, halaman Islamic Center, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Agung Awwal Fathul Mubien Manado",
			Description: "Masjid tertua di Kota Manado, didirikan sekitar 1770 dan menjadi salah satu pusat penyebaran Islam pertama di kawasan Sulawesi Utara.",
			Address:     "Jl. Sultan Hasanuddin, Kelurahan Islam, Kec. Tuminting, Kota Manado, Sulawesi Utara 95122",
			District:    "Tuminting",
			City:        "Manado",
			Province:    "Sulawesi Utara",
			Latitude:    1.521000,
			Longitude:   124.848000,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Situs bersejarah, halaman masjid, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Agung Baiturrahim Gorontalo",
			Description: "Masjid agung peninggalan Kesultanan Gorontalo, didirikan Raja Botutihe pada 1728. Bangunannya menyerupai dua bangunan kembar yang menyatu.",
			Address:     "Jl. Nani Wartabone, Heledulaa Selatan, Kec. Kota Selatan, Kota Gorontalo, Gorontalo 96114",
			District:    "Kota Selatan",
			City:        "Gorontalo",
			Province:    "Gorontalo",
			Latitude:    0.537908,
			Longitude:   123.060309,
			Phone:       "",
			Capacity:    4000,
			Facilities:  "Situs bersejarah, halaman masjid, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Raya Baitul Khairaat Provinsi Sulawesi Tengah",
			Description: "Masjid raya Provinsi Sulawesi Tengah yang hancur total akibat gempa dan tsunami Palu 2018 saat masih bernama Masjid Agung Darussalam, lalu dibangun kembali dan diresmikan dengan nama baru Masjid Raya Baitul Khairaat pada Februari 2025.",
			Address:     "Jl. WR Supratman, Kelurahan Kamonji, Kec. Palu Barat, Kota Palu, Sulawesi Tengah 94223",
			District:    "Palu Barat",
			City:        "Palu",
			Province:    "Sulawesi Tengah",
			Latitude:    -0.899148,
			Longitude:   119.848710,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Bangunan tahan gempa, museum, halaman luas, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Agung Mamuju (Masjid Syuhada)",
			Description: "Masjid agung Kabupaten Mamuju, dikenal juga sebagai Masjid Syuhada, selesai dibangun dan mulai digunakan pada 2009 dengan empat menara setinggi 75 meter.",
			Address:     "Jl. KH Abdul Ahadi, Kabupaten Mamuju, Sulawesi Barat",
			District:    "Mamuju",
			City:        "Mamuju",
			Province:    "Sulawesi Barat",
			Latitude:    -2.453759,
			Longitude:   119.135361,
			Phone:       "",
			Capacity:    10000,
			Facilities:  "Empat menara, halaman luas, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Al-Markaz Al-Islami Makassar",
			Description: "Masjid raya Provinsi Sulawesi Selatan yang dibangun atas prakarsa Jenderal M. Jusuf pada 1994-1996, salah satu pusat kegiatan keislaman terbesar di Indonesia Timur.",
			Address:     "Jl. Masjid Raya, Timungan Lompoa, Kec. Bontoala, Kota Makassar, Sulawesi Selatan",
			District:    "Bontoala",
			City:        "Makassar",
			Province:    "Sulawesi Selatan",
			Latitude:    -5.129989,
			Longitude:   119.426323,
			Phone:       "",
			Capacity:    10000,
			Facilities:  "Halaman luas, perpustakaan, aula serbaguna, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Al-Alam Kendari",
			Description: "Masjid terapung ikon Kota Kendari yang berdiri di atas perairan Teluk Kendari, mulai dibangun 2010 dan diresmikan 2018, dengan empat menara terinspirasi Burj Al Arab Dubai.",
			Address:     "Teluk Kendari, Kelurahan Lalolara, Kec. Kambu, Kota Kendari, Sulawesi Tenggara",
			District:    "Kambu",
			City:        "Kendari",
			Province:    "Sulawesi Tenggara",
			Latitude:    -4.015152,
			Longitude:   122.530309,
			Phone:       "",
			Capacity:    10000,
			Facilities:  "Masjid terapung di tepi teluk, plaza terbuka, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Raya Al-Fatah Ambon",
			Description: "Masjid raya terbesar di Provinsi Maluku, dibangun 1979, dikenal sebagai simbol toleransi dan kerukunan antarumat di Kota Ambon.",
			Address:     "Jl. Sultan Babullah, Honipopu, Kec. Sirimau, Kota Ambon, Maluku 97123",
			District:    "Sirimau",
			City:        "Ambon",
			Province:    "Maluku",
			Latitude:    -3.693372,
			Longitude:   128.176613,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Halaman luas, tujuh pintu masuk, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Sultan Ternate",
			Description: "Masjid peninggalan Kesultanan Ternate, kesultanan Islam pertama di kawasan timur Nusantara sejak akhir abad ke-15. Dibangun dari susunan batu dengan bahan perekat getah pohon kalumpang, kini berstatus cagar budaya.",
			Address:     "Jl. Sultan Khairun, Kelurahan Soa Sio, Kec. Ternate Utara, Kota Ternate, Maluku Utara 97711",
			District:    "Ternate Utara",
			City:        "Ternate",
			Province:    "Maluku Utara",
			Latitude:    0.807350,
			Longitude:   127.379671,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Situs cagar budaya, kompleks Kedaton Kesultanan Ternate, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Raya Baiturrahim Jayapura",
			Description: "Masjid raya Provinsi Papua, dibangun 1971 dan direnovasi sejak 2006, menjadi salah satu ikon umat Islam di Tanah Papua.",
			Address:     "Jl. Jenderal Ahmad Yani, Gurabesi, Kec. Jayapura Utara, Kota Jayapura, Papua 99221",
			District:    "Jayapura Utara",
			City:        "Jayapura",
			Province:    "Papua",
			Latitude:    -2.547561,
			Longitude:   140.692809,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Halaman masjid, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
	}
}

func getRadioIslamicData() []model.RadioIslamic {
	return []model.RadioIslamic{
		{
			Name:        "Radio Rodja 756 AM",
			Frequency:   "756 AM",
			City:        "Jakarta",
			Province:    "DKI Jakarta",
			StreamURL:   "https://live2.radiorodja.com/rodja.mp3",
			Description: "Radio Menebar Cahaya Sunnah. Siaran kajian ilmiah Islam berlandaskan Al-Qur'an dan As-Sunnah pemahaman Salafush Shalih.",
			LogoURL:     "",
			Website:     "https://radiorodja.com",
			IsActive:    true,
			Tags:        "kajian,sunnah,salaf,ceramah,bahasa-arab,tanya-jawab",
		},
		{
			Name:        "Radio Silaturahim (Rasil) 720 AM",
			Frequency:   "720 AM",
			City:        "Jakarta",
			Province:    "DKI Jakarta",
			StreamURL:   "https://ssg.streamingmurah.com:9300/;",
			Description: "Untuk Islam yang Satu. Radio dakwah, berita Islam terkini, dialog kebangsaan, dan kesehatan.",
			LogoURL:     "",
			Website:     "https://radiosilaturahim.com",
			IsActive:    true,
			Tags:        "dakwah,berita,dialog,kesehatan,silaturahim",
		},
		{
			Name:        "Radio Muadz Jakarta & Kendari",
			Frequency:   "Streaming / Relay",
			City:        "Jakarta",
			Province:    "DKI Jakarta",
			StreamURL:   "https://radioislamindonesia.com/radiomuadz.mp3",
			Description: "Radio dakwah Ahlussunnah wal Jama'ah menyiarkan kajian fiqih, tafsir, aqidah, dan murottal Al-Qur'an 24 jam.",
			LogoURL:     "",
			Website:     "https://radiomuadz.com",
			IsActive:    true,
			Tags:        "murottal,kajian,aqidah,fiqih,sunnah",
		},
		{
			Name:        "Radio Tarbiyah Sunnah Bandung (1476 AM)",
			Frequency:   "1476 AM",
			City:        "Bandung",
			Province:    "Jawa Barat",
			StreamURL:   "https://radioislamindonesia.com/tarbiyah.mp3",
			Description: "Radio kajian sunnah asuhan Ustadz Abu Haidar As-Sundawy, Ustadz Yazid Jawas, dan asatidzah lainnya.",
			LogoURL:     "",
			Website:     "https://tarbiyahsunnah.com",
			IsActive:    true,
			Tags:        "kajian,sunnah,tarbiyah,tazkiyatun-nufus",
		},
		{
			Name:        "Radio Muslim Jogja (1467 AM)",
			Frequency:   "1467 AM",
			City:        "Yogyakarta",
			Province:    "DI Yogyakarta",
			StreamURL:   "https://streaming.radiomuslim.com/;stream/1",
			Description: "Memurnikan Aqidah Menebarkan Sunnah. Radio dakwah komunitas mahasiswa dan masyarakat Jogja.",
			LogoURL:     "",
			Website:     "https://radiomuslim.com",
			IsActive:    true,
			Tags:        "mahasiswa,kajian,aqidah,sunnah,jogja",
		},
		{
			Name:        "Radio Suara Al-Iman Surabaya (846 AM)",
			Frequency:   "846 AM",
			City:        "Surabaya",
			Province:    "Jawa Timur",
			StreamURL:   "https://radioislamindonesia.com/aliman.mp3",
			Description: "Sarana Menyapa Hati dengan Sunnah. Radio dakwah Jawa Timur berpusat di STDI Imam Syafi'i.",
			LogoURL:     "",
			Website:     "https://suaraaliman.com",
			IsActive:    true,
			Tags:        "kajian,surabaya,sunnah,fiqih",
		},
		{
			Name:        "Radio Fajri FM 99.3 FM (Bogor-Jakarta)",
			Frequency:   "99.3 FM",
			City:        "Bogor",
			Province:    "Jawa Barat",
			StreamURL:   "https://radio.mitradio.com/listen/fajrifm/radio.mp3",
			Description: "Suara Kebangkitan Islam. Menjangkau wilayah Bogor, Depok, dan sebagian Jakarta.",
			LogoURL:     "",
			Website:     "https://fajrifm.com",
			IsActive:    true,
			Tags:        "dakwah,bogor,jakarta,keluarga-islami",
		},
		{
			Name:        "Radio Hang FM 106.0 FM (Batam-Kepri)",
			Frequency:   "106.0 FM",
			City:        "Batam",
			Province:    "Kepulauan Riau",
			StreamURL:   "https://icecast.surau.tv/hangfm",
			Description: "Radio Sunnah tertua di Kepulauan Riau menjangkau Batam, Singapura, dan Johor Bahru Malaysia.",
			LogoURL:     "",
			Website:     "https://hangfm.id",
			IsActive:    true,
			Tags:        "sunnah,batam,singapura,serumpun",
		},
		{
			Name:        "Radio Kita FM 94.3 FM (Cirebon)",
			Frequency:   "94.3 FM",
			City:        "Cirebon",
			Province:    "Jawa Barat",
			StreamURL:   "https://broadcast.yufid.com/listen/radio_sunnah_cirebon/kitafm",
			Description: "Menebar Sunnah Membangun Umat di wilayah Ciayumajakuning.",
			LogoURL:     "",
			Website:     "https://radiokitafm.com",
			IsActive:    true,
			Tags:        "sunnah,cirebon,pantura",
		},
		{
			Name:        "Quran Stream Radio 24 Jam",
			Frequency:   "Digital Stream",
			City:        "Nasional",
			Province:    "Indonesia",
			StreamURL:   "",
			Description: "Lantunan Murottal Al-Qur'an 30 Juz 24 jam nonstop dari para Qari Masyhur dunia.",
			LogoURL:     "",
			Website:     "",
			IsActive:    true,
			Tags:        "murottal,quran,tilawah,24jam,tanpa-jeda",
		},
	}
}

func seedMasjids() []model.Masjid {
	return getMasjidData()
}

func seedRadioIslamic() []model.RadioIslamic {
	return getRadioIslamicData()
}

func SeedMasjids(db *gorm.DB) {
	masjids := getMasjidData()
	for _, m := range masjids {
		_ = db.Clauses(clause.OnConflict{
			Columns:   []clause.Column{{Name: "name"}},
			DoUpdates: clause.AssignmentColumns([]string{"description", "address", "district", "city", "province", "latitude", "longitude", "phone", "capacity", "facilities", "website", "is_active"}),
		}).Create(&m).Error
	}
}

func SeedRadioIslamic(db *gorm.DB) {
	radios := getRadioIslamicData()
	for _, r := range radios {
		_ = db.Clauses(clause.OnConflict{
			Columns:   []clause.Column{{Name: "name"}},
			DoUpdates: clause.AssignmentColumns([]string{"frequency", "city", "province", "stream_url", "description", "website", "is_active", "tags"}),
		}).Create(&r).Error
	}
}
