package migrations

import (
	"github.com/agambondan/islamic-explorer/app/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

func SeedLessons(db *gorm.DB) {
	modules := []model.LessonModule{
		{Slug: "wudhu", Title: "Tata Cara Wudhu", Description: "Belajar wudhu tahap demi tahap, lengkap dengan bacaan Arab, dalil, dan adab yang disunnahkan.", Category: "Fiqh Ibadah", Level: "Pemula", EstimatedMinutes: 8, Icon: "wudhu", Order: 1},
		{Slug: "sholat", Title: "Tata Cara Sholat", Description: "Panduan gerakan, bacaan rukun dan sunnah, lengkap dengan dalil Quran-Hadis.", Category: "Fiqh Ibadah", Level: "Pemula", EstimatedMinutes: 15, Icon: "sholat", Order: 2},
		{Slug: "adzan-iqomah", Title: "Mengenal Adzan & Iqomah", Description: "Makna, lafaz lengkap, urutan rukun, dan adab muadzin.", Category: "Fiqh Ibadah", Level: "Pemula", EstimatedMinutes: 10, Icon: "adzan", Order: 3},
		{Slug: "puasa", Title: "Fikih Puasa Ramadan", Description: "Syarat, rukun, pembatal, dan sunnah puasa, lengkap dengan contoh aplikatif.", Category: "Fiqh Ibadah", Level: "Menengah", EstimatedMinutes: 12, Icon: "puasa", Order: 4},
		{Slug: "zakat", Title: "Zakat Fitrah & Mal", Description: "Nisab, haul, dan 8 asnaf penerima zakat.", Category: "Fiqh Ibadah", Level: "Menengah", EstimatedMinutes: 12, Icon: "zakat", Order: 5},
		{Slug: "tajwid", Title: "Tajwid Dasar", Description: "Hukum nun mati/tanwin, mim mati, dan mad dengan contoh ayat.", Category: "Al-Quran", Level: "Menengah", EstimatedMinutes: 18, Icon: "tajwid", Order: 6},
		{Slug: "rukun-iman", Title: "Rukun Iman", Description: "Enam pilar keimanan dengan dalil Quran-Hadis.", Category: "Aqidah", Level: "Pemula", EstimatedMinutes: 10, Icon: "iman", Order: 7},
		{Slug: "adab-talab-ilmu", Title: "Adab Menuntut Ilmu", Description: "Etika menuntut ilmu, niat yang benar, dan keutamaan tholabul 'ilmi.", Category: "Adab", Level: "Pemula", EstimatedMinutes: 8, Icon: "book", Order: 8},
	}
	for i := range modules {
		db.Clauses(clause.OnConflict{
			Columns: []clause.Column{{Name: "slug"}},
			DoUpdates: clause.AssignmentColumns([]string{
				"title", "description", "category", "level", "estimated_minutes", "icon", "order", "updated_at",
			}),
		}).Create(&modules[i])
	}

	var stored []model.LessonModule
	db.Find(&stored)
	bySlug := map[string]int{}
	for _, m := range stored {
		if m.ID != nil {
			bySlug[m.Slug] = *m.ID
		}
	}

	steps := []model.LessonStep{
		// ===== WUDHU =====
		{ModuleID: bySlug["wudhu"], StepOrder: 1, Kind: "rukun", Title: "Niat di Hati & Membaca Bismillah", Body: "Niat wudhu letaknya di dalam hati tanpa dilafazkan lisan, karena tidak ada dalil shahih bahwa Rasulullah ﷺ melafazkan niat wudhu. Disunnahkan mengawali wudhu dengan membaca basmalah.", Arabic: "بِسْمِ اللَّهِ", Latin: "Bismillah", Translation: "Dengan menyebut nama Allah.", Dalil: "HR. Abu Dawud No. 101, Tirmidzi No. 25, Ibnu Majah No. 399 (Shahih): \"Tidak ada wudhu bagi orang yang tidak menyebut nama Allah padanya.\"", Tip: "Hadirkan niat di dalam hati untuk bersuci dari hadas kecil, lalu ucapkan basmalah sebelum mulai membasuh."},
		{ModuleID: bySlug["wudhu"], StepOrder: 2, Kind: "rukun", Title: "Membasuh Wajah", Body: "Siramkan air ke seluruh wajah: dari dahi tempat tumbuhnya rambut sampai dagu, dan dari telinga kanan ke telinga kiri. Wajah adalah anggota wudhu pertama yang wajib dibasuh.", Dalil: "QS. Al-Maidah: 6: \"...فَاغْسِلُوا وُجُوهَكُمْ...\" (Maka basuhlah wajahmu).", Tip: "Pastikan seluruh bagian wajah dan jenggot/rambut tipis basah merata."},
		{ModuleID: bySlug["wudhu"], StepOrder: 3, Kind: "rukun", Title: "Membasuh Kedua Tangan hingga Siku", Body: "Membasuh tangan mulai ujung jari hingga melewati siku. Dimulai dari tangan kanan terlebih dahulu sebanyak tiga kali, lalu tangan kiri dengan cara yang sama, sambil menyela-nyela jari jemari.", Dalil: "QS. Al-Maidah: 6: \"...وَأَيْدِيَكُمْ إِلَى الْمَرَافِقِ...\" (Dan tanganmu sampai ke siku); HR. Bukhari No. 159 (wudhu Utsman bin Affan).", Tip: "Jangan ada doa khusus per-anggota wudhu karena tidak ada riwayat shahih dari Nabi ﷺ."},
		{ModuleID: bySlug["wudhu"], StepOrder: 4, Kind: "rukun", Title: "Mengusap Kepala", Body: "Mengusap seluruh kepala sekali: menjalankan kedua telapak tangan dari depan kepala hingga ke tengkuk, lalu mengembalikannya ke tempat semula.", Dalil: "QS. Al-Maidah: 6: \"...وَامْسَحُوا بِرُءُوسِكُمْ...\" (Dan usaplah kepalamu); HR. Bukhari No. 185."},
		{ModuleID: bySlug["wudhu"], StepOrder: 5, Kind: "sunnah", Title: "Mengusap Kedua Telinga", Body: "Mengusap kedua telinga bersamaan setelah mengusap kepala dengan sisa air kepala: jari telunjuk membersihkan bagian dalam telinga, dan ibu jari membersihkan daun telinga bagian luar.", Dalil: "HR. Abu Dawud No. 135, Tirmidzi No. 36 (Shahih): \"Kedua telinga termasuk bagian dari kepala.\""},
		{ModuleID: bySlug["wudhu"], StepOrder: 6, Kind: "rukun", Title: "Membasuh Kedua Kaki hingga Mata Kaki", Body: "Membasuh kedua kaki hingga mata kaki, dimulai dari kaki kanan sebanyak tiga kali lalu kaki kiri, serta menyela-nyela jari kaki dengan jari kelingking.", Dalil: "QS. Al-Maidah: 6: \"...وَأَرْجُلَكُمْ إِلَى الْكَعْبَيْنِ...\" (Dan kakimu sampai ke kedua mata kaki); HR. Bukhari No. 165: \"Celakalah tumit-tumit (yang tidak basah) dari api neraka.\"", Tip: "Pastikan tumit dan lipatan mata kaki terkena air secara sempurna."},
		{ModuleID: bySlug["wudhu"], StepOrder: 7, Kind: "sunnah", Title: "Membaca Doa Setelah Wudhu", Body: "Setelah selesai wudhu, disunnahkan membaca doa persaksian tauhid dan permohonan ampunan serta kesucian.", Arabic: "أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ، اللَّهُمَّ اجْعَلْنِي مِنَ التَّوَّابِينَ وَاجْعَلْنِي مِنَ الْمُتَطَهِّرِينَ", Latin: "Asyhadu allaa ilaaha illallaah wahdahu laa syariika lah, wa asyhadu anna Muhammadan 'abduhu wa rasuuluh. Allaahummaj'alnii minat tawwaabiina waj'alnii minal mutathahhiriin", Translation: "Aku bersaksi bahwa tidak ada sesembahan yang berhak disembah selain Allah semata, tidak ada sekutu bagi-Nya. Dan aku bersaksi bahwa Muhammad adalah hamba dan utusan-Nya. Ya Allah, jadikanlah aku termasuk orang-orang yang bertaubat dan jadikanlah aku termasuk orang-orang yang menyucikan diri.", Dalil: "HR. Muslim No. 234 & HR. Tirmidzi No. 55 (Shahih): Dibukakan baginya delapan pintu surga."},

		{ModuleID: bySlug["sholat"], StepOrder: 1, Kind: "rukun", Title: "Takbiratul Ihram", Body: "Berdiri tegak menghadap kiblat, angkat kedua tangan sejajar telinga (laki-laki) atau sejajar bahu (perempuan), lalu bertakbir.", Arabic: "اللَّهُ أَكْبَرُ", Latin: "Allahu Akbar", Translation: "Allah Maha Besar.", Dalil: "HR. Bukhari No. 735: Panduan posisi tangan dan takbir pembuka shalat.", Tip: "Pastikan tumit rapat, pandangan ke tempat sujud, dan sudah berniat di hati untuk shalat tertentu."},
		{ModuleID: bySlug["sholat"], StepOrder: 2, Kind: "rukun", Title: "Membaca Al-Fatihah", Body: "Surat wajib dalam tiap rakaat setelah takbiratul ihram dan berdiri. Tidak sah shalat tanpa membacanya bagi imam maupun munfarid.", Arabic: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ ۝ الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ ۝ الرَّحْمَٰنِ الرَّحِيمِ ۝ مَالِكِ يَوْمِ الدِّينِ ۝ إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ ۝ اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ ۝ صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ", Latin: "Bismillahirrahmanirrahim. Alhamdu lillahi rabbil 'aalamin. Arrahmanirrahim. Maaliki yawmid diin. Iyyaaka na'budu wa iyyaaka nasta'iin. Ihdinash shirathal mustaqiim. Shirathal ladziina an'amta 'alaihim ghairil maghdhuubi 'alaihim wa ladhdhaalliin", Translation: "Dengan nama Allah Yang Maha Pengasih lagi Maha Penyayang. Segala puji bagi Allah, Tuhan semesta alam. Yang Maha Pengasih lagi Maha Penyayang. Yang menguasai Hari Pembalasan. Hanya kepada Engkaulah kami menyembah dan hanya kepada Engkaulah kami memohon pertolongan. Tunjukilah kami jalan yang lurus. (Yaitu) jalan orang-orang yang telah Engkau beri nikmat, bukan (jalan) mereka yang dimurkai dan bukan (pula jalan) mereka yang sesat.", Dalil: "HR. Bukhari No. 756; HR. Muslim No. 395: \"Tidak sah shalatnya orang yang tidak membaca Al-Fatihah.\""},
		{ModuleID: bySlug["sholat"], StepOrder: 3, Kind: "sunnah", Title: "Membaca Surat Pendamping", Body: "Setelah Al-Fatihah, disunnahkan membaca ayat atau surat lain. Bacaan diselingi dengan jeda yang cukup agar bisa bernapas.", Tip: "Untuk pemula, surat pendek seperti Al-Ikhlas, Al-Falaq, dan An-Nas cukup mudah untuk diamalkan."},
		{ModuleID: bySlug["sholat"], StepOrder: 4, Kind: "rukun", Title: "Ruku' dengan Tuma'ninah", Body: "Bungkukkan badan, tangan di lutut, punggung rata (tidak bengkok), dan kepala sejajar punggung. Saat ruku' membaca tasbih minimal tiga kali.", Arabic: "سُبْحَانَ رَبِّيَ الْعَظِيمِ", Latin: "Subhaana Rabbiyal 'Adziim", Translation: "Maha Suci Tuhanku Yang Maha Agung.", Dalil: "HR. Bukhari No. 816: \"Lalu ruku'lah dan tuma'ninahlah ketika ruku'.\"", Tip: "Tuma'ninah berarti diam sejenak (sekitar satu kali bacaan Subhanallah) di setiap perpindahan gerakan."},
		{ModuleID: bySlug["sholat"], StepOrder: 5, Kind: "rukun", Title: "Iktidal dengan Tuma'ninah", Body: "Bangun dari ruku' hingga berdiri tegak kembali. Membaca doa iktidal.", Arabic: "سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ، رَبَّنَا لَكَ الْحَمْدُ", Latin: "Sami'allaahu liman hamidah, Rabbanaa lakal hamdu", Translation: "Allah mendengar orang yang memuji-Nya. Ya Tuhan kami, bagi-Mu segala puji.", Dalil: "HR. Bukhari No. 789: Bacaan imam dan makmum."},
		{ModuleID: bySlug["sholat"], StepOrder: 6, Kind: "rukun", Title: "Sujud dengan Tuma'ninah", Body: "Turun hingga tujuh anggota sujud menyentuh lantai: dahi (termasuk hidung), telapak tangan, lutut, dan kaki. Saat sujud membaca tasbih minimal tiga kali.", Arabic: "سُبْحَانَ رَبِّيَ الْأَعْلَى", Latin: "Subhaana Rabbiyal A'laa", Translation: "Maha Suci Tuhanku Yang Maha Tinggi.", Dalil: "HR. Muslim No. 497: \"Tujuh anggota badan bersujud: dahi (termasuk hidung), dua telapak tangan, dua lutut, dan ujung dua kaki.\""},
		{ModuleID: bySlug["sholat"], StepOrder: 7, Kind: "rukun", Title: "Duduk di Antara Dua Sujud", Body: "Setelah sujud, duduk iftirasy (dengan kaki kiri di bawah, kanan tegak) sejenak. Membaca doa antara dua sujud.", Arabic: "رَبِّ اغْفِرْ لِي، رَبِّ اغْفِرْ لِي", Latin: "Rabbighfir lii, Rabbighfir lii", Translation: "Ya Tuhanku, ampunilah aku. Ya Tuhanku, ampunilah aku.", Dalil: "HR. Abu Dawud No. 874 (Hasan): Bacaan duduk di antara dua sujud."},
		{ModuleID: bySlug["sholat"], StepOrder: 8, Kind: "rukun", Title: "Tasyahud Akhir", Body: "Duduk dengan posisi tawarruk (pantat kiri di atas kaki kiri, kanan tegak) dan membaca tahiyat. Ini rukun yang tidak boleh ditinggalkan.", Arabic: "التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ، السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ، السَّلَامُ عَلَيْنَا وَعَلَى عِبَادِ اللَّهِ الصَّالِحِينَ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا رَسُولُ اللَّهِ", Latin: "Attahiyyaatu lillaahi wash shalawaatu wat thayyibaat. Assalaamu 'alaika ayyuhan nabiyyu wa rahmatullaahi wa barakaatuh. Assalaamu 'alainaa wa 'alaa 'ibaadillaahish shaalihiin. Asyhadu allaa ilaaha illallah wa asyhadu anna Muhammadan rasuulullah", Translation: "Segala penghormatan, shalat, dan kebaikan hanya milik Allah. Semoga keselamatan, rahmat, dan keberkahan Allah tercurah kepadamu wahai Nabi. Keselamatan tercurah kepada kami dan kepada hamba-hamba Allah yang shalih. Aku bersaksi bahwa tiada ilah yang berhak disembah selain Allah, dan aku bersaksi bahwa Muhammad adalah utusan Allah.", Dalil: "HR. Muslim No. 402: \"Jika kamu duduk (tasyahud), bacalah tahiyat.\""},
		{ModuleID: bySlug["sholat"], StepOrder: 9, Kind: "rukun", Title: "Shalawat Nabi", Body: "Setelah tahiyat, lanjutkan dengan shalawat atas Nabi ﷺ. Ini bagian dari rukun menurut sebagian ulama.", Arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ. اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ", Latin: "Allahumma shalli 'ala Muhammad wa 'ala aali Muhammad, kama shallayta 'ala Ibraahiim wa 'ala aali Ibraahiim, innaka hamiidum majiid. Allahumma baarik 'ala Muhammad wa 'ala aali Muhammad, kama baarakta 'ala Ibraahiim wa 'ala aali Ibraahiim, innaka hamiidum majiid", Translation: "Ya Allah, berilah shalawat kepada Muhammad dan keluarga Muhammad, sebagaimana Engkau memberi shalawat kepada Ibrahim dan keluarga Ibrahim. Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia. Ya Allah, berilah berkah kepada Muhammad dan keluarga Muhammad, sebagaimana Engkau memberi berkah kepada Ibrahim dan keluarga Ibrahim. Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia.", Dalil: "HR. Muslim No. 405: \"Bacalah shalawat atas aku, karena shalawatmu sampai kepadaku.\""},
		{ModuleID: bySlug["sholat"], StepOrder: 10, Kind: "rukun", Title: "Salam Penutup", Body: "Akhiri shalat dengan menoleh ke kanan dan ke kiri sambil mengucapkan salam.", Arabic: "السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ", Latin: "Assalaamu 'alaikum wa rahmatullah", Translation: "Semoga keselamatan dan rahmat Allah tercurah kepada kalian.", Dalil: "HR. Muslim No. 582: Panduan salam penutup shalat."},

		{ModuleID: bySlug["adzan-iqomah"], StepOrder: 1, Kind: "teori", Title: "Pengertian Adzan", Body: "Adzan adalah panggilan untuk menunaikan shalat fardhu, berisi kalimat-kalimat yang disyariatkan untuk mengingatkan waktu shalat.", Arabic: "الْأَذَانُ", Latin: "Al-adzaan", Translation: "Adzan (panggilan shalat).", Dalil: "HR. Bukhari No. 604: Awal pensyariatan adzan adalah pada tahun pertama hijriah setelah Rasulullah ﷺ bermusyawarah dengan para sahabat."},
		{ModuleID: bySlug["adzan-iqomah"], StepOrder: 2, Kind: "teori", Title: "Syarat-syarat Muadzin", Body: "Disunnahkan muadzin adalah muslim yang baligh, berakal, laki-laki, dan memahami hukum adzan. Dianjurkan pula memiliki suara yang merdu.", Dalil: "HR. Abu Dawud No. 5148 (Hasan): Disunnahkan agar muadzin adalah orang yang paling memahami waktu dan paling bagus suaranya."},
		{ModuleID: bySlug["adzan-iqomah"], StepOrder: 3, Kind: "praktik", Title: "Lafaz Adzan Lengkap", Body: "Adzan terdiri dari 15 kalimat dengan susunan berikut, dibaca dua kali untuk kalimat Hayya 'alas shalah dan Hayya 'alal falah.", Arabic: "اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ. أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ. أَشْهَدُ أَنَّ مُحَمَّدًا رَسُولُ اللَّهِ، أَشْهَدُ أَنَّ مُحَمَّدًا رَسُولُ اللَّهِ. حَيَّ عَلَى الصَّلَاةِ، حَيَّ عَلَى الصَّلَاةِ. حَيَّ عَلَى الْفَلَاحِ، حَيَّ عَلَى الْفَلَاحِ. اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ. لَا إِلَهَ إِلَّا اللَّهُ", Latin: "Allahu Akbar Allahu Akbar, Allahu Akbar Allahu Akbar. Asyhadu allaa ilaaha illallah, asyhadu allaa ilaaha illallah. Asyhadu anna Muhammadan rasuulullah, asyhadu anna Muhammadan rasuulullah. Hayya 'alash shalah, hayya 'alash shalah. Hayya 'alal falah, hayya 'alal falah. Allahu Akbar Allahu Akbar. Laa ilaaha illallah", Translation: "Allah Maha Besar (4x). Aku bersaksi bahwa tiada ilah selain Allah (2x). Aku bersaksi bahwa Muhammad utusan Allah (2x). Marilah menuju shalat (2x). Marilah menuju kejayaan (2x). Allah Maha Besar (2x). Tiada ilah selain Allah.", Dalil: "HR. Muslim No. 379: Lafaz adzan sesuai sunnah."},
		{ModuleID: bySlug["adzan-iqomah"], StepOrder: 4, Kind: "praktik", Title: "Shalawat Setelah Adzan", Body: "Setelah muadzin selesai, disunnahkan bagi yang mendengar untuk membaca shalawat atas Nabi ﷺ, lalu memohon syafaat.", Arabic: "اللَّهُمَّ رَبَّ هَذِهِ الدَّعْوَةِ التَّامَّةِ وَالصَّلَاةِ الْقَائِمَةِ آتِ مُحَمَّدًا الْوَسِيلَةَ وَالْفَضِيلَةَ وَابْعَثْهُ مَقَامًا مَحْمُودًا الَّذِي وَعَدْتَهُ", Latin: "Allahumma Rabba hadzihid da'watit taammah wash shalaatil qaa'imah, aati Muhammadanil wasiilata wal fadhilah, wab'atshu maqaamam mahmuudanil ladzii wa'adtah", Translation: "Ya Allah, Tuhan pemilik seruan yang sempurna ini dan shalat yang akan didirikan, berikanlah kepada Muhammad wasilah (kedudukan tinggi) dan keutamaan, dan bangkitkanlah beliau ke tempat yang terpuji yang telah Engkau janjikan.", Dalil: "HR. Bukhari No. 614: Doa setelah adzan.", Tip: "Wassilah adalah tempat yang tinggi di surga. Rasulullah ﷺ sendiri bersabda bahwa wasilah hanya akan diberikan kepada satu hamba, dan beliau berharap itu adalah dirinya."},
		{ModuleID: bySlug["adzan-iqomah"], StepOrder: 5, Kind: "praktik", Title: "Iqomah", Body: "Iqomah mirip adzan, hanya ada beberapa perbedaan: dibaca lebih pelan, shahadat hanya satu kali, ditambah 'Qad qaamatish shalah' dua kali di antara Hayya 'alal falah dan takbir penutup.", Arabic: "قَدْ قَامَتِ الصَّلَاةُ، قَدْ قَامَتِ الصَّلَاةُ", Latin: "Qad qaamatish shalah, qad qaamatish shalah", Translation: "Sungguh shalat telah berdiri, sungguh shalat telah berdiri.", Dalil: "HR. Ahmad No. 19312 (Shahih): Lafaz iqomah."},

		{ModuleID: bySlug["puasa"], StepOrder: 1, Kind: "teori", Title: "Pengertian Puasa", Body: "Menahan diri dari makan, minum, dan segala hal yang membatalkan dari terbit fajar (shubuh) hingga terbenam matahari, dengan niat karena Allah.", Arabic: "الصَّوْمُ", Latin: "Ash-shiyaam", Translation: "Puasa.", Dalil: "QS. Al-Baqarah: 183: \"Wahai orang-orang yang beriman, diwajibkan atas kamu berpuasa sebagaimana diwajibkan atas orang-orang sebelum kamu agar kamu bertakwa.\""},
		{ModuleID: bySlug["puasa"], StepOrder: 2, Kind: "rukun", Title: "Rukun Puasa", Body: "Rukun puasa ada dua: (1) Niat, yaitu membedaakan puasa wajib dari sekadar menahan lapar. (2) Menahan diri dari segala pembatal dari terbit fajar hingga terbenam matahari.", Dalil: "HR. Bukhari No. 1901; HR. Muslim No. 1153: \"Barangsiapa yang tidak berniat puasa sebelum fajar, maka tidak ada puasa baginya.\""},
		{ModuleID: bySlug["puasa"], StepOrder: 3, Kind: "praktik", Title: "Hal-hal yang Membatalkan Puasa", Body: "Makan dan minum sengaja, muntah sengaja, haid dan nifas, serta hal lain yang masuk ke lubang terbuka (qubul/dubur).", Tip: "Jika lupa makan atau minum dan langsung sadar, lanjutkan puasa. Peristiwa tersebut tidak membatalkan puasa menurut hadis.", Dalil: "HR. Abu Dawud No. 2340 (Hasan): \"Jika salah seorang di antara kamu lupa dan makan atau minum, maka hendaklah ia menyempurnakan puasanya, karena sesungguhnya Allahlah yang telah memberinya makan dan minum.\""},
		{ModuleID: bySlug["puasa"], StepOrder: 4, Kind: "sunnah", Title: "Sunnah-sunnah Puasa", Body: "Menyegerakan berbuka, mengakhirkan sahur, memperbanyak doa terutama di 10 hari terakhir Ramadan, bersedekah, dan membaca Al-Quran.", Arabic: "ذَهَبَ الظَّمَأُ وَابْتَلَّتِ الْعُرُوقُ وَثَبَتَ الْأَجْرُ إِنْ شَاءَ اللَّهُ", Latin: "Dzahabazh zhama'u wabtallatil 'uruuqu wa tsabatal ajru insyaa Allah", Translation: "Telah hilang dahaga, telah basah urat-urat, dan telah tetap pahala insya Allah.", Dalil: "HR. Abu Dawud No. 2356 (Hasan): Doa berbuka puasa.", Tip: "Utamakan berbuka dengan kurma atau air putih, lalu shalat Maghrib."},
		{ModuleID: bySlug["puasa"], StepOrder: 5, Kind: "teori", Title: "Hikmah Puasa", Body: "Puasa melatih kesabaran, mengendalikan hawa nafsu, menumbuhkan rasa empati kepada yang kurang mampu, dan menjadi sarana taqarrub kepada Allah.", Dalil: "QS. Al-Baqarah: 183: \"...agar kamu bertakwa.\""},

		{ModuleID: bySlug["zakat"], StepOrder: 1, Kind: "teori", Title: "Zakat Fitrah", Body: "Zakat fitrah wajib bagi setiap muslim yang memiliki kelebihan makanan untuk dirinya dan keluarganya pada malam dan hari Idul Fitri. Besarannya 2.5 kg makanan pokok atau senilai 3.5 liter makanan pokok.", Dalil: "HR. Abu Dawud No. 1609 (Shahih): \"Rasulullah ﷺ mewajibkan zakat fitrah satu sha' kurma atau satu sha' gandum, atas budak dan orang merdeka, laki-laki dan perempuan, kecil dan besar dari kaum muslimin.\""},
		{ModuleID: bySlug["zakat"], StepOrder: 2, Kind: "teori", Title: "Zakat Mal (Harta)", Body: "Zakat mal wajib atas harta yang memenuhi syarat: milik penuh, mencapai nisab (batas minimum), sudah haul (genap satu tahun), dan lebih dari kebutuhan pokok. Kadar umumnya 2.5%.", Tip: "Nisab emas zakat mal setara 85 gram emas, sedangkan nisab perak 595 gram perak."},
		{ModuleID: bySlug["zakat"], StepOrder: 3, Kind: "praktik", Title: "8 Golongan Penerima (Asnaf)", Body: "Penerima zakat ada 8: (1) Fakir, (2) Miskin, (3) Amil, (4) Muallaf, (5) Memerdekakan budak, (6) Gharim, (7) Fisabilillah, (8) Ibnu Sabil.", Arabic: "إِنَّمَا الصَّدَقَاتُ لِلْفُقَرَاءِ وَالْمَسَاكِينِ وَالْعَامِلِينَ عَلَيْهَا وَالْمُؤَلَّفَةِ قُلُوبُهُمْ وَفِي الرِّقَابِ وَالْغَارِمِينَ وَفِي سَبِيلِ اللَّهِ وَابْنِ السَّبِيلِ", Latin: "Innama ash shadaqaatu lilfuqaraa'i wal masaakiini wal 'aamiliina 'alaihaa wal mu'allafati quluubuhum wa fir riqaabi wal ghaarimiina wa fii sabiilillaahi wabnis sabiil", Translation: "Sesungguhnya zakat-zakat itu hanyalah untuk orang-orang fakir, orang-orang miskin, para amil zakat, para muallaf yang dibujuk hatinya, untuk (memerdekakan) budak, orang-orang yang berutang, untuk jalan Allah, dan orang-orang yang sedang dalam perjalanan.", Dalil: "QS. At-Taubah: 60."},

		{ModuleID: bySlug["tajwid"], StepOrder: 1, Kind: "teori", Title: "Hukum Nun Mati & Tanwin", Body: "Nun mati (نْ) dan tanwin (ـً ـٍ ـٌ) apabila bertemu huruf hijaiyah tertentu memiliki empat hukum: Izhar, Idgham, Iqlab, dan Ikhfa.", Dalil: "QS. Al-An'am: 73: \"...وَقَدْ فَصَّلَ لَكُم مَّا حَرَّمَ عَلَيْكُمْ...\" - contoh Ikhfa karena nun mati bertemu fa'."},
		{ModuleID: bySlug["tajwid"], StepOrder: 2, Kind: "praktik", Title: "Idzhar Halqi", Body: "Nun mati/tanwin dibaca jelas apabila bertemu huruf halq (tenggorokan): ء ه ع غ ح خ.", Arabic: "مَنْ ءَامَنَ", Latin: "Man aamana", Translation: "Barangsiapa yang beriman.", Dalil: "QS. Al-Baqarah: 62."},
		{ModuleID: bySlug["tajwid"], StepOrder: 3, Kind: "praktik", Title: "Idgham Bighunnah", Body: "Nun mati/tanwin bertemu ي ن م و ل ر dilebur menjadi satu dengan dengung (nunnasal terdengar di akhir).", Arabic: "مَن يَعْمَلْ سُوءًا", Latin: "May ya'mal suu-an", Translation: "Barangsiapa yang mengerjakan kejahatan.", Dalil: "QS. An-Nisa: 123."},
		{ModuleID: bySlug["tajwid"], StepOrder: 4, Kind: "praktik", Title: "Iqlab", Body: "Nun mati/tanwin bertemu ب (ba) diganti menjadi bunyi م (mim) dengan dengung. Tanda: terdapat nun mati/tanwin berbunyi seperti 'mb'.", Arabic: "أَنۢبِئُوهُم", Latin: "Anbii-uhum", Translation: "Kabarkanlah kepada mereka.", Dalil: "QS. Al-Baqarah: 33."},
		{ModuleID: bySlug["tajwid"], StepOrder: 5, Kind: "praktik", Title: "Ikhfa Haqiqi", Body: "Nun mati/tanwin bertemu 15 huruf (selain Idzhar, Idgham, Iqlab) dibaca samar-samar dengan dengung.", Arabic: "مِن وَرَائِهِمْ", Latin: "Min waraa'ihim", Translation: "Dari belakang mereka.", Dalil: "QS. Al-Buruj: 20."},
		{ModuleID: bySlug["tajwid"], StepOrder: 6, Kind: "praktik", Title: "Hukum Mim Mati", Body: "Mim mati (مْ) terbagi tiga: Ikhfa Syafawi (bertemu ب), Idgham Mimi (bertemu م), dan Idzhar Syafawi (bertemu semua huruf selain mim dan ba).", Arabic: "تَرْمِيهِم بِحِجَارَةٍ", Latin: "Tarmihim bihijaaratin", Translation: "Melempari mereka dengan batu.", Dalil: "QS. Al-Fil: 4."},
		{ModuleID: bySlug["tajwid"], StepOrder: 7, Kind: "praktik", Title: "Mad (Panjang Bacaan)", Body: "Mad Thabi'i dibaca 2 harakat. Mad Far'i (cabang) seperti Mad Layyin, Mad 'Aridh, Mad Wajib Muttashil, dan lain-lain.", Arabic: "قَالَ رَبِّ", Latin: "Qaala Rabbi", Translation: "Dia berkata, \"Ya Tuhanku.\"", Dalil: "QS. Maryam: 4.", Tip: "Berlatih dengan qari terkenal untuk mendengar langsung panjang-pendek bacaan."},

		{ModuleID: bySlug["rukun-iman"], StepOrder: 1, Kind: "teori", Title: "Iman kepada Allah", Body: "Meyakini dengan sebenar-benar keyakinan bahwa Allah ﷻ ada, Esa dalam Rububiyah (penciptaan), Uluhiyah (penyembahan), dan Asma' wa Sifat (nama dan sifat).", Dalil: "QS. Al-Ikhlas: 1-4: \"Katakanlah, Dialah Allah Yang Maha Esa. Allah tempat bergantung. Tidak beranak dan tidak dilahirkan. Dan tiada seorangpun setara dengan-Nya.\""},
		{ModuleID: bySlug["rukun-iman"], StepOrder: 2, Kind: "teori", Title: "Iman kepada Malaikat", Body: "Meyakini bahwa malaikat adalah makhluk gaib yang diciptakan dari cahaya, patuh pada perintah Allah, dan tidak pernah durhaka.", Arabic: "الْمَلَائِكَةُ", Latin: "Al-malaa'ikah", Translation: "Para malaikat.", Dalil: "QS. Al-Baqarah: 285: \"...mereka (para rasul) beriman kepada-Nya, dan mereka semua tunduk kepada-Nya.\""},
		{ModuleID: bySlug["rukun-iman"], StepOrder: 3, Kind: "teori", Title: "Iman kepada Kitab-kitab", Body: "Meyakini bahwa Allah menurunkan kitab-kitab kepada para rasul: Suhuf (Ibrahim & Musa), Taurat (Musa), Zabur (Daud), Injil (Isa), dan Al-Quran (Muhammad ﷺ).", Dalil: "QS. Al-Baqarah: 285: \"Rasul (Muhammad) beriman kepada apa yang diturunkan kepadanya dari Tuhannya...\"."},
		{ModuleID: bySlug["rukun-iman"], StepOrder: 4, Kind: "teori", Title: "Iman kepada Rasul", Body: "Meyakini para rasul yang wajib diketahui secara umum ada 25, dimulai dari Nuh hingga Muhammad ﷺ sebagai penutup para nabi.", Dalil: "QS. Al-Ahzab: 40: \"Muhammad itu sekali-kali bukanlah (bapak) dari seorang laki-laki di antara kamu, tetapi dia adalah Rasulullah dan penutup para nabi.\""},
		{ModuleID: bySlug["rukun-iman"], StepOrder: 5, Kind: "teori", Title: "Iman kepada Hari Akhir", Body: "Meyakini bahwa kehidupan dunia akan berakhir. Setelahnya ada kebangkitan, hisab (penghitungan amal), shirat (jembatan), surga, dan neraka.", Dalil: "QS. Al-Qiyamah: 1-3: \"Aku bersumpah dengan hari kiamat, dan aku bersumpah dengan jiwa yang selalu menyesal (dirinya sendiri). Apakah manusia mengira bahwa Kami tidak akan mengumpulkan (kembali) tulang belulangnya?\"."},
		{ModuleID: bySlug["rukun-iman"], StepOrder: 6, Kind: "teori", Title: "Iman kepada Qada & Qadar", Body: "Meyakini bahwa semua yang terjadi di alam semesta ini merupakan ketetapan Allah ﷻ yang sudah tercatat di Lauhul Mahfuz, baik maupun buruk.", Dalil: "HR. Tirmidzi No. 2515 (Shahih): \"Berimanlah kamu kepada qada dan qadar, bahwa seluruh perkara itu telah ditetapkan dari Allah.\""},

		{ModuleID: bySlug["adab-talab-ilmu"], StepOrder: 1, Kind: "sunnah", Title: "Meniatkan Ilmu untuk Mencapai Ridha Allah", Body: "Langkah pertama tholabul 'ilmi adalah meluruskan niat: menuntut ilmu bukan karena gengsi, pujian, atau kedudukan, melainkan karena Allah ﷻ.", Arabic: "رَبِّ زِدْنِي عِلْمًا", Latin: "Rabbi zidnii 'ilmaa", Translation: "Ya Tuhanku, tambahkanlah aku ilmu.", Dalil: "QS. Thaha: 114.", Tip: "Tiap kali mulai belajar, bisikkan niat ini di hati. Niat adalah fondasi yang membedakan ilmu yang bermanfaat dan yang sia-sia."},
		{ModuleID: bySlug["adab-talab-ilmu"], StepOrder: 2, Kind: "sunnah", Title: "Membersihkan Hati Sebelum Menuntut Ilmu", Body: "Membersihkan hati dari penyakit seperti hasad, sombong, dan ujub. Karena ilmu adalah cahaya, dan cahaya tidak masuk dalam hati yang gelap.", Dalil: "HR. Muslim No. 2701: \"Tidak akan masuk surga orang yang di dalam hatinya terdapat kesombongan sebesar biji sawi.\""},
		{ModuleID: bySlug["adab-talab-ilmu"], StepOrder: 3, Kind: "sunnah", Title: "Memulai dengan Bismillah dan Memperhatikan Wudhu", Body: "Disunnahkan memulai belajar dalam keadaan suci, berpakaian rapi, dan duduk dengan sopan menghadap guru.", Tip: "Menghadap guru secara langsung (tatap muka) akan lebih melekat dalam hati dibanding belajar dari layar."},
		{ModuleID: bySlug["adab-talab-ilmu"], StepOrder: 4, Kind: "sunnah", Title: "Senantiasa Rendah Hati terhadap Guru", Body: "Memuliakan guru adalah bagian dari memuliakan ilmu itu sendiri. Jangan membantah, jangan mencela, dan jagalah adab saat bertanya.", Dalil: "HR. Tirmidzi No. 2671 (Hasan): \"Tidak termasuk golongan kami orang yang tidak memuliakan yang tua di antara kami, dan tidak menyayangi yang muda di antara kami.\""},
		{ModuleID: bySlug["adab-talab-ilmu"], StepOrder: 5, Kind: "sunnah", Title: "Mengamalkan Ilmu yang Dipelajari", Body: "Ilmu tanpa amal bagaikan pohon tanpa buah. Tujuan akhir tholabul 'ilmi adalah diamalkan agar menjadi penerang di dunia dan akhirat.", Dalil: "HR. Ath-Thabrani: \"Sungguh akan datang kepada suatu kaum yang mencari ilmu, namun tidak dicari melainkan untuk berhias dengan-nya, dan mereka tidak dituntut dengan ilmu melainkan untuk berdebat.\""},
	}

	for i := range steps {
		if steps[i].ModuleID == 0 {
			continue
		}
		var existing model.LessonStep
		if err := db.Where("module_id = ? AND step_order = ?", steps[i].ModuleID, steps[i].StepOrder).First(&existing).Error; err == nil {
			db.Model(&existing).Updates(map[string]interface{}{
				"kind":        steps[i].Kind,
				"title":       steps[i].Title,
				"body":        steps[i].Body,
				"arabic":      steps[i].Arabic,
				"latin":       steps[i].Latin,
				"translation": steps[i].Translation,
				"dalil":       steps[i].Dalil,
				"tip":         steps[i].Tip,
			})
		} else {
			db.Create(&steps[i])
		}
	}
}
