package migrations

import (
	"github.com/agambondan/islamic-explorer/app/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

func SeedTier3(db *gorm.DB) {
	seedHistoryEvents(db)
	seedManasikSteps(db)
	seedIslamicEvents(db)
	seedQuizQuestions(db)
	SeedIlmuRijal(db)
	seedAchievements(db)
}

func seedAchievements(db *gorm.DB) {
	var count int64
	db.Model(&model.Achievement{}).Count(&count)
	if count > 0 {
		return
	}
	achievements := []model.Achievement{
		// Streak
		{Code: "streak_3", Name: "Konsisten 3 Hari", NameEn: "3-Day Streak", Description: "Belajar 3 hari berturut-turut", DescEn: "Learn 3 days in a row", Icon: "🔥", Category: "streak", Threshold: 3},
		{Code: "streak_7", Name: "Seminggu Penuh", NameEn: "Full Week", Description: "Streak 7 hari", DescEn: "7-day streak", Icon: "⚡", Category: "streak", Threshold: 7},
		{Code: "streak_30", Name: "Sebulan Istiqomah", NameEn: "Month of Istiqomah", Description: "Streak 30 hari — luar biasa!", DescEn: "30-day streak — amazing!", Icon: "🌟", Category: "streak", Threshold: 30},
		{Code: "streak_100", Name: "100 Hari Bersama", NameEn: "100 Days Together", Description: "Streak 100 hari", DescEn: "100-day streak", Icon: "💎", Category: "streak", Threshold: 100},
		// Hafalan
		{Code: "hafalan_1", Name: "Hafal Pertama", NameEn: "First Memorization", Description: "Hafal 1 surah", DescEn: "Memorize 1 surah", Icon: "📖", Category: "hafalan", Threshold: 1},
		{Code: "hafalan_5", Name: "5 Surah Hafal", NameEn: "5 Surahs Memorized", Description: "Hafal 5 surah", DescEn: "Memorize 5 surahs", Icon: "🕌", Category: "hafalan", Threshold: 5},
		{Code: "hafalan_10", Name: "Juz Amma", NameEn: "Juz Amma", Description: "Hafal 10 surah juz 30", DescEn: "Memorized 10 surahs", Icon: "🎓", Category: "hafalan", Threshold: 10},
		{Code: "hafalan_30", Name: "Penghafal Sejati", NameEn: "True Hafiz", Description: "Hafal 30 surah", DescEn: "Memorize 30 surahs", Icon: "👑", Category: "hafalan", Threshold: 30},
		// Bookmark
		{Code: "bookmark_1", Name: "Pertama Disimpan", NameEn: "First Saved", Description: "Simpan 1 bookmark", DescEn: "Save 1 bookmark", Icon: "🔖", Category: "bookmark", Threshold: 1},
		{Code: "bookmark_10", Name: "Kolektor", NameEn: "Collector", Description: "Simpan 10 bookmark", DescEn: "Save 10 bookmarks", Icon: "📚", Category: "bookmark", Threshold: 10},
		{Code: "bookmark_50", Name: "Pustakawan", NameEn: "Librarian", Description: "Simpan 50 bookmark", DescEn: "Save 50 bookmarks", Icon: "🏛️", Category: "bookmark", Threshold: 50},
	}
	db.Clauses(clause.OnConflict{DoNothing: true}).Create(&achievements)
}

func seedQuizQuestions(db *gorm.DB) {
	var count int64
	db.Model(&model.Quiz{}).Count(&count)
	if count > 0 {
		return
	}

	questions := []model.Quiz{
		// Fiqh
		{Type: model.QuizTypeFiqh, Difficulty: "easy", QuestionText: "Apa hukum membaca Al-Fatihah dalam sholat fardhu?", CorrectAnswer: "Wajib — rukun sholat yang tidak sah sholat tanpanya", Options: `["Wajib — rukun sholat yang tidak sah sholat tanpanya","Sunnah muakkad","Boleh diganti surah lain","Hanya wajib di rakaat pertama"]`, Explanation: "Nabi ﷺ bersabda: 'Tidak sah sholat bagi yang tidak membaca Al-Fatihah.' (HR. Bukhari No. 756, Muslim No. 394)"},
		{Type: model.QuizTypeFiqh, Difficulty: "easy", QuestionText: "Berapa jumlah rakaat sholat Dzuhur?", CorrectAnswer: "4 rakaat", Options: `["2 rakaat","3 rakaat","4 rakaat","6 rakaat"]`, Explanation: "Sholat Dzuhur terdiri dari 4 rakaat fardhu."},
		{Type: model.QuizTypeFiqh, Difficulty: "medium", QuestionText: "Manakah yang TIDAK membatalkan wudhu?", CorrectAnswer: "Menyentuh Al-Quran", Options: `["Buang air kecil","Buang air besar","Menyentuh Al-Quran","Tidur nyenyak"]`, Explanation: "Menyentuh Al-Quran tidak membatalkan wudhu menurut pendapat mayoritas ulama. Yang membatalkan wudhu: buang air, tidur nyenyak, menyentuh kemaluan dengan tangan, dan hal-hal yang keluar dari dua jalan."},
		{Type: model.QuizTypeFiqh, Difficulty: "medium", QuestionText: "Berapa nishab zakat maal dalam ukuran emas?", CorrectAnswer: "85 gram emas", Options: `["20 gram emas","50 gram emas","85 gram emas","100 gram emas"]`, Explanation: "Nishab zakat maal setara 85 gram emas (20 mitsqal) atau 595 gram perak. Jika kepemilikan mencapai nishab dan sudah haul (1 tahun), wajib zakat 2.5%."},
		{Type: model.QuizTypeFiqh, Difficulty: "hard", QuestionText: "Apa yang dimaksud dengan 'tayammum'?", CorrectAnswer: "Bersuci menggunakan debu/tanah yang suci sebagai pengganti air", Options: `["Mandi wajib dengan air","Bersuci menggunakan debu/tanah yang suci sebagai pengganti air","Membersihkan najis dengan air","Wudhu menggunakan air zamzam"]`, Explanation: "Tayammum adalah pengganti wudhu dan mandi wajib ketika tidak ada air atau tidak mampu menggunakan air. Dalil: QS. Al-Maidah: 6."},
		{Type: model.QuizTypeFiqh, Difficulty: "medium", QuestionText: "Berapa jumlah rakaat sholat Tarawih yang paling shahih dari sunnah Nabi ﷺ?", CorrectAnswer: "11 rakaat (8 tarawih + 3 witir)", Options: `["20 rakaat","11 rakaat (8 tarawih + 3 witir)","23 rakaat","36 rakaat"]`, Explanation: "Aisyah ra. meriwayatkan bahwa Nabi ﷺ tidak pernah sholat malam lebih dari 11 rakaat, baik di Ramadan maupun di luar Ramadan (HR. Bukhari No. 1147, Muslim No. 738)."},

		// Sirah
		{Type: model.QuizTypeSirah, Difficulty: "easy", QuestionText: "Di kota mana Nabi Muhammad ﷺ dilahirkan?", CorrectAnswer: "Makkah Al-Mukarramah", Options: `["Madinah Al-Munawwarah","Makkah Al-Mukarramah","Thaif","Yaman"]`, Explanation: "Nabi Muhammad ﷺ lahir di Makkah pada 12 Rabi'ul Awwal, Tahun Gajah (570 M), bertepatan dengan peristiwa pasukan gajah Abrahah yang dihancurkan Allah."},
		{Type: model.QuizTypeSirah, Difficulty: "easy", QuestionText: "Siapakah istri pertama Nabi Muhammad ﷺ?", CorrectAnswer: "Khadijah binti Khuwailid", Options: `["Aisyah binti Abu Bakar","Khadijah binti Khuwailid","Hafsah binti Umar","Ummu Salamah"]`, Explanation: "Khadijah binti Khuwailid adalah istri pertama dan paling dicintai Nabi ﷺ. Beliau menikah pada usia 25 tahun, Khadijah 40 tahun. Khadijah adalah wanita pertama yang masuk Islam."},
		{Type: model.QuizTypeSirah, Difficulty: "medium", QuestionText: "Pada tahun berapa Nabi ﷺ hijrah dari Makkah ke Madinah?", CorrectAnswer: "622 M (tahun 1 H)", Options: `["610 M","615 M","622 M (tahun 1 H)","630 M"]`, Explanation: "Hijrah ke Madinah terjadi pada tahun 622 M dan menjadi awal kalender Hijriah (1 H). Peristiwa ini menandai pembentukan komunitas Muslim pertama di Madinah."},
		{Type: model.QuizTypeSirah, Difficulty: "medium", QuestionText: "Berapa jumlah pasukan Muslim dalam Perang Badar (2 H)?", CorrectAnswer: "313 orang", Options: `["100 orang","313 orang","500 orang","1000 orang"]`, Explanation: "Pasukan Muslim berjumlah 313 orang menghadapi 1.000 pasukan Quraisy. Dengan pertolongan Allah, kaum muslimin menang gemilang. 70 musuh tewas termasuk Abu Jahal (HR. Bukhari No. 3992)."},
		{Type: model.QuizTypeSirah, Difficulty: "hard", QuestionText: "Apa nama perjanjian damai antara Nabi ﷺ dan kaum Quraisy pada tahun 6 H?", CorrectAnswer: "Perjanjian Hudaibiyyah", Options: `["Perjanjian Madinah","Perjanjian Hudaibiyyah","Perjanjian Aqabah","Perjanjian Tabuk"]`, Explanation: "Perjanjian Hudaibiyyah (6 H) adalah perjanjian damai 10 tahun antara kaum muslimin dan Quraisy. Meski tampak merugikan, Allah menyebutnya 'kemenangan yang nyata' (QS. Al-Fath: 1)."},
		{Type: model.QuizTypeSirah, Difficulty: "medium", QuestionText: "Siapakah sahabat yang mengusulkan penggalian parit dalam Perang Khandaq?", CorrectAnswer: "Salman Al-Farisi ra.", Options: `["Abu Bakar Ash-Shiddiq","Umar bin Khattab","Salman Al-Farisi ra.","Ali bin Abi Thalib"]`, Explanation: "Salman Al-Farisi ra., sahabat asal Persia, mengusulkan strategi menggali parit (khandaq) di utara Madinah — strategi yang tidak dikenal orang Arab. Ini menyelamatkan Madinah dari pengepungan 10.000 pasukan musuh."},

		// Hadith
		{Type: model.QuizTypeHadith, Difficulty: "easy", QuestionText: "Berapa jumlah kitab hadith utama yang dikenal sebagai Kutub As-Sittah?", CorrectAnswer: "6 kitab", Options: `["4 kitab","5 kitab","6 kitab","9 kitab"]`, Explanation: "Kutub As-Sittah (Enam Kitab Hadith Utama): Shahih Bukhari, Shahih Muslim, Sunan Abu Dawud, Sunan Tirmidzi, Sunan An-Nasa'i, dan Sunan Ibnu Majah."},
		{Type: model.QuizTypeHadith, Difficulty: "medium", QuestionText: "Siapakah sahabat yang meriwayatkan hadith paling banyak?", CorrectAnswer: "Abu Hurairah ra. (5.374 hadith)", Options: `["Aisyah ra.","Abdullah bin Umar ra.","Abu Hurairah ra. (5.374 hadith)","Anas bin Malik ra."]`, Explanation: "Abu Hurairah ra. meriwayatkan sekitar 5.374 hadith — terbanyak di antara sahabat. Beliau selalu bersama Nabi ﷺ dan mendoakan diri agar diberi hafalan kuat."},
		{Type: model.QuizTypeHadith, Difficulty: "medium", QuestionText: "Apa yang dimaksud dengan hadith Mutawatir?", CorrectAnswer: "Hadith yang diriwayatkan oleh banyak perawi sehingga mustahil bersepakat dusta", Options: `["Hadith dengan satu jalur sanad","Hadith yang diriwayatkan oleh banyak perawi sehingga mustahil bersepakat dusta","Hadith yang lemah (dhaif)","Hadith yang hanya dari Abu Hurairah"]`, Explanation: "Hadith Mutawatir diriwayatkan oleh sejumlah perawi yang secara adat mustahil bersepakat berdusta. Statusnya memberikan keyakinan penuh (qath'iy). Contoh: hadith tentang sholat 5 waktu."},
		{Type: model.QuizTypeHadith, Difficulty: "hard", QuestionText: "Imam Bukhari lahir pada tahun berapa?", CorrectAnswer: "194 H / 810 M", Options: `["150 H / 767 M","170 H / 786 M","194 H / 810 M","210 H / 825 M"]`, Explanation: "Imam Muhammad bin Ismail Al-Bukhari lahir pada 13 Syawal 194 H (810 M) di Bukhara (Uzbekistan saat ini). Beliau mulai menghafal hadith sejak usia 11 tahun dan menulis Shahih Bukhari selama 16 tahun."},
		{Type: model.QuizTypeHadith, Difficulty: "medium", QuestionText: "Apa perbedaan hadith Shahih dan Hadith Hasan?", CorrectAnswer: "Hadith Hasan memiliki perawi yang adil namun hafalannya sedikit kurang dibanding Shahih", Options: `["Tidak ada perbedaan, keduanya sama","Hadith Hasan lebih kuat dari Shahih","Hadith Hasan memiliki perawi yang adil namun hafalannya sedikit kurang dibanding Shahih","Hadith Hasan adalah hadith palsu"]`, Explanation: "Hadith Shahih: semua perawinya adil, hafalan kuat (dhabith), sanad bersambung, tidak ada syadz/illat. Hadith Hasan: seperti Shahih namun hafalan perawi lebih rendah. Keduanya bisa dijadikan hujjah."},

		// Asmaul Husna
		{Type: model.QuizTypeAsmaUlHusna, Difficulty: "easy", QuestionText: "Apa arti dari Asma Allah 'Ar-Rahman'?", CorrectAnswer: "Yang Maha Pengasih (di dunia untuk semua makhluk)", Options: `["Yang Maha Kuasa","Yang Maha Pengasih (di dunia untuk semua makhluk)","Yang Maha Mengetahui","Yang Maha Bijaksana"]`, Explanation: "Ar-Rahman (الرَّحْمَن) artinya Yang Maha Pengasih. Kasih sayang-Nya di dunia meliputi semua makhluk, Muslim maupun non-Muslim. Berbeda dengan Ar-Rahim yang kasihnya khusus untuk orang beriman di akhirat."},
		{Type: model.QuizTypeAsmaUlHusna, Difficulty: "easy", QuestionText: "Apa arti dari Asma Allah 'Al-Quddus'?", CorrectAnswer: "Yang Maha Suci dari segala kekurangan", Options: `["Yang Maha Besar","Yang Maha Suci dari segala kekurangan","Yang Maha Perkasa","Yang Maha Adil"]`, Explanation: "Al-Quddus (الْقُدُّوس) artinya Yang Maha Suci — suci dari segala aib, kekurangan, sekutu, dan tandingan. Disebutkan dalam QS. Al-Hasyr: 23 dan QS. Al-Jumu'ah: 1."},
		{Type: model.QuizTypeAsmaUlHusna, Difficulty: "medium", QuestionText: "Apa arti dari Asma Allah 'Al-Hafizh'?", CorrectAnswer: "Yang Maha Memelihara dan Menjaga", Options: `["Yang Maha Menghitung","Yang Maha Memelihara dan Menjaga","Yang Maha Mendengar","Yang Maha Melihat"]`, Explanation: "Al-Hafizh (الْحَفِيظ) artinya Yang Maha Memelihara dan Menjaga. Allah memelihara seluruh makhluk-Nya dan menjaga amal perbuatan manusia. Disebutkan dalam QS. Hud: 57 dan QS. Saba': 21."},
		{Type: model.QuizTypeAsmaUlHusna, Difficulty: "medium", QuestionText: "Berapa jumlah Asmaul Husna yang disebutkan dalam hadith Nabi ﷺ?", CorrectAnswer: "99 nama", Options: `["33 nama","66 nama","99 nama","100 nama"]`, Explanation: "Nabi ﷺ bersabda: 'Sesungguhnya Allah memiliki 99 nama — seratus kurang satu — barangsiapa menghafalnya akan masuk surga.' (HR. Bukhari No. 2736, Muslim No. 2677)"},
		{Type: model.QuizTypeAsmaUlHusna, Difficulty: "easy", QuestionText: "Apa arti dari Asma Allah 'As-Sami'?", CorrectAnswer: "Yang Maha Mendengar", Options: `["Yang Maha Melihat","Yang Maha Mendengar","Yang Maha Mengetahui","Yang Maha Bijaksana"]`, Explanation: "As-Sami' (السَّمِيع) artinya Yang Maha Mendengar. Allah mendengar segala sesuatu tanpa terbatas — doa yang paling pelan sekalipun sampai ke hadapan-Nya. Sering disandingkan dengan Al-Bashir (Yang Maha Melihat)."},

		// Hafalan (pengetahuan tentang Al-Quran)
		{Type: model.QuizTypeHafalan, Difficulty: "easy", QuestionText: "Surah apa yang disebut 'Umm Al-Quran' (Induk Al-Quran)?", CorrectAnswer: "Al-Fatihah (Surah ke-1)", Options: `["Al-Baqarah (Surah ke-2)","Al-Fatihah (Surah ke-1)","Al-Ikhlas (Surah ke-112)","Yasin (Surah ke-36)"]`, Explanation: "Al-Fatihah disebut 'Umm Al-Quran' karena merangkum inti ajaran Al-Quran: tauhid, pujian kepada Allah, ibadah, dan doa. Juga disebut As-Sab'ul Matsaani (7 ayat yang diulang-ulang)."},
		{Type: model.QuizTypeHafalan, Difficulty: "medium", QuestionText: "Berapa jumlah total ayat dalam Al-Quran?", CorrectAnswer: "6.236 ayat", Options: `["5.000 ayat","6.000 ayat","6.236 ayat","6.666 ayat"]`, Explanation: "Jumlah ayat dalam Al-Quran yang disepakati ulama adalah 6.236 ayat (tanpa menghitung basmalah di awal tiap surah sebagai ayat, kecuali Al-Fatihah). Al-Quran terdiri dari 114 surah, 30 juz."},
		{Type: model.QuizTypeHafalan, Difficulty: "easy", QuestionText: "Surah apa yang paling pendek dalam Al-Quran?", CorrectAnswer: "Al-Kautsar (3 ayat)", Options: `["Al-Ikhlas (4 ayat)","Al-Kautsar (3 ayat)","Al-Falaq (5 ayat)","An-Nas (6 ayat)"]`, Explanation: "Surah Al-Kautsar (QS. 108) adalah surah terpendek dengan hanya 3 ayat. Meski pendek, maknanya sangat agung — berisi kabar gembira tentang Al-Kautsar (sungai/nikmat berlimpah di surga)."},
		{Type: model.QuizTypeHafalan, Difficulty: "medium", QuestionText: "Ayat apakah yang disebut 'Sayyid Al-Ayat' (penghulu segala ayat)?", CorrectAnswer: "Ayat Kursi (QS. Al-Baqarah: 255)", Options: `["QS. Al-Fatihah: 1","Ayat Kursi (QS. Al-Baqarah: 255)","QS. Al-Ikhlas: 1","QS. Al-Hasyr: 22-24"]`, Explanation: "Nabi ﷺ bersabda: 'Sayyid Al-Ayat adalah Ayat Kursi.' (HR. Al-Hakim; Shahih). Ayat Kursi menggambarkan keagungan Allah — Dia yang Maha Hidup dan terus mengurus makhluk-Nya."},
		{Type: model.QuizTypeHafalan, Difficulty: "easy", QuestionText: "Surah manakah yang dianjurkan dibaca setiap malam Jumat?", CorrectAnswer: "Al-Kahfi (Surah ke-18)", Options: `["Yasin (Surah ke-36)","Al-Kahfi (Surah ke-18)","Al-Mulk (Surah ke-67)","Al-Waqiah (Surah ke-56)"]`, Explanation: "Nabi ﷺ bersabda: 'Barangsiapa membaca Surat Al-Kahfi pada hari Jumat, maka ia akan mendapat cahaya di antara dua Jumat.' (HR. Al-Hakim; Shahih Al-Albani, Shahihul Jami' No. 6470)"},
	}

	db.Create(&questions)
}

func seedIslamicEvents(db *gorm.DB) {
	events := []model.IslamicEvent{
		{Name: "Tahun Baru Hijriah", HijriMonth: 1, HijriDay: 1, Category: model.EventCategoryPeristiwa, Description: "Awal tahun baru dalam kalender Islam. Momentum muhasabah dan penyegaran niat."},
		{Name: "Hari Asyura", HijriMonth: 1, HijriDay: 10, Category: model.EventCategoryPuasa, Description: "Hari ke-10 Muharram. Puasa sunnah yang sangat dianjurkan. Nabi ﷺ bersabda: 'Puasa Asyura menghapus dosa setahun yang lalu.' (HR. Muslim)"},
		{Name: "Nisfu Sya'ban", HijriMonth: 8, HijriDay: 15, Category: model.EventCategoryPeristiwa, Description: "Malam pertengahan bulan Sya'ban. Dianjurkan memperbanyak ibadah dan istighfar."},
		{Name: "Awal Ramadan", HijriMonth: 9, HijriDay: 1, Category: model.EventCategoryPuasa, Description: "Awal bulan suci Ramadan. Bulan diturunkannya Al-Quran (QS. Al-Baqarah: 185). Puasa wajib bagi setiap Muslim yang mampu."},
		{Name: "Nuzulul Quran", HijriMonth: 9, HijriDay: 17, Category: model.EventCategoryPeristiwa, Description: "Peringatan turunnya Al-Quran pertama kali kepada Nabi Muhammad ﷺ di Gua Hira pada malam 17 Ramadan."},
		{Name: "Lailatul Qadar (malam ke-21)", HijriMonth: 9, HijriDay: 21, Category: model.EventCategoryPeristiwa, Description: "Salah satu malam ganjil 10 akhir Ramadan yang berpotensi Lailatul Qadar — malam lebih baik dari seribu bulan (QS. Al-Qadr)."},
		{Name: "Lailatul Qadar (malam ke-23)", HijriMonth: 9, HijriDay: 23, Category: model.EventCategoryPeristiwa, Description: "Salah satu malam ganjil 10 akhir Ramadan yang berpotensi Lailatul Qadar."},
		{Name: "Lailatul Qadar (malam ke-25)", HijriMonth: 9, HijriDay: 25, Category: model.EventCategoryPeristiwa, Description: "Salah satu malam ganjil 10 akhir Ramadan yang berpotensi Lailatul Qadar."},
		{Name: "Lailatul Qadar (malam ke-27)", HijriMonth: 9, HijriDay: 27, Category: model.EventCategoryPeristiwa, Description: "Malam ke-27 Ramadan — malam yang paling sering disebut ulama sebagai Lailatul Qadar berdasarkan hadith."},
		{Name: "Lailatul Qadar (malam ke-29)", HijriMonth: 9, HijriDay: 29, Category: model.EventCategoryPeristiwa, Description: "Salah satu malam ganjil 10 akhir Ramadan yang berpotensi Lailatul Qadar."},
		{Name: "Idul Fitri", HijriMonth: 10, HijriDay: 1, Category: model.EventCategoryEid, Description: "Hari raya setelah sebulan penuh berpuasa Ramadan. Diawali sholat Id, zakat fitrah, dan silaturahmi."},
		{Name: "Puasa Syawal 6 Hari", HijriMonth: 10, HijriDay: 2, Category: model.EventCategoryPuasa, Description: "Puasa 6 hari di bulan Syawal setelah Idul Fitri. Nabi ﷺ bersabda: 'Barangsiapa berpuasa Ramadan kemudian diikuti 6 hari Syawal maka seakan ia berpuasa setahun penuh.' (HR. Muslim)"},
		{Name: "Hari Arafah", HijriMonth: 12, HijriDay: 9, Category: model.EventCategoryPuasa, Description: "Hari wukuf di Arafah bagi jamaah haji. Puasa Arafah sangat dianjurkan bagi yang tidak berhaji — menghapus dosa dua tahun (HR. Muslim)."},
		{Name: "Idul Adha", HijriMonth: 12, HijriDay: 10, Category: model.EventCategoryEid, Description: "Hari raya kurban. Peringatan ketaatan Nabi Ibrahim dan Ismail. Sholat Id dan penyembelihan hewan kurban."},
		{Name: "Hari Tasyrik (11 Dzulhijjah)", HijriMonth: 12, HijriDay: 11, Category: model.EventCategoryPeristiwa, Description: "Bagian dari hari-hari tasyrik (11-13 Dzulhijjah). Hari makan, minum, dan dzikir kepada Allah (HR. Muslim). Jamaah haji mabit di Mina."},
		{Name: "Hari Tasyrik (12 Dzulhijjah)", HijriMonth: 12, HijriDay: 12, Category: model.EventCategoryPeristiwa, Description: "Hari tasyrik kedua. Bagi yang ingin nafar awal, bisa meninggalkan Mina sebelum Maghrib."},
		{Name: "Hari Tasyrik (13 Dzulhijjah)", HijriMonth: 12, HijriDay: 13, Category: model.EventCategoryPeristiwa, Description: "Hari tasyrik terakhir. Akhir dari rangkaian ibadah haji di Mina (nafar tsani)."},
		{Name: "Maulid Nabi ﷺ", HijriMonth: 3, HijriDay: 12, Category: model.EventCategoryPeristiwa, Description: "Peringatan kelahiran Nabi Muhammad ﷺ pada 12 Rabiul Awal tahun Gajah (± 571 M). Momentum meningkatkan sholawat dan kecintaan kepada beliau."},
		{Name: "Isra Mi'raj", HijriMonth: 7, HijriDay: 27, Category: model.EventCategoryPeristiwa, Description: "Perjalanan malam Nabi ﷺ dari Masjidil Haram ke Masjidil Aqsha (Isra), lalu naik ke Sidratul Muntaha (Mi'raj). Turunnya kewajiban sholat 5 waktu."},
		{Name: "Puasa Senin-Kamis", HijriMonth: 0, HijriDay: 0, Category: model.EventCategoryPuasa, Description: "Puasa sunnah setiap hari Senin dan Kamis. Nabi ﷺ bersabda: 'Amal-amal diangkat pada hari Senin dan Kamis, maka aku suka jika amalku diangkat saat aku sedang berpuasa.' (HR. Tirmidzi)"},
		{Name: "Puasa Ayyamul Bidh (13-15)", HijriMonth: 0, HijriDay: 13, Category: model.EventCategoryPuasa, Description: "Puasa 3 hari di pertengahan setiap bulan Hijriah (13, 14, 15). Setara dengan puasa sepanjang tahun karena satu kebaikan dilipatkan 10x (HR. An-Nasa'i)."},
	}
	for i := range events {
		db.Clauses(clause.OnConflict{
			Columns:   []clause.Column{{Name: "hijri_month"}, {Name: "hijri_day"}, {Name: "name"}},
			DoUpdates: clause.AssignmentColumns([]string{"description", "category"}),
		}).Create(&events[i])
	}
}

func upsertHistory(db *gorm.DB, e *model.HistoryEvent) {
	db.Clauses(clause.OnConflict{
		Columns:   []clause.Column{{Name: "slug"}},
		DoUpdates: clause.AssignmentColumns([]string{"title", "description", "year_hijri", "year_miladi", "category", "is_significant"}),
	}).Create(e)
}

func seedHistoryEvents(db *gorm.DB) {
	events := []model.HistoryEvent{
		{YearHijri: -53, YearMiladi: 570, Title: "Kelahiran Nabi Muhammad ﷺ", Slug: "kelahiran-nabi", Description: "Nabi Muhammad ﷺ lahir di Makkah pada 12 Rabi'ul Awwal, Tahun Gajah (570 M). Ayahnya, Abdullah, wafat sebelum beliau lahir. Ibunya, Aminah binti Wahb, menyusui beliau hingga beberapa bulan, kemudian diserahkan kepada Halimah Sa'diyah dari Bani Sa'd untuk disusui di pedesaan.\n\nSumber: Ar-Raheeq Al-Makhtum, hal. 56-65", Category: model.HistoryCategoryNabi, IsSignificant: true},
		{YearHijri: -43, YearMiladi: 580, Title: "Wafatnya Ibu Nabi: Aminah binti Wahb", Slug: "wafat-aminah", Description: "Ketika Nabi ﷺ berusia sekitar 6 tahun, ibunya Aminah wafat di Abwa' dalam perjalanan pulang dari Madinah (Yatsrib) setelah mengunjungi keluarga ayahnya. Beliau kemudian diasuh oleh kakeknya, Abdul Muthalib.\n\nSumber: Ar-Raheeq Al-Makhtum, hal. 67", Category: model.HistoryCategoryNabi, IsSignificant: false},
		{YearHijri: -40, YearMiladi: 583, Title: "Wafatnya Abdul Muthalib, Kakek Nabi", Slug: "wafat-abdul-muthalib", Description: "Ketika Nabi ﷺ berusia 8 tahun, kakeknya Abdul Muthalib wafat. Penjagaan beliau kemudian diserahkan kepada pamannya, Abu Thalib.\n\nSumber: Sirah Ibnu Hisyam", Category: model.HistoryCategoryNabi, IsSignificant: false},
		{YearHijri: -28, YearMiladi: 595, Title: "Pernikahan Nabi dengan Khadijah", Slug: "pernikahan-khadijah", Description: "Pada usia 25 tahun, Nabi ﷺ menikahi Khadijah binti Khuwailid (40 tahun) setelah beliau bekerja sebagai pedagang untuk Khadijah. Khadijah adalah wanita pertama yang masuk Islam dan merupakan istri paling dicintai Nabi. Mereka dikaruniai 6 anak: Qasim, Abdullah, Zainab, Ruqayyah, Ummu Kulsum, dan Fatimah.\n\nSumber: Ar-Raheeq Al-Makhtum, hal. 83", Category: model.HistoryCategoryNabi, IsSignificant: true},
		{YearHijri: 1, YearMiladi: 610, Title: "Turunnya Wahyu Pertama (Nuzulul Quran)", Slug: "wahyu-pertama", Description: "Pada malam 17 Ramadan, tahun 610 M, ketika Nabi ﷺ berusia 40 tahun sedang berkhalwat di Gua Hira, malaikat Jibril datang dan menurunkan wahyu pertama: QS. Al-Alaq ayat 1-5 ('Iqra' bismi rabbika...'). Inilah awal kenabian Muhammad ﷺ.\n\nSumber: HR. Bukhari No. 3, Muslim No. 160", Category: model.HistoryCategoryNabi, IsSignificant: true},
		{YearHijri: 3, YearMiladi: 613, Title: "Dakwah Terbuka di Makkah", Slug: "dakwah-terbuka-makkah", Description: "Setelah 3 tahun dakwah secara sembunyi-sembunyi (sirriyah), Nabi ﷺ diperintahkan untuk berdakwah secara terang-terangan berdasarkan QS. Al-Hijr: 94. Beliau menyeru keluarga besar Bani Hasyim di bukit Shafa: 'Andaikan kuberitahu kalian bahwa di balik bukit ini ada pasukan kuda yang hendak menyerang kalian, apakah kalian percaya?' Mereka menjawab: 'Ya.' Beliau berkata: 'Sesungguhnya aku adalah pemberi peringatan kepada kalian dari azab yang pedih.'\n\nSumber: HR. Bukhari No. 4770, Muslim No. 208", Category: model.HistoryCategoryNabi, IsSignificant: true},
		{YearHijri: 5, YearMiladi: 615, Title: "Hijrah Pertama ke Habasyah", Slug: "hijrah-habasyah", Description: "Karena tekanan keras kaum Quraisy, Nabi ﷺ mengizinkan sekelompok kaum muslimin (sekitar 15 orang, dipimpin Utsman bin Affan) untuk berhijrah ke Habasyah (Ethiopia) mencari perlindungan kepada Raja Najasyi (Ashhamah). Ini adalah hijrah pertama dalam sejarah Islam.\n\nSumber: Ar-Raheeq Al-Makhtum, hal. 128", Category: model.HistoryCategoryNabi, IsSignificant: true},
		{YearHijri: 10, YearMiladi: 619, Title: "Tahun Duka Cita ('Aam Al-Huzn)", Slug: "tahun-duka-cita", Description: "Dalam satu tahun yang sama, dua orang paling dekat dengan Nabi ﷺ wafat: pertama, Khadijah istri beliau yang setia selama 25 tahun; kemudian Abu Thalib paman yang selalu melindungi beliau meski tidak masuk Islam. Nabi ﷺ sangat berduka, dan tahun ini dikenal sebagai 'Aam Al-Huzn' (Tahun Duka Cita).\n\nSumber: Ar-Raheeq Al-Makhtum, hal. 163", Category: model.HistoryCategoryNabi, IsSignificant: true},
		{YearHijri: 10, YearMiladi: 621, Title: "Isra' Mi'raj", Slug: "isra-miraj", Description: "Nabi ﷺ diperjalankan dari Masjidil Haram ke Masjidil Aqsha (Isra'), kemudian naik ke Sidratul Muntaha (Mi'raj) dalam satu malam. Di sinilah beliau menerima perintah sholat 5 waktu langsung dari Allah SWT — awalnya 50 waktu, kemudian dikurangi menjadi 5 waktu atas saran Nabi Musa as.\n\nSumber: HR. Bukhari No. 349, Muslim No. 163; QS. Al-Isra: 1", Category: model.HistoryCategoryNabi, IsSignificant: true},
		{YearHijri: 13, YearMiladi: 622, Title: "Hijrah ke Madinah", Slug: "hijrah-madinah", Description: "Pada bulan Rabi'ul Awwal tahun 622 M, Nabi ﷺ dan Abu Bakar berhijrah dari Makkah ke Madinah (Yatsrib). Peristiwa ini menjadi tonggak awal kalender Hijriah dan pembentukan komunitas Islam pertama. Di Madinah, Nabi ﷺ mempersaudarakan kaum Muhajirin dan Anshar, serta menyusun Piagam Madinah.\n\nSumber: Ar-Raheeq Al-Makhtum, hal. 201-215", Category: model.HistoryCategoryNabi, IsSignificant: true},
		{YearHijri: 2, YearMiladi: 624, Title: "Perang Badar", Slug: "perang-badar", Description: "Perang Badar (17 Ramadan 2 H / 624 M) adalah perang besar pertama kaum muslimin. 313 pasukan Muslim menghadapi 1.000 pasukan Quraisy. Dengan pertolongan Allah, kaum muslimin menang. 70 musuh tewas (termasuk pemimpin Quraisy: Abu Jahal) dan 70 tertawan. Kemenangan ini memperkuat posisi Islam di jazirah Arab.\n\nSumber: HR. Bukhari No. 3992; QS. Al-Anfal: 9", Category: model.HistoryCategoryNabi, IsSignificant: true},
		{YearHijri: 3, YearMiladi: 625, Title: "Perang Uhud", Slug: "perang-uhud", Description: "Dalam perang Uhud (7 Syawal 3 H), kaum muslimin awalnya unggul namun sebagian pasukan pemanah meninggalkan posnya karena rakus terhadap harta rampasan. Hal ini dimanfaatkan Khalid bin Walid (saat itu masih kafir) untuk menyerang dari belakang. 70 sahabat syahid termasuk Hamzah bin Abdul Muthalib. Nabi ﷺ sendiri terluka.\n\nSumber: HR. Bukhari No. 4043; QS. Ali Imran: 121-179", Category: model.HistoryCategoryNabi, IsSignificant: true},
		{YearHijri: 5, YearMiladi: 627, Title: "Perang Khandaq (Ahzab)", Slug: "perang-khandaq", Description: "Kaum Quraisy bersama sekutu (sekitar 10.000 pasukan) mengepung Madinah. Atas saran Salman Al-Farisi, Nabi ﷺ memerintahkan penggalian parit (khandaq) di utara Madinah. Pengepungan berlangsung sebulan tanpa berhasil menerobos. Akhirnya Allah mengutus angin kencang yang memorak-porandakan pasukan musuh dan mereka mundur.\n\nSumber: HR. Bukhari No. 4106; QS. Al-Ahzab: 9-27", Category: model.HistoryCategoryNabi, IsSignificant: true},
		{YearHijri: 6, YearMiladi: 628, Title: "Perjanjian Hudaibiyyah", Slug: "perjanjian-hudaibiyyah", Description: "Nabi ﷺ dan 1.400 sahabat berangkat untuk umrah, namun dihadang Quraisy di Hudaibiyyah. Ditandatangani perjanjian damai 10 tahun: kaum muslimin tidak boleh umrah tahun ini, namun boleh tahun depan; jika ada Quraisy yang lari ke Muslim harus dikembalikan, tapi jika ada Muslim yang lari ke Quraisy tidak perlu dikembalikan. Meski tampak merugikan, Allah menyebutnya sebagai 'kemenangan yang nyata' (QS. Al-Fath: 1).\n\nSumber: HR. Bukhari No. 2731; QS. Al-Fath: 1-3", Category: model.HistoryCategoryNabi, IsSignificant: true},
		{YearHijri: 8, YearMiladi: 630, Title: "Fathu Makkah (Pembebasan Makkah)", Slug: "fathu-makkah", Description: "Setelah Quraisy melanggar perjanjian Hudaibiyyah, Nabi ﷺ bergerak dengan 10.000 pasukan menuju Makkah. Kota Makkah menyerah hampir tanpa perlawanan pada 20 Ramadan 8 H. Nabi ﷺ memberi amnesti umum kepada penduduk Makkah: 'Pergilah kalian, kalian bebas.' Ka'bah dibersihkan dari 360 berhala. Mayoritas penduduk Makkah masuk Islam.\n\nSumber: HR. Bukhari No. 4280; Ar-Raheeq Al-Makhtum, hal. 376-386", Category: model.HistoryCategoryNabi, IsSignificant: true},
		{YearHijri: 10, YearMiladi: 632, Title: "Haji Wada' dan Khutbah Terakhir", Slug: "haji-wada", Description: "Pada tahun 10 H (632 M), Nabi ﷺ melaksanakan haji terakhir bersama lebih dari 100.000 sahabat. Di Padang Arafah, beliau menyampaikan Khutbah Wada' yang berisi prinsip-prinsip fundamental Islam: kesetaraan manusia, kesucian darah dan harta, penghapusan riba, hak-hak perempuan, dan amanah Al-Quran & Sunnah. Turun QS. Al-Maidah: 3 menyatakan kesempurnaan agama Islam.\n\nSumber: HR. Bukhari No. 1741, Muslim No. 1218", Category: model.HistoryCategoryNabi, IsSignificant: true},
		{YearHijri: 11, YearMiladi: 632, Title: "Wafatnya Rasulullah ﷺ", Slug: "wafat-rasulullah", Description: "Pada Senin, 12 Rabi'ul Awwal 11 H (8 Juni 632 M), Nabi ﷺ wafat di kamar Aisyah ra. dalam usia 63 tahun. Abu Bakar berkhutbah: 'Barangsiapa menyembah Muhammad, sesungguhnya Muhammad telah wafat. Barangsiapa menyembah Allah, sesungguhnya Allah Maha Hidup tidak akan mati.' (QS. Ali Imran: 144). Beliau dikebumikan di tempat beliau wafat.\n\nSumber: HR. Bukhari No. 4448; Ar-Raheeq Al-Makhtum", Category: model.HistoryCategoryNabi, IsSignificant: true},
		{YearHijri: 11, YearMiladi: 632, Title: "Khalifah Abu Bakar Ash-Shiddiq (11-13 H)", Slug: "khilafah-abu-bakar", Description: "Abu Bakar ra. terpilih sebagai khalifah pertama melalui musyawarah di Saqifah Bani Sa'idah. Masa kekhalifahannya (632-634 M) ditandai dengan: (1) Memerangi kaum murtad (Riddah Wars), (2) Memerangi Musailamah Al-Kadzab, (3) Pengumpulan Al-Quran pertama kali atas usulan Umar bin Khattab dan dilaksanakan oleh Zaid bin Tsabit setelah banyak hafizh syahid di Yamamah.\n\nSumber: HR. Bukhari No. 4986", Category: model.HistoryCategoryKhulafa, IsSignificant: true},
		{YearHijri: 13, YearMiladi: 634, Title: "Khalifah Umar bin Khattab (13-23 H)", Slug: "khilafah-umar", Description: "Umar bin Khattab ra. menjadi khalifah kedua (634-644 M), ditunjuk langsung oleh Abu Bakar. Masa kekhalifahannya adalah masa ekspansi terbesar Islam: penaklukan Persia, Syam, dan Mesir. Beliau mendirikan sistem administrasi, menetapkan kalender Hijriah, membangun Baitul Mal, dan dikenal sebagai pemimpin yang sangat adil dan sederhana. Beliau syahid ditikam oleh Abu Lu'lu'ah Al-Majusi.\n\nSumber: Ar-Raheeq Al-Makhtum; Tarikh Ath-Thabari", Category: model.HistoryCategoryKhulafa, IsSignificant: true},
		{YearHijri: 23, YearMiladi: 644, Title: "Khalifah Utsman bin Affan (23-35 H)", Slug: "khilafah-utsman", Description: "Utsman bin Affan ra. terpilih melalui syura (musyawarah enam orang). Masa kekhalifahannya (644-656 M) ditandai dengan: (1) Pembukuan resmi Al-Quran (Mushaf Utsmani) yang menjadi standar hingga kini, (2) Ekspansi ke Afrika Utara dan Persia timur, (3) Pembangunan angkatan laut Islam pertama. Beliau syahid dibunuh oleh kaum pemberontak pada usia sekitar 82 tahun.\n\nSumber: HR. Bukhari No. 4986", Category: model.HistoryCategoryKhulafa, IsSignificant: true},
		{YearHijri: 35, YearMiladi: 656, Title: "Khalifah Ali bin Abi Thalib (35-40 H)", Slug: "khilafah-ali", Description: "Ali bin Abi Thalib ra. menjadi khalifah keempat (656-661 M). Masa kekhalifahannya diwarnai fitnah (ujian besar): Perang Jamal (melawan Aisyah, Thalhah, dan Zubair) dan Perang Shiffin (melawan Mu'awiyah). Kedua perang ini berakhir tanpa pemenang jelas. Ali ra. syahid ditikam Abdurrahman bin Muljam dari kelompok Khawarij. Kekhalifahannya menandai berakhirnya era Khulafaur Rasyidin.\n\nSumber: Tarikh Al-Khulafa, As-Suyuthi", Category: model.HistoryCategoryKhulafa, IsSignificant: true},
		{YearHijri: 41, YearMiladi: 661, Title: "Dinasti Umayyah (41-132 H / 661-750 M)", Slug: "dinasti-umayyah", Description: "Dinasti Umayyah didirikan oleh Mu'awiyah bin Abi Sufyan setelah Hassan bin Ali menyerahkan kekuasaan demi persatuan umat. Ibu kota dipindah ke Damaskus. Masa ini ditandai dengan ekspansi Islam terluas: ke Spanyol (Al-Andalus) di barat, Asia Tengah di timur, dan India. Puncak kejayaan pada masa Umar bin Abdul Aziz (Umar II, 99-101 H) yang terkenal dengan keadilannya.\n\nSumber: Tarikh Ath-Thabari; Al-Bidayah wan Nihayah", Category: model.HistoryCategoryDinasti, IsSignificant: true},
		{YearHijri: 132, YearMiladi: 750, Title: "Dinasti Abbasiyyah (132-656 H / 750-1258 M)", Slug: "dinasti-abbasiyyah", Description: "Dinasti Abbasiyyah menggantikan Umayyah dengan ibu kota Baghdad. Masa ini adalah Zaman Keemasan Islam (The Golden Age of Islam): kemajuan pesat ilmu pengetahuan, filsafat, matematika, astronomi, kedokteran (Ibnu Sina, Al-Khawarizmi, Al-Biruni, dll). Bayt Al-Hikmah (Rumah Kebijaksanaan) di Baghdad menjadi pusat keilmuan dunia. Berakhir dengan penghancuran Baghdad oleh Mongol (Hulagu Khan) pada 656 H/1258 M.\n\nSumber: Tarikh Al-Islam, Adz-Dzahabi", Category: model.HistoryCategoryDinasti, IsSignificant: true},
		{YearHijri: 656, YearMiladi: 1258, Title: "Jatuhnya Baghdad ke Tangan Mongol", Slug: "jatuhnya-baghdad", Description: "Pada 656 H (1258 M), pasukan Mongol di bawah Hulagu Khan menghancurkan Baghdad — ibu kota Kekhalifahan Abbasiyyah. Khalifah Al-Mu'tashim billah dibunuh. Jutaan manuskrip ilmu pengetahuan dibuang ke Sungai Tigris hingga air sungai berubah warna karena tinta. Peristiwa ini menandai berakhirnya kekuasaan Abbasiyyah di Baghdad.\n\nSumber: Al-Bidayah wan Nihayah, Ibnu Katsir", Category: model.HistoryCategoryPeristiwa, IsSignificant: true},
		{YearHijri: 583, YearMiladi: 1187, Title: "Shalahuddin Al-Ayyubi Membebaskan Yerusalem", Slug: "pembebasan-yerusalem", Description: "Setelah Yerusalem (Al-Quds) dikuasai Tentara Salib selama 88 tahun (1099-1187 M), Shalahuddin Al-Ayyubi (Saladin) berhasil membebaskannya pada 27 Rajab 583 H. Berbeda dengan penaklukan Tentara Salib yang penuh pembantaian, Shalahuddin memberikan amnesti kepada penduduk Kristen yang ingin pergi, dan melindungi gereja-gereja mereka.\n\nSumber: Al-Kamil fit Tarikh, Ibnu Al-Atsir", Category: model.HistoryCategoryPeristiwa, IsSignificant: true},
		{YearHijri: 926, YearMiladi: 1520, Title: "Puncak Kejayaan Kesultanan Utsmaniyah (Ottoman)", Slug: "ottoman-suleiman", Description: "Masa pemerintahan Sultan Suleiman Al-Qanuni (926-974 H / 1520-1566 M) merupakan puncak kejayaan Kesultanan Utsmaniyah. Wilayahnya mencakup tiga benua: Asia, Afrika, dan Eropa. Istanbul menjadi pusat peradaban Islam. Masjid Sulaiman (Süleymaniye Mosque) dibangun sebagai simbol kejayaan. Beliau juga dikenal sebagai legislator ulung.\n\nSumber: The Ottoman Empire and the World Around It, Suraiya Faroqhi", Category: model.HistoryCategoryDinasti, IsSignificant: true},
		{YearHijri: 150, YearMiladi: 767, Title: "Imam Abu Hanifah (80-150 H)", Slug: "imam-abu-hanifah", Description: "Nu'man bin Tsabit, dikenal sebagai Imam Abu Hanifah atau 'Al-Imam Al-A'zham' (Imam Terbesar). Pendiri mazhab Hanafi — mazhab fiqh terbesar di dunia (mencakup Turki, Asia Selatan, Asia Tengah). Dikenal dengan metode qiyas (analogi) yang kuat. Pernah dipenjara karena menolak jabatan qadhi (hakim) yang ditawarkan khalifah Abbasiyyah.\n\nSumber: Siyar A'lam An-Nubala, Adz-Dzahabi", Category: model.HistoryCategoryUlama, IsSignificant: true},
		{YearHijri: 179, YearMiladi: 795, Title: "Imam Malik bin Anas (93-179 H)", Slug: "imam-malik", Description: "Imam Malik bin Anas, pendiri mazhab Maliki. Karya monumentalnya Al-Muwaththa' adalah koleksi hadith tertua yang masih ada. Imam Syafi'i menyebutnya: 'Jika ulama disebut, maka Malik adalah bintang.' Pernah dihukum cambuk karena memberikan fatwa yang tidak sesuai keinginan penguasa. Muridnya tersebar di Afrika Utara dan Spanyol.\n\nSumber: Siyar A'lam An-Nubala, Adz-Dzahabi", Category: model.HistoryCategoryUlama, IsSignificant: true},
		{YearHijri: 204, YearMiladi: 820, Title: "Imam Muhammad bin Idris Asy-Syafi'i (150-204 H)", Slug: "imam-syafii", Description: "Imam Syafi'i adalah pendiri mazhab Syafi'i dan Ilmu Ushul Fiqh. Karya terbesarnya: Ar-Risalah (pertama membahas metodologi hukum Islam) dan Al-Umm. Beliau belajar kepada Imam Malik di Madinah dan murid-murid Abu Hanifah di Irak. Mazhab Syafi'i menjadi mazhab dominan di Indonesia, Malaysia, Mesir, dan sebagian besar dunia Muslim.\n\nSumber: Manaqib Asy-Syafi'i, Al-Baihaqi", Category: model.HistoryCategoryUlama, IsSignificant: true},
		{YearHijri: 241, YearMiladi: 855, Title: "Imam Ahmad bin Hanbal (164-241 H)", Slug: "imam-ahmad-hanbal", Description: "Imam Ahmad bin Hanbal, pendiri mazhab Hanbali dan Imam Ahli Sunnah. Karya terbesarnya: Musnad Ahmad (sekitar 30.000 hadith). Beliau mengalami ujian berat (Mihnah) di bawah Khalifah Al-Ma'mun dan Al-Mu'tashim yang memaksanya menerima paham Mu'tazilah bahwa Al-Quran adalah makhluk. Beliau menolak meski disiksa, dan menjadi simbol keteguhan aqidah.\n\nSumber: Manaqib Al-Imam Ahmad, Ibnu Al-Jauzi", Category: model.HistoryCategoryUlama, IsSignificant: true},
		{YearHijri: 256, YearMiladi: 870, Title: "Imam Al-Bukhari Menyelesaikan Shahih Bukhari (194-256 H)", Slug: "shahih-bukhari", Description: "Muhammad bin Ismail Al-Bukhari menyelesaikan kitab Shahih-nya — koleksi hadith paling shahih setelah Al-Quran. Dari 600.000 hadith yang dihafal, beliau memilih sekitar 7.275 hadith (2.602 tanpa pengulangan) setelah seleksi ketat selama 16 tahun. Imam Syafi'i berkata: 'Aku tidak melihat orang yang lebih faqih tentang hadith daripada pemuda dari Khurasan ini.'\n\nSumber: Hady As-Sari, Ibnu Hajar", Category: model.HistoryCategoryUlama, IsSignificant: true},
		{YearHijri: 728, YearMiladi: 1328, Title: "Ibnu Taimiyah (661-728 H)", Slug: "ibnu-taimiyah", Description: "Taqiyuddin Ahmad Ibnu Taimiyah — ulama besar mazhab Hanbali yang sangat berpengaruh. Hidup di masa invasi Mongol dan Tentara Salib, beliau aktif berjihad dan berfatwa. Dikenal dengan seruan kembali kepada Al-Quran dan Sunnah, menolak bid'ah dan khurafat. Dipenjara beberapa kali karena fatwa-fatwanya yang kontroversial. Muridnya: Ibnu Qayyim Al-Jauziyyah.\n\nSumber: Siyar A'lam An-Nubala, Adz-Dzahabi", Category: model.HistoryCategoryUlama, IsSignificant: true},
	}

	for i := range events {
		upsertHistory(db, &events[i])
	}
}

func seedManasikSteps(db *gorm.DB) {
	umrahSteps := []model.ManasikStep{
		{Type: model.ManasikTypeUmrah, StepOrder: 1, Title: "Miqat dan Niat Ihram", Description: "Miqat adalah batas tempat wajib memulai ihram. Untuk jemaah Indonesia umumnya miqat di Yalamlam (jalur laut) atau Bir Ali/Dzul Hulaifah (jalur Madinah-Makkah). Di miqat: mandi sunnah, memakai pakaian ihram (2 kain putih untuk laki-laki, baju biasa menutup aurat untuk perempuan), sholat sunnah ihram 2 rakaat, kemudian niat umrah.", Arabic: "لَبَّيْكَ اللَّهُمَّ عُمْرَةً", Transliteration: "Labbaika Allahumma 'umratan", TranslationText: "Aku memenuhi panggilan-Mu ya Allah untuk umrah.", Notes: "Larangan ihram: mencukur rambut/kuku, memakai wewangian, berhubungan suami-istri, berburu binatang, menikah/menikahkan.", IsWajib: true},
		{Type: model.ManasikTypeUmrah, StepOrder: 2, Title: "Talbiyah dalam Perjalanan", Description: "Setelah niat ihram, perbanyak membaca talbiyah dalam perjalanan menuju Makkah, terutama saat naik kendaraan, naik turun bukit, berpapasan dengan rombongan lain, dan di waktu-waktu utama.", Arabic: "لَبَّيْكَ اللَّهُمَّ لَبَّيْكَ، لَبَّيْكَ لاَ شَرِيكَ لَكَ لَبَّيْكَ، إِنَّ الْحَمْدَ وَالنِّعْمَةَ لَكَ وَالْمُلْكَ، لاَ شَرِيكَ لَكَ", Transliteration: "Labbaika Allahumma labbaik, labbaika laa syariika laka labbaik, innal hamda wan ni'mata laka wal mulk, laa syariika lak", TranslationText: "Aku memenuhi panggilan-Mu ya Allah, aku memenuhi panggilan-Mu. Aku memenuhi panggilan-Mu, tiada sekutu bagi-Mu, aku memenuhi panggilan-Mu. Sesungguhnya segala puji, nikmat, dan kerajaan adalah milik-Mu. Tiada sekutu bagi-Mu.", Notes: "Baca talbiyah dengan suara keras untuk laki-laki, pelan untuk perempuan.", IsWajib: false},
		{Type: model.ManasikTypeUmrah, StepOrder: 3, Title: "Memasuki Masjidil Haram", Description: "Masuk Masjidil Haram dengan kaki kanan terlebih dahulu, membaca doa masuk masjid dan doa melihat Ka'bah. Saat pertama kali melihat Ka'bah, panjatkan doa karena ini adalah waktu mustajab.", Arabic: "اللَّهُمَّ أَنْتَ السَّلاَمُ وَمِنْكَ السَّلاَمُ، فَحَيِّنَا رَبَّنَا بِالسَّلاَمِ", Transliteration: "Allahumma antas salaam wa minkas salaam, fa hayyina rabbana bis salaam", TranslationText: "Ya Allah, Engkau adalah Maha Sejahtera dan dari-Mu lah kesejahteraan, maka hidupkanlah kami wahai Tuhan kami dengan kesejahteraan.", Notes: "Saat melihat Ka'bah pertama kali: angkat tangan, berdoa, dan sampaikan hajat karena waktu mustajab.", IsWajib: false},
		{Type: model.ManasikTypeUmrah, StepOrder: 4, Title: "Thawaf (7 Putaran)", Description: "Thawaf adalah mengelilingi Ka'bah sebanyak 7 putaran berlawanan arah jarum jam, dimulai dan diakhiri di Hajar Aswad. Posisi Ka'bah selalu di sebelah kiri. Pada 3 putaran pertama, laki-laki dianjurkan berlari-lari kecil (raml). Baca doa dan dzikir selama thawaf sesuai sunnah.", Arabic: "بِسْمِ اللَّهِ وَاللَّهُ أَكْبَرُ", Transliteration: "Bismillahi wallahu Akbar", TranslationText: "Dengan menyebut nama Allah, dan Allah Maha Besar.", Notes: "Syarat thawaf: suci dari hadats, menutup aurat, Ka'bah di sebelah kiri. Tidak ada doa khusus per putaran — baca doa bebas, Al-Quran, atau dzikir.", IsWajib: true},
		{Type: model.ManasikTypeUmrah, StepOrder: 5, Title: "Sholat 2 Rakaat di Belakang Maqam Ibrahim", Description: "Setelah thawaf, sholat 2 rakaat di belakang Maqam Ibrahim (jika tidak memungkinkan karena penuh, boleh di tempat lain dalam Masjidil Haram). Rakaat pertama baca Al-Fatihah + Al-Kafirun, rakaat kedua baca Al-Fatihah + Al-Ikhlas.", Arabic: "وَاتَّخِذُوا مِن مَّقَامِ إِبْرَاهِيمَ مُصَلًّى", Transliteration: "Wattakhidzu min maqaami ibraahiima mushalla", TranslationText: "Dan jadikanlah sebagian maqam Ibrahim sebagai tempat sholat.", Notes: "Maqam Ibrahim adalah batu tempat Nabi Ibrahim berdiri saat membangun Ka'bah. QS. Al-Baqarah: 125.", IsWajib: true},
		{Type: model.ManasikTypeUmrah, StepOrder: 6, Title: "Sa'i (7 Kali antara Shafa dan Marwah)", Description: "Sa'i adalah berjalan 7 kali antara bukit Shafa dan Marwah — mengenang perjuangan Hajar mencari air untuk bayinya Ismail. Dimulai dari Shafa (hitungan 1) ke Marwah (hitungan 2), berakhir di Marwah (hitungan 7). Di Shafa dan Marwah, berhenti sejenak menghadap Ka'bah dan berdoa.", Arabic: "إِنَّ الصَّفَا وَالْمَرْوَةَ مِن شَعَائِرِ اللَّهِ", Transliteration: "Innas shofa wal marwata min sya'aa'irillah", TranslationText: "Sesungguhnya Shafa dan Marwah adalah sebagian dari syiar-syiar Allah.", Notes: "Berlari-lari kecil (bagi laki-laki) antara dua tanda hijau yang ada di lorong sa'i.", IsWajib: true},
		{Type: model.ManasikTypeUmrah, StepOrder: 7, Title: "Tahallul: Memotong Rambut", Description: "Tahallul adalah pencabutan larangan ihram dengan memotong rambut. Untuk laki-laki: dianjurkan mencukur habis (halq) atau minimal memotong sebagian rambut (taqshir, minimal 3 helai dari seluruh kepala). Untuk perempuan: memotong ujung rambut sepanjang ruas jari. Dengan tahallul, seluruh larangan ihram berakhir.", Arabic: "مُحَلِّقِينَ رُءُوسَكُمْ وَمُقَصِّرِينَ", Transliteration: "Muhalliqiina ru'usakum wa muqashshiriin", TranslationText: "Dengan mencukur kepala kalian dan memotong rambut.", Notes: "QS. Al-Fath: 27. Umrah selesai setelah tahallul.", IsWajib: true},
	}

	hajiSteps := []model.ManasikStep{
		{Type: model.ManasikTypeHaji, StepOrder: 1, Title: "Ihram dari Miqat (8 Dzulhijjah)", Description: "Pada 8 Dzulhijjah (Hari Tarwiyah), jemaah haji berihram dari miqat atau dari Makkah (bagi yang sudah di sana). Niat haji, kenakan pakaian ihram, baca talbiyah.", Arabic: "لَبَّيْكَ اللَّهُمَّ حَجًّا", Transliteration: "Labbaika Allahumma hajjan", TranslationText: "Aku memenuhi panggilan-Mu ya Allah untuk haji.", Notes: "Untuk haji tamattu': berihram khusus haji setelah tahallul dari umrah.", IsWajib: true},
		{Type: model.ManasikTypeHaji, StepOrder: 2, Title: "Mabit di Mina (8 Dzulhijjah)", Description: "Pada 8 Dzulhijjah, jemaah berangkat ke Mina dan mabit (menginap) di sana. Ini adalah sunnah Nabi ﷺ. Di Mina, sholat Dzuhur, Ashar, Maghrib, Isya, dan Subuh diqashar (diringkas) tanpa dijama'.", Arabic: "", Transliteration: "", TranslationText: "", Notes: "Mabit di Mina 8 Dzulhijjah adalah sunnah. Yang wajib adalah mabit di Mina pada malam-malam 11-13 Dzulhijjah.", IsWajib: false},
		{Type: model.ManasikTypeHaji, StepOrder: 3, Title: "Wukuf di Arafah (9 Dzulhijjah) — Rukun Terpenting", Description: "Wukuf di Arafah pada 9 Dzulhijjah adalah rukun haji terpenting: 'Al-Hajj 'Arafah' (HR. Abu Dawud). Dimulai setelah tergelincir matahari (Dzuhur) hingga terbit fajar 10 Dzulhijjah. Perbanyak doa, dzikir, istighfar, membaca talbiyah. Di Arafah, sholat Dzuhur dan Ashar dijama'-qashar.", Arabic: "لاَ إِلَهَ إِلاَّ اللهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ", Transliteration: "Laa ilaaha illallah wahdahu laa syariika lah, lahul mulku wa lahul hamdu wa huwa 'alaa kulli syai'in qadiir", TranslationText: "Tiada tuhan selain Allah, Maha Esa, tiada sekutu bagi-Nya. Milik-Nya kerajaan dan milik-Nya segala pujian, dan Dia Maha Kuasa atas segala sesuatu.", Notes: "Doa terbaik di Arafah adalah doa ini (HR. Tirmidzi No. 3585). Wukuf tidak sah jika tidak hadir di Arafah sama sekali.", IsWajib: true},
		{Type: model.ManasikTypeHaji, StepOrder: 4, Title: "Mabit di Muzdalifah (Malam 10 Dzulhijjah)", Description: "Setelah matahari terbenam di Arafah, berangkat ke Muzdalifah. Di Muzdalifah: sholat Maghrib dan Isya dijama' (Maghrib 3 rakaat + Isya 2 rakaat), mabit hingga setelah sholat Subuh. Kumpulkan batu kerikil untuk jumrah (minimal 49 butir untuk 3 hari, atau 70 butir untuk 4 hari).", Arabic: "", Transliteration: "", TranslationText: "", Notes: "Wajib mabit di Muzdalifah. Yang udzur (sakit, wanita, lansia) boleh meninggalkan Muzdalifah setelah tengah malam.", IsWajib: true},
		{Type: model.ManasikTypeHaji, StepOrder: 5, Title: "Melontar Jumrah Aqabah (10 Dzulhijjah)", Description: "Pada 10 Dzulhijjah (Hari Nahr/Idul Adha), setelah tiba di Mina, lempar Jumrah Aqabah (Jumrah Kubra) dengan 7 batu kerikil. Setiap lemparan diiringi takbir 'Allahu Akbar'. Setelah melontar, baca: 'Allahumma ij'alhu hajjan mabruran wa dzanban maghfuran'.", Arabic: "اللَّهُ أَكْبَرُ", Transliteration: "Allahu Akbar", TranslationText: "Allah Maha Besar", Notes: "Jumrah Aqabah adalah yang paling dekat ke Makkah. Waktu utama: setelah matahari terbit. HR. Bukhari No. 1751.", IsWajib: true},
		{Type: model.ManasikTypeHaji, StepOrder: 6, Title: "Menyembelih Hewan Qurban (Haji Tamattu'/Qiran)", Description: "Bagi yang haji tamattu' atau qiran, wajib membayar dam (menyembelih hewan: kambing, atau 1/7 sapi/unta). Penyembelihan di Mina pada 10-13 Dzulhijjah.", Arabic: "", Transliteration: "", TranslationText: "", Notes: "Haji ifrad tidak wajib dam. Jika tidak mampu menyembelih, wajib puasa 3 hari selama haji dan 7 hari setelah pulang (total 10 hari). QS. Al-Baqarah: 196.", IsWajib: true},
		{Type: model.ManasikTypeHaji, StepOrder: 7, Title: "Tahallul Awal: Mencukur/Memotong Rambut", Description: "Setelah melontar Jumrah Aqabah dan menyembelih (atau niat dam), lakukan tahallul awal dengan mencukur/memotong rambut. Dengan tahallul awal, sebagian larangan ihram berakhir: boleh memakai pakaian biasa, memotong kuku, memakai wewangian — kecuali berhubungan suami-istri.", Arabic: "", Transliteration: "", TranslationText: "", Notes: "Urutan sunnah di 10 Dzulhijjah: lontar jumrah → sembelih → cukur → thawaf ifadhah.", IsWajib: true},
		{Type: model.ManasikTypeHaji, StepOrder: 8, Title: "Thawaf Ifadhah (Thawaf Ziarah) — Rukun Haji", Description: "Thawaf Ifadhah adalah rukun haji yang wajib dilakukan. Waktunya: setelah 10 Dzulhijjah. Tata caranya sama dengan thawaf umrah: 7 putaran mengelilingi Ka'bah. Setelah thawaf, sholat 2 rakaat di Maqam Ibrahim dan sa'i (jika belum sa'i sebelumnya).", Arabic: "وَلْيَطَّوَّفُوا بِالْبَيْتِ الْعَتِيقِ", Transliteration: "Walyatthowwafuu bil baytil 'atiiq", TranslationText: "Dan hendaklah mereka melakukan thawaf sekeliling rumah yang tua itu.", Notes: "QS. Al-Hajj: 29. Tahallul tsani (lengkap) terjadi setelah thawaf ifadhah: semua larangan ihram berakhir.", IsWajib: true},
		{Type: model.ManasikTypeHaji, StepOrder: 9, Title: "Mabit di Mina dan Lontar 3 Jumrah (11-12/13 Dzulhijjah)", Description: "Kembali ke Mina, mabit pada malam 11 dan 12 Dzulhijjah (wajib). Pada siang 11 dan 12 Dzulhijjah (setelah zawal/tergelincir matahari), lempar 3 jumrah: Jumrah Ula (7 batu), Jumrah Wustha (7 batu), Jumrah Aqabah (7 batu). Boleh nafar awwal (pulang 12 Dzulhijjah sebelum Maghrib) atau nafar tsani (pulang 13 Dzulhijjah).", Arabic: "", Transliteration: "", TranslationText: "", Notes: "Urutan: dari jumrah yang paling kecil (Ula) → tengah (Wustha) → besar (Aqabah/Kubra). Lontar setelah zawal (tergelincir matahari) adalah waktu yang sah.", IsWajib: true},
		{Type: model.ManasikTypeHaji, StepOrder: 10, Title: "Thawaf Wada' (Thawaf Perpisahan)", Description: "Sebelum meninggalkan Makkah, wajib melakukan Thawaf Wada' (thawaf perpisahan) sebanyak 7 putaran. Ini adalah thawaf terakhir sebelum pulang ke tanah air. Setelah thawaf wada', tidak boleh tinggal lama di Makkah — segera berangkat.", Arabic: "", Transliteration: "", TranslationText: "", Notes: "Wanita haid/nifas dimaafkan dari thawaf wada' (HR. Bukhari No. 1755). Haji selesai.", IsWajib: true},
	}

	allSteps := append(umrahSteps, hajiSteps...)
	for i := range allSteps {
		db.Clauses(clause.OnConflict{
			Columns:   []clause.Column{{Name: "type"}, {Name: "step_order"}},
			DoUpdates: clause.AssignmentColumns([]string{"title", "description", "arabic", "transliteration", "translation", "notes", "is_wajib"}),
		}).Create(&allSteps[i])
	}
}
