package migrations

import (
	"github.com/agambondan/islamic-explorer/app/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

func getMasjidData() []model.Masjid {
	return []model.Masjid{
		{
			Name:        "Masjid Jami' Al-Barkah (Rodja)",
			Description: "Masjid utama sekaligus pusat Radio Rodja 756 AM. Siaran kajian ilmiah Islam berlandaskan Al-Qur'an dan As-Sunnah pemahaman Salafush Shalih.",
			Address:     "Jl. Pahlawan, Kp. Tengah RT 03/03, Cileungsi, Kabupaten Bogor, Jawa Barat 16820",
			District:    "Cileungsi",
			City:        "Bogor",
			Province:    "Jawa Barat",
			Latitude:    -6.3952078,
			Longitude:   106.9588901,
			Phone:       "021-22887131",
			Capacity:    2500,
			Facilities:  "Kajian sunnah rutin, live streaming Rodja, perpustakaan kitab, ruang wudhu, parkir",
			ImageURL:    "",
			Website:     "https://radiorodja.com",
			IsActive:    true,
		},
		{
			Name:        "Masjid Nur-Salma",
			Description: "Masjid yayasan Nur-Salma yang diasuh Ustadz Dr. Erwandi Tarmizi, MA. Fokus kajian tauhid, jual-beli riba, dan hadits arbain.",
			Address:     "Centennial Tower Lt. 22, Jl. Jenderal Gatot Subroto Kav. 24-25, Karet Semanggi, Setiabudi, Kota Jakarta Selatan, DKI Jakarta 12950",
			District:    "Setiabudi",
			City:        "Jakarta Selatan",
			Province:    "DKI Jakarta",
			Latitude:    -6.2301492,
			Longitude:   106.8208588,
			Phone:       "021-52901234",
			Capacity:    1500,
			Facilities:  "Kajian sunnah, perpustakaan kitab kuning, ruang wudhu, kelas tahsin & tahfizh",
			ImageURL:    "",
			Website:     "https://nursalma.or.id",
			IsActive:    true,
		},
		{
			Name:        "Masjid Nurim Blok M",
			Description: "Masjid di pusat Blok M, pengajian rutin ahlussunnah waljama'ah yang ramai dikunjungi karyawan & mahasiswa sekitar Kebayoran.",
			Address:     "Jl. Wolter Monginsidi No.71, Kebayoran Baru, Kota Jakarta Selatan, DKI Jakarta 12180",
			District:    "Kebayoran Baru",
			City:        "Jakarta Selatan",
			Province:    "DKI Jakarta",
			Latitude:    -6.2397,
			Longitude:   106.8058,
			Phone:       "021-7206123",
			Capacity:    1800,
			Facilities:  "Kajian sunnah pekanan, kelas bahasa Arab, wudhu & parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Sunda Kelapa",
			Description: "Pusat dakwah dan kajian sunnah di kawasan Menteng. Dipimpin Ustadz Dudi Muttaqien dan asatidzah salaf lainnya.",
			Address:     "Jl. Taman Sunda Kelapa No.16, Menteng, Kota Jakarta Pusat, DKI Jakarta 10310",
			District:    "Menteng",
			City:        "Jakarta Pusat",
			Province:    "DKI Jakarta",
			Latitude:    -6.2012984,
			Longitude:   106.8322571,
			Phone:       "021-31934261",
			Capacity:    4000,
			Facilities:  "Kajian rutin, perpustakaan, aula, klinik dhuafa, parkir",
			ImageURL:    "",
			Website:     "https://masjidsundakelapa.id",
			IsActive:    true,
		},
		{
			Name:        "Masjid Al-Ikhlas Cipete",
			Description: "Salah satu pusat kajian ilmiah dan tadabbur Qur'an teraktif di Cipete-Cilandak, salaf-affiliated.",
			Address:     "Jl. Cipete III No.3, Cipete Selatan, Cilandak, Kota Jakarta Selatan, DKI Jakarta 12410",
			District:    "Cilandak",
			City:        "Jakarta Selatan",
			Province:    "DKI Jakarta",
			Latitude:    -6.2789206,
			Longitude:   106.7997904,
			Phone:       "021-7690123",
			Capacity:    2500,
			Facilities:  "Kajian sunnah rutin, streaming YouTube/Audio, perpustakaan, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Baitussalam Billy Moon",
			Description: "Masjid kajian sunnah tematik di kawasan Duren Sawit dengan pengajian keluarga dan pemuda aktif.",
			Address:     "Komplek Billy Moon, Pondok Kelapa, Duren Sawit, Kota Jakarta Timur, DKI Jakarta 13450",
			District:    "Duren Sawit",
			City:        "Jakarta Timur",
			Province:    "DKI Jakarta",
			Latitude:    -6.2480321,
			Longitude:   106.9291752,
			Phone:       "021-8645123",
			Capacity:    3000,
			Facilities:  "Kajian sunnah tematik, AC, perpustakaan, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Jami' Imam Asy-Syafi'i BSD",
			Description: "Masjid jami ahlussunnah di kawasan BSD City, dikenal dengan kajian hadits arbain dan fikih perbandingan madzhab.",
			Address:     "Jl. Kalimantan, BSD City, Serpong, Kota Tangerang Selatan, Banten 15310",
			District:    "Serpong",
			City:        "Tangerang Selatan",
			Province:    "Banten",
			Latitude:    -6.3006,
			Longitude:   106.6854,
			Phone:       "021-5371234",
			Capacity:    2000,
			Facilities:  "Kajian sunnah, perpustakaan, ruang wudhu, parkir luas",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Ar-Rohmah Cibubur",
			Description: "Masjid ahlussunnah di Cibubur, pengajian keluarga dan remaja aktif dengan tema tarbiyah dan aqidah.",
			Address:     "Komp. Kota Wisata Cibubur, Nagrak, Gunung Putri, Kabupaten Bogor, Jawa Barat 16968",
			District:    "Gunung Putri",
			City:        "Bogor",
			Province:    "Jawa Barat",
			Latitude:    -6.3851121,
			Longitude:   106.9543061,
			Phone:       "021-84934567",
			Capacity:    1500,
			Facilities:  "Kajian keluarga, kelas tahfizh, wudhu, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Nurul Iman Blok M Square",
			Description: "Masjid kajian sunnah di lantai 7 Blok M Square, salah satu rujukan utama kajian manhaj salaf di Jakarta Selatan dengan kapasitas sekitar 6.000 jamaah, kajian rutin Jumat & Ahad diisi berbagai asatidz Ahlussunnah.",
			Address:     "Lt. 7, Blok M Square, Jl. Melawai 5 No. 3, Kebayoran Baru, Jakarta Selatan 12160",
			District:    "Kebayoran Baru",
			City:        "Jakarta Selatan",
			Province:    "DKI Jakarta",
			Latitude:    -6.2445743,
			Longitude:   106.8006164,
			Phone:       "",
			Capacity:    6000,
			Facilities:  "Ruang shalat ber-AC, area parkir mall, kajian rutin",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Baitul Muqarrabin",
			Description: "Masjid kajian sunnah di Banda Aceh dengan motto \"Memurnikan Akidah, Menebar Sunnah\". Kajian rutin harian ba'da Maghrib (Kitab Tauhid, Tadabbur Qur'an, Khudz Aqidatak, Adab & Akhlak) dan ba'da Subuh.",
			Address:     "Jl. Punge Blang Cut, Gampong Punge Blang Cut, Kec. Jaya Baru, Kota Banda Aceh, Aceh 23116",
			District:    "Jaya Baru",
			City:        "Banda Aceh",
			Province:    "Aceh",
			Latitude:    5.5450334,
			Longitude:   95.3055301,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Kajian rutin harian, area wudhu, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Raya Al-Mashun Medan",
			Description: "Masjid utama peninggalan Kesultanan Deli, dibangun 1906-1909 di kompleks Istana Maimun. Memadukan gaya arsitektur Timur Tengah, India, dan Spanyol, dibiayai antara lain oleh Kesultanan Deli dan pengusaha Tjong A Fie.",
			Address:     "Jl. Masjid Raya, Kelurahan Aur, Kec. Medan Maimun, Kota Medan, Sumatera Utara",
			District:    "Medan Maimun",
			City:        "Medan",
			Province:    "Sumatera Utara",
			Latitude:    3.575111,
			Longitude:   98.687321,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Halaman kompleks Istana Maimun, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Raya Sumatera Barat",
			Description: "Masjid raya Provinsi Sumatera Barat, dikenal sebagai Masjid Mahligai Minang karena atapnya berbentuk gonjong khas arsitektur Minangkabau. Dibangun 2007-2019 melalui sayembara desain yang dimenangkan arsitek Rizal Muslimin.",
			Address:     "Jl. Khatib Sulaiman, Alai Parak Kopi, Padang Utara, Kota Padang, Sumatera Barat 25173",
			District:    "Padang Utara",
			City:        "Padang",
			Province:    "Sumatera Barat",
			Latitude:    -0.924306,
			Longitude:   100.362611,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Halaman luas, area parkir, ukiran kaligrafi khas Minang",
			ImageURL:    "",
			Website:     "https://masjidraya.sumbarprov.go.id",
			IsActive:    true,
		},
		{
			Name:        "Masjid Raya An-Nur Pekanbaru",
			Description: "Masjid raya Provinsi Riau, dibangun 1963 dan diresmikan 1968, lalu direnovasi besar pada masa Gubernur Saleh Djasit hingga menjadi salah satu masjid termegah di Sumatera.",
			Address:     "Jl. Hangtuah, Sumahilang, Kec. Pekanbaru Kota, Kota Pekanbaru, Riau 28156",
			District:    "Pekanbaru Kota",
			City:        "Pekanbaru",
			Province:    "Riau",
			Latitude:    0.5267,
			Longitude:   101.4508,
			Phone:       "",
			Capacity:    4500,
			Facilities:  "Halaman luas, perpustakaan, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Raya Sultan Riau Penyengat",
			Description: "Masjid bersejarah peninggalan Kesultanan Riau-Lingga di Pulau Penyengat, mulai dibangun sekitar 1803 dan direnovasi 1832. Memiliki 13 kubah dan 17 menara-kubah kecil, dan berstatus cagar budaya nasional.",
			Address:     "Pulau Penyengat, Kota Tanjungpinang, Kepulauan Riau",
			District:    "Tanjungpinang Kota",
			City:        "Tanjungpinang",
			Province:    "Kepulauan Riau",
			Latitude:    0.929440,
			Longitude:   104.420390,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Situs cagar budaya, halaman masjid, dermaga penyeberangan",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Agung Al-Falah Jambi",
			Description: "Masjid agung Kota Jambi yang dikenal sebagai Masjid Seribu Tiang, dibangun 1971-1980 dan diresmikan Presiden Soeharto pada 29 September 1980.",
			Address:     "Jl. Sultan Thaha, Legok, Telanaipura, Kota Jambi, Jambi 36124",
			District:    "Telanaipura",
			City:        "Jambi",
			Province:    "Jambi",
			Latitude:    -1.594178,
			Longitude:   103.608285,
			Phone:       "",
			Capacity:    10000,
			Facilities:  "Halaman luas, perpustakaan, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Agung Sultan Mahmud Badaruddin I Jayo Wikramo Palembang",
			Description: "Masjid tertua dan terbesar di Palembang, dibangun Sultan Mahmud Badaruddin I sejak 1738-1748 di kawasan permukiman Melayu-Arab 19 Ilir. Arsitekturnya memadukan unsur Melayu, Tionghoa, dan Eropa.",
			Address:     "Jl. Jenderal Sudirman, 19 Ilir, Bukit Kecil, Kota Palembang, Sumatera Selatan",
			District:    "Bukit Kecil",
			City:        "Palembang",
			Province:    "Sumatera Selatan",
			Latitude:    -2.987480,
			Longitude:   104.759970,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Halaman kompleks bersejarah, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Jamik Pangkalpinang",
			Description: "Masjid tertua dan terbesar di Pangkalpinang, dibangun para penambang timah keturunan Melayu, Tionghoa, dan Arab pada 1936. Ornamennya memadukan ukiran kayu, keramik porselen, dan kubah berlapis emas.",
			Address:     "Jl. Masjid Jamik, Kec. Rangkui, Kota Pangkalpinang, Kepulauan Bangka Belitung 33684",
			District:    "Rangkui",
			City:        "Pangkal Pinang",
			Province:    "Kepulauan Bangka Belitung",
			Latitude:    -2.130821,
			Longitude:   106.109828,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Halaman masjid, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Jamik Bengkulu",
			Description: "Masjid bersejarah yang rekonstruksinya dirancang Ir. Soekarno saat menjalani masa pengasingan di Bengkulu, memadukan gaya arsitektur Jawa dan Sumatra. Ditetapkan sebagai cagar budaya nasional pada 2004.",
			Address:     "Jl. Jenderal Suprapto, Kel. Penggantungan, Kec. Gading Cempaka, Kota Bengkulu, Bengkulu",
			District:    "Gading Cempaka",
			City:        "Bengkulu",
			Province:    "Bengkulu",
			Latitude:    -3.792340,
			Longitude:   102.262240,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Situs cagar budaya, halaman masjid, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Agung Al-Furqon Bandar Lampung",
			Description: "Masjid agung Kota Bandar Lampung yang dibangun atas prakarsa Presiden Soekarno sejak 1951 dan diresmikan 1961, dengan menara setinggi 114 meter yang menjadi salah satu ikon kota.",
			Address:     "Jl. Diponegoro, Gulak Galik, Kec. Tlk. Betung Utara, Kota Bandar Lampung, Lampung 35212",
			District:    "Teluk Betung Utara",
			City:        "Bandar Lampung",
			Province:    "Lampung",
			Latitude:    -5.435162,
			Longitude:   105.246967,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Halaman luas, menara ikon kota, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Nurussunnah",
			Description: "Masjid kajian sunnah Semarang, pusat kegiatan Yayasan Islam Nurus Sunnah, disebut sebagai salah satu dari 7 Masjid Referensi Kajian Sunnah di Semarang. Kajian rutin harian ba'da Maghrib dan akhir pekan ba'da Subuh.",
			Address:     "Jl. Bulusan Utara Raya No. 12, RT 05 RW 03, Bulusan, Tembalang, Kota Semarang, Jawa Tengah 50277",
			District:    "Tembalang",
			City:        "Semarang",
			Province:    "Jawa Tengah",
			Latitude:    -7.0605962,
			Longitude:   110.4445674,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Kajian rutin, sekolah Islam, area wudhu, parkir",
			ImageURL:    "",
			Website:     "https://nurussunnah.sch.id",
			IsActive:    true,
		},
		{
			Name:        "Masjid Pogung Dalangan (MPD)",
			Description: "Masjid kajian sunnah dekat kampus UGM dengan tagline \"Menebar Kajian Sunnah\", pengajar tetap di antaranya Ustadz Ammi Nur Baits, B.A. dan Ustadz Muhammad Abduh Tuasikal, S.T., M.Sc. (pengasuh rumaysho.com/konsultasisyariah.com).",
			Address:     "Pogung Dalangan SIA XVI RT.11 RW.50, Sinduadi, Mlati, Kabupaten Sleman, DI Yogyakarta 55284",
			District:    "Mlati",
			City:        "Sleman",
			Province:    "DI Yogyakarta",
			Latitude:    -7.7604908,
			Longitude:   110.3733215,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Kajian rutin, asrama/mahad, area wudhu, parkir",
			ImageURL:    "",
			Website:     "https://mpd.or.id",
			IsActive:    true,
		},
		{
			Name:        "Masjid Darul Hijrah",
			Description: "Masjid kajian sunnah satu kompleks dengan STAI Ali bin Abi Thalib Surabaya, kampus ahlussunnah/salafi berizin resmi Ditjen Pendis (No. Dj.I/495/2007), jadi lokasi kajian dan kuliah rutin bermanhaj salaf.",
			Address:     "Jl. Sidotopo Kidul No. 51, Sidotopo, Kec. Semampir, Kota Surabaya, Jawa Timur 60152",
			District:    "Semampir",
			City:        "Surabaya",
			Province:    "Jawa Timur",
			Latitude:    -7.2321546,
			Longitude:   112.7515384,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Kajian rutin, kampus STAI, area wudhu, parkir",
			ImageURL:    "",
			Website:     "https://stai-ali.ac.id",
			IsActive:    true,
		},
		{
			Name:        "Masjid Agung Sudirman Denpasar",
			Description: "Masjid agung utama Kota Denpasar, berdiri sejak 1974 di dalam kawasan Kodam IX/Udayana namun tetap terbuka untuk umum. Dikenal karena memadukan unsur arsitektur Bali pada bangunannya.",
			Address:     "Jl. Slamet Riyadi No.1, Dauh Puri, Denpasar Barat, Kota Denpasar, Bali",
			District:    "Denpasar Barat",
			City:        "Denpasar",
			Province:    "Bali",
			Latitude:    -8.667030,
			Longitude:   115.219610,
			Phone:       "0361-264595",
			Capacity:    0,
			Facilities:  "Halaman masjid, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Raya Hubbul Wathan Islamic Center NTB",
			Description: "Masjid raya sekaligus Islamic Center Provinsi Nusa Tenggara Barat, dibangun 2010-2013. Memiliki 4 lantai, 5 kubah, dan 5 menara, salah satunya setinggi 99 meter melambangkan asmaul husna.",
			Address:     "Jl. Udayana No.1, Kelurahan Gomong, Kec. Selaparang, Kota Mataram, Nusa Tenggara Barat",
			District:    "Selaparang",
			City:        "Mataram",
			Province:    "Nusa Tenggara Barat",
			Latitude:    -8.579965,
			Longitude:   116.100609,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Halaman luas, menara pandang, perpustakaan, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Agung Al-Baitul Qadim Kupang",
			Description: "Masjid tertua di Pulau Timor, telah berdiri lebih dari dua abad di kawasan Kampung Airmata, Kota Kupang, dan menjadi salah satu pusat sejarah masuknya Islam di Nusa Tenggara Timur.",
			Address:     "Kelurahan Airmata, Kec. Kota Lama, Kota Kupang, Nusa Tenggara Timur",
			District:    "Kota Lama",
			City:        "Kupang",
			Province:    "Nusa Tenggara Timur",
			Latitude:    -10.165516,
			Longitude:   123.578035,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Situs bersejarah, halaman masjid, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Abu Bakar Ash-Shiddiq (Ma'had Taqribussunnah)",
			Description: "Masjid kajian sunnah di kawasan Pal Lima, Pontianak, terdaftar sebagai lokasi kajian rutin (Riyadhussalihin, Hadits, Sirah Nabawiyah) di darussalaf.or.id — rujukan situs salafi nasional.",
			Address:     "Kawasan Pal Lima, Kec. Pontianak Barat, Kota Pontianak, Kalimantan Barat 78114",
			District:    "Pontianak Barat",
			City:        "Pontianak",
			Province:    "Kalimantan Barat",
			Latitude:    -0.0248763,
			Longitude:   109.2886278,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Kajian rutin, area wudhu, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Raya Darussalam Palangka Raya",
			Description: "Masjid raya Provinsi Kalimantan Tengah, awalnya didirikan 1984 lalu direnovasi 2011-2014. Arsitekturnya memadukan gaya modern dan Arab dengan ornamen khas suku Dayak.",
			Address:     "Jl. George Obos, Menteng, Kec. Jekan Raya, Kota Palangka Raya, Kalimantan Tengah 73112",
			District:    "Jekan Raya",
			City:        "Palangka Raya",
			Province:    "Kalimantan Tengah",
			Latitude:    -2.230718,
			Longitude:   113.890220,
			Phone:       "",
			Capacity:    20000,
			Facilities:  "Halaman luas, ornamen khas Dayak, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Raya Sabilal Muhtadin Banjarmasin",
			Description: "Masjid raya Provinsi Kalimantan Selatan, dibangun 1974 dan diresmikan 1981 untuk menghormati ulama besar Syekh Muhammad Arsyad al-Banjari. Berdiri di bekas lokasi benteng kolonial Fort Van Tatas.",
			Address:     "Jl. Jenderal Sudirman, Antasan Besar, Kec. Banjarmasin Tengah, Kota Banjarmasin, Kalimantan Selatan 70114",
			District:    "Banjarmasin Tengah",
			City:        "Banjarmasin",
			Province:    "Kalimantan Selatan",
			Latitude:    -3.319012,
			Longitude:   114.591256,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Halaman luas di tengah kota, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Islamic Center Samarinda (Baitul Muttaqien)",
			Description: "Masjid raya Provinsi Kalimantan Timur di tepi Sungai Mahakam, salah satu masjid terbesar di Asia Tenggara dengan tujuh menara dan satu kubah besar.",
			Address:     "Jl. Slamet Riyadi No.1, Teluk Lerong Ulu, Kec. Sungai Kunjang, Kota Samarinda, Kalimantan Timur 75243",
			District:    "Sungai Kunjang",
			City:        "Samarinda",
			Province:    "Kalimantan Timur",
			Latitude:    -0.502440,
			Longitude:   117.119810,
			Phone:       "",
			Capacity:    10000,
			Facilities:  "Halaman tepi Sungai Mahakam, tujuh menara, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Baitul Izzah Islamic Center Tarakan",
			Description: "Masjid raya sekaligus Islamic Center terbesar di Provinsi Kalimantan Utara, diresmikan 2012 dan berdiri di atas lahan sekitar 30 hektare.",
			Address:     "Jl. Sei Sesayap, Kampung Empat, Kec. Tarakan Timur, Kota Tarakan, Kalimantan Utara 77112",
			District:    "Tarakan Timur",
			City:        "Tarakan",
			Province:    "Kalimantan Utara",
			Latitude:    3.298636,
			Longitude:   117.624100,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Lahan luas, halaman Islamic Center, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Agung Awwal Fathul Mubien Manado",
			Description: "Masjid tertua di Kota Manado, didirikan sekitar 1770 dan menjadi salah satu pusat penyebaran Islam pertama di kawasan Sulawesi Utara.",
			Address:     "Jl. Sultan Hasanuddin, Kelurahan Islam, Kec. Tuminting, Kota Manado, Sulawesi Utara 95122",
			District:    "Tuminting",
			City:        "Manado",
			Province:    "Sulawesi Utara",
			Latitude:    1.50655,
			Longitude:   124.84564,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Situs bersejarah, halaman masjid, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Umar Al-Faruq",
			Description: "Masjid pusat dakwah DPW Wahdah Islamiyah Gorontalo, satu kompleks dengan pesantren dan TPQ. Wahdah Islamiyah adalah ormas Islam beridentitas Ahlussunnah/salafi yang diakui akademis sebagai bagian gerakan salafi Indonesia.",
			Address:     "Jl. Pangeran Hidayat II, Kel. Liluwo, Kec. Kota Tengah, Kota Gorontalo, Gorontalo",
			District:    "Kota Tengah",
			City:        "Gorontalo",
			Province:    "Gorontalo",
			Latitude:    0.5642429,
			Longitude:   123.0523153,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Pesantren, TPQ, kajian rutin, parkir",
			ImageURL:    "",
			Website:     "https://wahdahgorontalo.or.id",
			IsActive:    true,
		},
		{
			Name:        "Masjid Al-Quds Islamic Center Wahdah Islamiyah",
			Description: "Masjid pusat dakwah DPW Wahdah Islamiyah Sulawesi Tengah, aktif menyelenggarakan kegiatan dakwah dan sosial. Wahdah Islamiyah adalah ormas Islam beridentitas Ahlussunnah/salafi yang diakui akademis sebagai bagian gerakan salafi Indonesia.",
			Address:     "Jl. Sungai Manonda, Kel. Duyu, Kec. Tatanga, Kota Palu, Sulawesi Tengah 94221",
			District:    "Tatanga",
			City:        "Palu",
			Province:    "Sulawesi Tengah",
			Latitude:    -0.9240105,
			Longitude:   119.8338031,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Kajian rutin, kegiatan sosial, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Agung Mamuju (Masjid Syuhada)",
			Description: "Masjid agung Kabupaten Mamuju, dikenal juga sebagai Masjid Syuhada, selesai dibangun dan mulai digunakan pada 2009 dengan empat menara setinggi 75 meter.",
			Address:     "Jl. KH Abdul Ahadi, Kabupaten Mamuju, Sulawesi Barat",
			District:    "Mamuju",
			City:        "Mamuju",
			Province:    "Sulawesi Barat",
			Latitude:    -2.6747476,
			Longitude:   118.8862879,
			Phone:       "",
			Capacity:    10000,
			Facilities:  "Empat menara, halaman luas, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Al-Markaz Al-Islami Makassar",
			Description: "Masjid raya Provinsi Sulawesi Selatan yang dibangun atas prakarsa Jenderal M. Jusuf pada 1994-1996, salah satu pusat kegiatan keislaman terbesar di Indonesia Timur.",
			Address:     "Jl. Masjid Raya, Timungan Lompoa, Kec. Bontoala, Kota Makassar, Sulawesi Selatan",
			District:    "Bontoala",
			City:        "Makassar",
			Province:    "Sulawesi Selatan",
			Latitude:    -5.129989,
			Longitude:   119.426323,
			Phone:       "",
			Capacity:    10000,
			Facilities:  "Halaman luas, perpustakaan, aula serbaguna, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Al-Alam Kendari",
			Description: "Masjid terapung ikon Kota Kendari yang berdiri di atas perairan Teluk Kendari, mulai dibangun 2010 dan diresmikan 2018, dengan empat menara terinspirasi Burj Al Arab Dubai.",
			Address:     "Teluk Kendari, Kelurahan Lalolara, Kec. Kambu, Kota Kendari, Sulawesi Tenggara",
			District:    "Kambu",
			City:        "Kendari",
			Province:    "Sulawesi Tenggara",
			Latitude:    -4.015152,
			Longitude:   122.530309,
			Phone:       "",
			Capacity:    10000,
			Facilities:  "Masjid terapung di tepi teluk, plaza terbuka, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Raya Al-Fatah Ambon",
			Description: "Masjid raya terbesar di Provinsi Maluku, dibangun 1979, dikenal sebagai simbol toleransi dan kerukunan antarumat di Kota Ambon.",
			Address:     "Jl. Sultan Babullah, Honipopu, Kec. Sirimau, Kota Ambon, Maluku 97123",
			District:    "Sirimau",
			City:        "Ambon",
			Province:    "Maluku",
			Latitude:    -3.693372,
			Longitude:   128.176613,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Halaman luas, tujuh pintu masuk, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Sultan Ternate",
			Description: "Masjid peninggalan Kesultanan Ternate, kesultanan Islam pertama di kawasan timur Nusantara sejak akhir abad ke-15. Dibangun dari susunan batu dengan bahan perekat getah pohon kalumpang, kini berstatus cagar budaya.",
			Address:     "Jl. Sultan Khairun, Kelurahan Soa Sio, Kec. Ternate Utara, Kota Ternate, Maluku Utara 97711",
			District:    "Ternate Utara",
			City:        "Ternate",
			Province:    "Maluku Utara",
			Latitude:    0.807350,
			Longitude:   127.379671,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Situs cagar budaya, kompleks Kedaton Kesultanan Ternate, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
		{
			Name:        "Masjid Raya Baiturrahim Jayapura",
			Description: "Masjid raya Provinsi Papua, dibangun 1971 dan direnovasi sejak 2006, menjadi salah satu ikon umat Islam di Tanah Papua.",
			Address:     "Jl. Jenderal Ahmad Yani, Gurabesi, Kec. Jayapura Utara, Kota Jayapura, Papua 99221",
			District:    "Jayapura Utara",
			City:        "Jayapura",
			Province:    "Papua",
			Latitude:    -2.547561,
			Longitude:   140.692809,
			Phone:       "",
			Capacity:    0,
			Facilities:  "Halaman masjid, parkir",
			ImageURL:    "",
			Website:     "",
			IsActive:    true,
		},
	}
}

func getRadioIslamicData() []model.RadioIslamic {
	return []model.RadioIslamic{
		{
			Name:        "Radio Rodja 756 AM",
			Frequency:   "756 AM",
			City:        "Jakarta",
			Province:    "DKI Jakarta",
			StreamURL:   "https://live2.radiorodja.com/rodja.mp3",
			Description: "Radio Menebar Cahaya Sunnah. Siaran kajian ilmiah Islam berlandaskan Al-Qur'an dan As-Sunnah pemahaman Salafush Shalih.",
			LogoURL:     "",
			Website:     "https://radiorodja.com",
			IsActive:    true,
			Tags:        "kajian,sunnah,salaf,ceramah,bahasa-arab,tanya-jawab",
		},
		{
			Name:        "Radio Silaturahim (Rasil) 720 AM",
			Frequency:   "720 AM",
			City:        "Jakarta",
			Province:    "DKI Jakarta",
			StreamURL:   "https://ssg.streamingmurah.com:9300/;",
			Description: "Untuk Islam yang Satu. Radio dakwah, berita Islam terkini, dialog kebangsaan, dan kesehatan.",
			LogoURL:     "",
			Website:     "https://radiosilaturahim.com",
			IsActive:    true,
			Tags:        "dakwah,berita,dialog,kesehatan,silaturahim",
		},
		{
			Name:        "Radio Muadz Jakarta & Kendari",
			Frequency:   "Streaming / Relay",
			City:        "Jakarta",
			Province:    "DKI Jakarta",
			StreamURL:   "https://radioislamindonesia.com/radiomuadz.mp3",
			Description: "Radio dakwah Ahlussunnah wal Jama'ah menyiarkan kajian fiqih, tafsir, aqidah, dan murottal Al-Qur'an 24 jam.",
			LogoURL:     "",
			Website:     "https://radiomuadz.com",
			IsActive:    true,
			Tags:        "murottal,kajian,aqidah,fiqih,sunnah",
		},
		{
			Name:        "Radio Tarbiyah Sunnah Bandung (1476 AM)",
			Frequency:   "1476 AM",
			City:        "Bandung",
			Province:    "Jawa Barat",
			StreamURL:   "https://radioislamindonesia.com/tarbiyah.mp3",
			Description: "Radio kajian sunnah asuhan Ustadz Abu Haidar As-Sundawy, Ustadz Yazid Jawas, dan asatidzah lainnya.",
			LogoURL:     "",
			Website:     "https://tarbiyahsunnah.com",
			IsActive:    true,
			Tags:        "kajian,sunnah,tarbiyah,tazkiyatun-nufus",
		},
		{
			Name:        "Radio Muslim Jogja (1467 AM)",
			Frequency:   "1467 AM",
			City:        "Yogyakarta",
			Province:    "DI Yogyakarta",
			StreamURL:   "https://streaming.radiomuslim.com/;stream/1",
			Description: "Memurnikan Aqidah Menebarkan Sunnah. Radio dakwah komunitas mahasiswa dan masyarakat Jogja.",
			LogoURL:     "",
			Website:     "https://radiomuslim.com",
			IsActive:    true,
			Tags:        "mahasiswa,kajian,aqidah,sunnah,jogja",
		},
		{
			Name:        "Radio Suara Al-Iman Surabaya (846 AM)",
			Frequency:   "846 AM",
			City:        "Surabaya",
			Province:    "Jawa Timur",
			StreamURL:   "https://radioislamindonesia.com/aliman.mp3",
			Description: "Sarana Menyapa Hati dengan Sunnah. Radio dakwah Jawa Timur berpusat di STDI Imam Syafi'i.",
			LogoURL:     "",
			Website:     "https://suaraaliman.com",
			IsActive:    true,
			Tags:        "kajian,surabaya,sunnah,fiqih",
		},
		{
			Name:        "Radio Fajri FM 99.3 FM (Bogor-Jakarta)",
			Frequency:   "99.3 FM",
			City:        "Bogor",
			Province:    "Jawa Barat",
			StreamURL:   "https://radio.mitradio.com/listen/fajrifm/radio.mp3",
			Description: "Suara Kebangkitan Islam. Menjangkau wilayah Bogor, Depok, dan sebagian Jakarta.",
			LogoURL:     "",
			Website:     "https://fajrifm.com",
			IsActive:    true,
			Tags:        "dakwah,bogor,jakarta,keluarga-islami",
		},
		{
			Name:        "Radio Hang FM 106.0 FM (Batam-Kepri)",
			Frequency:   "106.0 FM",
			City:        "Batam",
			Province:    "Kepulauan Riau",
			StreamURL:   "https://icecast.surau.tv/hangfm",
			Description: "Radio Sunnah tertua di Kepulauan Riau menjangkau Batam, Singapura, dan Johor Bahru Malaysia.",
			LogoURL:     "",
			Website:     "https://hangfm.id",
			IsActive:    true,
			Tags:        "sunnah,batam,singapura,serumpun",
		},
		{
			Name:        "Radio Kita FM 94.3 FM (Cirebon)",
			Frequency:   "94.3 FM",
			City:        "Cirebon",
			Province:    "Jawa Barat",
			StreamURL:   "https://broadcast.yufid.com/listen/radio_sunnah_cirebon/kitafm",
			Description: "Menebar Sunnah Membangun Umat di wilayah Ciayumajakuning.",
			LogoURL:     "",
			Website:     "https://radiokitafm.com",
			IsActive:    true,
			Tags:        "sunnah,cirebon,pantura",
		},
		{
			Name:        "Quran Stream Radio 24 Jam",
			Frequency:   "Digital Stream",
			City:        "Nasional",
			Province:    "Indonesia",
			StreamURL:   "",
			Description: "Lantunan Murottal Al-Qur'an 30 Juz 24 jam nonstop dari para Qari Masyhur dunia.",
			LogoURL:     "",
			Website:     "",
			IsActive:    true,
			Tags:        "murottal,quran,tilawah,24jam,tanpa-jeda",
		},
	}
}

func seedMasjids() []model.Masjid {
	return getMasjidData()
}

func seedRadioIslamic() []model.RadioIslamic {
	return getRadioIslamicData()
}

// retiredMasjidNames are landmark entries replaced on 2026-09-12 after a
// manhaj audit found them tied to traditions considered bid'ah under strict
// salafi criteria (routine maulid akbar, tarekat sufi ties, adat rituals) —
// see docs/reviews/2026-09-12-audit-manhaj-masjid-landmark.md. OnConflict
// below matches on `name`, so a rename alone would leave these as orphaned
// rows instead of being replaced; delete them explicitly first.
var retiredMasjidNames = []string{
	"Masjid Istiqlal",
	"Masjid Raya Baiturrahman Banda Aceh",
	"Masjid Jami' Sultan Syarif Abdurrahman Pontianak",
	"Masjid Gedhe Kauman Yogyakarta",
	"Masjid Nasional Al-Akbar Surabaya",
	"Masjid Agung Jawa Tengah",
	"Masjid Agung Baiturrahim Gorontalo",
	"Masjid Raya Baitul Khairaat Provinsi Sulawesi Tengah",
}

func SeedMasjids(db *gorm.DB) {
	db.Where("name IN ?", retiredMasjidNames).Delete(&model.Masjid{})

	masjids := getMasjidData()
	for _, m := range masjids {
		_ = db.Clauses(clause.OnConflict{
			Columns:   []clause.Column{{Name: "name"}},
			DoUpdates: clause.AssignmentColumns([]string{"description", "address", "district", "city", "province", "latitude", "longitude", "phone", "capacity", "facilities", "website", "is_active"}),
		}).Create(&m).Error
	}
}

func SeedRadioIslamic(db *gorm.DB) {
	radios := getRadioIslamicData()
	for _, r := range radios {
		_ = db.Clauses(clause.OnConflict{
			Columns:   []clause.Column{{Name: "name"}},
			DoUpdates: clause.AssignmentColumns([]string{"frequency", "city", "province", "stream_url", "description", "website", "is_active", "tags"}),
		}).Create(&r).Error
	}
}
