import { StyleSheet } from "react-native";
import { arabicTypography } from "../styles/arabicTypography";
import { colors, radius, spacing } from "../theme";

const WEB_APP_EXPLORE_BG = "#020617";
const WEB_APP_EXPLORE_SURFACE = "#111827";
const WEB_APP_EXPLORE_BORDER = "#243044";
const WEB_APP_EXPLORE_ACCENT = "#34d399";
const WEB_APP_EXPLORE_MUTED = "#94a3b8";

export const styles = StyleSheet.create({
    backToExplore: {
        alignItems: "center",
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        justifyContent: "center",
        marginBottom: spacing.md,
        minHeight: 42,
    },
    backToExploreText: {
        color: colors.primary,
        fontSize: 12,
        fontWeight: "900",
    },
    webAppCatalogRoot: {
        backgroundColor: WEB_APP_EXPLORE_BG,
        flex: 1,
    },
    webAppCatalogContent: {
        backgroundColor: WEB_APP_EXPLORE_BG,
        flexGrow: 1,
        padding: spacing.md,
        paddingBottom: spacing.xl,
    },
    webAppCatalogHero: {
        backgroundColor: WEB_APP_EXPLORE_SURFACE,
        borderColor: WEB_APP_EXPLORE_BORDER,
        borderRadius: radius.md,
        borderWidth: 1,
        padding: spacing.md,
    },
    webAppCatalogEyebrow: {
        color: WEB_APP_EXPLORE_ACCENT,
        fontSize: 11,
        fontWeight: "900",
        letterSpacing: 0,
        marginBottom: spacing.xs,
    },
    webAppCatalogTitle: {
        color: "#f8fafc",
        fontSize: 28,
        fontWeight: "900",
        letterSpacing: 0,
        lineHeight: 34,
    },
    webAppCatalogSubtitle: {
        color: WEB_APP_EXPLORE_MUTED,
        fontSize: 13,
        lineHeight: 20,
        marginTop: spacing.xs,
    },
    webAppCatalogSearch: {
        backgroundColor: "#1e293b",
        borderColor: WEB_APP_EXPLORE_ACCENT,
        borderRadius: 12,
        borderWidth: 2,
        justifyContent: "center",
        marginTop: spacing.md,
        minHeight: 46,
        paddingHorizontal: spacing.md,
    },
    webAppCatalogInput: {
        color: "#e2e8f0",
        fontSize: 14,
        minHeight: 42,
        padding: 0,
    },
    webAppBookmarksRoot: {
        backgroundColor: WEB_APP_EXPLORE_BG,
        flex: 1,
    },
    webAppBookmarksContent: {
        backgroundColor: WEB_APP_EXPLORE_BG,
        flexGrow: 1,
        padding: spacing.md,
        paddingBottom: spacing.xl,
    },
    webAppBookmarksHeader: {
        backgroundColor: WEB_APP_EXPLORE_SURFACE,
        borderColor: WEB_APP_EXPLORE_BORDER,
        borderRadius: radius.md,
        borderWidth: 1,
        padding: spacing.md,
    },
    webAppBookmarksBack: {
        alignSelf: "flex-start",
        backgroundColor: "#1e293b",
        borderColor: WEB_APP_EXPLORE_BORDER,
        borderRadius: 999,
        borderWidth: 1,
        marginBottom: spacing.md,
        minHeight: 34,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.xs,
    },
    webAppBookmarksBackText: {
        color: "#d1fae5",
        fontSize: 12,
        fontWeight: "900",
    },
    webAppBookmarksTitleRow: {
        alignItems: "flex-start",
        flexDirection: "row",
        gap: spacing.sm,
        justifyContent: "space-between",
        marginTop: spacing.xs,
    },
    webAppBookmarksCount: {
        backgroundColor: "#1e293b",
        borderColor: WEB_APP_EXPLORE_BORDER,
        borderRadius: 999,
        borderWidth: 1,
        color: WEB_APP_EXPLORE_MUTED,
        fontSize: 11,
        fontWeight: "900",
        overflow: "hidden",
        paddingHorizontal: spacing.sm,
        paddingVertical: 5,
    },
    webAppBookmarksError: {
        backgroundColor: "#3f1d1d",
        borderColor: "#7f1d1d",
        borderRadius: radius.md,
        borderWidth: 1,
        color: "#fecaca",
        fontSize: 13,
        fontWeight: "800",
        lineHeight: 18,
        marginTop: spacing.md,
        padding: spacing.md,
    },
    webAppBookmarksState: {
        alignItems: "center",
        backgroundColor: WEB_APP_EXPLORE_SURFACE,
        borderColor: WEB_APP_EXPLORE_BORDER,
        borderRadius: radius.md,
        borderWidth: 1,
        gap: spacing.sm,
        justifyContent: "center",
        marginTop: spacing.md,
        minHeight: 130,
        padding: spacing.md,
    },
    webAppBookmarksStateText: {
        color: WEB_APP_EXPLORE_MUTED,
        fontSize: 13,
        fontWeight: "800",
    },
    webAppBookmarksEmpty: {
        alignItems: "center",
        backgroundColor: WEB_APP_EXPLORE_SURFACE,
        borderColor: WEB_APP_EXPLORE_BORDER,
        borderRadius: radius.md,
        borderWidth: 1,
        justifyContent: "center",
        marginTop: spacing.md,
        minHeight: 180,
        padding: spacing.lg,
    },
    webAppBookmarksEmptyTitle: {
        color: "#f8fafc",
        fontSize: 16,
        fontWeight: "900",
        marginTop: spacing.sm,
    },
    webAppBookmarksEmptyText: {
        color: WEB_APP_EXPLORE_MUTED,
        fontSize: 13,
        lineHeight: 20,
        marginTop: spacing.xs,
        textAlign: "center",
    },
    webAppBookmarksGroups: {
        gap: spacing.md,
        marginTop: spacing.md,
    },
    webAppBookmarksGroup: {
        gap: spacing.sm,
    },
    webAppBookmarksGroupHeader: {
        alignItems: "center",
        flexDirection: "row",
        gap: spacing.sm,
        justifyContent: "space-between",
        paddingHorizontal: 2,
    },
    webAppBookmarksGroupTitle: {
        color: "#cbd5e1",
        fontSize: 12,
        fontWeight: "900",
        letterSpacing: 0,
        textTransform: "uppercase",
    },
    webAppBookmarksGroupCount: {
        color: WEB_APP_EXPLORE_MUTED,
        fontSize: 12,
        fontWeight: "900",
    },
    webAppBookmarkCard: {
        backgroundColor: WEB_APP_EXPLORE_SURFACE,
        borderColor: WEB_APP_EXPLORE_BORDER,
        borderRadius: radius.md,
        borderWidth: 1,
        flexDirection: "row",
        minHeight: 118,
        overflow: "hidden",
    },
    webAppBookmarkStripe: {
        backgroundColor: WEB_APP_EXPLORE_ACCENT,
        width: 4,
    },
    webAppBookmarkBody: {
        flex: 1,
        minWidth: 0,
        padding: spacing.md,
    },
    webAppBookmarkHeader: {
        alignItems: "center",
        flexDirection: "row",
        gap: spacing.sm,
        justifyContent: "space-between",
        marginBottom: spacing.xs,
    },
    webAppBookmarkType: {
        color: WEB_APP_EXPLORE_ACCENT,
        fontSize: 11,
        fontWeight: "900",
        letterSpacing: 0,
        textTransform: "uppercase",
    },
    webAppBookmarkRef: {
        color: WEB_APP_EXPLORE_MUTED,
        fontSize: 11,
        fontWeight: "800",
    },
    webAppBookmarkTitle: {
        color: "#f8fafc",
        fontSize: 15,
        fontWeight: "900",
        lineHeight: 20,
    },
    webAppBookmarkText: {
        color: "#cbd5e1",
        fontSize: 13,
        lineHeight: 19,
        marginTop: spacing.xs,
    },
    webAppBookmarkSlug: {
        color: WEB_APP_EXPLORE_MUTED,
        fontSize: 12,
        fontWeight: "800",
        marginTop: spacing.xs,
    },
    webAppBookmarkFooter: {
        alignItems: "center",
        flexDirection: "row",
        gap: spacing.sm,
        justifyContent: "space-between",
        marginTop: spacing.md,
    },
    webAppBookmarkHint: {
        color: WEB_APP_EXPLORE_MUTED,
        flex: 1,
        fontSize: 12,
        fontWeight: "800",
    },
    webAppBookmarkManage: {
        backgroundColor: "#1e293b",
        borderColor: WEB_APP_EXPLORE_BORDER,
        borderRadius: 999,
        borderWidth: 1,
        minHeight: 30,
        paddingHorizontal: spacing.md,
        paddingVertical: 6,
    },
    webAppBookmarkManageText: {
        color: "#d1fae5",
        fontSize: 12,
        fontWeight: "900",
    },
    webAppNotesSearch: {
        backgroundColor: "#1e293b",
        borderColor: WEB_APP_EXPLORE_BORDER,
        borderRadius: 12,
        borderWidth: 1,
        justifyContent: "center",
        marginTop: spacing.md,
        minHeight: 46,
        paddingHorizontal: spacing.md,
    },
    webAppNotesList: {
        gap: spacing.md,
        marginTop: spacing.md,
    },
    webAppNotificationsContent: {
        backgroundColor: WEB_APP_EXPLORE_BG,
        flexGrow: 1,
        padding: spacing.md,
        paddingBottom: spacing.xl,
    },
    webAppNotificationsPanel: {
        backgroundColor: WEB_APP_EXPLORE_SURFACE,
        borderColor: WEB_APP_EXPLORE_BORDER,
        borderRadius: radius.md,
        borderWidth: 1,
        marginTop: spacing.md,
        overflow: "hidden",
        padding: spacing.sm,
    },
    webAppNoteCard: {
        backgroundColor: WEB_APP_EXPLORE_SURFACE,
        borderColor: WEB_APP_EXPLORE_BORDER,
        borderRadius: radius.md,
        borderWidth: 1,
        flexDirection: "row",
        gap: spacing.md,
        minHeight: 128,
        padding: spacing.md,
    },
    webAppNoteIcon: {
        alignItems: "center",
        backgroundColor: "#1e293b",
        borderColor: WEB_APP_EXPLORE_BORDER,
        borderRadius: 14,
        borderWidth: 1,
        height: 42,
        justifyContent: "center",
        width: 42,
    },
    webAppNoteBody: {
        flex: 1,
        minWidth: 0,
    },
    webAppNoteTags: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: spacing.xs,
        marginTop: spacing.sm,
    },
    webAppNoteTag: {
        backgroundColor: "#1e293b",
        borderColor: WEB_APP_EXPLORE_BORDER,
        borderRadius: 999,
        borderWidth: 1,
        color: "#cbd5e1",
        fontSize: 11,
        fontWeight: "800",
        overflow: "hidden",
        paddingHorizontal: spacing.sm,
        paddingVertical: 4,
    },
    webAppGoalsSummary: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: spacing.sm,
        marginTop: spacing.md,
    },
    webAppGoalSummaryPill: {
        alignItems: "center",
        backgroundColor: "#1e293b",
        borderColor: WEB_APP_EXPLORE_BORDER,
        borderRadius: 999,
        borderWidth: 1,
        flexDirection: "row",
        gap: spacing.xs,
        minHeight: 34,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.xs,
    },
    webAppGoalSummaryText: {
        color: "#cbd5e1",
        fontSize: 12,
        fontWeight: "900",
    },
    webAppGoalsList: {
        gap: spacing.md,
        marginTop: spacing.md,
    },
    webAppGoalCard: {
        backgroundColor: WEB_APP_EXPLORE_SURFACE,
        borderColor: WEB_APP_EXPLORE_BORDER,
        borderRadius: radius.md,
        borderWidth: 1,
        minHeight: 146,
        padding: spacing.md,
    },
    webAppGoalHeader: {
        alignItems: "flex-start",
        flexDirection: "row",
        gap: spacing.sm,
    },
    webAppGoalIcon: {
        alignItems: "center",
        backgroundColor: "#1e293b",
        borderColor: WEB_APP_EXPLORE_BORDER,
        borderRadius: 14,
        borderWidth: 1,
        height: 42,
        justifyContent: "center",
        width: 42,
    },
    webAppGoalTitleBlock: {
        flex: 1,
        minWidth: 0,
    },
    webAppGoalStatus: {
        backgroundColor: "rgba(52, 211, 153, 0.12)",
        borderColor: "rgba(52, 211, 153, 0.32)",
        borderRadius: 999,
        borderWidth: 1,
        color: WEB_APP_EXPLORE_ACCENT,
        fontSize: 11,
        fontWeight: "900",
        overflow: "hidden",
        paddingHorizontal: spacing.sm,
        paddingVertical: 4,
    },
    webAppGoalStatusDone: {
        backgroundColor: "#1f2937",
        borderColor: "#374151",
        color: "#d1d5db",
    },
    webAppGoalBody: {
        color: "#cbd5e1",
        fontSize: 13,
        lineHeight: 19,
        marginTop: spacing.sm,
    },
    webAppGoalProgressTrack: {
        backgroundColor: "#1f2937",
        borderRadius: 999,
        height: 8,
        marginTop: spacing.md,
        overflow: "hidden",
    },
    webAppGoalProgressFill: {
        backgroundColor: WEB_APP_EXPLORE_ACCENT,
        borderRadius: 999,
        height: "100%",
    },
    webAppGoalProgressFillDone: {
        backgroundColor: "#9ca3af",
    },
    webAppMuhasabahSummary: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: spacing.sm,
        marginTop: spacing.md,
    },
    webAppMuhasabahCard: {
        backgroundColor: WEB_APP_EXPLORE_SURFACE,
        borderColor: WEB_APP_EXPLORE_BORDER,
        borderRadius: radius.md,
        borderWidth: 1,
        minHeight: 136,
        padding: spacing.md,
    },
    webAppMuhasabahHeader: {
        alignItems: "flex-start",
        flexDirection: "row",
        gap: spacing.sm,
    },
    webAppMuhasabahTitleBlock: {
        flex: 1,
        minWidth: 0,
    },
    webAppMuhasabahMood: {
        backgroundColor: "rgba(52, 211, 153, 0.12)",
        borderColor: "rgba(52, 211, 153, 0.32)",
        borderRadius: 999,
        borderWidth: 1,
        color: WEB_APP_EXPLORE_ACCENT,
        fontSize: 11,
        fontWeight: "900",
        overflow: "hidden",
        paddingHorizontal: spacing.sm,
        paddingVertical: 4,
    },
    webAppMuhasabahText: {
        color: "#cbd5e1",
        fontSize: 14,
        lineHeight: 21,
        marginTop: spacing.md,
    },
    webAppHafalanCard: {
        backgroundColor: WEB_APP_EXPLORE_SURFACE,
        borderColor: WEB_APP_EXPLORE_BORDER,
        borderRadius: radius.md,
        borderWidth: 1,
        minHeight: 138,
        padding: spacing.md,
    },
    webAppHafalanStatus: {
        backgroundColor: "#1f2937",
        borderColor: "#374151",
        borderRadius: 999,
        borderWidth: 1,
        color: "#d1d5db",
        fontSize: 11,
        fontWeight: "900",
        overflow: "hidden",
        paddingHorizontal: spacing.sm,
        paddingVertical: 4,
    },
    webAppHafalanStatusDone: {
        backgroundColor: "rgba(52, 211, 153, 0.12)",
        borderColor: "rgba(52, 211, 153, 0.32)",
        color: WEB_APP_EXPLORE_ACCENT,
    },
    webAppHafalanStatusProgress: {
        backgroundColor: "rgba(245, 158, 11, 0.12)",
        borderColor: "rgba(245, 158, 11, 0.32)",
        color: "#fbbf24",
    },
    webAppHafalanProgressFill: {
        backgroundColor: "#f59e0b",
    },
    webAppHafalanProgressTrack: {
        backgroundColor: "#1f2937",
        borderRadius: 999,
        height: 8,
        marginTop: spacing.md,
        overflow: "hidden",
    },
    webAppMurojaahCard: {
        backgroundColor: WEB_APP_EXPLORE_SURFACE,
        borderColor: WEB_APP_EXPLORE_BORDER,
        borderRadius: radius.md,
        borderWidth: 1,
        minHeight: 126,
        padding: spacing.md,
    },
    webAppMurojaahStatus: {
        backgroundColor: "#1f2937",
        borderColor: "#374151",
        borderRadius: 999,
        borderWidth: 1,
        color: "#d1d5db",
        fontSize: 11,
        fontWeight: "900",
        maxWidth: 104,
        overflow: "hidden",
        paddingHorizontal: spacing.sm,
        paddingVertical: 4,
    },
    webAppMurojaahStatusUrgent: {
        backgroundColor: "rgba(248, 113, 113, 0.12)",
        borderColor: "rgba(248, 113, 113, 0.32)",
        color: "#fecaca",
    },
    webAppTilawahTodayPanel: {
        backgroundColor: "rgba(245, 158, 11, 0.12)",
        borderColor: "rgba(245, 158, 11, 0.32)",
        borderRadius: radius.md,
        borderWidth: 1,
        marginTop: spacing.md,
        padding: spacing.md,
    },
    webAppTilawahTodayPanelDone: {
        backgroundColor: "rgba(52, 211, 153, 0.12)",
        borderColor: "rgba(52, 211, 153, 0.32)",
    },
    webAppTilawahTodayTitle: {
        color: "#f8fafc",
        fontSize: 14,
        fontWeight: "900",
    },
    webAppTilawahTodayText: {
        color: "#cbd5e1",
        fontSize: 12,
        lineHeight: 18,
        marginTop: 4,
    },
    webAppTilawahCard: {
        backgroundColor: WEB_APP_EXPLORE_SURFACE,
        borderColor: WEB_APP_EXPLORE_BORDER,
        borderRadius: radius.md,
        borderWidth: 1,
        minHeight: 132,
        padding: spacing.md,
    },
    webAppTilawahPageChip: {
        backgroundColor: "rgba(52, 211, 153, 0.12)",
        borderColor: "rgba(52, 211, 153, 0.32)",
        borderRadius: 999,
        borderWidth: 1,
        color: WEB_APP_EXPLORE_ACCENT,
        fontSize: 11,
        fontWeight: "900",
        maxWidth: 104,
        overflow: "hidden",
        paddingHorizontal: spacing.sm,
        paddingVertical: 4,
    },
    webAppStatsHeroCard: {
        backgroundColor: "rgba(52, 211, 153, 0.12)",
        borderColor: "rgba(52, 211, 153, 0.32)",
        borderRadius: radius.md,
        borderWidth: 1,
        marginTop: spacing.md,
        padding: spacing.md,
    },
    webAppStatsHeroValue: {
        color: WEB_APP_EXPLORE_ACCENT,
        fontSize: 16,
        fontWeight: "900",
    },
    webAppStatsGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: spacing.sm,
        marginTop: spacing.md,
    },
    webAppStatsTile: {
        backgroundColor: WEB_APP_EXPLORE_SURFACE,
        borderColor: WEB_APP_EXPLORE_BORDER,
        borderRadius: radius.md,
        borderWidth: 1,
        flexBasis: "48%",
        flexGrow: 1,
        minHeight: 94,
        padding: spacing.md,
    },
    webAppStatsValue: {
        fontSize: 24,
        fontWeight: "900",
    },
    webAppStatsLabel: {
        color: WEB_APP_EXPLORE_MUTED,
        fontSize: 12,
        fontWeight: "700",
        lineHeight: 17,
        marginTop: spacing.xs,
    },
    webAppStatsProgressPanel: {
        backgroundColor: WEB_APP_EXPLORE_SURFACE,
        borderColor: WEB_APP_EXPLORE_BORDER,
        borderRadius: radius.md,
        borderWidth: 1,
        marginTop: spacing.md,
        padding: spacing.md,
    },
    webAppSectionTitle: {
        color: WEB_APP_EXPLORE_MUTED,
        fontSize: 11,
        fontWeight: "900",
        letterSpacing: 0,
    },
    webAppStatsProgressRows: {
        gap: spacing.sm,
        marginTop: spacing.md,
    },
    webAppStatsProgressRow: {
        alignItems: "center",
        backgroundColor: "#1e293b",
        borderColor: WEB_APP_EXPLORE_BORDER,
        borderRadius: radius.md,
        borderWidth: 1,
        flexDirection: "row",
        gap: spacing.sm,
        minHeight: 48,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
    },
    webAppStatsProgressLabel: {
        color: "#e5e7eb",
        flex: 1,
        fontSize: 13,
        fontWeight: "800",
    },
    webAppStatsProgressValue: {
        color: WEB_APP_EXPLORE_ACCENT,
        fontSize: 12,
        fontWeight: "900",
    },
    webAppStatsChartPanel: {
        backgroundColor: WEB_APP_EXPLORE_SURFACE,
        borderColor: WEB_APP_EXPLORE_BORDER,
        borderRadius: radius.md,
        borderWidth: 1,
        marginTop: spacing.md,
        padding: spacing.md,
    },
    webAppStatsChart: {
        alignItems: "flex-end",
        flexDirection: "row",
        gap: spacing.xs,
        height: 152,
        marginTop: spacing.md,
    },
    webAppStatsBarColumn: {
        alignItems: "center",
        flex: 1,
        gap: 5,
    },
    webAppStatsBarCount: {
        color: "#cbd5e1",
        fontSize: 11,
        fontWeight: "800",
    },
    webAppStatsBarTrack: {
        alignItems: "center",
        backgroundColor: "#1f2937",
        borderRadius: 999,
        height: 100,
        justifyContent: "flex-end",
        overflow: "hidden",
        width: "100%",
    },
    webAppStatsBarFill: {
        backgroundColor: "#475569",
        borderRadius: 999,
        width: "100%",
    },
    webAppStatsBarFillDone: {
        backgroundColor: WEB_APP_EXPLORE_ACCENT,
    },
    webAppStatsBarFillPartial: {
        backgroundColor: "#fbbf24",
    },
    webAppStatsBarLabel: {
        color: WEB_APP_EXPLORE_MUTED,
        fontSize: 10,
        fontWeight: "700",
    },
    webAppSurface: {
        backgroundColor: "#f8fafc",
        borderRadius: radius.md,
        padding: spacing.sm,
    },
    webAppDetailRoot: {
        backgroundColor: "#f8fafc",
        flex: 1,
    },
    webAppDetailContent: {
        backgroundColor: "#f8fafc",
        flexGrow: 1,
        padding: spacing.md,
        paddingBottom: spacing.xl,
    },
    webAppDetailHeader: {
        marginBottom: spacing.lg,
    },
    webAppDetailBack: {
        alignItems: "center",
        alignSelf: "flex-start",
        backgroundColor: "#ffffff",
        borderColor: "#d1fae5",
        borderRadius: 999,
        borderWidth: 1,
        flexDirection: "row",
        gap: spacing.xs,
        marginBottom: spacing.md,
        paddingHorizontal: spacing.sm,
        paddingVertical: 7,
    },
    webAppDetailBackText: {
        color: colors.primary,
        fontSize: 12,
        fontWeight: "900",
    },
    webAppDetailEyebrow: {
        color: colors.primary,
        fontSize: 11,
        fontWeight: "900",
        letterSpacing: 0,
        marginBottom: spacing.xs,
    },
    webAppDetailTitle: {
        color: "#0f172a",
        fontSize: 24,
        fontWeight: "900",
        lineHeight: 30,
    },
    webAppDetailSubtitle: {
        color: "#64748b",
        fontSize: 14,
        lineHeight: 21,
        marginTop: spacing.xs,
    },
    webAppZakatHistorySurface: {
        gap: spacing.md,
    },
    webAppZakatHistoryBack: {
        alignItems: "center",
        alignSelf: "flex-start",
        backgroundColor: "#ffffff",
        borderColor: "#d1fae5",
        borderRadius: 999,
        borderWidth: 1,
        flexDirection: "row",
        gap: spacing.xs,
        minHeight: 34,
        paddingHorizontal: spacing.sm,
        paddingVertical: 7,
    },
    webAppZakatHistoryBackText: {
        color: "#047857",
        fontSize: 12,
        fontWeight: "900",
    },
    webAppZakatHistoryHero: {
        alignItems: "center",
        marginBottom: spacing.xs,
        paddingTop: spacing.xs,
    },
    webAppZakatHistoryHeroIcon: {
        alignItems: "center",
        backgroundColor: "#d1fae5",
        borderRadius: radius.md,
        height: 56,
        justifyContent: "center",
        marginBottom: spacing.sm,
        width: 56,
    },
    webAppZakatHistoryTitle: {
        color: "#064e3b",
        fontSize: 24,
        fontWeight: "900",
        lineHeight: 30,
        textAlign: "center",
    },
    webAppZakatHistorySubtitle: {
        color: "#64748b",
        fontSize: 13,
        fontWeight: "700",
        lineHeight: 19,
        marginTop: spacing.xs,
        textAlign: "center",
    },
    webAppZakatHistoryStats: {
        flexDirection: "row",
        gap: spacing.sm,
    },
    webAppZakatHistoryStatCard: {
        backgroundColor: "#ffffff",
        borderColor: "#e2e8f0",
        borderRadius: radius.md,
        borderWidth: 1,
        flex: 1,
        padding: spacing.md,
    },
    webAppZakatHistoryStatValue: {
        color: "#047857",
        fontSize: 17,
        fontWeight: "900",
    },
    webAppZakatHistoryStatLabel: {
        color: "#64748b",
        fontSize: 11,
        fontWeight: "900",
        marginTop: 2,
        textTransform: "uppercase",
    },
    webAppZakatHistoryNotice: {
        backgroundColor: "#ecfdf5",
        borderColor: "#a7f3d0",
        borderRadius: radius.md,
        borderWidth: 1,
        color: "#047857",
        fontSize: 12,
        fontWeight: "800",
        lineHeight: 18,
        padding: spacing.md,
    },
    webAppZakatHistoryEmpty: {
        alignItems: "center",
        backgroundColor: "#ffffff",
        borderColor: "#e2e8f0",
        borderRadius: radius.md,
        borderWidth: 1,
        justifyContent: "center",
        minHeight: 140,
        padding: spacing.lg,
    },
    webAppZakatHistoryEmptyTitle: {
        color: "#0f172a",
        fontSize: 15,
        fontWeight: "900",
        textAlign: "center",
    },
    webAppZakatHistoryEmptyText: {
        color: "#64748b",
        fontSize: 12,
        fontWeight: "700",
        lineHeight: 18,
        marginTop: spacing.xs,
        textAlign: "center",
    },
    webAppZakatHistoryList: {
        gap: spacing.sm,
    },
    webAppZakatHistoryCard: {
        backgroundColor: "#ffffff",
        borderColor: "#e2e8f0",
        borderRadius: radius.md,
        borderWidth: 1,
        padding: spacing.md,
    },
    webAppZakatHistoryCardHeader: {
        alignItems: "flex-start",
        flexDirection: "row",
        gap: spacing.sm,
        justifyContent: "space-between",
        marginBottom: spacing.sm,
    },
    webAppZakatHistoryTypeRow: {
        alignItems: "center",
        flex: 1,
        flexDirection: "row",
        gap: spacing.sm,
        minWidth: 0,
    },
    webAppZakatHistoryIcon: {
        alignItems: "center",
        backgroundColor: "#ecfdf5",
        borderRadius: 999,
        height: 34,
        justifyContent: "center",
        width: 34,
    },
    webAppZakatHistoryIconText: {
        color: "#047857",
        fontSize: 10,
        fontWeight: "900",
    },
    webAppZakatHistoryTypeText: {
        flex: 1,
        minWidth: 0,
    },
    webAppZakatHistoryType: {
        color: "#0f172a",
        fontSize: 14,
        fontWeight: "900",
    },
    webAppZakatHistoryDate: {
        color: "#94a3b8",
        fontSize: 11,
        fontWeight: "700",
        marginTop: 2,
    },
    webAppZakatHistoryDelete: {
        alignItems: "center",
        minHeight: 32,
        justifyContent: "center",
        width: 32,
    },
    webAppZakatHistoryMeta: {
        gap: 3,
        minHeight: 16,
    },
    webAppZakatHistoryMetaText: {
        color: "#64748b",
        fontSize: 12,
        fontWeight: "700",
    },
    webAppZakatHistoryNote: {
        color: "#64748b",
        fontSize: 12,
        fontStyle: "italic",
        fontWeight: "700",
    },
    webAppZakatHistoryAmountRow: {
        alignItems: "flex-end",
        flexDirection: "row",
        gap: spacing.sm,
        justifyContent: "space-between",
        marginTop: spacing.md,
    },
    webAppZakatHistoryAmount: {
        color: "#047857",
        flex: 1,
        fontSize: 19,
        fontWeight: "900",
    },
    webAppZakatHistoryStatus: {
        borderRadius: 999,
        fontSize: 11,
        fontWeight: "900",
        overflow: "hidden",
        paddingHorizontal: spacing.sm,
        paddingVertical: 5,
    },
    webAppZakatHistoryStatusPaid: {
        backgroundColor: "#d1fae5",
        color: "#047857",
    },
    webAppZakatHistoryStatusUnpaid: {
        backgroundColor: "#fef3c7",
        color: "#b45309",
    },
    searchRow: {
        flexDirection: "row",
        gap: spacing.sm,
    },
    input: {
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        color: colors.ink,
        flex: 1,
        fontSize: 14,
        marginBottom: spacing.sm,
        minHeight: 44,
        paddingHorizontal: spacing.md,
    },
    textArea: {
        minHeight: 86,
        paddingTop: spacing.sm,
        textAlignVertical: "top",
    },
    arabicInput: {
        ...arabicTypography.input,
    },
    inputLabel: {
        color: colors.muted,
        fontSize: 12,
        fontWeight: "800",
        marginBottom: spacing.xs,
        marginTop: spacing.md,
    },
    wirdField: {
        flex: 1,
    },
    wirdGrid: {
        flexDirection: "row",
        gap: spacing.sm,
    },
    wirdGridItem: {
        flex: 1,
    },
    currencyField: {
        marginTop: spacing.md,
    },
    currencyInputShell: {
        alignItems: "center",
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        flexDirection: "row",
        minHeight: 46,
        paddingHorizontal: spacing.md,
    },
    currencyPrefix: {
        color: colors.primary,
        fontSize: 13,
        fontWeight: "900",
        marginRight: spacing.sm,
    },
    currencyInput: {
        color: colors.ink,
        flex: 1,
        fontSize: 15,
        fontWeight: "800",
        paddingVertical: spacing.sm,
    },
    primaryButton: {
        alignItems: "center",
        backgroundColor: colors.primary,
        borderRadius: radius.md,
        justifyContent: "center",
        marginBottom: spacing.sm,
        paddingHorizontal: spacing.md,
    },
    primaryButtonText: {
        color: "#ffffff",
        fontSize: 13,
        fontWeight: "900",
    },
    formActions: {
        flexDirection: "row",
        gap: spacing.sm,
        marginTop: spacing.sm,
    },
    formPrimaryButton: {
        flex: 1,
        minHeight: 42,
    },
    loginButton: {
        marginTop: spacing.md,
        minHeight: 42,
    },
    secondaryButton: {
        alignItems: "center",
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        justifyContent: "center",
        marginBottom: spacing.sm,
        minHeight: 42,
        paddingHorizontal: spacing.md,
    },
    secondaryButtonText: {
        color: colors.primary,
        fontSize: 13,
        fontWeight: "900",
    },
    disabledButton: {
        opacity: 0.6,
    },
    itemCard: {
        marginBottom: spacing.md,
    },
    tafsirCard: {
        marginBottom: spacing.md,
        paddingTop: spacing.md,
    },
    itemTitleBlock: {
        marginBottom: spacing.sm,
        minWidth: 0,
        paddingRight: 44,
    },
    itemTitle: {
        color: colors.ink,
        fontFamily: "serif",
        fontSize: 16,
        fontWeight: "900",
        lineHeight: 20,
    },
    itemMeta: {
        color: colors.primary,
        fontSize: 12,
        fontWeight: "900",
        lineHeight: 16,
        marginTop: 3,
    },
    itemActions: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: spacing.sm,
        marginTop: spacing.sm,
    },
    feedHeader: {
        alignItems: "center",
        flexDirection: "row",
        gap: spacing.sm,
        marginBottom: spacing.sm,
    },
    feedAvatar: {
        alignItems: "center",
        backgroundColor: colors.surfaceMuted,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        height: 38,
        justifyContent: "center",
        width: 38,
    },
    feedAvatarText: {
        color: colors.primary,
        fontSize: 13,
        fontWeight: "900",
    },
    feedTitleBlock: {
        flex: 1,
        minWidth: 0,
    },
    feedRefPanel: {
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        marginTop: spacing.md,
        padding: spacing.sm,
    },
    feedRefLabel: {
        color: colors.primary,
        fontSize: 11,
        fontWeight: "900",
        marginBottom: 2,
    },
    feedRefText: {
        color: colors.text,
        fontSize: 12,
        fontWeight: "800",
    },
    detailPanel: {
        borderTopColor: colors.faint,
        borderTopWidth: 1,
        marginTop: spacing.md,
        paddingTop: spacing.md,
    },
    detailTitle: {
        color: colors.ink,
        fontSize: 13,
        fontWeight: "900",
        marginBottom: spacing.sm,
    },
    detailLine: {
        color: colors.muted,
        fontSize: 12,
        lineHeight: 18,
        marginTop: spacing.xs,
    },
    detailActions: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: spacing.sm,
        marginTop: spacing.md,
    },
    detailCard: {
        marginBottom: spacing.md,
        padding: spacing.md,
    },
    detailArabic: {
        ...arabicTypography.large,
        color: colors.ink,
        marginBottom: spacing.md,
    },
    detailBody: {
        color: colors.text,
        fontSize: 15,
        lineHeight: 24,
    },
    detailTranslationBox: {
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        marginBottom: spacing.md,
        padding: spacing.md,
    },
    detailTranslation: {
        color: colors.text,
        fontSize: 14,
        lineHeight: 22,
    },
    detailTafsirPanel: {
        backgroundColor: colors.surfaceMuted,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        marginTop: spacing.md,
        padding: spacing.md,
    },
    detailMetaPanel: {
        borderTopColor: colors.faint,
        borderTopWidth: 1,
        marginTop: spacing.md,
        paddingTop: spacing.md,
    },
    libraryProgressPanel: {
        backgroundColor: colors.surface,
        borderColor: colors.faint,
        borderRadius: radius.lg,
        borderWidth: 1,
        marginBottom: spacing.md,
        padding: spacing.md,
    },
    librarySourcePanel: {
        backgroundColor: colors.surfaceMuted,
        borderColor: colors.faint,
        borderRadius: radius.lg,
        borderWidth: 1,
        marginBottom: spacing.md,
        padding: spacing.md,
    },
    libraryFilterPanel: {
        marginBottom: spacing.md,
    },
    libraryStatusRow: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: spacing.sm,
        marginBottom: spacing.sm,
    },
    libraryProgressBadgeRow: {
        alignItems: "center",
        alignSelf: "flex-start",
        backgroundColor: colors.surfaceMuted,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        flexDirection: "row",
        gap: spacing.sm,
        marginTop: spacing.sm,
        paddingHorizontal: spacing.sm,
        paddingVertical: 6,
    },
    libraryProgressBadgeText: {
        color: colors.primary,
        fontSize: 11,
        fontWeight: "900",
    },
    libraryProgressPageText: {
        color: colors.muted,
        fontSize: 11,
        fontWeight: "700",
    },
    commentsPanel: {
        borderTopColor: colors.faint,
        borderTopWidth: 1,
        marginTop: spacing.md,
        paddingTop: spacing.md,
    },
    commentsHeader: {
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "space-between",
    },
    commentRow: {
        alignItems: "flex-start",
        flexDirection: "row",
        gap: spacing.sm,
        marginTop: spacing.md,
    },
    commentAvatar: {
        alignItems: "center",
        backgroundColor: colors.surfaceMuted,
        borderColor: colors.faint,
        borderRadius: radius.sm,
        borderWidth: 1,
        height: 30,
        justifyContent: "center",
        width: 30,
    },
    commentAvatarText: {
        color: colors.primary,
        fontSize: 11,
        fontWeight: "900",
    },
    commentCopy: {
        flex: 1,
        minWidth: 0,
    },
    commentAuthor: {
        color: colors.ink,
        fontSize: 12,
        fontWeight: "900",
    },
    commentText: {
        color: colors.text,
        fontSize: 12,
        lineHeight: 18,
        marginTop: 2,
    },
    commentForm: {
        gap: spacing.sm,
        marginTop: spacing.md,
    },
    commentInput: {
        backgroundColor: colors.surface,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        color: colors.ink,
        fontSize: 13,
        minHeight: 70,
        padding: spacing.sm,
        textAlignVertical: "top",
    },
    commentSubmit: {
        alignItems: "center",
        backgroundColor: colors.primary,
        borderRadius: radius.md,
        justifyContent: "center",
        minHeight: 38,
    },
    commentSubmitDisabled: {
        opacity: 0.55,
    },
    commentSubmitText: {
        color: colors.onPrimary,
        fontSize: 12,
        fontWeight: "900",
    },
    arabic: {
        ...arabicTypography.body,
        color: colors.ink,
        marginBottom: spacing.sm,
    },
    tafsirArabic: {
        ...arabicTypography.body,
        color: colors.ink,
        marginBottom: spacing.md,
    },
    tafsirTranslationBox: {
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        marginBottom: spacing.md,
        padding: spacing.md,
    },
    tafsirTranslation: {
        color: colors.muted,
        fontSize: 13,
        lineHeight: 20,
    },
    tafsirPanel: {
        backgroundColor: colors.surfaceMuted,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        marginTop: spacing.sm,
        padding: spacing.md,
    },
    tafsirPanelSecondary: {
        backgroundColor: colors.bg,
    },
    tafsirSource: {
        color: colors.primary,
        fontSize: 11,
        fontWeight: "900",
        letterSpacing: 0,
        marginBottom: spacing.xs,
        textTransform: "uppercase",
    },
    tafsirSourceSecondary: {
        color: colors.ink,
    },
    tafsirText: {
        color: colors.text,
        fontSize: 14,
        lineHeight: 22,
    },
    cardReadMore: {
        color: colors.primary,
        fontSize: 12,
        fontWeight: "900",
        marginTop: spacing.sm,
    },
    body: {
        color: colors.text,
        fontSize: 14,
        lineHeight: 21,
    },
    answerRow: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: spacing.sm,
        marginTop: spacing.md,
    },
    answerButton: {
        alignItems: "center",
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        minHeight: 40,
        minWidth: 48,
        justifyContent: "center",
        paddingHorizontal: spacing.md,
    },
    answerButtonActive: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    answerText: {
        color: colors.text,
        fontSize: 12,
        fontWeight: "800",
    },
    answerTextActive: {
        color: "#ffffff",
    },
    surahSelector: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: spacing.sm,
        marginTop: spacing.md,
    },
    surahSearchInput: {
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.lg,
        borderWidth: 1,
        color: colors.text,
        fontSize: 14,
        marginTop: spacing.md,
        minHeight: 46,
        paddingHorizontal: spacing.md,
    },
    selectorHint: {
        color: colors.muted,
        fontSize: 12,
        lineHeight: 18,
        marginTop: spacing.sm,
    },
    surahChip: {
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
    },
    surahChipActive: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    surahChipText: {
        color: colors.text,
        fontSize: 11,
        fontWeight: "800",
    },
    surahChipTextActive: {
        color: "#ffffff",
    },
    counter: {
        alignItems: "center",
        backgroundColor: colors.surfaceMuted,
        borderRadius: radius.xl,
        justifyContent: "center",
        minHeight: 180,
    },
    counterNumber: {
        color: colors.primaryDark,
        fontSize: 64,
        fontWeight: "900",
    },
    counterLabel: {
        color: colors.primary,
        fontSize: 14,
        fontWeight: "800",
    },
    result: {
        color: colors.ink,
        fontSize: 14,
        fontWeight: "800",
        lineHeight: 22,
        marginBottom: spacing.sm,
    },
    resultPanel: {
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.lg,
        borderWidth: 1,
        marginTop: spacing.md,
        padding: spacing.md,
    },
    resultRow: {
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "space-between",
        gap: spacing.md,
        marginBottom: spacing.sm,
    },
    resultLabel: {
        color: colors.muted,
        flex: 1,
        fontSize: 12,
        fontWeight: "800",
    },
    resultLabelStrong: {
        color: colors.ink,
        flex: 1,
        fontSize: 13,
        fontWeight: "900",
    },
    resultValue: {
        color: colors.text,
        fontSize: 13,
        fontWeight: "800",
        textAlign: "right",
    },
    resultValueStrong: {
        color: colors.primary,
        fontSize: 16,
        fontWeight: "900",
        textAlign: "right",
    },
    resultDivider: {
        backgroundColor: colors.faint,
        height: 1,
        marginBottom: spacing.sm,
    },
    statusNote: {
        color: colors.muted,
        fontSize: 12,
        fontWeight: "700",
        lineHeight: 18,
    },
    statusNoteActive: {
        color: colors.primary,
    },
    statusNoteWarning: {
        color: colors.accent,
    },
    trackerList: {
        gap: spacing.sm,
        marginTop: spacing.md,
    },
    trackerRow: {
        alignItems: "center",
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        flexDirection: "row",
        gap: spacing.md,
        minHeight: 52,
        paddingHorizontal: spacing.md,
    },
    trackerLabel: {
        color: colors.muted,
        fontSize: 15,
        fontWeight: "700",
    },
    trackerLabelDone: {
        color: colors.primary,
        fontWeight: "800",
    },
    loader: {
        marginVertical: spacing.lg,
    },
    error: {
        color: colors.danger,
        fontSize: 13,
        fontWeight: "700",
        marginBottom: spacing.md,
    },
    empty: {
        color: colors.muted,
        fontSize: 13,
        marginBottom: spacing.md,
    },
    loadMoreFooter: {
        alignItems: "center",
        flexDirection: "row",
        gap: spacing.sm,
        justifyContent: "center",
        minHeight: 44,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
    },
    loadMoreText: {
        color: colors.primary,
        fontSize: 13,
        fontWeight: "900",
    },
    actionSheetRow: {
        alignItems: "center",
        borderRadius: radius.md,
        flexDirection: "row",
        padding: spacing.md,
    },
    actionSheetRowActive: {
        backgroundColor: colors.primary,
    },
    actionSheetIcon: {
        alignItems: "center",
        justifyContent: "center",
        width: 24,
    },
    actionSheetCopy: {
        flex: 1,
        marginLeft: spacing.md,
    },
    actionSheetTitle: {
        color: colors.ink,
        fontSize: 15,
        fontWeight: "700",
    },
    actionSheetTitleActive: {
        color: colors.onPrimary,
    },
    actionSheetSubtitle: {
        color: colors.muted,
        fontSize: 13,
        marginTop: 2,
    },
    actionSheetSubtitleActive: {
        color: colors.onPrimary,
        opacity: 0.8,
    },
    heirGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: spacing.sm,
        marginTop: spacing.sm,
    },
    heirItem: {
        alignItems: "center",
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        minWidth: 72,
        padding: spacing.sm,
    },
    heirLabel: {
        color: colors.muted,
        fontSize: 11,
        fontWeight: "800",
        marginBottom: 2,
    },
    heirCount: {
        color: colors.ink,
        fontSize: 20,
        fontWeight: "900",
    },
    heirActions: {
        flexDirection: "row",
        gap: 4,
        marginTop: 4,
    },
    heirButton: {
        alignItems: "center",
        backgroundColor: colors.primary,
        borderRadius: radius.sm,
        justifyContent: "center",
        minHeight: 28,
        minWidth: 28,
    },
    heirButtonDisabled: {
        opacity: 0.3,
    },
    heirButtonText: {
        color: "#ffffff",
        fontSize: 16,
        fontWeight: "900",
    },
    faraidhHistoryAmount: {
        color: colors.primary,
        fontSize: 15,
        fontWeight: "900",
    },
    asmaulHeader: {
        alignItems: "center",
        flexDirection: "row",
        gap: spacing.sm,
        marginTop: spacing.md,
    },
    asmaulArabic: {
        ...arabicTypography.centered,
        color: colors.ink,
        marginBottom: 4,
    },
    asmaulLatin: {
        color: colors.primary,
        fontSize: 14,
        fontWeight: "800",
        marginBottom: 2,
        textAlign: "center",
    },
    asmaulArti: {
        color: colors.muted,
        fontSize: 12,
        lineHeight: 18,
        textAlign: "center",
    },
    flashcard: {
        alignItems: "center",
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.lg,
        borderWidth: 1,
        justifyContent: "center",
        marginTop: spacing.md,
        minHeight: 250,
        padding: spacing.lg,
    },
    flashcardArabic: {
        ...arabicTypography.hero,
        color: colors.ink,
        marginBottom: spacing.sm,
    },
    flashcardHint: {
        color: colors.muted,
        fontSize: 12,
        fontWeight: "800",
        marginTop: spacing.md,
    },
    flashcardLatin: {
        color: colors.primary,
        fontSize: 18,
        fontWeight: "900",
        marginBottom: spacing.sm,
        textAlign: "center",
    },
    flashcardMeaning: {
        color: colors.text,
        fontSize: 15,
        fontWeight: "700",
        lineHeight: 22,
        marginTop: spacing.sm,
        textAlign: "center",
    },
    flashcardNumber: {
        color: colors.accent,
        fontSize: 12,
        fontWeight: "900",
        marginBottom: spacing.md,
        textTransform: "uppercase",
    },
    toggleRow: {
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "space-between",
        marginVertical: spacing.sm,
    },
    toggleLabel: {
        color: colors.ink,
        flex: 1,
        fontSize: 14,
    },
    faraidhHistoryCard: {
        alignItems: "center",
        backgroundColor: colors.surface,
        borderColor: colors.faint,
        borderRadius: 12,
        borderWidth: 1,
        flexDirection: "row",
        padding: spacing.sm,
    },
    badge: {
        backgroundColor: colors.surfaceMuted,
        borderRadius: 4,
        paddingHorizontal: 6,
        paddingVertical: 2,
    },
    badgeText: {
        color: colors.primary,
        fontSize: 11,
        fontWeight: "600",
    },
});
