import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from '../theme';

export const WEB_APP_PROFILE_BG = '#020617';
export const WEB_APP_PROFILE_SURFACE = '#111827';
export const WEB_APP_PROFILE_TILE = '#1e293b';
export const WEB_APP_PROFILE_BORDER = '#243044';
export const WEB_APP_PROFILE_ACCENT = '#34d399';
export const WEB_APP_PROFILE_MUTED = '#94a3b8';

export const styles = StyleSheet.create({
    flex: {
        flex: 1,
        backgroundColor: colors.bg,
    },
    webAppSurface: {
        backgroundColor: '#f8fafc',
        borderRadius: radius.md,
        padding: spacing.sm,
    },
    webAppProfileRoot: {
        backgroundColor: WEB_APP_PROFILE_BG,
        flex: 1,
    },
    webAppProfileContent: {
        backgroundColor: WEB_APP_PROFILE_BG,
        flexGrow: 1,
        padding: spacing.md,
        paddingBottom: spacing.xl,
    },
    webAppProfileHero: {
        alignItems: 'center',
        backgroundColor: WEB_APP_PROFILE_SURFACE,
        borderColor: WEB_APP_PROFILE_BORDER,
        borderRadius: radius.md,
        borderWidth: 1,
        padding: spacing.lg,
    },
    webAppAvatar: {
        alignItems: 'center',
        backgroundColor: '#059669',
        borderRadius: 34,
        height: 68,
        justifyContent: 'center',
        marginBottom: spacing.md,
        width: 68,
    },
    webAppAvatarText: {
        color: '#ffffff',
        fontSize: 22,
        fontWeight: '900',
    },
    webAppEyebrow: {
        color: WEB_APP_PROFILE_ACCENT,
        fontSize: 11,
        fontWeight: '900',
        letterSpacing: 0,
        marginBottom: 4,
    },
    webAppProfileName: {
        color: '#f8fafc',
        fontSize: 24,
        fontWeight: '900',
        letterSpacing: 0,
        textAlign: 'center',
    },
    webAppProfileEmail: {
        color: WEB_APP_PROFILE_MUTED,
        fontSize: 13,
        lineHeight: 19,
        marginTop: spacing.xs,
        textAlign: 'center',
    },
    webAppSettingsButton: {
        alignItems: 'center',
        backgroundColor: '#059669',
        borderRadius: 10,
        flexDirection: 'row',
        gap: spacing.xs,
        justifyContent: 'center',
        marginTop: spacing.md,
        minHeight: 42,
        paddingHorizontal: spacing.md,
    },
    webAppSettingsText: {
        color: '#ffffff',
        fontSize: 13,
        fontWeight: '900',
    },
    webAppStatsGrid: {
        flexDirection: 'row',
        gap: spacing.sm,
        marginTop: spacing.lg,
    },
    webAppStatTile: {
        alignItems: 'center',
        backgroundColor: WEB_APP_PROFILE_TILE,
        borderColor: WEB_APP_PROFILE_BORDER,
        borderRadius: 8,
        borderWidth: 1,
        flex: 1,
        padding: spacing.md,
    },
    webAppStatValue: {
        color: WEB_APP_PROFILE_ACCENT,
        fontSize: 24,
        fontWeight: '900',
    },
    webAppStatLabel: {
        color: '#cbd5e1',
        fontSize: 11,
        fontWeight: '800',
        marginTop: spacing.xs,
        textAlign: 'center',
        textTransform: 'uppercase',
    },
    webAppSection: {
        marginTop: spacing.lg,
    },
    webAppSectionHeader: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: spacing.sm,
        marginBottom: spacing.sm,
    },
    webAppSectionTitle: {
        color: WEB_APP_PROFILE_ACCENT,
        flex: 1,
        fontSize: 11,
        fontWeight: '900',
        letterSpacing: 0,
    },
    webAppSectionLink: {
        alignItems: 'center',
        backgroundColor: WEB_APP_PROFILE_TILE,
        borderColor: WEB_APP_PROFILE_BORDER,
        borderRadius: 8,
        borderWidth: 1,
        flexDirection: 'row',
        gap: 2,
        minHeight: 30,
        paddingHorizontal: spacing.sm,
    },
    webAppSectionLinkText: {
        color: WEB_APP_PROFILE_ACCENT,
        fontSize: 11,
        fontWeight: '900',
    },
    webAppSectionHint: {
        color: WEB_APP_PROFILE_MUTED,
        fontSize: 12,
        lineHeight: 17,
        marginBottom: spacing.sm,
    },
    webAppProgressGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: spacing.sm,
    },
    webAppProgressTile: {
        alignItems: 'center',
        backgroundColor: WEB_APP_PROFILE_TILE,
        borderColor: WEB_APP_PROFILE_BORDER,
        borderRadius: 8,
        borderWidth: 1,
        flexBasis: '31%',
        flexGrow: 1,
        minHeight: 98,
        padding: spacing.sm,
    },
    webAppProgressValue: {
        color: '#f8fafc',
        fontSize: 20,
        fontWeight: '900',
        marginTop: spacing.xs,
    },
    webAppProgressLabel: {
        color: '#cbd5e1',
        fontSize: 10,
        fontWeight: '800',
        marginTop: 3,
        textAlign: 'center',
        textTransform: 'uppercase',
    },
    webAppBadgeGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: spacing.sm,
    },
    webAppBadge: {
        alignItems: 'center',
        backgroundColor: WEB_APP_PROFILE_TILE,
        borderColor: WEB_APP_PROFILE_BORDER,
        borderRadius: 8,
        borderWidth: 1,
        flexBasis: '31%',
        flexGrow: 1,
        minHeight: 96,
        padding: spacing.sm,
    },
    webAppBadgeLocked: {
        opacity: 0.72,
    },
    webAppBadgeIcon: {
        color: '#f8fafc',
        fontSize: 22,
        marginBottom: spacing.xs,
    },
    webAppBadgeLabel: {
        color: '#f8fafc',
        fontSize: 11,
        fontWeight: '800',
        lineHeight: 15,
        textAlign: 'center',
    },
    webAppBadgeLabelLocked: {
        color: WEB_APP_PROFILE_MUTED,
    },
    webAppActionGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: spacing.sm,
    },
    webAppActionTile: {
        backgroundColor: WEB_APP_PROFILE_TILE,
        borderColor: WEB_APP_PROFILE_BORDER,
        borderRadius: 8,
        borderWidth: 1,
        flexBasis: '48%',
        flexGrow: 1,
        minHeight: 112,
        padding: spacing.md,
    },
    webAppActionTileDanger: {
        backgroundColor: '#2a1720',
        borderColor: '#7f1d1d',
    },
    webAppActionIcon: {
        alignItems: 'center',
        backgroundColor: 'rgba(52, 211, 153, 0.10)',
        borderRadius: 8,
        height: 34,
        justifyContent: 'center',
        marginBottom: spacing.sm,
        width: 34,
    },
    webAppActionIconDanger: {
        backgroundColor: 'rgba(248, 113, 113, 0.12)',
    },
    webAppActionLabel: {
        color: '#f8fafc',
        fontSize: 15,
        fontWeight: '900',
        letterSpacing: 0,
    },
    webAppActionLabelDanger: {
        color: '#fecaca',
    },
    webAppActionMeta: {
        color: '#cbd5e1',
        fontSize: 12,
        lineHeight: 17,
        marginTop: 4,
    },
    webAppAchievementsRoot: {
        backgroundColor: '#f8fafc',
        flex: 1,
    },
    webAppAchievementsContent: {
        padding: spacing.lg,
        paddingBottom: spacing.xl,
    },
    webAppAchievementsHeader: {
        alignItems: 'center',
        marginBottom: spacing.lg,
    },
    webAppAchievementsIcon: {
        alignItems: 'center',
        backgroundColor: '#fef3c7',
        borderRadius: 8,
        height: 64,
        justifyContent: 'center',
        marginBottom: spacing.md,
        width: 64,
    },
    webAppAchievementsTitle: {
        color: '#111827',
        fontSize: 24,
        fontWeight: '900',
        letterSpacing: 0,
        lineHeight: 30,
        textAlign: 'center',
    },
    webAppAchievementsSubtitle: {
        color: '#6b7280',
        fontSize: 14,
        lineHeight: 20,
        marginTop: 4,
        textAlign: 'center',
    },
    webAppAchievementsHero: {
        alignItems: 'center',
        backgroundColor: '#b45309',
        borderRadius: 8,
        marginBottom: spacing.lg,
        padding: spacing.lg,
    },
    webAppAchievementsHeroLabel: {
        color: 'rgba(255, 255, 255, 0.82)',
        fontSize: 11,
        fontWeight: '800',
        letterSpacing: 0,
        textTransform: 'uppercase',
    },
    webAppAchievementsHeroValue: {
        color: '#ffffff',
        fontSize: 38,
        fontWeight: '900',
        lineHeight: 44,
        marginTop: spacing.xs,
    },
    webAppAchievementsHeroMeta: {
        color: 'rgba(255, 255, 255, 0.76)',
        fontSize: 12,
        fontWeight: '700',
        marginTop: spacing.xs,
    },
    webAppAchievementsNotice: {
        alignItems: 'center',
        backgroundColor: '#ffffff',
        borderColor: '#e5e7eb',
        borderRadius: 8,
        borderWidth: 1,
        marginBottom: spacing.lg,
        padding: spacing.xl,
    },
    webAppAchievementsNoticeIcon: {
        fontSize: 34,
        marginBottom: spacing.sm,
    },
    webAppAchievementsNoticeText: {
        color: '#6b7280',
        fontSize: 14,
        lineHeight: 20,
        textAlign: 'center',
    },
    webAppAchievementsHint: {
        color: '#6b7280',
        fontSize: 12,
        lineHeight: 18,
        marginBottom: spacing.md,
        textAlign: 'center',
    },
    webAppAchievementsState: {
        paddingVertical: spacing.md,
    },
    webAppAchievementsList: {
        gap: spacing.sm,
    },
    webAppAchievementsCard: {
        alignItems: 'flex-start',
        backgroundColor: '#ffffff',
        borderColor: '#fde68a',
        borderRadius: 8,
        borderWidth: 1,
        flexDirection: 'row',
        gap: spacing.md,
        padding: spacing.md,
    },
    webAppAchievementsCardLocked: {
        backgroundColor: '#f9fafb',
        borderColor: '#e5e7eb',
        opacity: 0.72,
    },
    webAppAchievementsBadge: {
        alignItems: 'center',
        backgroundColor: '#e5e7eb',
        borderRadius: 8,
        height: 48,
        justifyContent: 'center',
        width: 48,
    },
    webAppAchievementsBadgeEarned: {
        backgroundColor: '#fef3c7',
    },
    webAppAchievementsBadgeIcon: {
        fontSize: 22,
    },
    webAppAchievementsCardBody: {
        flex: 1,
        minWidth: 0,
    },
    webAppAchievementsCardTitle: {
        color: '#111827',
        fontSize: 14,
        fontWeight: '900',
        lineHeight: 19,
    },
    webAppAchievementsCardDescription: {
        color: '#6b7280',
        fontSize: 12,
        lineHeight: 17,
        marginTop: 3,
    },
    webAppAchievementsStatus: {
        backgroundColor: '#f3f4f6',
        borderRadius: 999,
        paddingHorizontal: spacing.sm,
        paddingVertical: 4,
    },
    webAppAchievementsStatusEarned: {
        backgroundColor: '#d1fae5',
    },
    webAppAchievementsStatusText: {
        color: '#6b7280',
        fontSize: 10,
        fontWeight: '800',
    },
    webAppAchievementsStatusTextEarned: {
        color: '#047857',
    },
    webAppAchievementsEmpty: {
        alignItems: 'center',
        backgroundColor: '#ffffff',
        borderColor: '#e5e7eb',
        borderRadius: 8,
        borderWidth: 1,
        padding: spacing.xl,
    },
    webAppAchievementsEmptyText: {
        color: '#6b7280',
        fontSize: 14,
        lineHeight: 20,
        marginTop: spacing.sm,
        textAlign: 'center',
    },
    subHeader: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderBottomColor: colors.faint,
        borderBottomWidth: 1,
        flexDirection: 'row',
        gap: spacing.md,
        minHeight: 56,
        paddingHorizontal: spacing.lg,
        paddingVertical: spacing.sm,
    },
    backButton: {
        alignItems: 'center',
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        height: 38,
        justifyContent: 'center',
        width: 38,
    },
    subTitle: {
        color: colors.ink,
        fontFamily: 'serif',
        fontSize: 16,
        fontWeight: '900',
    },
    subContent: {
        backgroundColor: colors.bg,
        padding: spacing.lg,
        paddingBottom: spacing.xl,
    },
    gap: {
        height: spacing.md,
    },
    profileCard: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: spacing.md,
    },
    avatar: {
        alignItems: 'center',
        backgroundColor: colors.primary,
        borderRadius: 24,
        height: 52,
        justifyContent: 'center',
        width: 52,
    },
    avatarText: {
        color: colors.onPrimary,
        fontFamily: 'serif',
        fontSize: 18,
        fontWeight: '900',
    },
    profileBody: {
        flex: 1,
    },
    name: {
        color: colors.ink,
        fontFamily: 'serif',
        fontSize: 16,
        fontWeight: '900',
    },
    email: {
        color: colors.muted,
        fontSize: 12,
        lineHeight: 18,
        marginTop: spacing.xs,
    },
    gearButton: {
        alignItems: 'center',
        height: 40,
        justifyContent: 'center',
        width: 40,
    },
    statsRow: {
        flexDirection: 'row',
        gap: spacing.md,
    },
    statCard: {
        alignItems: 'center',
        flex: 1,
        paddingVertical: spacing.md,
    },
    statValue: {
        color: colors.primaryDark,
        fontFamily: 'serif',
        fontSize: 24,
        fontWeight: '900',
    },
    statLabel: {
        color: colors.muted,
        fontSize: 11,
        fontWeight: '700',
        marginTop: spacing.xs,
        textTransform: 'uppercase',
    },
    progressSection: {
        marginBottom: spacing.md,
    },
    progressGrid: {
        flexDirection: 'row',
        gap: spacing.sm,
    },
    progressCard: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        flex: 1,
        gap: spacing.xs,
        paddingVertical: spacing.md,
    },
    progressValue: {
        color: colors.primaryDark,
        fontFamily: 'serif',
        fontSize: 20,
        fontWeight: '900',
    },
    progressLabel: {
        color: colors.muted,
        fontSize: 10,
        fontWeight: '700',
        textAlign: 'center',
        textTransform: 'uppercase',
    },
    badgeSection: {
        marginBottom: spacing.md,
    },
    sectionHeaderRow: {
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: spacing.xs,
    },
    sectionHeaderActions: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: spacing.sm,
    },
    sectionLink: {
        alignItems: 'center',
        backgroundColor: colors.surfaceMuted,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        flexDirection: 'row',
        gap: 2,
        minHeight: 30,
        paddingHorizontal: spacing.sm,
    },
    sectionLinkText: {
        color: colors.primary,
        fontSize: 11,
        fontWeight: '900',
    },
    sectionLabel: {
        color: colors.muted,
        fontSize: 11,
        fontWeight: '800',
        letterSpacing: 1,
        marginBottom: spacing.sm,
        textTransform: 'uppercase',
    },
    sectionHint: {
        color: colors.muted,
        fontSize: 12,
        lineHeight: 17,
        marginBottom: spacing.sm,
    },
    badgeGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: spacing.sm,
    },
    badge: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        flexBasis: '47%',
        flexGrow: 1,
        gap: spacing.xs,
        minHeight: 124,
        paddingHorizontal: spacing.sm,
        paddingVertical: spacing.md,
    },
    badgeLocked: {
        backgroundColor: colors.bg,
    },
    badgeIconShell: {
        alignItems: 'center',
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        height: 42,
        justifyContent: 'center',
        width: 42,
    },
    badgeIconShellUnlocked: {
        backgroundColor: colors.surfaceMuted,
        borderColor: colors.primary,
    },
    badgeEmoji: {
        color: colors.muted,
        fontSize: 21,
    },
    badgeLock: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderColor: colors.faint,
        borderRadius: 9,
        borderWidth: 1,
        bottom: -4,
        height: 18,
        justifyContent: 'center',
        position: 'absolute',
        right: -4,
        width: 18,
    },
    badgeLabel: {
        color: colors.ink,
        fontSize: 12,
        fontWeight: '700',
        textAlign: 'center',
    },
    badgeLabelLocked: {
        color: colors.muted,
    },
    badgeDescription: {
        color: colors.muted,
        fontSize: 10,
        lineHeight: 14,
        paddingHorizontal: spacing.xs,
        textAlign: 'center',
    },
    achievementHero: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: spacing.md,
    },
    achievementHeroIcon: {
        alignItems: 'center',
        backgroundColor: colors.surfaceMuted,
        borderColor: colors.faint,
        borderRadius: radius.lg,
        borderWidth: 1,
        height: 58,
        justifyContent: 'center',
        width: 58,
    },
    achievementHeroBody: {
        flex: 1,
    },
    achievementHeroValue: {
        color: colors.primaryDark,
        fontFamily: 'serif',
        fontSize: 28,
        fontWeight: '900',
    },
    achievementHeroLabel: {
        color: colors.muted,
        fontSize: 11,
        fontWeight: '800',
        textTransform: 'uppercase',
    },
    achievementHeroMeta: {
        color: colors.text,
        fontSize: 12,
        fontWeight: '700',
        marginTop: spacing.xs,
    },
    emptyAchievementCard: {
        alignItems: 'center',
    },
    emptyAchievementIcon: {
        fontSize: 34,
        marginBottom: spacing.sm,
    },
    emptyAchievementTitle: {
        color: colors.ink,
        fontSize: 14,
        fontWeight: '900',
        textAlign: 'center',
    },
    emptyAchievementText: {
        color: colors.muted,
        fontSize: 12,
        lineHeight: 18,
        marginTop: spacing.xs,
        textAlign: 'center',
    },
    achievementList: {
        gap: spacing.md,
    },
    achievementDetailCard: {
        gap: spacing.md,
    },
    achievementDetailLocked: {
        backgroundColor: colors.bg,
    },
    achievementDetailTop: {
        alignItems: 'flex-start',
        flexDirection: 'row',
        gap: spacing.md,
    },
    achievementDetailIcon: {
        alignItems: 'center',
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.lg,
        borderWidth: 1,
        height: 48,
        justifyContent: 'center',
        width: 48,
    },
    achievementDetailIconUnlocked: {
        backgroundColor: colors.surfaceMuted,
        borderColor: colors.primary,
    },
    achievementDetailEmoji: {
        color: colors.muted,
        fontSize: 22,
    },
    achievementDetailBody: {
        flex: 1,
        minWidth: 0,
    },
    achievementDetailTitleRow: {
        alignItems: 'flex-start',
        flexDirection: 'row',
        gap: spacing.sm,
        justifyContent: 'space-between',
    },
    achievementDetailTitle: {
        color: colors.ink,
        flex: 1,
        fontFamily: 'serif',
        fontSize: 15,
        fontWeight: '900',
        lineHeight: 20,
    },
    achievementDetailDescription: {
        color: colors.muted,
        fontSize: 12,
        lineHeight: 18,
        marginTop: spacing.xs,
    },
    achievementStatePill: {
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: 999,
        borderWidth: 1,
        paddingHorizontal: spacing.sm,
        paddingVertical: 4,
    },
    achievementStatePillUnlocked: {
        backgroundColor: '#ecfdf5',
        borderColor: '#bbf7d0',
    },
    achievementStateText: {
        color: colors.muted,
        fontSize: 10,
        fontWeight: '900',
    },
    achievementStateTextUnlocked: {
        color: '#047857',
    },
    achievementProgressBlock: {
        gap: spacing.xs,
    },
    achievementProgressHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    achievementProgressLabel: {
        color: colors.muted,
        fontSize: 11,
        fontWeight: '800',
        textTransform: 'uppercase',
    },
    achievementProgressValue: {
        color: colors.primaryDark,
        fontSize: 11,
        fontWeight: '900',
    },
    achievementProgressTrack: {
        backgroundColor: colors.faint,
        borderRadius: 999,
        height: 8,
        overflow: 'hidden',
    },
    achievementProgressFill: {
        backgroundColor: colors.primary,
        borderRadius: 999,
        height: '100%',
    },
    achievementRewardRow: {
        alignItems: 'center',
        borderTopColor: colors.faint,
        borderTopWidth: 1,
        flexDirection: 'row',
        gap: spacing.xs,
        paddingTop: spacing.sm,
    },
    achievementRewardText: {
        color: colors.text,
        flex: 1,
        fontSize: 12,
        fontWeight: '800',
    },
    achievementEarnedDate: {
        color: colors.muted,
        fontSize: 11,
        fontWeight: '700',
    },
    menuRow: {
        alignItems: 'center',
        borderBottomColor: colors.faint,
        borderBottomWidth: 1,
        flexDirection: 'row',
        gap: spacing.md,
        minHeight: 56,
        paddingVertical: spacing.sm,
    },
    menuIcon: {
        alignItems: 'center',
        backgroundColor: colors.surfaceMuted,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        height: 38,
        justifyContent: 'center',
        width: 38,
    },
    menuIconDanger: {
        backgroundColor: '#fef2f2',
        borderColor: '#fecaca',
    },
    menuText: {
        flex: 1,
    },
    menuLabel: {
        color: colors.ink,
        fontFamily: 'serif',
        fontSize: 14,
        fontWeight: '900',
    },
    menuLabelDanger: {
        color: colors.danger,
    },
    menuMeta: {
        color: colors.muted,
        fontSize: 12,
        marginTop: 2,
    },
    signOutButton: {
        alignItems: 'center',
        borderColor: '#fecaca',
        borderRadius: radius.lg,
        borderWidth: 1,
        flexDirection: 'row',
        gap: spacing.sm,
        justifyContent: 'center',
        marginTop: spacing.md,
        minHeight: 46,
    },
    signOutText: {
        color: colors.danger,
        fontSize: 13,
        fontWeight: '800',
    },
    choiceGroup: {
        gap: spacing.sm,
        marginTop: spacing.md,
    },
    choiceRow: {
        alignItems: 'center',
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        flexDirection: 'row',
        gap: spacing.md,
        minHeight: 58,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
    },
    choiceRowActive: {
        backgroundColor: colors.surfaceMuted,
        borderColor: colors.primary,
    },
    choiceBody: {
        flex: 1,
        minWidth: 0,
    },
    choiceLabel: {
        color: colors.ink,
        fontSize: 13,
        fontWeight: '900',
    },
    choiceLabelActive: {
        color: colors.primaryDark,
    },
    choiceMeta: {
        color: colors.muted,
        fontSize: 11,
        lineHeight: 16,
        marginTop: 2,
    },
    choiceDot: {
        alignItems: 'center',
        borderColor: colors.faint,
        borderRadius: 10,
        borderWidth: 2,
        height: 20,
        justifyContent: 'center',
        width: 20,
    },
    choiceDotActive: {
        borderColor: colors.primary,
    },
    choiceDotInner: {
        backgroundColor: colors.primary,
        borderRadius: 5,
        height: 10,
        width: 10,
    },
    formBlock: {
        gap: spacing.sm,
        marginTop: spacing.md,
    },
    formInput: {
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        color: colors.ink,
        fontSize: 14,
        minHeight: 46,
        paddingHorizontal: spacing.md,
    },
    formButton: {
        alignItems: 'center',
        backgroundColor: colors.primary,
        borderRadius: radius.md,
        flexDirection: 'row',
        gap: spacing.sm,
        justifyContent: 'center',
        minHeight: 46,
        paddingHorizontal: spacing.md,
    },
    formButtonDisabled: {
        opacity: 0.65,
    },
    formButtonText: {
        color: colors.onPrimary,
        fontSize: 13,
        fontWeight: '900',
    },
    formButtonDanger: {
        backgroundColor: '#fef2f2',
        borderColor: '#fecaca',
        borderWidth: 1,
        marginTop: spacing.md,
    },
    formButtonDangerText: {
        color: colors.danger,
        fontSize: 13,
        fontWeight: '900',
    },
    sessionDeviceCard: {
        alignItems: 'center',
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        flexDirection: 'row',
        gap: spacing.md,
        marginTop: spacing.md,
        padding: spacing.md,
    },
    sessionDeviceIcon: {
        alignItems: 'center',
        backgroundColor: colors.surfaceMuted,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        height: 42,
        justifyContent: 'center',
        width: 42,
    },
    sessionDeviceBody: {
        flex: 1,
        minWidth: 0,
    },
    sessionDeviceTitle: {
        color: colors.ink,
        fontSize: 13,
        fontWeight: '900',
    },
    sessionDeviceMeta: {
        color: colors.muted,
        fontSize: 12,
        lineHeight: 17,
        marginTop: 2,
    },
    sessionList: {
        gap: spacing.xs,
        marginTop: spacing.sm,
    },
    sessionListRow: {
        backgroundColor: colors.surfaceMuted,
        borderColor: colors.faint,
        borderRadius: radius.sm,
        borderWidth: 1,
        paddingHorizontal: spacing.sm,
        paddingVertical: spacing.xs,
    },
    sessionListTitle: {
        color: colors.ink,
        fontSize: 12,
        fontWeight: '900',
    },
    sessionListMeta: {
        color: colors.muted,
        fontSize: 11,
        marginTop: 1,
    },
    settingsStatus: {
        color: colors.primary,
        fontSize: 12,
        fontWeight: '800',
        lineHeight: 18,
        textAlign: 'center',
    },
    settingsStatusError: {
        color: colors.danger,
    },
    appearanceLabel: {
        color: colors.ink,
        fontFamily: 'serif',
        fontSize: 14,
        fontWeight: '900',
        marginBottom: spacing.xs,
    },
    appearanceLabelGap: {
        marginTop: spacing.lg,
    },
    appearanceMeta: {
        color: colors.muted,
        fontSize: 13,
        lineHeight: 19,
    },
});
