import { StyleSheet } from 'react-native';

import { QURAN_FONT_FAMILIES } from '../constants/quranFonts';
import { colors, radius, spacing } from '../theme';
import {
    WEB_APP_QURAN_ACCENT,
    WEB_APP_QURAN_ACCENT_BG,
    WEB_APP_QURAN_BG,
    WEB_APP_QURAN_BORDER,
    WEB_APP_QURAN_MUTED,
    WEB_APP_QURAN_SURFACE,
} from './QuranScreen.helpers';

export const styles = StyleSheet.create({
    quranScroll: {
        backgroundColor: colors.bg,
        flex: 1,
    },
    webAppQuranScroll: {
        backgroundColor: WEB_APP_QURAN_BG,
    },
    quranListContent: {
        backgroundColor: colors.bg,
        flexGrow: 1,
        padding: spacing.lg,
        paddingBottom: spacing.xl,
        paddingTop: spacing.xl,
    },
    webAppQuranListContent: {
        backgroundColor: WEB_APP_QURAN_BG,
        paddingBottom: spacing.lg,
        paddingTop: spacing.lg,
    },
    readerList: {
        backgroundColor: colors.bg,
        flex: 1,
    },
    webAppReaderList: {
        backgroundColor: '#f8fafc',
    },
    readerListContent: {
        backgroundColor: colors.bg,
        flexGrow: 1,
        gap: spacing.md,
        padding: spacing.lg,
        paddingBottom: spacing.xl,
    },
    webAppReaderListContent: {
        backgroundColor: '#f8fafc',
        paddingBottom: spacing.lg,
        paddingTop: spacing.lg,
    },
    mushafScrollContent: {
        backgroundColor: colors.bg,
        flexGrow: 1,
        padding: spacing.md,
        paddingBottom: spacing.xl,
    },
    webAppMushafScrollContent: {
        backgroundColor: '#f8fafc',
        paddingBottom: spacing.lg,
        paddingTop: spacing.lg,
    },
    mushafListContent: {
        gap: 0,
        paddingHorizontal: spacing.md,
    },
    mushafGestureSurface: {
        minHeight: '100%',
    },
    readerHeader: {
        borderBottomColor: colors.faint,
        borderBottomWidth: 1,
        marginBottom: spacing.sm,
        paddingBottom: spacing.md,
        paddingTop: spacing.md,
    },
    webAppReaderHeader: {
        alignItems: 'center',
        backgroundColor: '#ffffff',
        borderColor: '#e5e7eb',
        borderRadius: 18,
        borderWidth: 1,
        marginBottom: spacing.md,
        padding: spacing.lg,
    },
    readerHeaderSerious: {
        marginBottom: spacing.xs,
        paddingBottom: spacing.sm,
    },
    readerHeaderTop: {
        alignItems: 'flex-start',
        flexDirection: 'row',
        gap: spacing.md,
        justifyContent: 'space-between',
    },
    readerHeaderCopy: {
        flex: 1,
    },
    readerHeaderActions: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: spacing.sm,
    },
    surahPagerRow: {
        flexDirection: 'row',
        gap: spacing.sm,
        marginBottom: spacing.md,
    },
    surahPagerButton: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderColor: colors.faint,
        borderRadius: radius.sm,
        borderWidth: 1,
        flex: 1,
        flexDirection: 'row',
        gap: spacing.xs,
        justifyContent: 'center',
        minHeight: 34,
        paddingHorizontal: spacing.sm,
    },
    surahPagerButtonText: {
        color: colors.primaryDark,
        flexShrink: 1,
        fontSize: 12,
        fontWeight: '800',
        lineHeight: 16,
        textAlign: 'center',
    },
    readerTitle: {
        color: colors.ink,
        fontFamily: 'serif',
        fontSize: 20,
        fontWeight: '900',
    },
    webAppReaderEyebrow: {
        color: WEB_APP_QURAN_ACCENT,
        fontSize: 11,
        fontWeight: '900',
        letterSpacing: 0,
        marginBottom: spacing.xs,
        textTransform: 'uppercase',
    },
    webAppReaderTitle: {
        color: '#111827',
        fontSize: 24,
        textAlign: 'left',
    },
    readerSubtitle: {
        color: colors.muted,
        fontSize: 14,
        lineHeight: 20,
        marginTop: spacing.sm,
    },
    webAppReaderSubtitle: {
        color: '#64748b',
        fontWeight: '700',
    },
    webAppReaderArabicTitle: {
        color: '#111827',
        fontFamily: QURAN_FONT_FAMILIES.kitab,
        fontSize: 42,
        lineHeight: 62,
        marginTop: spacing.md,
        textAlign: 'right',
        writingDirection: 'rtl',
    },
    webAppReaderBismillah: {
        color: '#334155',
        fontFamily: QURAN_FONT_FAMILIES.kitab,
        fontSize: 25,
        lineHeight: 40,
        marginTop: spacing.xs,
        textAlign: 'right',
        writingDirection: 'rtl',
    },
    webAppSurahPagerRow: {
        marginBottom: spacing.md,
    },
    webAppSurahPagerButton: {
        backgroundColor: '#ffffff',
        borderColor: '#e5e7eb',
        borderRadius: 12,
        minHeight: 42,
    },
    webAppSurahPagerButtonText: {
        color: WEB_APP_QURAN_ACCENT,
        fontSize: 12,
        fontWeight: '900',
    },
    readerLoadingMore: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: spacing.sm,
        justifyContent: 'center',
        paddingVertical: spacing.lg,
    },
    readerLoadingMoreText: {
        color: colors.muted,
        fontSize: 12,
        fontWeight: '800',
    },
    quranTitle: {
        color: colors.ink,
        fontFamily: 'serif',
        fontSize: 22,
        fontWeight: '900',
        marginBottom: spacing.sm,
    },
    webAppQuranHeader: {
        marginBottom: spacing.md,
    },
    webAppQuranArabicTitle: {
        color: WEB_APP_QURAN_ACCENT,
        fontFamily: QURAN_FONT_FAMILIES.kitab,
        fontSize: 31,
        lineHeight: 44,
        marginBottom: 2,
        textAlign: 'left',
        writingDirection: 'rtl',
    },
    webAppQuranTitle: {
        color: '#f8fafc',
        fontSize: 28,
        fontWeight: '900',
        letterSpacing: 0,
        lineHeight: 34,
        marginBottom: spacing.xs,
    },
    webAppQuranSubtitle: {
        color: WEB_APP_QURAN_MUTED,
        fontSize: 14,
        lineHeight: 20,
        marginBottom: spacing.md,
    },
    quranSearch: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderColor: colors.faint,
        borderRadius: radius.sm,
        borderWidth: 1,
        flexDirection: 'row',
        gap: spacing.sm,
        minHeight: 34,
        paddingHorizontal: spacing.md,
    },
    quranSearchInput: {
        color: colors.ink,
        flex: 1,
        fontSize: 13,
        minHeight: 32,
        padding: 0,
    },
    webAppQuranSearch: {
        alignItems: 'center',
        backgroundColor: WEB_APP_QURAN_SURFACE,
        borderColor: '#475569',
        borderRadius: 11,
        borderWidth: 1,
        flexDirection: 'row',
        gap: spacing.sm,
        minHeight: 38,
        paddingHorizontal: spacing.md,
    },
    webAppQuranSearchInput: {
        color: '#e2e8f0',
        flex: 1,
        fontSize: 14,
        minHeight: 36,
        padding: 0,
    },
    webAppMushafCta: {
        alignItems: 'center',
        backgroundColor: WEB_APP_QURAN_BG,
        borderColor: '#059669',
        borderRadius: 10,
        borderWidth: 1,
        flexDirection: 'row',
        gap: spacing.sm,
        marginTop: spacing.lg,
        minHeight: 60,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
    },
    webAppMushafCtaIcon: {
        alignItems: 'center',
        height: 30,
        justifyContent: 'center',
        width: 30,
    },
    webAppMushafCtaCopy: {
        flex: 1,
        minWidth: 0,
    },
    webAppMushafCtaTitle: {
        color: WEB_APP_QURAN_ACCENT,
        fontSize: 15,
        fontWeight: '900',
        lineHeight: 20,
    },
    webAppMushafCtaSubtitle: {
        color: WEB_APP_QURAN_ACCENT,
        fontSize: 12,
        lineHeight: 16,
    },
    quranTabs: {
        backgroundColor: colors.surface,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        flexDirection: 'row',
        gap: 4,
        marginBottom: spacing.md,
        marginTop: spacing.sm,
        padding: 4,
    },
    quranTabButton: {
        alignItems: 'center',
        borderRadius: radius.sm,
        flex: 1,
        justifyContent: 'center',
        minHeight: 32,
    },
    quranTabButtonActive: {
        backgroundColor: colors.primary,
    },
    quranTabText: {
        color: colors.primary,
        fontSize: 11,
        fontWeight: '900',
        textAlign: 'center',
    },
    quranTabTextActive: {
        color: colors.onPrimary,
    },
    surahRow: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderColor: colors.faint,
        borderRadius: radius.sm,
        borderWidth: 1,
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: spacing.sm,
        minHeight: 58,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
    },
    webAppSurahRow: {
        alignItems: 'center',
        backgroundColor: WEB_APP_QURAN_SURFACE,
        borderColor: WEB_APP_QURAN_BORDER,
        borderRadius: 10,
        borderWidth: 1,
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: spacing.sm,
        minHeight: 72,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
    },
    surahLeft: {
        alignItems: 'center',
        flex: 1,
        flexDirection: 'row',
        minWidth: 0,
    },
    webAppSurahLeft: {
        alignItems: 'center',
        flex: 1,
        flexDirection: 'row',
        minWidth: 0,
    },
    surahNumberWrap: {
        height: 38,
        justifyContent: 'center',
        marginRight: spacing.md,
        width: 38,
    },
    surahNumberDiamond: {
        alignItems: 'center',
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: 6,
        borderWidth: 1,
        height: 34,
        justifyContent: 'center',
        transform: [{ rotate: '45deg' }],
        width: 34,
    },
    surahNumberText: {
        color: colors.primary,
        fontSize: 12,
        fontWeight: '900',
        transform: [{ rotate: '-45deg' }],
    },
    webAppSurahNumberBadge: {
        alignItems: 'center',
        backgroundColor: WEB_APP_QURAN_ACCENT_BG,
        borderRadius: 4,
        height: 38,
        justifyContent: 'center',
        marginRight: spacing.md,
        width: 38,
    },
    webAppSurahNumberText: {
        color: WEB_APP_QURAN_ACCENT,
        fontSize: 12,
        fontWeight: '900',
    },
    surahInfo: {
        flex: 1,
        minWidth: 0,
    },
    webAppSurahInfo: {
        flex: 1,
        minWidth: 0,
    },
    surahNameRow: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: spacing.xs,
    },
    surahName: {
        color: colors.ink,
        fontFamily: 'serif',
        fontSize: 14,
        fontWeight: '900',
    },
    webAppSurahName: {
        color: '#f8fafc',
        flexShrink: 1,
        fontSize: 15,
        fontWeight: '900',
        lineHeight: 20,
    },
    surahMeta: {
        color: colors.muted,
        fontSize: 12,
        marginTop: 2,
    },
    webAppSurahMeta: {
        color: WEB_APP_QURAN_MUTED,
        fontSize: 12,
        lineHeight: 17,
        marginTop: 1,
    },
    surahArabic: {
        color: colors.ink,
        fontFamily: QURAN_FONT_FAMILIES.kitab,
        fontSize: 19,
        fontWeight: '400',
        lineHeight: 28,
        marginLeft: spacing.sm,
        maxWidth: '38%',
        textAlign: 'right',
        writingDirection: 'rtl',
    },
    webAppSurahArabic: {
        color: '#cbd5e1',
        fontFamily: QURAN_FONT_FAMILIES.kitab,
        fontSize: 20,
        lineHeight: 30,
        marginLeft: spacing.sm,
        maxWidth: '34%',
        textAlign: 'right',
        writingDirection: 'rtl',
    },
    modePanelText: {
        color: colors.text,
        fontSize: 13,
        lineHeight: 20,
        marginBottom: spacing.md,
    },
    modePanelMeta: {
        color: colors.muted,
        fontSize: 12,
        fontWeight: '800',
    },
    modePanelAction: {
        alignItems: 'center',
        backgroundColor: colors.primary,
        borderRadius: radius.md,
        justifyContent: 'center',
        minHeight: 42,
        paddingHorizontal: spacing.md,
    },
    modePanelActionText: {
        color: colors.onPrimary,
        fontSize: 13,
        fontWeight: '900',
    },
    message: {
        color: colors.primary,
        fontSize: 12,
        marginTop: spacing.sm,
    },
    webAppMessage: {
        color: WEB_APP_QURAN_ACCENT,
        fontSize: 12,
        fontWeight: '700',
        marginTop: spacing.sm,
    },
    targetPreview: {
        backgroundColor: colors.surface,
        borderColor: colors.primary,
        borderRadius: radius.lg,
        borderWidth: 2,
        marginTop: spacing.md,
        padding: spacing.lg,
    },
    targetPreviewKicker: {
        color: colors.primary,
        fontSize: 11,
        fontWeight: '900',
        marginBottom: spacing.xs,
        textTransform: 'uppercase',
    },
    targetPreviewTitle: {
        color: colors.ink,
        fontFamily: 'serif',
        fontSize: 16,
        fontWeight: '900',
        marginBottom: spacing.xs,
    },
    targetPreviewText: {
        color: colors.muted,
        fontSize: 12,
        fontWeight: '700',
        lineHeight: 18,
    },
    targetPreviewButton: {
        alignItems: 'center',
        borderColor: colors.primary,
        borderRadius: radius.md,
        borderWidth: 1,
        justifyContent: 'center',
        marginTop: spacing.md,
        minHeight: 38,
    },
    targetPreviewButtonText: {
        color: colors.primary,
        fontSize: 12,
        fontWeight: '900',
    },
    navigatorTabs: {
        flexDirection: 'row',
        gap: spacing.xs,
        marginBottom: spacing.sm,
    },
    navigatorTab: {
        alignItems: 'center',
        borderColor: colors.faint,
        borderRadius: radius.sm,
        borderWidth: 1,
        flex: 1,
        justifyContent: 'center',
        minHeight: 32,
    },
    navigatorTabActive: {
        backgroundColor: colors.surfaceMuted,
        borderColor: colors.primary,
    },
    navigatorTabText: {
        color: colors.text,
        fontSize: 11,
        fontWeight: '800',
    },
    navigatorTabTextActive: {
        color: colors.primaryDark,
    },
    inputRow: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: spacing.sm,
    },
    numberInput: {
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        color: colors.ink,
        flex: 1,
        fontSize: 16,
        fontWeight: '800',
        minHeight: 42,
        paddingHorizontal: spacing.md,
    },
    loader: {
        marginVertical: spacing.md,
    },
    focusAyahCard: {
        paddingBottom: spacing.lg,
    },
    focusAyahRow: {
        borderBottomColor: colors.faint,
        borderBottomWidth: 1,
        paddingBottom: spacing.lg,
        paddingTop: spacing.md,
    },
    focusAyahHeader: {
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: spacing.sm,
    },
    focusAyahNumber: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderColor: colors.faint,
        borderRadius: 999,
        borderWidth: 1,
        height: 28,
        justifyContent: 'center',
        width: 28,
    },
    focusAyahNumberText: {
        color: colors.primary,
        fontSize: 11,
        fontWeight: '900',
    },
    focusAyahMenuButton: {
        alignItems: 'center',
        borderRadius: radius.sm,
        height: 32,
        justifyContent: 'center',
        width: 32,
    },
    targetAyahCard: {
        borderColor: colors.primary,
        borderWidth: 2,
    },
    ayahHeader: {
        alignItems: 'flex-start',
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: spacing.md,
    },
    ayahHeaderCopy: {
        flex: 1,
        minWidth: 0,
    },
    ayahHeaderTitle: {
        color: colors.ink,
        fontFamily: 'serif',
        fontSize: 16,
        fontWeight: '900',
    },
    ayahHeaderMeta: {
        color: colors.primary,
        fontSize: 12,
        fontWeight: '900',
        marginTop: 2,
    },
    ayahMenuButton: {
        alignItems: 'center',
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.sm,
        borderWidth: 1,
        height: 34,
        justifyContent: 'center',
        marginLeft: spacing.sm,
        width: 34,
    },
    lineAyahRow: {
        borderBottomColor: colors.faint,
        borderBottomWidth: 1,
        paddingBottom: spacing.md,
        paddingTop: spacing.md,
    },
    lineAyahHeader: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: spacing.sm,
        marginBottom: spacing.sm,
    },
    lineAyahNumber: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderColor: colors.faint,
        borderRadius: 999,
        borderWidth: 1,
        height: 28,
        justifyContent: 'center',
        width: 28,
    },
    lineAyahNumberText: {
        color: colors.primary,
        fontSize: 11,
        fontWeight: '900',
    },
    lineAyahMeta: {
        color: colors.muted,
        flex: 1,
        fontSize: 12,
        fontWeight: '800',
        minWidth: 0,
    },
    lineAyahMenuButton: {
        alignItems: 'center',
        borderRadius: radius.sm,
        height: 32,
        justifyContent: 'center',
        width: 32,
    },
    inlineArabicRow: {
        alignItems: 'flex-start',
        flexDirection: 'row',
        gap: spacing.sm,
    },
    inlineArabicText: {
        flex: 1,
        minWidth: 0,
    },
    inlineAyahMenuButton: {
        alignItems: 'center',
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.sm,
        borderWidth: 1,
        height: 34,
        justifyContent: 'center',
        marginTop: 4,
        width: 34,
    },
    ayahArabic: {
        color: colors.ink,
        fontWeight: '800',
        lineHeight: 48,
        marginBottom: 0,
        textAlign: 'right',
        writingDirection: 'rtl',
    },
    lineArabic: {
        color: colors.ink,
        fontWeight: '800',
        lineHeight: 46,
        marginBottom: spacing.sm,
        textAlign: 'right',
        writingDirection: 'rtl',
    },
    inlineAyahMarker: {
        color: '#6f6a58',
        fontFamily: QURAN_FONT_FAMILIES.kitab,
        fontSize: 24,
        fontWeight: '400',
        lineHeight: 34,
    },
    mushafPagesStack: {
        gap: spacing.lg,
    },
    mushafPageShell: {
        backgroundColor: '#f4ecd6',
        borderColor: '#c8a955',
        borderRadius: radius.lg,
        borderWidth: 1,
        padding: spacing.sm,
    },
    mushafFrameOuter: {
        backgroundColor: '#f8efd4',
        borderColor: '#1f8f7a',
        borderRadius: radius.md,
        borderWidth: 2,
        padding: 4,
    },
    mushafFrame: {
        backgroundColor: '#fdf7e3',
        borderColor: '#c8a955',
        borderRadius: radius.sm,
        borderWidth: 1,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.md,
    },
    mushafFrameTop: {
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: spacing.lg,
    },
    mushafFrameJuzBadge: {
        backgroundColor: '#fffdf2',
        borderColor: '#c8a955',
        borderRadius: 999,
        borderWidth: 1,
        flex: 1,
        marginRight: 6,
        paddingHorizontal: spacing.sm,
        paddingVertical: 5,
    },
    mushafFrameJuzText: {
        color: '#1f8f7a',
        fontSize: 11,
        fontWeight: '900',
        letterSpacing: 0.6,
        textAlign: 'center',
        textTransform: 'uppercase',
    },
    mushafFramePageBadge: {
        alignItems: 'center',
        backgroundColor: '#1f8f7a',
        borderColor: '#c8a955',
        borderRadius: 999,
        borderWidth: 1,
        height: 30,
        justifyContent: 'center',
        minWidth: 50,
        paddingHorizontal: spacing.sm,
    },
    mushafFramePageText: {
        color: '#fffdf2',
        fontSize: 13,
        fontWeight: '900',
    },
    mushafFrameSurahBadge: {
        backgroundColor: '#fffdf2',
        borderColor: '#c8a955',
        borderRadius: 999,
        borderWidth: 1,
        flex: 1.4,
        marginLeft: 6,
        paddingHorizontal: spacing.sm,
        paddingVertical: 5,
    },
    mushafFrameSurahText: {
        color: '#1f8f7a',
        fontSize: 11,
        fontWeight: '900',
        letterSpacing: 0.4,
        textAlign: 'center',
    },
    mushafFrameBottom: {
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: spacing.lg,
        paddingTop: spacing.sm,
    },
    mushafFootPageBadge: {
        alignItems: 'center',
        backgroundColor: '#fffdf2',
        borderColor: '#c8a955',
        borderRadius: 999,
        borderWidth: 1,
        justifyContent: 'center',
        minWidth: 32,
        paddingHorizontal: spacing.sm,
        paddingVertical: 3,
    },
    mushafFootPageText: {
        color: '#1f8f7a',
        fontSize: 11,
        fontWeight: '900',
    },
    mushafPerKataStack: {
        gap: spacing.md,
        paddingTop: spacing.sm,
    },
    mushafPerKataAyah: {
        borderRadius: radius.sm,
        paddingVertical: spacing.xs,
    },
    mushafPerKataAyahTarget: {
        backgroundColor: '#e9f7ef',
    },
    mushafPerKataRow: {
        flexDirection: 'row-reverse',
        flexWrap: 'wrap',
        justifyContent: 'flex-start',
        marginHorizontal: -2,
    },
    mushafWordCell: {
        alignItems: 'center',
        marginBottom: 6,
        marginHorizontal: 2,
        minWidth: 56,
        paddingHorizontal: 4,
        paddingVertical: 4,
    },
    mushafWordArabic: {
        color: colors.ink,
        fontSize: 22,
        fontWeight: '800',
        lineHeight: 32,
        marginBottom: 2,
        textAlign: 'center',
        writingDirection: 'rtl',
    },
    mushafWordLatin: {
        color: '#5b6e5b',
        fontSize: 9,
        fontStyle: 'italic',
        lineHeight: 11,
        marginBottom: 1,
        textAlign: 'center',
    },
    mushafWordIndo: {
        color: '#b91c1c',
        fontSize: 9,
        fontWeight: '700',
        lineHeight: 11,
        textAlign: 'center',
    },
    mushafVerseEndCell: {
        alignItems: 'center',
        justifyContent: 'center',
        marginHorizontal: 2,
        paddingTop: 4,
    },
    mushafVerseEndCircle: {
        alignItems: 'center',
        backgroundColor: '#fffdf2',
        borderColor: '#1f8f7a',
        borderRadius: 999,
        borderWidth: 1.5,
        height: 28,
        justifyContent: 'center',
        width: 28,
    },
    mushafVerseEndText: {
        color: '#1f8f7a',
        fontSize: 12,
        fontWeight: '900',
    },
    mushafPerKataFullTranslation: {
        color: colors.text,
        fontSize: 11,
        fontStyle: 'italic',
        lineHeight: 16,
        marginTop: 4,
        paddingHorizontal: 4,
        textAlign: 'left',
    },
    mushafBismillah: {
        color: colors.ink,
        fontSize: 30,
        fontWeight: '900',
        lineHeight: 52,
        marginBottom: spacing.md,
        textAlign: 'center',
        writingDirection: 'rtl',
    },
    mushafContinuousArabic: {
        color: colors.ink,
        fontWeight: '800',
        lineHeight: 64,
        textAlign: 'right',
        writingDirection: 'rtl',
    },
    mushafPageArabic: {
        color: colors.ink,
        includeFontPadding: false,
        marginBottom: 2,
        textAlign: 'right',
        textAlignVertical: 'top',
        writingDirection: 'rtl',
    },
    mushafAyahBlockStack: {
        borderTopColor: '#d9cfae',
        borderTopWidth: 1,
        marginTop: spacing.sm,
    },
    mushafAyahBlockLine: {
        borderBottomColor: '#d9cfae',
        borderBottomWidth: 1,
        paddingBottom: 8,
        paddingTop: 8,
    },
    mushafInlineTarget: {
        backgroundColor: '#e9f7ef',
        color: colors.primaryDark,
    },
    mushafPageTranslation: {
        color: colors.text,
        flex: 0,
        fontSize: 9,
        lineHeight: 12,
        marginTop: 0,
        textAlign: 'right',
    },
    mushafInlineLoading: {
        alignItems: 'center',
        paddingTop: spacing.sm,
    },
    mushafVerseMark: {
        color: '#7f6f44',
        fontSize: 15,
        fontWeight: '900',
    },
    mushafRangeMeta: {
        color: colors.muted,
        fontSize: 11,
        marginTop: spacing.md,
        textAlign: 'center',
    },
    mushafAyahBlock: {
        backgroundColor: '#fffdf2',
        borderColor: '#d8c897',
        borderLeftWidth: 2,
        borderRightWidth: 2,
        paddingHorizontal: spacing.md,
        paddingTop: spacing.lg,
    },
    mushafArabic: {
        color: colors.ink,
        fontWeight: '800',
        lineHeight: 52,
        marginBottom: spacing.sm,
        textAlign: 'right',
        writingDirection: 'rtl',
    },
    mushafAyahNumber: {
        alignSelf: 'center',
        backgroundColor: colors.surface,
        borderColor: '#c9b675',
        borderRadius: 999,
        borderWidth: 1,
        color: colors.primaryDark,
        fontSize: 12,
        fontWeight: '900',
        marginBottom: spacing.md,
        minWidth: 28,
        overflow: 'hidden',
        paddingHorizontal: spacing.sm,
        paddingVertical: 4,
        textAlign: 'center',
    },
    ayahLatin: {
        color: colors.muted,
        fontSize: 13,
        lineHeight: 20,
        marginBottom: spacing.sm,
    },
    ayahTranslation: {
        color: colors.text,
        fontSize: 14,
        lineHeight: 22,
    },
    ayahReadMore: {
        color: colors.primary,
        fontSize: 12,
        fontWeight: '900',
        marginTop: spacing.sm,
        textAlign: 'right',
    },
    quranDetailCard: {
        padding: spacing.lg,
    },
    webAppQuranDetailSurface: {
        backgroundColor: '#f8fafc',
        borderRadius: radius.md,
        padding: spacing.sm,
    },
    quranDetailKicker: {
        color: colors.primary,
        fontSize: 12,
        fontWeight: '900',
        marginBottom: spacing.md,
    },
    quranDetailArabic: {
        color: colors.ink,
        fontWeight: '800',
        lineHeight: 54,
        marginBottom: spacing.md,
        textAlign: 'right',
        writingDirection: 'rtl',
    },
    quranDetailLatin: {
        color: colors.muted,
        fontSize: 13,
        lineHeight: 21,
        marginBottom: spacing.md,
    },
    quranDetailTranslationBox: {
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        padding: spacing.md,
    },
    quranDetailTranslation: {
        color: colors.text,
        fontSize: 15,
        lineHeight: 24,
    },
    quranDetailActions: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: spacing.sm,
        marginBottom: spacing.md,
    },
    quranDetailNoteCard: {
        marginTop: spacing.sm,
    },
    hiddenBlock: {
        backgroundColor: colors.surfaceMuted,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        marginBottom: spacing.sm,
        padding: spacing.md,
    },
    hiddenTitle: {
        color: colors.primaryDark,
        fontSize: 13,
        fontWeight: '900',
        textAlign: 'center',
    },
    revealButton: {
        alignItems: 'center',
        borderColor: colors.primary,
        borderRadius: radius.md,
        borderWidth: 1,
        justifyContent: 'center',
        marginTop: spacing.sm,
        minHeight: 38,
    },
    revealButtonText: {
        color: colors.primary,
        fontSize: 12,
        fontWeight: '900',
    },
    referenceItem: {
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        marginTop: spacing.sm,
        padding: spacing.md,
    },
    referenceTitle: {
        color: colors.ink,
        fontSize: 14,
        fontWeight: '900',
        marginBottom: spacing.xs,
    },
    referenceMeta: {
        color: colors.primary,
        fontSize: 12,
        fontWeight: '800',
        marginBottom: spacing.xs,
    },
    referenceBody: {
        color: colors.text,
        fontSize: 13,
        lineHeight: 20,
    },
    referenceEmpty: {
        color: colors.muted,
        fontSize: 13,
        lineHeight: 19,
        marginTop: spacing.sm,
    },
    tafsirModeRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: spacing.xs,
        marginBottom: spacing.sm,
    },
    tafsirModePill: {
        borderColor: colors.faint,
        borderRadius: 16,
        borderWidth: 1,
        paddingHorizontal: 12,
        paddingVertical: 5,
    },
    tafsirModePillActive: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    tafsirModePillText: {
        color: colors.text,
        fontSize: 12,
        fontWeight: '600',
    },
    tafsirModePillTextActive: {
        color: '#fff',
    },
    sideBySideRow: {
        flexDirection: 'row',
        gap: spacing.sm,
    },
    sideBySideCol: {
        borderRadius: radius.md,
        flex: 1,
        padding: spacing.md,
    },
    sideBySideColPrimary: {
        backgroundColor: '#f0fdf4',
    },
    sideBySideColSecondary: {
        backgroundColor: '#f0f9ff',
    },
    sideBySideColTitle: {
        color: colors.ink,
        fontSize: 13,
        fontWeight: '900',
        marginBottom: spacing.sm,
    },
    qariGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: spacing.sm,
        marginTop: spacing.sm,
    },
    qariButton: {
        alignItems: 'center',
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        justifyContent: 'center',
        minHeight: 34,
        paddingHorizontal: spacing.md,
    },
    qariButtonActive: {
        backgroundColor: colors.surfaceMuted,
        borderColor: colors.primary,
    },
    qariText: {
        color: colors.text,
        fontSize: 11,
        fontWeight: '800',
    },
    qariTextActive: {
        color: colors.primaryDark,
    },
    audioPanel: {
        backgroundColor: colors.surface,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        gap: spacing.sm,
        marginBottom: spacing.md,
        padding: spacing.md,
    },
    audioPanelHeader: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: spacing.sm,
        justifyContent: 'space-between',
    },
    audioPanelHeaderActions: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: spacing.xs,
    },
    audioPanelIconButton: {
        alignItems: 'center',
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.sm,
        borderWidth: 1,
        height: 36,
        justifyContent: 'center',
        width: 36,
    },
    audioPanelTitleRow: {
        alignItems: 'center',
        flex: 1,
        flexDirection: 'row',
        gap: spacing.sm,
        minWidth: 0,
    },
    audioPanelTitleCopy: {
        flex: 1,
        minWidth: 0,
    },
    audioPanelTitle: {
        color: colors.ink,
        fontSize: 14,
        fontWeight: '900',
    },
    audioPanelMeta: {
        color: colors.muted,
        fontSize: 11,
        fontWeight: '800',
        marginTop: 2,
    },
    audioPrimaryButton: {
        alignItems: 'center',
        backgroundColor: colors.primary,
        borderRadius: radius.sm,
        flexDirection: 'row',
        gap: spacing.xs,
        justifyContent: 'center',
        minHeight: 36,
        paddingHorizontal: spacing.md,
    },
    audioPrimaryButtonText: {
        color: colors.onPrimary,
        fontSize: 12,
        fontWeight: '900',
    },
    audioInputGrid: {
        flexDirection: 'row',
        gap: spacing.sm,
    },
    audioInputGroup: {
        flex: 1,
        minWidth: 0,
    },
    audioInputLabel: {
        color: colors.muted,
        fontSize: 10,
        fontWeight: '900',
        marginBottom: 4,
        textTransform: 'uppercase',
    },
    audioInput: {
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.sm,
        borderWidth: 1,
        color: colors.ink,
        fontSize: 13,
        fontWeight: '900',
        minHeight: 38,
        paddingHorizontal: spacing.sm,
        paddingVertical: 0,
        textAlign: 'center',
    },
    audioTransportRow: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: spacing.sm,
        justifyContent: 'center',
    },
    audioSkipButton: {
        alignItems: 'center',
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.sm,
        borderWidth: 1,
        height: 36,
        justifyContent: 'center',
        width: 44,
    },
    audioQueueText: {
        color: colors.muted,
        fontSize: 11,
        fontWeight: '900',
        minWidth: 74,
        textAlign: 'center',
    },
    audioSectionLabel: {
        color: colors.primaryDark,
        fontSize: 11,
        fontWeight: '900',
        marginTop: spacing.xs,
        textTransform: 'uppercase',
    },
    audioChipRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: spacing.xs,
    },
    audioChip: {
        alignItems: 'center',
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.sm,
        borderWidth: 1,
        justifyContent: 'center',
        minHeight: 32,
        paddingHorizontal: spacing.sm,
    },
    audioChipActive: {
        backgroundColor: colors.surfaceMuted,
        borderColor: colors.primary,
    },
    audioChipText: {
        color: colors.text,
        fontSize: 11,
        fontWeight: '800',
    },
    audioChipTextActive: {
        color: colors.primaryDark,
    },
    audioControlRow: {
        alignItems: 'flex-end',
        flexDirection: 'row',
        gap: spacing.sm,
        justifyContent: 'space-between',
    },
    audioControlGroup: {
        flex: 1,
        minWidth: 0,
    },
    audioRepeatButton: {
        alignItems: 'center',
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.sm,
        borderWidth: 1,
        justifyContent: 'center',
        minHeight: 32,
        paddingHorizontal: spacing.md,
    },
    audioRepeatButtonActive: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    audioRepeatText: {
        color: colors.text,
        fontSize: 11,
        fontWeight: '900',
    },
    audioRepeatTextActive: {
        color: colors.onPrimary,
    },
    audioStatusText: {
        color: colors.primary,
        fontSize: 12,
        fontWeight: '800',
        lineHeight: 17,
    },
    audioMiniPanel: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderColor: colors.faint,
        borderRadius: radius.lg,
        borderWidth: 1,
        flexDirection: 'row',
        gap: spacing.sm,
        marginBottom: spacing.md,
        padding: spacing.sm,
        shadowColor: '#0f172a',
        shadowOpacity: 0.08,
        shadowRadius: 10,
    },
    audioMiniPlayButton: {
        alignItems: 'center',
        backgroundColor: colors.primary,
        borderRadius: 999,
        height: 40,
        justifyContent: 'center',
        width: 40,
    },
    audioMiniCopy: {
        flex: 1,
        minWidth: 0,
    },
    audioMiniTitle: {
        color: colors.primaryDark,
        fontSize: 12,
        fontWeight: '900',
    },
    audioMiniMeta: {
        color: colors.muted,
        fontSize: 11,
        fontWeight: '700',
        marginTop: 2,
    },
    audioMiniIconButton: {
        alignItems: 'center',
        borderRadius: 999,
        height: 34,
        justifyContent: 'center',
        width: 34,
    },
    hafalanSummary: {
        flexDirection: 'row',
        gap: spacing.sm,
        marginBottom: spacing.md,
    },
    hafalanStat: {
        alignItems: 'center',
        backgroundColor: colors.surfaceMuted,
        borderColor: colors.faint,
        borderRadius: 8,
        borderWidth: 1,
        flex: 1,
        paddingVertical: spacing.sm,
    },
    hafalanStatValue: {
        color: colors.primaryDark,
        fontFamily: 'serif',
        fontSize: 20,
        fontWeight: '900',
    },
    hafalanStatLabel: {
        color: colors.muted,
        fontSize: 11,
        fontWeight: '700',
        marginTop: 2,
        textTransform: 'uppercase',
    },
    hafalanRow: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderColor: colors.faint,
        borderRadius: 8,
        borderWidth: 1,
        flexDirection: 'row',
        gap: spacing.md,
        marginBottom: spacing.sm,
        minHeight: 52,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
    },
    hafalanInfo: {
        flex: 1,
    },
    statusBadge: {
        alignItems: 'center',
        borderColor: colors.faint,
        borderRadius: 6,
        borderWidth: 1,
        justifyContent: 'center',
        minHeight: 28,
        paddingHorizontal: spacing.sm,
    },
    statusInProgress: {
        backgroundColor: '#fffbeb',
        borderColor: '#fde68a',
    },
    statusMemorized: {
        backgroundColor: '#f0fdf4',
        borderColor: '#bbf7d0',
    },
    statusText: {
        color: colors.muted,
        fontSize: 11,
        fontWeight: '900',
    },
    statusTextColored: {
        color: colors.ink,
    },
    murojaahSurahGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: spacing.xs,
        marginTop: spacing.sm,
    },
    murojaahChip: {
        alignItems: 'center',
        borderColor: colors.faint,
        borderRadius: 6,
        borderWidth: 1,
        justifyContent: 'center',
        paddingHorizontal: spacing.sm,
        paddingVertical: spacing.xs,
    },
    murojaahChipActive: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    murojaahChipText: {
        color: colors.text,
        fontSize: 12,
        fontWeight: '800',
    },
    murojaahChipTextActive: {
        color: '#ffffff',
    },
    scoreRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: spacing.xs,
        marginTop: spacing.sm,
    },
    murojaahNoteInput: {
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: 8,
        borderWidth: 1,
        color: colors.ink,
        fontSize: 13,
        lineHeight: 19,
        marginTop: spacing.sm,
        minHeight: 72,
        padding: spacing.md,
        textAlignVertical: 'top',
    },
    labelGap: {
        marginTop: spacing.md,
    },
    disabled: {
        opacity: 0.55,
    },
    compactPrimaryButton: {
        alignItems: 'center',
        backgroundColor: colors.primary,
        borderRadius: radius.md,
        justifyContent: 'center',
        minHeight: 42,
        paddingHorizontal: spacing.md,
    },
    primaryButtonText: {
        color: '#ffffff',
        fontSize: 13,
        fontWeight: '900',
    },
    modalLoader: {
        marginVertical: spacing.lg,
    },
    actionSheetNotice: {
        color: colors.muted,
        fontSize: 12,
        lineHeight: 18,
        marginTop: spacing.sm,
    },
    // Settings modal
    settingLabel: {
        color: colors.ink,
        fontSize: 13,
        fontWeight: '900',
        marginBottom: spacing.sm,
        marginTop: spacing.md,
    },
    settingHint: {
        color: colors.muted,
        fontSize: 11,
        lineHeight: 16,
        marginTop: 4,
    },
    displayModeStack: {
        gap: spacing.sm,
    },
    displayModeCard: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        flexDirection: 'row',
        gap: spacing.md,
        padding: spacing.md,
    },
    displayModeCardActive: {
        backgroundColor: colors.surfaceMuted,
        borderColor: colors.primary,
    },
    displayModePreview: {
        alignItems: 'center',
        backgroundColor: colors.bg,
        borderColor: colors.faint,
        borderRadius: radius.sm,
        borderWidth: 1,
        height: 54,
        justifyContent: 'center',
        width: 46,
    },
    displayModePreviewTop: {
        backgroundColor: colors.primary,
        borderRadius: 2,
        height: 4,
        marginBottom: 7,
        width: 22,
    },
    displayModePreviewLine: {
        backgroundColor: colors.ink,
        borderRadius: 2,
        height: 5,
        marginBottom: 6,
        width: 28,
    },
    displayModePreviewLineFull: {
        height: 6,
        width: 34,
    },
    displayModePreviewSmall: {
        backgroundColor: colors.muted,
        borderRadius: 2,
        height: 3,
        width: 24,
    },
    displayModeCopy: {
        flex: 1,
        minWidth: 0,
    },
    displayModeLabel: {
        color: colors.primary,
        fontSize: 11,
        fontWeight: '900',
        textTransform: 'uppercase',
    },
    displayModeLabelActive: {
        color: colors.primaryDark,
    },
    displayModeTitle: {
        color: colors.ink,
        fontSize: 14,
        fontWeight: '900',
        marginTop: 2,
    },
    displayModeDescription: {
        color: colors.muted,
        fontSize: 12,
        lineHeight: 17,
        marginTop: 2,
    },
    settingChips: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: spacing.xs,
    },
    settingChip: {
        alignItems: 'center',
        borderColor: colors.faint,
        borderRadius: radius.sm,
        borderWidth: 1,
        justifyContent: 'center',
        minHeight: 34,
        paddingHorizontal: spacing.md,
    },
    settingChipActive: {
        backgroundColor: colors.surfaceMuted,
        borderColor: colors.primary,
    },
    settingChipText: {
        color: colors.text,
        fontSize: 12,
        fontWeight: '800',
    },
    settingChipTextActive: {
        color: colors.primaryDark,
    },
    fontSizeRow: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: spacing.md,
    },
    fontSizeButton: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderColor: colors.faint,
        borderRadius: radius.sm,
        borderWidth: 1,
        height: 36,
        justifyContent: 'center',
        width: 36,
    },
    fontSizeButtonText: {
        color: colors.ink,
        fontSize: 13,
        fontWeight: '900',
    },
    fontSizeValue: {
        color: colors.text,
        fontSize: 13,
        fontWeight: '800',
        minWidth: 44,
        textAlign: 'center',
    },
    tajweedButton: {
        alignItems: 'center',
        borderColor: colors.primary,
        borderRadius: radius.md,
        borderWidth: 1,
        flexDirection: 'row',
        gap: spacing.sm,
        justifyContent: 'center',
        marginTop: spacing.lg,
        minHeight: 42,
    },
    tajweedButtonText: {
        color: colors.primary,
        fontSize: 13,
        fontWeight: '900',
    },
    // Tajweed modal
    tajweedIntro: {
        color: colors.text,
        fontSize: 13,
        lineHeight: 20,
        marginBottom: spacing.md,
    },
    tajweedGroup: {
        backgroundColor: colors.surface,
        borderColor: colors.faint,
        borderRadius: radius.md,
        borderWidth: 1,
        marginBottom: spacing.sm,
        padding: spacing.md,
    },
    tajweedGroupHeader: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: spacing.sm,
        marginBottom: spacing.xs,
    },
    tajweedDot: {
        borderRadius: 6,
        height: 12,
        width: 12,
    },
    tajweedGroupTitle: {
        color: colors.ink,
        fontSize: 15,
        fontWeight: '900',
    },
    tajweedGroupDesc: {
        color: colors.muted,
        fontSize: 12,
        lineHeight: 17,
        marginBottom: spacing.sm,
        paddingLeft: 20,
    },
    tajweedRule: {
        alignItems: 'flex-start',
        borderTopColor: colors.faint,
        borderTopWidth: 1,
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingTop: spacing.sm,
        marginTop: spacing.sm,
        gap: spacing.sm,
    },
    tajweedRuleLeft: {
        alignItems: 'flex-start',
        flex: 1,
        flexDirection: 'row',
        gap: spacing.sm,
    },
    tajweedRuleDot: {
        borderRadius: 5,
        height: 10,
        marginTop: 3,
        width: 10,
    },
    tajweedRuleInfo: {
        flex: 1,
    },
    tajweedRuleTitle: {
        color: colors.ink,
        fontSize: 13,
        fontWeight: '900',
    },
    tajweedRuleDesc: {
        color: colors.muted,
        fontSize: 11,
        lineHeight: 16,
        marginTop: 2,
    },
    tajweedRuleExample: {
        color: colors.primary,
        fontSize: 16,
        fontWeight: '700',
        textAlign: 'right',
        writingDirection: 'rtl',
    },
});
