export const SURAH_LIST = [
    {
        number: 1,
        name: "Al-Fatihah",
        name_en: "Al-Faatiha",
        meaning: "Pembukaan",
        meaning_en: "The Opening",
        ayat: 7,
        name_ar: "سُورَةُ ٱلْفَاتِحَةِ",
        arabic: "ٱلْفَاتِحَةِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 2,
        name: "Al-Baqarah",
        name_en: "Al-Baqara",
        meaning: "Sapi Betina",
        meaning_en: "The Cow",
        ayat: 286,
        name_ar: "سُورَةُ البَقَرَةِ",
        arabic: "البَقَرَةِ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 3,
        name: "Ali 'Imran",
        name_en: "Aal-i-Imraan",
        meaning: "Keluarga Imran",
        meaning_en: "The Family of Imraan",
        ayat: 200,
        name_ar: "سُورَةُ آلِ عِمۡرَانَ",
        arabic: "آلِ عِمۡرَانَ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 4,
        name: "An-Nisa",
        name_en: "An-Nisaa",
        meaning: "Wanita",
        meaning_en: "The Women",
        ayat: 176,
        name_ar: "سُورَةُ النِّسَاءِ",
        arabic: "النِّسَاءِ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 5,
        name: "Al-Ma'idah",
        name_en: "Al-Maaida",
        meaning: "Hidangan",
        meaning_en: "The Table",
        ayat: 120,
        name_ar: "سُورَةُ المَائـِدَةِ",
        arabic: "المَائـِدَةِ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 6,
        name: "Al-An'am",
        name_en: "Al-An'aam",
        meaning: "Binatang Ternak",
        meaning_en: "The Cattle",
        ayat: 165,
        name_ar: "سُورَةُ الأَنۡعَامِ",
        arabic: "الأَنۡعَامِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 7,
        name: "Al-A'raf",
        name_en: "Al-A'raaf",
        meaning: "Tempat Tertinggi",
        meaning_en: "The Heights",
        ayat: 206,
        name_ar: "سُورَةُ الأَعۡرَافِ",
        arabic: "الأَعۡرَافِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 8,
        name: "Al-Anfal",
        name_en: "Al-Anfaal",
        meaning: "Rampasan Perang",
        meaning_en: "The Spoils of War",
        ayat: 75,
        name_ar: "سُورَةُ الأَنفَالِ",
        arabic: "الأَنفَالِ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 9,
        name: "At-Taubah",
        name_en: "At-Tawba",
        meaning: "Pengampunan",
        meaning_en: "The Repentance",
        ayat: 129,
        name_ar: "سُورَةُ التَّوۡبَةِ",
        arabic: "التَّوۡبَةِ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 10,
        name: "Yunus",
        name_en: "Yunus",
        meaning: "Nabi Yunus",
        meaning_en: "Jonah",
        ayat: 109,
        name_ar: "سُورَةُ يُونُسَ",
        arabic: "يُونُسَ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 11,
        name: "Hud",
        name_en: "Hud",
        meaning: "Nabi Hud",
        meaning_en: "Hud",
        ayat: 123,
        name_ar: "سُورَةُ هُودٍ",
        arabic: "هُودٍ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 12,
        name: "Yusuf",
        name_en: "Yusuf",
        meaning: "Nabi Yusuf",
        meaning_en: "Joseph",
        ayat: 111,
        name_ar: "سُورَةُ يُوسُفَ",
        arabic: "يُوسُفَ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 13,
        name: "Ar-Ra'd",
        name_en: "Ar-Ra'd",
        meaning: "Guruh",
        meaning_en: "The Thunder",
        ayat: 43,
        name_ar: "سُورَةُ الرَّعۡدِ",
        arabic: "الرَّعۡدِ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 14,
        name: "Ibrahim",
        name_en: "Ibrahim",
        meaning: "Nabi Ibrahim",
        meaning_en: "Abraham",
        ayat: 52,
        name_ar: "سُورَةُ إِبۡرَاهِيمَ",
        arabic: "إِبۡرَاهِيمَ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 15,
        name: "Al-Hijr",
        name_en: "Al-Hijr",
        meaning: "Gunung Al-Hijr",
        meaning_en: "The Rock",
        ayat: 99,
        name_ar: "سُورَةُ الحِجۡرِ",
        arabic: "الحِجۡرِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 16,
        name: "An-Nahl",
        name_en: "An-Nahl",
        meaning: "Lebah",
        meaning_en: "The Bee",
        ayat: 128,
        name_ar: "سُورَةُ النَّحۡلِ",
        arabic: "النَّحۡلِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 17,
        name: "Al-Isra",
        name_en: "Al-Israa",
        meaning: "Memperjalankan Malam Hari",
        meaning_en: "The Night Journey",
        ayat: 111,
        name_ar: "سُورَةُ الإِسۡرَاءِ",
        arabic: "الإِسۡرَاءِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 18,
        name: "Al-Kahf",
        name_en: "Al-Kahf",
        meaning: "Gua",
        meaning_en: "The Cave",
        ayat: 110,
        name_ar: "سُورَةُ الكَهۡفِ",
        arabic: "الكَهۡفِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 19,
        name: "Maryam",
        name_en: "Maryam",
        meaning: "Maryam",
        meaning_en: "Mary",
        ayat: 98,
        name_ar: "سُورَةُ مَرۡيَمَ",
        arabic: "مَرۡيَمَ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 20,
        name: "Taha",
        name_en: "Taa-Haa",
        meaning: "Taha",
        meaning_en: "Taa-Haa",
        ayat: 135,
        name_ar: "سُورَةُ طه",
        arabic: "طه",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 21,
        name: "Al-Anbiya",
        name_en: "Al-Anbiyaa",
        meaning: "Para Nabi",
        meaning_en: "The Prophets",
        ayat: 112,
        name_ar: "سُورَةُ الأَنبِيَاءِ",
        arabic: "الأَنبِيَاءِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 22,
        name: "Al-Hajj",
        name_en: "Al-Hajj",
        meaning: "Haji",
        meaning_en: "The Pilgrimage",
        ayat: 78,
        name_ar: "سُورَةُ الحَجِّ",
        arabic: "الحَجِّ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 23,
        name: "Al-Mu'minun",
        name_en: "Al-Muminoon",
        meaning: "Orang-Orang Mukmin",
        meaning_en: "The Believers",
        ayat: 118,
        name_ar: "سُورَةُ المُؤۡمِنُونَ",
        arabic: "المُؤۡمِنُونَ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 24,
        name: "An-Nur",
        name_en: "An-Noor",
        meaning: "Cahaya",
        meaning_en: "The Light",
        ayat: 64,
        name_ar: "سُورَةُ النُّورِ",
        arabic: "النُّورِ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 25,
        name: "Al-Furqan",
        name_en: "Al-Furqaan",
        meaning: "Pembeda",
        meaning_en: "The Criterion",
        ayat: 77,
        name_ar: "سُورَةُ الفُرۡقَانِ",
        arabic: "الفُرۡقَانِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 26,
        name: "Asy-Syu'ara",
        name_en: "Ash-Shu'araa",
        meaning: "Para Penyair",
        meaning_en: "The Poets",
        ayat: 227,
        name_ar: "سُورَةُ الشُّعَرَاءِ",
        arabic: "الشُّعَرَاءِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 27,
        name: "An-Naml",
        name_en: "An-Naml",
        meaning: "Semut",
        meaning_en: "The Ant",
        ayat: 93,
        name_ar: "سُورَةُ النَّمۡلِ",
        arabic: "النَّمۡلِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 28,
        name: "Al-Qasas",
        name_en: "Al-Qasas",
        meaning: "Kisah-Kisah",
        meaning_en: "The Stories",
        ayat: 88,
        name_ar: "سُورَةُ القَصَصِ",
        arabic: "القَصَصِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 29,
        name: "Al-'Ankabut",
        name_en: "Al-Ankaboot",
        meaning: "Laba-Laba",
        meaning_en: "The Spider",
        ayat: 69,
        name_ar: "سُورَةُ العَنكَبُوتِ",
        arabic: "العَنكَبُوتِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 30,
        name: "Ar-Rum",
        name_en: "Ar-Room",
        meaning: "Bangsa Romawi",
        meaning_en: "The Romans",
        ayat: 60,
        name_ar: "سُورَةُ الرُّومِ",
        arabic: "الرُّومِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 31,
        name: "Luqman",
        name_en: "Luqman",
        meaning: "Luqman",
        meaning_en: "Luqman",
        ayat: 34,
        name_ar: "سُورَةُ لُقۡمَانَ",
        arabic: "لُقۡمَانَ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 32,
        name: "As-Sajdah",
        name_en: "As-Sajda",
        meaning: "Sujud",
        meaning_en: "The Prostration",
        ayat: 30,
        name_ar: "سُورَةُ السَّجۡدَةِ",
        arabic: "السَّجۡدَةِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 33,
        name: "Al-Ahzab",
        name_en: "Al-Ahzaab",
        meaning: "Golongan yang Bersekutu",
        meaning_en: "The Clans",
        ayat: 73,
        name_ar: "سُورَةُ الأَحۡزَابِ",
        arabic: "الأَحۡزَابِ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 34,
        name: "Saba",
        name_en: "Saba",
        meaning: "Kaum Saba'",
        meaning_en: "Sheba",
        ayat: 54,
        name_ar: "سُورَةُ سَبَإٍ",
        arabic: "سَبَإٍ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 35,
        name: "Fatir",
        name_en: "Faatir",
        meaning: "Pencipta",
        meaning_en: "The Originator",
        ayat: 45,
        name_ar: "سُورَةُ فَاطِرٍ",
        arabic: "فَاطِرٍ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 36,
        name: "Yasin",
        name_en: "Yaseen",
        meaning: "Yasin",
        meaning_en: "Yaseen",
        ayat: 83,
        name_ar: "سُورَةُ يسٓ",
        arabic: "يسٓ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 37,
        name: "As-Saffat",
        name_en: "As-Saaffaat",
        meaning: "Barisan-Barisan",
        meaning_en: "Those drawn up in Ranks",
        ayat: 182,
        name_ar: "سُورَةُ الصَّافَّاتِ",
        arabic: "الصَّافَّاتِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 38,
        name: "Sad",
        name_en: "Saad",
        meaning: "Sad",
        meaning_en: "The letter Saad",
        ayat: 88,
        name_ar: "سُورَةُ صٓ",
        arabic: "صٓ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 39,
        name: "Az-Zumar",
        name_en: "Az-Zumar",
        meaning: "Rombongan",
        meaning_en: "The Groups",
        ayat: 75,
        name_ar: "سُورَةُ الزُّمَرِ",
        arabic: "الزُّمَرِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 40,
        name: "Ghafir",
        name_en: "Ghafir",
        meaning: "Maha Pengampun",
        meaning_en: "The Forgiver",
        ayat: 85,
        name_ar: "سُورَةُ غَافِرٍ",
        arabic: "غَافِرٍ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 41,
        name: "Fussilat",
        name_en: "Fussilat",
        meaning: "Yang Dijelaskan",
        meaning_en: "Explained in detail",
        ayat: 54,
        name_ar: "سُورَةُ فُصِّلَتۡ",
        arabic: "فُصِّلَتۡ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 42,
        name: "Asy-Syura",
        name_en: "Ash-Shura",
        meaning: "Musyawarah",
        meaning_en: "Consultation",
        ayat: 53,
        name_ar: "سُورَةُ الشُّورَىٰ",
        arabic: "الشُّورَىٰ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 43,
        name: "Az-Zukhruf",
        name_en: "Az-Zukhruf",
        meaning: "Perhiasan",
        meaning_en: "Ornaments of gold",
        ayat: 89,
        name_ar: "سُورَةُ الزُّخۡرُفِ",
        arabic: "الزُّخۡرُفِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 44,
        name: "Ad-Dukhan",
        name_en: "Ad-Dukhaan",
        meaning: "Kabut",
        meaning_en: "The Smoke",
        ayat: 59,
        name_ar: "سُورَةُ الدُّخَانِ",
        arabic: "الدُّخَانِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 45,
        name: "Al-Jasiyah",
        name_en: "Al-Jaathiya",
        meaning: "Yang Berlutut",
        meaning_en: "Crouching",
        ayat: 37,
        name_ar: "سُورَةُ الجَاثِيَةِ",
        arabic: "الجَاثِيَةِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 46,
        name: "Al-Ahqaf",
        name_en: "Al-Ahqaaf",
        meaning: "Bukit-Bukit Pasir",
        meaning_en: "The Dunes",
        ayat: 35,
        name_ar: "سُورَةُ الأَحۡقَافِ",
        arabic: "الأَحۡقَافِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 47,
        name: "Muhammad",
        name_en: "Muhammad",
        meaning: "Nabi Muhammad",
        meaning_en: "Muhammad",
        ayat: 38,
        name_ar: "سُورَةُ مُحَمَّدٍ",
        arabic: "مُحَمَّدٍ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 48,
        name: "Al-Fath",
        name_en: "Al-Fath",
        meaning: "Kemenangan",
        meaning_en: "The Victory",
        ayat: 29,
        name_ar: "سُورَةُ الفَتۡحِ",
        arabic: "الفَتۡحِ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 49,
        name: "Al-Hujurat",
        name_en: "Al-Hujuraat",
        meaning: "Kamar-Kamar",
        meaning_en: "The Rooms",
        ayat: 18,
        name_ar: "سُورَةُ الحُجُرَاتِ",
        arabic: "الحُجُرَاتِ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 50,
        name: "Qaf",
        name_en: "Qaaf",
        meaning: "Qaf",
        meaning_en: "The letter Qaaf",
        ayat: 45,
        name_ar: "سُورَةُ قٓ",
        arabic: "قٓ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 51,
        name: "Adz-Dzariyat",
        name_en: "Adh-Dhaariyaat",
        meaning: "Angin yang Menerbangkan",
        meaning_en: "The Winnowing Winds",
        ayat: 60,
        name_ar: "سُورَةُ الذَّارِيَاتِ",
        arabic: "الذَّارِيَاتِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 52,
        name: "At-Tur",
        name_en: "At-Toor",
        meaning: "Bukit Tursina",
        meaning_en: "The Mount",
        ayat: 49,
        name_ar: "سُورَةُ الطُّورِ",
        arabic: "الطُّورِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 53,
        name: "An-Najm",
        name_en: "An-Najm",
        meaning: "Bintang",
        meaning_en: "The Star",
        ayat: 62,
        name_ar: "سُورَةُ النَّجۡمِ",
        arabic: "النَّجۡمِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 54,
        name: "Al-Qamar",
        name_en: "Al-Qamar",
        meaning: "Bulan",
        meaning_en: "The Moon",
        ayat: 55,
        name_ar: "سُورَةُ القَمَرِ",
        arabic: "القَمَرِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 55,
        name: "Ar-Rahman",
        name_en: "Ar-Rahmaan",
        meaning: "Maha Pengasih",
        meaning_en: "The Beneficent",
        ayat: 78,
        name_ar: "سُورَةُ الرَّحۡمَٰن",
        arabic: "الرَّحۡمَٰن",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 56,
        name: "Al-Waqi'ah",
        name_en: "Al-Waaqia",
        meaning: "Hari Kiamat",
        meaning_en: "The Inevitable",
        ayat: 96,
        name_ar: "سُورَةُ الوَاقِعَةِ",
        arabic: "الوَاقِعَةِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 57,
        name: "Al-Hadid",
        name_en: "Al-Hadid",
        meaning: "Besi",
        meaning_en: "The Iron",
        ayat: 29,
        name_ar: "سُورَةُ الحَدِيدِ",
        arabic: "الحَدِيدِ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 58,
        name: "Al-Mujadilah",
        name_en: "Al-Mujaadila",
        meaning: "Gugatan",
        meaning_en: "The Pleading Woman",
        ayat: 22,
        name_ar: "سُورَةُ المُجَادلَةِ",
        arabic: "المُجَادلَةِ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 59,
        name: "Al-Hasyr",
        name_en: "Al-Hashr",
        meaning: "Pengusiran",
        meaning_en: "The Exile",
        ayat: 24,
        name_ar: "سُورَةُ الحَشۡرِ",
        arabic: "الحَشۡرِ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 60,
        name: "Al-Mumtahanah",
        name_en: "Al-Mumtahana",
        meaning: "Wanita yang Diuji",
        meaning_en: "She that is to be examined",
        ayat: 13,
        name_ar: "سُورَةُ المُمۡتَحنَةِ",
        arabic: "المُمۡتَحنَةِ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 61,
        name: "As-Saff",
        name_en: "As-Saff",
        meaning: "Barisan",
        meaning_en: "The Ranks",
        ayat: 14,
        name_ar: "سُورَةُ الصَّفِّ",
        arabic: "الصَّفِّ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 62,
        name: "Al-Jumu'ah",
        name_en: "Al-Jumu'a",
        meaning: "Hari Jumat",
        meaning_en: "Friday",
        ayat: 11,
        name_ar: "سُورَةُ الجُمُعَةِ",
        arabic: "الجُمُعَةِ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 63,
        name: "Al-Munafiqun",
        name_en: "Al-Munaafiqoon",
        meaning: "Orang-Orang Munafik",
        meaning_en: "The Hypocrites",
        ayat: 11,
        name_ar: "سُورَةُ المُنَافِقُونَ",
        arabic: "المُنَافِقُونَ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 64,
        name: "At-Tagabun",
        name_en: "At-Taghaabun",
        meaning: "Pengungkapan Kesalahan",
        meaning_en: "Mutual Disillusion",
        ayat: 18,
        name_ar: "سُورَةُ التَّغَابُنِ",
        arabic: "التَّغَابُنِ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 65,
        name: "At-Talaq",
        name_en: "At-Talaaq",
        meaning: "Talak",
        meaning_en: "Divorce",
        ayat: 12,
        name_ar: "سُورَةُ الطَّلَاقِ",
        arabic: "الطَّلَاقِ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 66,
        name: "At-Tahrim",
        name_en: "At-Tahrim",
        meaning: "Pengharaman",
        meaning_en: "The Prohibition",
        ayat: 12,
        name_ar: "سُورَةُ التَّحۡرِيمِ",
        arabic: "التَّحۡرِيمِ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 67,
        name: "Al-Mulk",
        name_en: "Al-Mulk",
        meaning: "Kerajaan",
        meaning_en: "The Sovereignty",
        ayat: 30,
        name_ar: "سُورَةُ المُلۡكِ",
        arabic: "المُلۡكِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 68,
        name: "Al-Qalam",
        name_en: "Al-Qalam",
        meaning: "Pena",
        meaning_en: "The Pen",
        ayat: 52,
        name_ar: "سُورَةُ القَلَمِ",
        arabic: "القَلَمِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 69,
        name: "Al-Haqqah",
        name_en: "Al-Haaqqa",
        meaning: "Hari Kiamat yang Pasti",
        meaning_en: "The Reality",
        ayat: 52,
        name_ar: "سُورَةُ الحَاقَّةِ",
        arabic: "الحَاقَّةِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 70,
        name: "Al-Ma'arij",
        name_en: "Al-Ma'aarij",
        meaning: "Tempat Naik",
        meaning_en: "The Ascending Stairways",
        ayat: 44,
        name_ar: "سُورَةُ المَعَارِجِ",
        arabic: "المَعَارِجِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 71,
        name: "Nuh",
        name_en: "Nooh",
        meaning: "Nabi Nuh",
        meaning_en: "Noah",
        ayat: 28,
        name_ar: "سُورَةُ نُوحٍ",
        arabic: "نُوحٍ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 72,
        name: "Al-Jin",
        name_en: "Al-Jinn",
        meaning: "Jin",
        meaning_en: "The Jinn",
        ayat: 28,
        name_ar: "سُورَةُ الجِنِّ",
        arabic: "الجِنِّ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 73,
        name: "Al-Muzzammil",
        name_en: "Al-Muzzammil",
        meaning: "Orang yang Berselimut",
        meaning_en: "The Enshrouded One",
        ayat: 20,
        name_ar: "سُورَةُ المُزَّمِّلِ",
        arabic: "المُزَّمِّلِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 74,
        name: "Al-Muddassir",
        name_en: "Al-Muddaththir",
        meaning: "Orang yang Berkemul",
        meaning_en: "The Cloaked One",
        ayat: 56,
        name_ar: "سُورَةُ المُدَّثِّرِ",
        arabic: "المُدَّثِّرِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 75,
        name: "Al-Qiyamah",
        name_en: "Al-Qiyaama",
        meaning: "Hari Kiamat",
        meaning_en: "The Resurrection",
        ayat: 40,
        name_ar: "سُورَةُ القِيَامَةِ",
        arabic: "القِيَامَةِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 76,
        name: "Al-Insan",
        name_en: "Al-Insaan",
        meaning: "Manusia",
        meaning_en: "Man",
        ayat: 31,
        name_ar: "سُورَةُ الإِنسَانِ",
        arabic: "الإِنسَانِ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 77,
        name: "Al-Mursalat",
        name_en: "Al-Mursalaat",
        meaning: "Malaikat yang Diutus",
        meaning_en: "The Emissaries",
        ayat: 50,
        name_ar: "سُورَةُ المُرۡسَلَاتِ",
        arabic: "المُرۡسَلَاتِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 78,
        name: "An-Naba",
        name_en: "An-Naba",
        meaning: "Berita Besar",
        meaning_en: "The Tidings",
        ayat: 40,
        name_ar: "سُورَةُ النَّبَإِ",
        arabic: "النَّبَإِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 79,
        name: "An-Nazi'at",
        name_en: "An-Naazi'aat",
        meaning: "Malaikat yang Mencabut",
        meaning_en: "Those who drag forth",
        ayat: 46,
        name_ar: "سُورَةُ النَّازِعَاتِ",
        arabic: "النَّازِعَاتِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 80,
        name: "'Abasa",
        name_en: "Abasa",
        meaning: "Bermuka Masam",
        meaning_en: "He frowned",
        ayat: 42,
        name_ar: "سُورَةُ عَبَسَ",
        arabic: "عَبَسَ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 81,
        name: "At-Takwir",
        name_en: "At-Takweer",
        meaning: "Menggulung",
        meaning_en: "The Overthrowing",
        ayat: 29,
        name_ar: "سُورَةُ التَّكۡوِيرِ",
        arabic: "التَّكۡوِيرِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 82,
        name: "Al-Infitar",
        name_en: "Al-Infitaar",
        meaning: "Terbelah",
        meaning_en: "The Cleaving",
        ayat: 19,
        name_ar: "سُورَةُ الانفِطَارِ",
        arabic: "الانفِطَارِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 83,
        name: "Al-Mutaffifin",
        name_en: "Al-Mutaffifin",
        meaning: "Orang-Orang yang Curang",
        meaning_en: "Defrauding",
        ayat: 36,
        name_ar: "سُورَةُ المُطَفِّفِينَ",
        arabic: "المُطَفِّفِينَ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 84,
        name: "Al-Insyiqaq",
        name_en: "Al-Inshiqaaq",
        meaning: "Terbelah",
        meaning_en: "The Splitting Open",
        ayat: 25,
        name_ar: "سُورَةُ الانشِقَاقِ",
        arabic: "الانشِقَاقِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 85,
        name: "Al-Buruj",
        name_en: "Al-Burooj",
        meaning: "Gugusan Bintang",
        meaning_en: "The Mansions of the Stars",
        ayat: 22,
        name_ar: "سُورَةُ البُرُوجِ",
        arabic: "البُرُوجِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 86,
        name: "At-Tariq",
        name_en: "At-Taariq",
        meaning: "Yang Datang di Malam Hari",
        meaning_en: "The Morning Star",
        ayat: 17,
        name_ar: "سُورَةُ الطَّارِقِ",
        arabic: "الطَّارِقِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 87,
        name: "Al-A'la",
        name_en: "Al-A'laa",
        meaning: "Maha Tinggi",
        meaning_en: "The Most High",
        ayat: 19,
        name_ar: "سُورَةُ الأَعۡلَىٰ",
        arabic: "الأَعۡلَىٰ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 88,
        name: "Al-Ghasyiyah",
        name_en: "Al-Ghaashiya",
        meaning: "Hari Pembalasan",
        meaning_en: "The Overwhelming",
        ayat: 26,
        name_ar: "سُورَةُ الغَاشِيَةِ",
        arabic: "الغَاشِيَةِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 89,
        name: "Al-Fajr",
        name_en: "Al-Fajr",
        meaning: "Fajar",
        meaning_en: "The Dawn",
        ayat: 30,
        name_ar: "سُورَةُ الفَجۡرِ",
        arabic: "الفَجۡرِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 90,
        name: "Al-Balad",
        name_en: "Al-Balad",
        meaning: "Negeri",
        meaning_en: "The City",
        ayat: 20,
        name_ar: "سُورَةُ البَلَدِ",
        arabic: "البَلَدِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 91,
        name: "Asy-Syams",
        name_en: "Ash-Shams",
        meaning: "Matahari",
        meaning_en: "The Sun",
        ayat: 15,
        name_ar: "سُورَةُ الشَّمۡسِ",
        arabic: "الشَّمۡسِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 92,
        name: "Al-Lail",
        name_en: "Al-Lail",
        meaning: "Malam",
        meaning_en: "The Night",
        ayat: 21,
        name_ar: "سُورَةُ اللَّيۡلِ",
        arabic: "اللَّيۡلِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 93,
        name: "Ad-Duha",
        name_en: "Ad-Dhuhaa",
        meaning: "Waktu Duha",
        meaning_en: "The Morning Hours",
        ayat: 11,
        name_ar: "سُورَةُ الضُّحَىٰ",
        arabic: "الضُّحَىٰ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 94,
        name: "Asy-Syarh",
        name_en: "Ash-Sharh",
        meaning: "Kelapangan",
        meaning_en: "The Relief",
        ayat: 8,
        name_ar: "سُورَةُ الشَّرۡحِ",
        arabic: "الشَّرۡحِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 95,
        name: "At-Tin",
        name_en: "At-Teen",
        meaning: "Buah Tin",
        meaning_en: "The Fig",
        ayat: 8,
        name_ar: "سُورَةُ التِّينِ",
        arabic: "التِّينِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 96,
        name: "Al-'Alaq",
        name_en: "Al-Alaq",
        meaning: "Segumpal Darah",
        meaning_en: "The Clot",
        ayat: 19,
        name_ar: "سُورَةُ العَلَقِ",
        arabic: "العَلَقِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 97,
        name: "Al-Qadr",
        name_en: "Al-Qadr",
        meaning: "Kemuliaan",
        meaning_en: "The Power",
        ayat: 5,
        name_ar: "سُورَةُ القَدۡرِ",
        arabic: "القَدۡرِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 98,
        name: "Al-Bayyinah",
        name_en: "Al-Bayyina",
        meaning: "Bukti Nyata",
        meaning_en: "The Clear Proof",
        ayat: 8,
        name_ar: "سُورَةُ البَيِّنَةِ",
        arabic: "البَيِّنَةِ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 99,
        name: "Az-Zalzalah",
        name_en: "Az-Zalzala",
        meaning: "Keguncangan",
        meaning_en: "The Earthquake",
        ayat: 8,
        name_ar: "سُورَةُ الزَّلۡزَلَةِ",
        arabic: "الزَّلۡزَلَةِ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 100,
        name: "Al-'Adiyat",
        name_en: "Al-Aadiyaat",
        meaning: "Kuda yang Berlari Kencang",
        meaning_en: "The Courser",
        ayat: 11,
        name_ar: "سُورَةُ العَادِيَاتِ",
        arabic: "العَادِيَاتِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 101,
        name: "Al-Qari'ah",
        name_en: "Al-Qaari'a",
        meaning: "Hari Kiamat yang Menggemparkan",
        meaning_en: "The Calamity",
        ayat: 11,
        name_ar: "سُورَةُ القَارِعَةِ",
        arabic: "القَارِعَةِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 102,
        name: "At-Takasur",
        name_en: "At-Takaathur",
        meaning: "Bermegah-megahan",
        meaning_en: "The Rivalry in World Increase",
        ayat: 8,
        name_ar: "سُورَةُ التَّكَاثُرِ",
        arabic: "التَّكَاثُرِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 103,
        name: "Al-'Asr",
        name_en: "Al-Asr",
        meaning: "Masa",
        meaning_en: "The Declining Day",
        ayat: 3,
        name_ar: "سُورَةُ العَصۡرِ",
        arabic: "العَصۡرِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 104,
        name: "Al-Humazah",
        name_en: "Al-Humaza",
        meaning: "Pengumpat",
        meaning_en: "The Traducer",
        ayat: 9,
        name_ar: "سُورَةُ الهُمَزَةِ",
        arabic: "الهُمَزَةِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 105,
        name: "Al-Fil",
        name_en: "Al-Feel",
        meaning: "Gajah",
        meaning_en: "The Elephant",
        ayat: 5,
        name_ar: "سُورَةُ الفِيلِ",
        arabic: "الفِيلِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 106,
        name: "Quraisy",
        name_en: "Quraish",
        meaning: "Suku Quraisy",
        meaning_en: "Quraysh",
        ayat: 4,
        name_ar: "سُورَةُ قُرَيۡشٍ",
        arabic: "قُرَيۡشٍ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 107,
        name: "Al-Ma'un",
        name_en: "Al-Maa'un",
        meaning: "Barang yang Berguna",
        meaning_en: "Small Kindness",
        ayat: 7,
        name_ar: "سُورَةُ المَاعُونِ",
        arabic: "المَاعُونِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 108,
        name: "Al-Kausar",
        name_en: "Al-Kawthar",
        meaning: "Nikmat yang Banyak",
        meaning_en: "Abundance",
        ayat: 3,
        name_ar: "سُورَةُ الكَوۡثَرِ",
        arabic: "الكَوۡثَرِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 109,
        name: "Al-Kafirun",
        name_en: "Al-Kaafiroon",
        meaning: "Orang-Orang Kafir",
        meaning_en: "The Disbelievers",
        ayat: 6,
        name_ar: "سُورَةُ الكَافِرُونَ",
        arabic: "الكَافِرُونَ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 110,
        name: "An-Nasr",
        name_en: "An-Nasr",
        meaning: "Pertolongan",
        meaning_en: "The Divine Support",
        ayat: 3,
        name_ar: "سُورَةُ النَّصۡرِ",
        arabic: "النَّصۡرِ",
        revelation: "Madani",
        revelation_id: "Madaniyah",
        revelation_city: "Madinah",
    },
    {
        number: 111,
        name: "Al-Masad",
        name_en: "Al-Masad",
        meaning: "Gejolak Api",
        meaning_en: "The Palm Fibre",
        ayat: 5,
        name_ar: "سُورَةُ المَسَدِ",
        arabic: "المَسَدِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 112,
        name: "Al-Ikhlas",
        name_en: "Al-Ikhlaas",
        meaning: "Ikhlas",
        meaning_en: "Sincerity",
        ayat: 4,
        name_ar: "سُورَةُ الإِخۡلَاصِ",
        arabic: "الإِخۡلَاصِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 113,
        name: "Al-Falaq",
        name_en: "Al-Falaq",
        meaning: "Waktu Subuh",
        meaning_en: "The Daybreak",
        ayat: 5,
        name_ar: "سُورَةُ الفَلَقِ",
        arabic: "الفَلَقِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
    {
        number: 114,
        name: "An-Nas",
        name_en: "An-Naas",
        meaning: "Manusia",
        meaning_en: "Mankind",
        ayat: 6,
        name_ar: "سُورَةُ النَّاسِ",
        arabic: "النَّاسِ",
        revelation: "Makki",
        revelation_id: "Makkiyah",
        revelation_city: "Makkah",
    },
];

export const findSurahByNumber = (n) =>
    SURAH_LIST.find((s) => s.number === Number(n));

export const getSurahName = (surah, lang = "ID") => {
    const isEn = String(lang ?? "ID").toUpperCase() === "EN";
    const num = Number(
        surah?.number ||
            surah?.surah_number ||
            surah?.surah_id ||
            surah?.surahNumber,
    );
    const item = num ? findSurahByNumber(num) : null;

    if (isEn) {
        return (
            surah?.translation?.latin_en ||
            item?.name_en ||
            item?.name ||
            surah?.translation?.latin_idn ||
            surah?.slug ||
            ""
        );
    }

    return (
        surah?.translation?.latin_idn ||
        item?.name ||
        surah?.translation?.latin_en ||
        surah?.slug ||
        ""
    );
};

export const getSurahMeaning = (surah, lang = "ID") => {
    const isEn = String(lang ?? "ID").toUpperCase() === "EN";
    const num = Number(
        surah?.number ||
            surah?.surah_number ||
            surah?.surah_id ||
            surah?.surahNumber,
    );
    const item = num ? findSurahByNumber(num) : null;

    if (isEn) {
        return (
            surah?.translation?.name_en ||
            surah?.translation?.en ||
            item?.meaning_en ||
            surah?.translation?.name_translation ||
            ""
        );
    }

    return (
        item?.meaning ||
        surah?.translation?.name_idn ||
        surah?.translation?.idn ||
        surah?.translation?.en ||
        surah?.arti ||
        ""
    );
};

export const getSurahRevelation = (surah, lang = "EN") => {
    const num = Number(
        surah?.number ||
            surah?.surah_number ||
            surah?.surah_id ||
            surah?.surahNumber,
    );
    const item = num ? findSurahByNumber(num) : null;
    const isId = String(lang ?? "").toUpperCase() === "ID";
    if (isId) {
        return (
            surah?.revelation_id ||
            item?.revelation_id ||
            (surah?.revelation_type === "Medinan" ? "Madaniyah" : "Makkiyah")
        );
    }
    return (
        surah?.revelation ||
        item?.revelation ||
        (surah?.revelation_type === "Medinan" ? "Madani" : "Makki")
    );
};

export const getSurahCity = (surah) => {
    const num = Number(
        surah?.number ||
            surah?.surah_number ||
            surah?.surah_id ||
            surah?.surahNumber,
    );
    const item = num ? findSurahByNumber(num) : null;
    return (
        surah?.revelation_city ||
        item?.revelation_city ||
        (surah?.revelation_type === "Medinan" ? "Madinah" : "Makkah")
    );
};

export const getSurahArabic = (surah) => {
    const num = Number(
        surah?.number ||
            surah?.surah_number ||
            surah?.surah_id ||
            surah?.surahNumber,
    );
    const item = num ? findSurahByNumber(num) : null;
    return (
        surah?.arabic ||
        item?.arabic ||
        surah?.name_ar ||
        item?.name_ar ||
        ""
    );
};

export const getSurahFullNameAr = (surah) => {
    const num = Number(
        surah?.number ||
            surah?.surah_number ||
            surah?.surah_id ||
            surah?.surahNumber,
    );
    const item = num ? findSurahByNumber(num) : null;
    return surah?.name_ar || item?.name_ar || surah?.arabic || item?.arabic || "";
};
