export const asmaulHusnaData = {
    1: {
        number: 1,
        latin: "Allah",
        arabic: "اللَّهُ",
        meaning_idn: "Nama Allah Yang Maha Agung",
        meaning_en: "The Greatest Name of Allah",
        explanation:
            "Nama Allah yang paling agung (Al-Ism Al-A'zham) yang mencakup seluruh makna nama-nama dan sifat-sifat kesempurnaan-Nya. Tidak ada yang berhak menyandang nama ini selain Dia semata.",
        dalilRef: "QS. Thaha: 14",
        dalilText: "إِنَّنِي أَنَا اللَّهُ لَا إِلَٰهَ إِلَّا أَنَا فَاعْبُدْنِي وَأَقِمِ الصَّلَاةَ لِذِكْرِي",
        dalilTrans:
            "Sungguh, Aku ini Allah, tidak ada tuhan selain Aku, maka sembahlah Aku dan laksanakanlah sholat untuk mengingat-Ku.",
        ulamaQuote:
            "Ibnu Katsir rahimahullah: 'Nama Allah adalah 'alam (nama khusus) bagi Rabb Tabaraka wa Ta'ala, dan merupakan pokok asal dari seluruh Asma'ul Husna.' (Tafsir Ibnu Katsir)",
        internalLink: "/quran/surah/20#verse-14",
        linkLabel: "Buka QS. Thaha: 14 di Quran",
    },
    2: {
        number: 2,
        latin: "Ar-Rahman",
        arabic: "الرَّحْمَنُ",
        meaning_idn: "Yang Maha Pengasih",
        meaning_en: "The Most Gracious",
        explanation:
            "Maha Pemilik rahmat yang sangat luas mencakup seluruh makhluk di alam semesta, baik yang beriman maupun yang kafir, dalam kehidupan dunia.",
        dalilRef: "QS. Al-Fatihah: 3",
        dalilText: "الرَّحْمَٰنِ الرَّحِيمِ",
        dalilTrans: "Yang Maha Pengasih, Maha Penyayang.",
        ulamaQuote:
            "Syaikh As-Sa'di: 'Ar-Rahman menunjukkan sifat dzatiyah Allah yang maha luas kasih sayang-Nya bagi segala sesuatu.' (Taisir Karimir Rahman)",
        internalLink: "/quran/surah/1#verse-3",
        linkLabel: "Buka QS. Al-Fatihah: 3 di Quran",
    },
    3: {
        number: 3,
        latin: "Ar-Rahim",
        arabic: "الرَّحِيمُ",
        meaning_idn: "Yang Maha Penyayang",
        meaning_en: "The Most Merciful",
        explanation:
            "Maha Penyayang yang melimpahkan rahmat dan kasih sayang khusus kepada hamba-hamba-Nya yang beriman di dunia dan terutama di akhirat kelak.",
        dalilRef: "QS. Al-Ahzab: 43",
        dalilText: "وَكَانَ بِالْمُؤْمِنِينَ رَحِيمًا",
        dalilTrans: "Dan Dia Maha Penyayang kepada orang-orang yang beriman.",
        ulamaQuote:
            "Ibnul Qayyim: 'Ar-Rahman adalah sifat kasih sayang yang menetap pada Dzat-Nya, sedangkan Ar-Rahim adalah perbuatan-Nya menyampaikan rahmat kepada orang-orang yang dirahmati-Nya.' (Bada'i al-Fawa'id)",
        internalLink: "/quran/surah/33#verse-43",
        linkLabel: "Buka QS. Al-Ahzab: 43 di Quran",
    },
    4: {
        number: 4,
        latin: "Al-Malik",
        arabic: "الْمَلِكُ",
        meaning_idn: "Yang Maha Merajai",
        meaning_en: "The Absolute Sovereign",
        explanation:
            "Maha Memiliki kerajaan mutlak di langit dan bumi. Dialah Penguasa yang mengatur, memerintah, dan menentukan segala urusan makhluk tanpa ada yang menandingi.",
        dalilRef: "QS. Al-Hasyr: 23",
        dalilText: "هُوَ اللَّهُ الَّذِي لَا إِلَٰهَ إِلَّا هُوَ الْمَلِكُ الْقُدُّوسُ السَّلَامُ",
        dalilTrans:
            "Dialah Allah tidak ada tuhan selain Dia. Maharaja, Yang Mahasuci, Yang Mahasejahtera...",
        ulamaQuote:
            "Imam Al-Qurthubi: 'Al-Malik adalah Dzat yang tidak membutuhkan kepada siapapun, sedangkan segala sesuatu membutuhkan-Nya.'",
        internalLink: "/quran/surah/59#verse-23",
        linkLabel: "Buka QS. Al-Hasyr: 23 di Quran",
    },
    5: {
        number: 5,
        latin: "Al-Quddus",
        arabic: "الْقُدُّوسُ",
        meaning_idn: "Yang Maha Suci",
        meaning_en: "The Most Holy",
        explanation:
            "Maha Suci dan bersih dari segala bentuk kekurangan, aib, kelemahan, sekutu, anak, maupun keserupaan dengan makhluk-Nya.",
        dalilRef: "QS. Al-Jumu'ah: 1",
        dalilText: "يُسَبِّحُ لِلَّهِ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ الْمَلِكِ الْقُدُّوسِ الْعَزِيزِ الْحَكِيمِ",
        dalilTrans:
            "Apa yang ada di langit dan apa yang ada di bumi senantiasa bertasbih kepada Allah. Maharaja, Yang Mahasuci, Yang Mahaperkasa, Mahabijaksana.",
        ulamaQuote:
            "Syaikh Shalih Al-Fauzan: 'Al-Quddus adalah Yang Maha Suci dari segala sesuatu yang tidak layak bagi keagungan dan kemuliaan-Nya.'",
        internalLink: "/quran/surah/62#verse-1",
        linkLabel: "Buka QS. Al-Jumu'ah: 1 di Quran",
    },
    6: {
        number: 6,
        latin: "As-Salam",
        arabic: "السَّلَامُ",
        meaning_idn: "Yang Maha Memberi Kesejahteraan",
        meaning_en: "The Source of Peace and Perfection",
        explanation:
            "Maha Selamat dari segala aib dan kekurangan, serta Dzat yang mengaruniakan keselamatan dan kedamaian kepada hamba-hamba-Nya.",
        dalilRef: "QS. Al-Hasyr: 23",
        dalilText: "الْمَلِكُ الْقُدُّوسُ السَّلَامُ الْمُؤْمِنُ الْمُهَيْمِنُ",
        dalilTrans: "...Maharaja, Yang Mahasuci, Yang Mahasejahtera, Yang Menjaga Keamanan, Pemelihara Keselamatan...",
        ulamaQuote:
            "Rasulullah ﷺ berdoa setelah sholat: 'Allahumma antas salam wa minkas salam tabarakta ya dzal jalali wal ikram.' (HR. Muslim 592)",
        internalLink: "/hadith/muslim/592",
        linkLabel: "Buka HR. Muslim No. 592 di Hadits",
    },
    7: {
        number: 7,
        latin: "Al-Mu'min",
        arabic: "الْمُؤْمِنُ",
        meaning_idn: "Yang Maha Memberi Keamanan",
        meaning_en: "The Granter of Security and Faith",
        explanation:
            "Dzat yang membenarkan para rasul-Nya dengan mukjizat, menepati janji-Nya kepada kaum mukminin, dan memberi rasa aman dari rasa takut dan azab yang zalim.",
        dalilRef: "QS. Quraisy: 4",
        dalilText: "الَّذِي أَطْعَمَهُمْ مِنْ جُوعٍ وَآمَنَهُمْ مِنْ خَوْفٍ",
        dalilTrans: "Yang telah memberi makanan kepada mereka untuk menghilangkan lapar dan mengamankan mereka dari rasa takut.",
        ulamaQuote:
            "Mujahid rahimahullah: 'Al-Mu'min adalah Yang mengesakan Diri-Nya sendiri dengan firman-Nya: Syahidallahu annahu la ilaha illa Huwa.'",
        internalLink: "/quran/surah/106#verse-4",
        linkLabel: "Buka QS. Quraisy: 4 di Quran",
    },
    8: {
        number: 8,
        latin: "Al-Muhaymin",
        arabic: "الْمُهَيْمِنُ",
        meaning_idn: "Yang Maha Mengawasi & Memelihara",
        meaning_en: "The Guardian & Overseer",
        explanation:
            "Dzat yang mengawasi seluruh amal perbuatan hamba-Nya, menjaga rezeki dan ajal mereka, serta memelihara seluruh ciptaan dengan keadilan-Nya.",
        dalilRef: "QS. Al-Hasyr: 23",
        dalilText: "الْمُؤْمِنُ الْمُهَيْمِنُ الْعَزِيزُ الْجَبَّارُ",
        dalilTrans: "...Yang Menjaga Keamanan, Pemelihara Keselamatan, Yang Mahaperkasa, Yang Mahakuasa...",
        ulamaQuote:
            "Ibnu Abbas: 'Al-Muhaymin adalah Yang Maha Menyaksikan lagi Maha Menjaga terhadap amal-amal hamba-Nya.' (Tafsir Ath-Thabari)",
        internalLink: "/quran/surah/59#verse-23",
        linkLabel: "Buka QS. Al-Hasyr: 23 di Quran",
    },
    9: {
        number: 9,
        latin: "Al-Aziz",
        arabic: "الْعَزِيزُ",
        meaning_idn: "Yang Maha Perkasa",
        meaning_en: "The Almighty",
        explanation:
            "Maha Perkasa dan tidak terkalahkan. Kemuliaan dan keperkasaan-Nya meliputi keperkasaan kekuatan, keperkasaan pencegahan, dan keperkasaan penundukan.",
        dalilRef: "QS. Ali 'Imran: 62",
        dalilText: "وَإِنَّ اللَّهَ لَهُوَ الْعَزِيزُ الْحَكِيمُ",
        dalilTrans: "Dan sesungguhnya Allah, Dialah Yang Mahaperkasa, Mahabijaksana.",
        ulamaQuote:
            "Syaikh As-Sa'di: 'Al-Aziz bermakna Dzat yang memiliki seluruh makna keperkasaan, yang tidak ada seorang pun mampu mendatangkan mudarat atau menandingi-Nya.'",
        internalLink: "/quran/surah/3#verse-62",
        linkLabel: "Buka QS. Ali 'Imran: 62 di Quran",
    },
    10: {
        number: 10,
        latin: "Al-Jabbar",
        arabic: "الْجَبَّارُ",
        meaning_idn: "Yang Maha Kuasa & Memperbaiki",
        meaning_en: "The Compeller & Restorer",
        explanation:
            "Maha Kuasa menundukkan seluruh makhluk, Maha Tinggi di atas mereka, dan Maha Memperbaiki hati orang-orang yang patah serta mencukupi orang yang fakir.",
        dalilRef: "QS. Al-Hasyr: 23",
        dalilText: "الْعَزِيزُ الْجَبَّارُ الْمُتَكَبِّرُ",
        dalilTrans: "...Yang Mahaperkasa, Yang Mahakuasa, Yang Memiliki Segala Keagungan...",
        ulamaQuote:
            "Doa Nabi ﷺ saat duduk di antara dua sujud: 'Rabbighfirli warhamni wajburni...' (Wahai Rabbku ampunilah aku, rahmatilah aku, dan cukupkan/perbaikilah keadaanku). (HR. Abu Dawud 850)",
        internalLink: "/quran/surah/59#verse-23",
        linkLabel: "Buka QS. Al-Hasyr: 23 di Quran",
    },
    11: {
        number: 11,
        latin: "Al-Mutakabbir",
        arabic: "الْمُتَكَبِّرُ",
        meaning_idn: "Yang Maha Megah & Agung",
        meaning_en: "The Supreme",
        explanation:
            "Maha Memiliki segala kebesaran dan keagungan sejati, Maha Tinggi dari segala keburukan dan kezaliman.",
        dalilRef: "QS. Al-Hasyr: 23",
        dalilText: "سُبْحَانَ اللَّهِ عَمَّا يُشْرِكُونَ",
        dalilTrans: "Mahasuci Allah dari apa yang mereka persekutukan.",
        ulamaQuote:
            "Hadits Qudsi: 'Keagungan adalah sarung-Ku dan kesombongan adalah selendang-Ku, barangsiapa merebut salah satunya maka Aku akan mengazabnya.' (HR. Muslim 2620)",
        internalLink: "/hadith/muslim/2620",
        linkLabel: "Buka HR. Muslim No. 2620 di Hadits",
    },
    12: {
        number: 12,
        latin: "Al-Khaliq",
        arabic: "الْخَالِقُ",
        meaning_idn: "Yang Maha Pencipta",
        meaning_en: "The Creator",
        explanation:
            "Dzat yang menciptakan segala sesuatu dari tiada menjadi ada sesuai dengan takdir dan ukuran yang Dia tentukan.",
        dalilRef: "QS. Az-Zumar: 62",
        dalilText: "اللَّهُ خَالِقُ كُلِّ شَيْءٍ ۖ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ وَكِيلٌ",
        dalilTrans: "Allah pencipta segala sesuatu dan Dia Maha Pemelihara atas segala sesuatu.",
        ulamaQuote:
            "Imam Ibnu Katsir: 'Al-Khaliq adalah Dzat yang mentakdirkan dan mengadakan segala sesuatu tanpa ada teladan sebelumnya.'",
        internalLink: "/quran/surah/39#verse-62",
        linkLabel: "Buka QS. Az-Zumar: 62 di Quran",
    },
    13: {
        number: 13,
        latin: "Al-Bari'",
        arabic: "الْبَارِئُ",
        meaning_idn: "Yang Maha Mengadakan",
        meaning_en: "The Evolver & Originator",
        explanation:
            "Dzat yang mewujudkan ciptaan ke alam nyata dan memisahkan karakteristik antar makhluk satu dengan makhluk lainnya dengan teratur.",
        dalilRef: "QS. Al-Hasyr: 24",
        dalilText: "هُوَ اللَّهُ الْخَالِقُ الْبَارِئُ الْمُصَوِّرُ",
        dalilTrans: "Dialah Allah Yang Menciptakan, Yang Mengadakan, Yang Membentuk Rupa...",
        ulamaQuote:
            "Syaikh Abdurrazzaq al-Badr: 'Al-Khaliq adalah penentu takdir, Al-Bari' adalah pelaksana yang mengeluarkannya menjadi wujud.'",
        internalLink: "/quran/surah/59#verse-24",
        linkLabel: "Buka QS. Al-Hasyr: 24 di Quran",
    },
    14: {
        number: 14,
        latin: "Al-Musawwir",
        arabic: "الْمُصَوِّرُ",
        meaning_idn: "Yang Maha Membentuk Rupa",
        meaning_en: "The Fashioner",
        explanation:
            "Dzat yang memberi bentuk, rupa, dan ciri khas yang beraneka ragam kepada setiap makhluk sesuai dengan hikmah-Nya.",
        dalilRef: "QS. Ghafir: 64",
        dalilText: "وَصَوَّرَكُمْ فَأَحْسَنَ صُوَرَكُمْ وَرَزَقَكُمْ مِنَ الطَّيِّبَاتِ",
        dalilTrans: "...dan Dia membentuk rupamu lalu memperbagus rupamu serta memberi rezeki kepadamu yang baik-baik...",
        ulamaQuote:
            "Imam Ath-Thabari: 'Al-Musawwir adalah Dzat yang menyusun bentuk setiap ciptaan sebagaimana yang Dia kehendaki.'",
        internalLink: "/quran/surah/40#verse-64",
        linkLabel: "Buka QS. Ghafir: 64 di Quran",
    },
    15: {
        number: 15,
        latin: "Al-Ghaffar",
        arabic: "الْغَفَّارُ",
        meaning_idn: "Yang Maha Pengampun",
        meaning_en: "The Great Forgiver",
        explanation:
            "Dzat yang berulang-ulang menutup dan mengampuni dosa hamba-Nya sebanyak apapun kesalahan itu ketika hamba-Nya bertaubat.",
        dalilRef: "QS. Nuh: 10",
        dalilText: "فَقُلْتُ اسْتَغْفِرُوا رَبَّكُمْ إِنَّهُ كَانَ غَفَّارًا",
        dalilTrans: "maka aku berkata (kepada mereka), 'Mohonlah ampunan kepada Tuhanmu, sungguh, Dia Maha Pengampun.'",
        ulamaQuote:
            "Imam Al-Khatthabi: 'Al-Ghaffar adalah Dzat yang senantiasa memaafkan dosa hamba-Nya berulang kali saat mereka memohon ampun.'",
        internalLink: "/quran/surah/71#verse-10",
        linkLabel: "Buka QS. Nuh: 10 di Quran",
    },
    16: {
        number: 16,
        latin: "Al-Qahhar",
        arabic: "الْقَهَّارُ",
        meaning_idn: "Yang Maha Menundukkan",
        meaning_en: "The All-Dominant",
        explanation:
            "Dzat yang menundukkan seluruh makhluk di bawah kekuasaan dan kehendak-Nya. Segala sesuatu tunduk dan patuh di hadapan kebesaran-Nya.",
        dalilRef: "QS. Ar-Ra'd: 16",
        dalilText: "قُلِ اللَّهُ خَالِقُ كُلِّ شَيْءٍ وَهُوَ الْوَاحِدُ الْقَهَّارُ",
        dalilTrans: "Katakanlah: 'Allah adalah Pencipta segala sesuatu dan Dialah Yang Maha Esa, Maha Menundukkan.'",
        ulamaQuote:
            "Syaikh As-Sa'di: 'Al-Qahhar adalah Yang menundukkan semua alam semesta, yang ubun-ubun semua makhluk berada di tangan-Nya.'",
        internalLink: "/quran/surah/13#verse-16",
        linkLabel: "Buka QS. Ar-Ra'd: 16 di Quran",
    },
    17: {
        number: 17,
        latin: "Al-Wahhab",
        arabic: "الْوَهَّابُ",
        meaning_idn: "Yang Maha Pemberi Karunia",
        meaning_en: "The Supreme Bestower",
        explanation:
            "Dzat yang melimpahkan berbagai anugerah dan pemberian tanpa batas serta tanpa meminta balasan sedikitpun dari makhluk-Nya.",
        dalilRef: "QS. Ali 'Imran: 8",
        dalilText: "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِنْ لَدُنْكَ رَحْمَةً ۚ إِنَّكَ أَنْتَ الْوَهَّابُ",
        dalilTrans: "...dan karuniakanlah kepada kami rahmat dari sisi-Mu; sungguh, Engkau Maha Pemberi (karunia).",
        ulamaQuote:
            "Ibnul Qayyim: 'Pemberian Allah kepada hamba-Nya merupakan karunia murni (hibah), bukan karena kewajiban atas-Nya.'",
        internalLink: "/quran/surah/3#verse-8",
        linkLabel: "Buka QS. Ali 'Imran: 8 di Quran",
    },
    18: {
        number: 18,
        latin: "Ar-Razzaq",
        arabic: "الرَّزَّاقُ",
        meaning_idn: "Yang Maha Pemberi Rezeki",
        meaning_en: "The Total Provider",
        explanation:
            "Dzat yang menciptakan rezeki dan menjamin pembagiannya untuk seluruh makhluk, baik rezeki lahiriyah berupa makanan maupun batiniyah berupa ilmu dan iman.",
        dalilRef: "QS. Adz-Dzariyat: 58",
        dalilText: "إِنَّ اللَّهَ هُوَ الرَّزَّاقُ ذُو الْقُوَّةِ الْمَتِينُ",
        dalilTrans: "Sungguh Allah, Dialah Pemberi rezeki Yang Mempunyai Kekuatan lagi Sangat Kokoh.",
        ulamaQuote:
            "Imam Ibnu Katsir: 'Ar-Razzaq maknanya adalah Yang melimpahkan rezeki kepada seluruh makhluk-Nya tanpa terkecuali.'",
        internalLink: "/quran/surah/51#verse-58",
        linkLabel: "Buka QS. Adz-Dzariyat: 58 di Quran",
    },
    19: {
        number: 19,
        latin: "Al-Fattah",
        arabic: "الْفَتَّاحُ",
        meaning_idn: "Yang Maha Pembuka",
        meaning_en: "The Supreme Opener & Judge",
        explanation:
            "Dzat yang membuka pintu-pintu rahmat, rezeki, dan kebaikan, serta Maha Memutuskan perselisihan di antara hamba-Nya dengan hukum yang adil.",
        dalilRef: "QS. Saba': 26",
        dalilText: "قُلْ يَجْمَعُ بَيْنَنَا رَبُّنَا ثُمَّ يَفْتَحُ بَيْنَنَا بِالْحَقِّ وَهُوَ الْفَتَّاحُ الْعَلِيمُ",
        dalilTrans: "Katakanlah, 'Tuhan kita akan mengumpulkan kita semua, kemudian Dia memberi keputusan antara kita dengan benar. Dan Dialah Maha Pemberi Keputusan, Maha Mengetahui.'",
        ulamaQuote:
            "Syaikh As-Sa'di: 'Al-Fattah membuka pintu rezeki dan rahmat, serta membukakan hati hamba-Nya untuk menerima petunjuk kebenaran.'",
        internalLink: "/quran/surah/34#verse-26",
        linkLabel: "Buka QS. Saba': 26 di Quran",
    },
    20: {
        number: 20,
        latin: "Al-'Alim",
        arabic: "الْعَلِيمُ",
        meaning_idn: "Yang Maha Mengetahui",
        meaning_en: "The All-Knowing",
        explanation:
            "Dzat yang ilmu-Nya meliputi segala sesuatu, baik yang tampak maupun yang gaib, yang lalu, sekarang, maupun yang akan datang, hingga lintasan hati manusia.",
        dalilRef: "QS. Al-Baqarah: 29",
        dalilText: "وَهُوَ بِكُلِّ شَيْءٍ عَلِيمٌ",
        dalilTrans: "...dan Dia Maha Mengetahui segala sesuatu.",
        ulamaQuote:
            "Imam Ath-Thabari: 'Tiada satupun helai daun yang jatuh melainkan Dia mengetahuinya, ilmu-Nya tidak diawali ketidaktahuan dan tidak tertimpa lupa.'",
        internalLink: "/quran/surah/2#verse-29",
        linkLabel: "Buka QS. Al-Baqarah: 29 di Quran",
    },
    21: {
        number: 21,
        latin: "Al-Qabidh",
        arabic: "الْقَابِضُ",
        meaning_idn: "Yang Maha Menyempitkan",
        meaning_en: "The Withholder",
        explanation:
            "Dzat yang menahan dan menyempitkan rezeki atau nyawa seseorang sesuai dengan keadilan dan hikmah-Nya yang mendalam.",
        dalilRef: "QS. Al-Baqarah: 245",
        dalilText: "وَاللَّهُ يَقْبِضُ وَيَبْسُطُ وَإِلَيْهِ تُرْجَعُونَ",
        dalilTrans: "...Dan Allah menyempitkan dan melapangkan (rezeki) dan kepada-Nyalah kamu dikembalikan.",
        ulamaQuote:
            "Nabi ﷺ bersabda: 'Sesungguhnya Allah adalah Al-Khaliq, Al-Qabidh, Al-Basith, Ar-Razzaq...' (HR. Tirmidzi 1314, Abu Dawud 3451)",
        internalLink: "/quran/surah/2#verse-245",
        linkLabel: "Buka QS. Al-Baqarah: 245 di Quran",
    },
    22: {
        number: 22,
        latin: "Al-Basith",
        arabic: "الْبَاسِطُ",
        meaning_idn: "Yang Maha Melapangkan",
        meaning_en: "The Extender & Reliever",
        explanation:
            "Dzat yang meluaskan dan melapangkan rezeki, kemudahan, dan rahmat kepada hamba-hamba yang dikehendaki-Nya.",
        dalilRef: "QS. Asy-Syura: 27",
        dalilText: "وَلَوْ بَسَطَ اللَّهُ الرِّزْقَ لِعِبَادِهِ لَبَغَوْا فِي الْأَرْضِ",
        dalilTrans: "Dan sekiranya Allah melapangkan rezeki kepada hamba-hamba-Nya niscaya mereka akan berbuat melampaui batas di bumi...",
        ulamaQuote:
            "Syaikh As-Sa'di: 'Al-Basith membentangkan rezeki lahiriah dan kelapangan dada serta ketentraman jiwa bagi kaum mukminin.'",
        internalLink: "/quran/surah/42#verse-27",
        linkLabel: "Buka QS. Asy-Syura: 27 di Quran",
    },
    23: {
        number: 23,
        latin: "Al-Khafidh",
        arabic: "الْخَافِضُ",
        meaning_idn: "Yang Maha Merendahkan",
        meaning_en: "The Abaser",
        explanation:
            "Dzat yang merendahkan orang-orang kafir, sombong, dan zalim dengan kehinaan di dunia dan azab di akhirat.",
        dalilRef: "QS. Al-Waqi'ah: 3",
        dalilText: "خَافِضَةٌ رَافِعَةٌ",
        dalilTrans: "(Kejadian itu) merendahkan (satu golongan) dan meninggikan (golongan yang lain).",
        ulamaQuote:
            "Imam Al-Baghawi: 'Merendahkan musuh-musuh-Nya ke dalam neraka, dan meninggikan para wali-Nya ke dalam surga.'",
        internalLink: "/quran/surah/56#verse-3",
        linkLabel: "Buka QS. Al-Waqi'ah: 3 di Quran",
    },
    24: {
        number: 24,
        latin: "Ar-Rafi'",
        arabic: "الرَّافِعُ",
        meaning_idn: "Yang Maha Meninggikan",
        meaning_en: "The Exalter",
        explanation:
            "Dzat yang meninggikan derajat orang-orang yang beriman, berilmu, dan bertakwa baik dalam kehidupan dunia maupun di akhirat.",
        dalilRef: "QS. Al-Mujadilah: 11",
        dalilText: "يَرْفَعِ اللَّهُ الَّذِينَ آمَنُوا مِنْكُمْ وَالَّذِينَ أُوتُوا الْعِلْمَ دَرَجَاتٍ",
        dalilTrans: "...Niscaya Allah akan mengangkat (derajat) orang-orang yang beriman di antaramu dan orang-orang yang diberi ilmu beberapa derajat...",
        ulamaQuote:
            "Ibnu Abbas: 'Allah meninggikan kedudukan orang berilmu di atas kaum mukmin lainnya sebanyak tujuh ratus derajat.'",
        internalLink: "/quran/surah/58#verse-11",
        linkLabel: "Buka QS. Al-Mujadilah: 11 di Quran",
    },
    25: {
        number: 25,
        latin: "Al-Mu'izz",
        arabic: "الْمُعِزُّ",
        meaning_idn: "Yang Maha Memuliakan",
        meaning_en: "The Bestower of Honor",
        explanation:
            "Dzat yang menganugerahkan kemuliaan, kejayaan, dan kehormatan sejati kepada hamba-hamba yang taat kepada-Nya.",
        dalilRef: "QS. Ali 'Imran: 26",
        dalilText: "تُعِزُّ مَنْ تَشَاءُ وَتُذِلُّ مَنْ تَشَاءُ ۖ بِيَدِكَ الْخَيْرُ",
        dalilTrans: "...Engkau muliakan siapa pun yang Engkau kehendaki dan Engkau hinakan siapa pun yang Engkau kehendaki. Di tangan-Mulah segala kebajikan...",
        ulamaQuote:
            "Hasan Al-Bashri: 'Barangsiapa mencari kemuliaan dengan ketaatan kepada Allah, maka Allah pasti memuliakannya.'",
        internalLink: "/quran/surah/3#verse-26",
        linkLabel: "Buka QS. Ali 'Imran: 26 di Quran",
    },
    26: {
        number: 26,
        latin: "Al-Mudzill",
        arabic: "الْمُذِلُّ",
        meaning_idn: "Yang Maha Menghinakan",
        meaning_en: "The Dishonorer",
        explanation:
            "Dzat yang menimpakan kehinaan dan kenistaan kepada orang-orang yang ingkar, durhaka, dan sombong terhadap syariat-Nya.",
        dalilRef: "QS. Ali 'Imran: 26",
        dalilText: "وَتُذِلُّ مَنْ تَشَاءُ ۖ بِيَدِكَ الْخَيْرُ ۖ إِنَّكَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
        dalilTrans: "...dan Engkau hinakan siapa pun yang Engkau kehendaki. Di tangan-Mulah segala kebajikan. Sungguh, Engkau Mahakuasa atas segala sesuatu.",
        ulamaQuote:
            "Imam Al-Ghazali: 'Kehinaan yang hakiki adalah dicabutnya taufik dan dibiarkannya manusia menuruti hawa nafsunya.'",
        internalLink: "/quran/surah/3#verse-26",
        linkLabel: "Buka QS. Ali 'Imran: 26 di Quran",
    },
    27: {
        number: 27,
        latin: "As-Sami'",
        arabic: "السَّمِيعُ",
        meaning_idn: "Yang Maha Mendengar",
        meaning_en: "The All-Hearing",
        explanation:
            "Dzat yang mendengar seluruh suara makhluk tanpa ada yang terluput, baik yang diucapkan dengan lantang maupun bisikan rahasia di dalam hati.",
        dalilRef: "QS. Asy-Syura: 11",
        dalilText: "لَيْسَ كَمِثْلِهِ شَيْءٌ ۖ وَهُوَ السَّمِيعُ الْبَصِيرُ",
        dalilTrans: "...Tidak ada sesuatu pun yang serupa dengan Dia. Dan Dia Yang Maha Mendengar, Maha Melihat.",
        ulamaQuote:
            "Aisyah radhiyallahu 'anha: 'Maha Suci Dzat yang pendengaran-Nya meliputi segala suara.' (HR. Bukhari 7386)",
        internalLink: "/quran/surah/42#verse-11",
        linkLabel: "Buka QS. Asy-Syura: 11 di Quran",
    },
    28: {
        number: 28,
        latin: "Al-Bashir",
        arabic: "الْبَصِيرُ",
        meaning_idn: "Yang Maha Melihat",
        meaning_en: "The All-Seeing",
        explanation:
            "Dzat yang melihat segala sesuatu, yang nyata maupun yang tersembunyi di kegelapan malam yang paling pekat, hingga gerakan semut hitam di atas batu hitam.",
        dalilRef: "QS. Al-Mulk: 19",
        dalilText: "إِنَّهُ بِكُلِّ شَيْءٍ بَصِيرٌ",
        dalilTrans: "...Sungguh, Dia Maha Melihat segala sesuatu.",
        ulamaQuote:
            "Syaikh As-Sa'di: 'Al-Bashir melihat seluruh apa yang ada di alam raya tanpa batas ruang dan waktu.'",
        internalLink: "/quran/surah/67#verse-19",
        linkLabel: "Buka QS. Al-Mulk: 19 di Quran",
    },
    29: {
        number: 29,
        latin: "Al-Hakam",
        arabic: "الْحَكَمُ",
        meaning_idn: "Yang Maha Menetapkan Hukum",
        meaning_en: "The Impartial Judge",
        explanation:
            "Dzat Hakim yang menetapkan hukum dengan seadil-adilnya. Tidak ada seorang pun yang mampu menolak atau mengubah ketetapan hukum-Nya.",
        dalilRef: "QS. Al-An'am: 114",
        dalilText: "أَفَغَيْرَ اللَّهِ أَبْتَغِي حَكَمًا وَهُوَ الَّذِي أَنْزَلَ إِلَيْكُمُ الْكِتَابَ مُفَصَّلًا",
        dalilTrans: "Pantaskah aku mencari hakim selain Allah, padahal Dialah yang menurunkan Kitab (Al-Qur'an) kepadamu secara rinci?",
        ulamaQuote:
            "Nabi ﷺ bersabda kepada Hani': 'Sesungguhnya Allah adalah Al-Hakam, dan kepada-Nyalah tempat kembalinya segala hukum.' (HR. Abu Dawud 4955)",
        internalLink: "/quran/surah/6#verse-114",
        linkLabel: "Buka QS. Al-An'am: 114 di Quran",
    },
    30: {
        number: 30,
        latin: "Al-'Adl",
        arabic: "الْعَدْلُ",
        meaning_idn: "Yang Maha Adil",
        meaning_en: "The Embodiment of Justice",
        explanation:
            "Dzat yang suci dari segala perbuatan aniaya dan kezaliman. Seluruh ketetapan, syariat, dan balasan-Nya adalah mutlak berlandaskan keadilan.",
        dalilRef: "QS. Al-An'am: 115",
        dalilText: "وَتَمَّتْ كَلِمَتُ رَبِّكَ صِدْقًا وَعَدْلًا ۚ لَا مُبَدِّلَ لِكَلِمَاتِهِ",
        dalilTrans: "Dan telah sempurna firman Tuhanmu (Al-Qur'an) dengan benar dan adil. Tidak ada yang dapat mengubah firman-Nya...",
        ulamaQuote:
            "Ibnu Katsir: 'Shidqan fil akhbar wa 'adlan fit thalab (Benar dalam setiap kabar berita-Nya dan adil dalam setiap perintah dan larangan-Nya).'",
        internalLink: "/quran/surah/6#verse-115",
        linkLabel: "Buka QS. Al-An'am: 115 di Quran",
    },
    31: {
        number: 31,
        latin: "Al-Lathif",
        arabic: "اللَّطِيفُ",
        meaning_idn: "Yang Maha Lembut & Halus",
        meaning_en: "The Subtle & Gracious",
        explanation:
            "Dzat yang mengetahui perkara-perkara yang paling samar dan tersembunyi, serta menyampaikan kebaikan kepada para hamba-Nya dengan cara yang amat halus.",
        dalilRef: "QS. Al-Mulk: 14",
        dalilText: "أَلَا يَعْلَمُ مَنْ خَلَقَ وَهُوَ اللَّطِيفُ الْخَبِيرُ",
        dalilTrans: "Apakah (pantas) Allah yang menciptakan itu tidak mengetahui? Dan Dia Mahahalus, Maha Mengetahui.",
        ulamaQuote:
            "Syaikh As-Sa'di: 'Al-Lathif bermakna ilmu-Nya menembus hal-hal tersembunyi dan mengarahkan hamba-Nya pada kemaslahatan tanpa disadari sang hamba.'",
        internalLink: "/quran/surah/67#verse-14",
        linkLabel: "Buka QS. Al-Mulk: 14 di Quran",
    },
    32: {
        number: 32,
        latin: "Al-Khabir",
        arabic: "الْخَبِيرُ",
        meaning_idn: "Yang Maha Mengenal / Waspada",
        meaning_en: "The All-Aware",
        explanation:
            "Dzat yang mengetahui rahasia yang paling dalam, hakikat setiap perkara, dan tidak ada satupun yang tersembunyi dari pengetahuan-Nya.",
        dalilRef: "QS. Luqman: 34",
        dalilText: "إِنَّ اللَّهَ عَلِيمٌ خَبِيرٌ",
        dalilTrans: "...Sungguh, Allah Maha Mengetahui, Maha Mengenal.",
        ulamaQuote:
            "Al-Halimi: 'Al-Khabir adalah Dzat yang tidak terlewat sedikit pun hal-hal yang terlintas dalam benak manusia.'",
        internalLink: "/quran/surah/31#verse-34",
        linkLabel: "Buka QS. Luqman: 34 di Quran",
    },
    33: {
        number: 33,
        latin: "Al-Halim",
        arabic: "الْحَلِيمُ",
        meaning_idn: "Yang Maha Penyantun",
        meaning_en: "The Most Forbearing",
        explanation:
            "Dzat yang tidak tergesa-gesa menimpakan siksaan kepada para pendosa, melainkan memberi tangguh waktu agar mereka sempat bertaubat.",
        dalilRef: "QS. Al-Baqarah: 225",
        dalilText: "وَاللَّهُ غَفُورٌ حَلِيمٌ",
        dalilTrans: "...dan Allah Maha Pengampun, Maha Penyantun.",
        ulamaQuote:
            "Imam Ibnu Jarir: 'Al-Halim adalah Yang tidak terpancing amarah oleh kemaksiatan orang-orang durhaka dan tidak mempercepat azab atas mereka.'",
        internalLink: "/quran/surah/2#verse-225",
        linkLabel: "Buka QS. Al-Baqarah: 225 di Quran",
    },
    34: {
        number: 34,
        latin: "Al-'Azhim",
        arabic: "الْعَظِيمُ",
        meaning_idn: "Yang Maha Agung",
        meaning_en: "The Magnificent",
        explanation:
            "Dzat yang memiliki keagungan mutlak pada Dzat, nama, sifat, dan perbuatan-Nya. Semua makhluk kerdil di hadapan keagungan-Nya.",
        dalilRef: "QS. Al-Baqarah: 255",
        dalilText: "وَهُوَ الْعَلِيُّ الْعَظِيمُ",
        dalilTrans: "...Dan Dia Maha Tinggi, Maha Agung.",
        ulamaQuote:
            "Bacaan rukuk: 'Subhana Rabbiyal 'Azhim' (Maha Suci Rabbku Yang Maha Agung). (HR. Muslim 772)",
        internalLink: "/quran/surah/2#verse-255",
        linkLabel: "Buka QS. Al-Baqarah: 255 di Quran",
    },
    35: {
        number: 35,
        latin: "Al-Ghafur",
        arabic: "الْغَفُورُ",
        meaning_idn: "Yang Maha Pengampun",
        meaning_en: "The All-Forgiving",
        explanation:
            "Dzat yang menutupi dosa hamba-hamba-Nya dan tidak mempermalukan mereka di hadapan makhluk serta memaafkan kesalahan mereka.",
        dalilRef: "QS. Az-Zumar: 53",
        dalilText: "إِنَّ اللَّهَ يَغْفِرُ الذُّنُوبَ جَمِيعًا ۚ إِنَّهُ هُوَ الْغَفُورُ الرَّحِيمُ",
        dalilTrans: "...Sungguh, Allah mengampuni dosa-dosa semuanya. Sungguh, Dialah Yang Maha Pengampun, Maha Penyayang.",
        ulamaQuote:
            "Syaikh As-Sa'di: 'Maghfirah Allah mencakup penghapusan dosa dan penjagaan dari akibat buruk dosa tersebut.'",
        internalLink: "/quran/surah/39#verse-53",
        linkLabel: "Buka QS. Az-Zumar: 53 di Quran",
    },
    36: {
        number: 36,
        latin: "Asy-Syakur",
        arabic: "الشَّكُورُ",
        meaning_idn: "Yang Maha Mensyukuri / Menghargai",
        meaning_en: "The Most Appreciative",
        explanation:
            "Dzat yang membalas amal kebaikan yang sedikit dari hamba-Nya dengan ganjaran pahala yang berlipat ganda tanpa batas.",
        dalilRef: "QS. Fatir: 30",
        dalilText: "لِيُوَفِّيَهُمْ أُجُورَهُمْ وَيَزِيدَهُمْ مِنْ فَضْلِهِ ۚ إِنَّهُ غَفُورٌ شَكُورٌ",
        dalilTrans: "...agar Allah menyempurnakan pahalanya kepada mereka dan menambah karunia-Nya. Sungguh, Allah Maha Pengampun, Maha Mensyukuri.",
        ulamaQuote:
            "Ibnul Qayyim: 'Asy-Syakur adalah Dzat yang mensyukuri ketaatan hamba-Nya, melipatgandakan balasan, dan memuji amal sholeh mereka.'",
        internalLink: "/quran/surah/35#verse-30",
        linkLabel: "Buka QS. Fatir: 30 di Quran",
    },
    37: {
        number: 37,
        latin: "Al-'Ali",
        arabic: "الْعَلِيُّ",
        meaning_idn: "Yang Maha Tinggi",
        meaning_en: "The Most High",
        explanation:
            "Dzat yang Maha Tinggi kedudukan-Nya, Maha Tinggi kekuasaan-Nya, dan Maha Tinggi Dzat-Nya di atas 'Arsy di atas langit ketujuh.",
        dalilRef: "QS. Al-A'la: 1",
        dalilText: "سَبِّحِ اسْمَ رَبِّكَ الْأَعْلَى",
        dalilTrans: "Sucikanlah nama Tuhanmu Yang Mahatinggi,",
        ulamaQuote:
            "Imam Adz-Dzahabi: 'Uluw (ketinggian) Allah adalah sifat dzatiyah yang tetap berdasarkan Al-Qur'an, As-Sunnah, Ijma', akal, dan fitrah yang lurus.' (Kitab Al-'Uluw)",
        internalLink: "/quran/surah/87#verse-1",
        linkLabel: "Buka QS. Al-A'la: 1 di Quran",
    },
    38: {
        number: 38,
        latin: "Al-Kabir",
        arabic: "الْكَبِيرُ",
        meaning_idn: "Yang Maha Besar",
        meaning_en: "The Most Great",
        explanation:
            "Dzat yang memiliki kebesaran dan kemegahan yang mutlak. Tidak ada satupun yang lebih besar dari-Nya, segala sesuatu kecil di hadapan-Nya.",
        dalilRef: "QS. Ar-Ra'd: 9",
        dalilText: "عَالِمُ الْغَيْبِ وَالشَّهَادَةِ الْكَبِيرُ الْمُتَعَالِ",
        dalilTrans: "(Dialah) Yang Mengetahui semua yang gaib dan yang nyata; Yang Mahabesar, Mahatinggi.",
        ulamaQuote:
            "Kalimat Takbir 'Allahu Akbar' mengikrarkan bahwa Allah jauh lebih besar dari segala urusan duniawi.",
        internalLink: "/quran/surah/13#verse-9",
        linkLabel: "Buka QS. Ar-Ra'd: 9 di Quran",
    },
    39: {
        number: 39,
        latin: "Al-Hafizh",
        arabic: "الْحَفِيظُ",
        meaning_idn: "Yang Maha Memelihara & Menjaga",
        meaning_en: "The Preserver",
        explanation:
            "Dzat yang memelihara keteraturan alam semesta, mencatat seluruh amal manusia tanpa ada yang terlupakan, dan melindungi para wali-Nya dari keburukan.",
        dalilRef: "QS. Hud: 57",
        dalilText: "إِنَّ رَبِّي عَلَىٰ كُلِّ شَيْءٍ حَفِيظٌ",
        dalilTrans: "...Sungguh, Tuhanku Maha Memelihara segala sesuatu.",
        ulamaQuote:
            "Nabi ﷺ menasihati Ibnu Abbas: 'Ihfazhillaha yahfazhka (Jagalah batasan-batasan Allah, niscaya Allah akan menjagamu).' (HR. Tirmidzi 2516)",
        internalLink: "/quran/surah/11#verse-57",
        linkLabel: "Buka QS. Hud: 57 di Quran",
    },
    40: {
        number: 40,
        latin: "Al-Muqit",
        arabic: "الْمُقِيتُ",
        meaning_idn: "Yang Maha Pemberi Kekuatan & Kecukupan",
        meaning_en: "The Sustainer & Nourisher",
        explanation:
            "Dzat yang menciptakan makanan dan asupan energi bagi tubuh, serta mengaruniakan kecukupan dan penjagaan bagi setiap makhluk.",
        dalilRef: "QS. An-Nisa': 85",
        dalilText: "وَكَانَ اللَّهُ عَلَىٰ كُلِّ شَيْءٍ مُقِيتًا",
        dalilTrans: "...dan Allah Mahakuasa atas segala sesuatu.",
        ulamaQuote:
            "Ibnu Abbas: 'Al-Muqit artinya Maha Kuasa dan Maha Memberi kecukupan rezeki kepada setiap jiwa.'",
        internalLink: "/quran/surah/4#verse-85",
        linkLabel: "Buka QS. An-Nisa': 85 di Quran",
    },
    41: {
        number: 41,
        latin: "Al-Hasib",
        arabic: "الْحَسِيبُ",
        meaning_idn: "Yang Maha Membuat Perhitungan",
        meaning_en: "The Reckoner & Sufficer",
        explanation:
            "Dzat yang mencukupi seluruh kebutuhan hamba-Nya yang bertawakal, serta Maha Menghisab dan memperhitungkan amal perbuatan dengan sangat cepat dan teliti.",
        dalilRef: "QS. An-Nisa': 6",
        dalilText: "وَكَفَىٰ بِاللَّهِ حَسِيبًا",
        dalilTrans: "...Dan cukuplah Allah sebagai Pengawas (dan Penghitung).",
        ulamaQuote:
            "QS. At-Talaq: 3: 'Wa man yatawakkal 'alallahi fahuwa hasbuh (Dan barangsiapa bertawakal kepada Allah, niscaya Dia mencukupinya).'",
        internalLink: "/quran/surah/4#verse-6",
        linkLabel: "Buka QS. An-Nisa': 6 di Quran",
    },
    42: {
        number: 42,
        latin: "Al-Jalil",
        arabic: "الْجَلِيلُ",
        meaning_idn: "Yang Maha Memiliki Keluhuran",
        meaning_en: "The Majestic",
        explanation:
            "Dzat yang berhak disifati dengan segala sifat keagungan, keluhuran derajat, dan kemuliaan yang sempurna.",
        dalilRef: "QS. Ar-Rahman: 27",
        dalilText: "وَيَبْقَىٰ وَجْهُ رَبِّكَ ذُو الْجَلَالِ وَالْإِكْرَامِ",
        dalilTrans: "Dan tetap kekal Wajah Tuhanmu yang mempunyai kebesaran dan kemuliaan.",
        ulamaQuote:
            "Syaikh As-Sa'di: 'Dzul Jalal wal Ikram adalah Pemilik segala keagungan dan sifat-sifat kemuliaan yang melahirkan rasa cinta dan pengagungan di hati hamba.'",
        internalLink: "/quran/surah/55#verse-27",
        linkLabel: "Buka QS. Ar-Rahman: 27 di Quran",
    },
    43: {
        number: 43,
        latin: "Al-Karim",
        arabic: "الْكَرِيمُ",
        meaning_idn: "Yang Maha Pemurah & Mulia",
        meaning_en: "The Most Generous",
        explanation:
            "Dzat yang sangat banyak kebaikan-Nya, memberi sebelum diminta, memaafkan kesalahan, dan tidak pernah mengecewakan harapan orang yang memohon kepada-Nya.",
        dalilRef: "QS. Al-Infitar: 6",
        dalilText: "يَا أَيُّهَا الْإِنْسَانُ مَا غَرَّكَ بِرَبِّكَ الْكَرِيمِ",
        dalilTrans: "Wahai manusia! Apakah yang telah memperdayakan kamu (berbuat durhaka) terhadap Tuhanmu Yang Mahamulia?",
        ulamaQuote:
            "Imam Al-Khatthabi: 'Al-Karim adalah Yang banyak kebajikan-Nya dan senantiasa melimpahkan karunia kepada makhluk-Nya tanpa batas.'",
        internalLink: "/quran/surah/82#verse-6",
        linkLabel: "Buka QS. Al-Infitar: 6 di Quran",
    },
    44: {
        number: 44,
        latin: "Ar-Raqib",
        arabic: "الرَّقِيبُ",
        meaning_idn: "Yang Maha Mengawasi",
        meaning_en: "The Watchful",
        explanation:
            "Dzat yang selalu mengawasi setiap gerak-gerik, ucapan, dan niat di dalam dada tanpa ada satu detik pun Dia terlelap atau lengah.",
        dalilRef: "QS. An-Nisa': 1",
        dalilText: "إِنَّ اللَّهَ كَانَ عَلَيْكُمْ رَقِيبًا",
        dalilTrans: "...Sungguh, Allah selalu menjaga dan mengawasimu.",
        ulamaQuote:
            "Ihsan adalah: 'Engkau beribadah kepada Allah seakan-akan engkau melihat-Nya, jika engkau tidak melihat-Nya maka sungguh Dia melihatmu.' (HR. Muslim 8)",
        internalLink: "/quran/surah/4#verse-1",
        linkLabel: "Buka QS. An-Nisa': 1 di Quran",
    },
    45: {
        number: 45,
        latin: "Al-Mujib",
        arabic: "الْمُجِيبُ",
        meaning_idn: "Yang Maha Mengabulkan Doa",
        meaning_en: "The Responsive",
        explanation:
            "Dzat yang menjawab permohonan orang yang berdoa, menolong orang yang tertindas, dan mencukupi orang yang berada dalam kesulitan.",
        dalilRef: "QS. Hud: 61",
        dalilText: "إِنَّ رَبِّي قَرِيبٌ مُجِيبٌ",
        dalilTrans: "...Sungguh, Tuhanku sangat dekat (rahmat-Nya) lagi memperkenankan (doa hamba-Nya).",
        ulamaQuote:
            "Rasulullah ﷺ bersabda: 'Sesungguhnya Rabb kalian Maha Pemalu lagi Maha Mulia, Dia malu jika hamba-Nya mengangkat kedua tangannya lalu menolaknya dengan hampa.' (HR. Abu Dawud 1488)",
        internalLink: "/quran/surah/11#verse-61",
        linkLabel: "Buka QS. Hud: 61 di Quran",
    },
    46: {
        number: 46,
        latin: "Al-Wasi'",
        arabic: "الْوَاسِعُ",
        meaning_idn: "Yang Maha Luas",
        meaning_en: "The All-Encompassing",
        explanation:
            "Dzat yang maha luas rahmat-Nya, ampunan-Nya, ilmu-Nya, kekayaan-Nya, dan kekuasaan-Nya yang meliputi seluruh penjuru alam.",
        dalilRef: "QS. Al-Baqarah: 115",
        dalilText: "إِنَّ اللَّهَ وَاسِعٌ عَلِيمٌ",
        dalilTrans: "...Sungguh, Allah Mahaluas (rahmat-Nya), Maha Mengetahui.",
        ulamaQuote:
            "Syaikh As-Sa'di: 'Al-Wasi' menunjukkan kelapangan sifat-sifat Allah sehingga tidak ada seorang pun mampu menghitung pujian bagi-Nya.'",
        internalLink: "/quran/surah/2#verse-115",
        linkLabel: "Buka QS. Al-Baqarah: 115 di Quran",
    },
    47: {
        number: 47,
        latin: "Al-Hakim",
        arabic: "الْحَكِيمُ",
        meaning_idn: "Yang Maha Bijaksana",
        meaning_en: "The All-Wise",
        explanation:
            "Dzat yang meletakkan segala sesuatu pada tempatnya yang tepat, menciptakan segala sesuatu dengan hikmah agung dan tujuan yang mulia.",
        dalilRef: "QS. Al-Baqarah: 32",
        dalilText: "إِنَّكَ أَنْتَ الْعَلِيمُ الْحَكِيمُ",
        dalilTrans: "...Sungguh, Engkaulah Yang Maha Mengetahui, Mahabijaksana.",
        ulamaQuote:
            "Ibnu Katsir: 'Al-Hakim adalah Yang Mahabijaksana dalam segenap perbuatan dan firman-Nya, tidak berbuat sesuatu dengan sia-sia.'",
        internalLink: "/quran/surah/2#verse-32",
        linkLabel: "Buka QS. Al-Baqarah: 32 di Quran",
    },
    48: {
        number: 48,
        latin: "Al-Wadud",
        arabic: "الْوَدُودُ",
        meaning_idn: "Yang Maha Pengasih & Mencintai",
        meaning_en: "The Loving & Affectionate",
        explanation:
            "Dzat yang mencintai para nabi, rasul, dan hamba-Nya yang beriman serta dicintai oleh hati orang-orang yang bertakwa.",
        dalilRef: "QS. Al-Buruj: 14",
        dalilText: "وَهُوَ الْغَفُورُ الْوَدُودُ",
        dalilTrans: "Dan Dialah Yang Maha Pengampun, Maha Pengasih,",
        ulamaQuote:
            "Syaikh As-Sa'di: 'Al-Wadud adalah Dzat yang menanamkan rasa cinta yang murni di hati hamba-hamba pilihan-Nya dan membalas cinta mereka dengan ridha-Nya.'",
        internalLink: "/quran/surah/85#verse-14",
        linkLabel: "Buka QS. Al-Buruj: 14 di Quran",
    },
    49: {
        number: 49,
        latin: "Al-Majid",
        arabic: "الْمَجِيدُ",
        meaning_idn: "Yang Maha Mulia & Terpuji",
        meaning_en: "The All-Glorious",
        explanation:
            "Dzat yang memiliki kemuliaan puncak, kebesaran wibawa, dan sifat-sifat kesempurnaan yang melimpah ruah.",
        dalilRef: "QS. Hud: 73",
        dalilText: "إِنَّهُ حَمِيدٌ مَجِيدٌ",
        dalilTrans: "...Sungguh, Dia Maha Terpuji, Maha Pengasih.",
        ulamaQuote:
            "Sholawat Ibrahimiyah: 'Innaka Hamidun Majid' (Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia).",
        internalLink: "/quran/surah/11#verse-73",
        linkLabel: "Buka QS. Hud: 73 di Quran",
    },
    50: {
        number: 50,
        latin: "Al-Ba'its",
        arabic: "الْبَاعِثُ",
        meaning_idn: "Yang Maha Membangkitkan",
        meaning_en: "The Resurrector",
        explanation:
            "Dzat yang mengutus para rasul sebagai pembawa petunjuk dan yang akan membangkitkan seluruh manusia dari kubur pada Hari Kiamat.",
        dalilRef: "QS. Al-Hajj: 7",
        dalilText: "وَأَنَّ السَّاعَةَ آتِيَةٌ لَا رَيْبَ فِيهَا وَأَنَّ اللَّهَ يَبْعَثُ مَنْ فِي الْقُبُورِ",
        dalilTrans: "Dan sungguh, (hari) Kiamat itu pasti datang, tidak ada keraguan padanya; dan sungguh, Allah akan membangkitkan siapa pun yang di dalam kubur.",
        ulamaQuote:
            "Imam Ath-Thabari: 'Al-Ba'its menghidupkan kembali jasad yang telah menjadi tanah untuk dihisab amalnya secara adil.'",
        internalLink: "/quran/surah/22#verse-7",
        linkLabel: "Buka QS. Al-Hajj: 7 di Quran",
    },
    51: {
        number: 51,
        latin: "Asy-Syahid",
        arabic: "الشَّهِيدُ",
        meaning_idn: "Yang Maha Menyaksikan",
        meaning_en: "The All-Observing Witness",
        explanation:
            "Dzat yang menyaksikan segala sesuatu dan hadir meliputi semua kejadian, tidak ada yang luput dari penglihatan dan pendengaran-Nya.",
        dalilRef: "QS. Al-Buruj: 9",
        dalilText: "وَاللَّهُ عَلَىٰ كُلِّ شَيْءٍ شَهِيدٌ",
        dalilTrans: "...Dan Allah Maha Menyaksikan segala sesuatu.",
        ulamaQuote:
            "Ibnu Katsir: 'Asy-Syahid adalah Yang tidak tersembunyi bagi-Nya rahasia manusia, dan Dia akan menjadi saksi atas setiap amal di Yaumil Mahsyar.'",
        internalLink: "/quran/surah/85#verse-9",
        linkLabel: "Buka QS. Al-Buruj: 9 di Quran",
    },
    52: {
        number: 52,
        latin: "Al-Haqq",
        arabic: "الْحَقُّ",
        meaning_idn: "Yang Maha Benar & Nyata",
        meaning_en: "The Absolute Truth",
        explanation:
            "Dzat yang wujud-Nya pasti, nama dan sifat-Nya sempurna, firman-Nya adalah kebenaran mutlak, dan janji-Nya pasti terwujud.",
        dalilRef: "QS. Al-Hajj: 6",
        dalilText: "ذَٰلِكَ بِأَنَّ اللَّهَ هُوَ الْحَقُّ وَأَنَّهُ يُحْيِي الْمَوْتَىٰ",
        dalilTrans: "Yang demikian itu karena sungguh, Allah, Dialah yang hak dan sungguh, Dialah yang menghidupkan segala yang mati...",
        ulamaQuote:
            "Doa Tahajud Nabi ﷺ: 'Antal Haqqu wa wa'dukal haqqu wa liqa'uka haq...' (Engkaulah Al-Haq, janji-Mu benar, dan pertemuan dengan-Mu benar). (HR. Bukhari 1120)",
        internalLink: "/hadith/bukhari/1120",
        linkLabel: "Buka HR. Bukhari No. 1120 di Hadits",
    },
    53: {
        number: 53,
        latin: "Al-Wakil",
        arabic: "الْوَكِيلُ",
        meaning_idn: "Yang Maha Memelihara / Pelindung",
        meaning_en: "The Ultimate Trustee",
        explanation:
            "Dzat yang diserahi segala urusan dan Dia menjamin pemeliharaan hamba-hamba-Nya yang bertawakal serta mencukupi kebutuhan mereka.",
        dalilRef: "QS. Ali 'Imran: 173",
        dalilText: "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ",
        dalilTrans: "...Cukuplah Allah (menjadi penolong) bagi kami dan Dia sebaik-baik pelindung.",
        ulamaQuote:
            "Ibnu Abbas: 'Hasbunallah wa ni'mal wakil diucapkan oleh Nabi Ibrahim saat dilempar ke api, dan diucapkan Nabi Muhammad ﷺ saat orang musyrik mengepung.' (HR. Bukhari 4563)",
        internalLink: "/quran/surah/3#verse-173",
        linkLabel: "Buka QS. Ali 'Imran: 173 di Quran",
    },
    54: {
        number: 54,
        latin: "Al-Qawi",
        arabic: "الْقَوِيُّ",
        meaning_idn: "Yang Maha Kuat",
        meaning_en: "The All-Strong",
        explanation:
            "Dzat yang memiliki kekuatan mutlak tanpa batas, tidak pernah merasa lelah, lemah, atau mengalami kegagalan dalam melakukan apapun.",
        dalilRef: "QS. Al-Hadid: 25",
        dalilText: "إِنَّ اللَّهَ قَوِيٌّ عَزِيزٌ",
        dalilTrans: "...Sungguh, Allah Mahakuat, Mahaperkasa.",
        ulamaQuote:
            "Syaikh As-Sa'di: 'Al-Qawi dan Al-Matin menunjukkan kesempurnaan daya dan kekuatan yang tidak dapat dilemahkan oleh siapapun.'",
        internalLink: "/quran/surah/57#verse-25",
        linkLabel: "Buka QS. Al-Hadid: 25 di Quran",
    },
    55: {
        number: 55,
        latin: "Al-Matin",
        arabic: "الْمَتِينُ",
        meaning_idn: "Yang Maha Kokoh",
        meaning_en: "The Firm & Steadfast",
        explanation:
            "Dzat yang sangat kokoh kekuatan-Nya, tidak ada kelelahan dalam perbuatan-Nya dan tidak pernah tertimpa kelemahan sedikitpun.",
        dalilRef: "QS. Adz-Dzariyat: 58",
        dalilText: "إِنَّ اللَّهَ هُوَ الرَّزَّاقُ ذُو الْقُوَّةِ الْمَتِينُ",
        dalilTrans: "Sungguh Allah, Dialah Pemberi rezeki Yang Mempunyai Kekuatan lagi Sangat Kokoh.",
        ulamaQuote:
            "Imam Ibnu Katsir: 'Al-Matin adalah Dzat yang memiliki kekuatan yang amat sangat kokoh dan tidak terkalahkan.'",
        internalLink: "/quran/surah/51#verse-58",
        linkLabel: "Buka QS. Adz-Dzariyat: 58 di Quran",
    },
    56: {
        number: 56,
        latin: "Al-Wali",
        arabic: "الْوَلِيُّ",
        meaning_idn: "Yang Maha Melindungi & Menolong",
        meaning_en: "The Protecting Friend",
        explanation:
            "Dzat yang mengatur urusan seluruh makhluk, dan secara khusus membimbing, menolong, serta membela hamba-hamba-Nya yang beriman.",
        dalilRef: "QS. Al-Baqarah: 257",
        dalilText: "اللَّهُ وَلِيُّ الَّذِينَ آمَنُوا يُخْرِجُهُمْ مِنَ الظُّلُمَاتِ إِلَى النُّورِ",
        dalilTrans: "Allah pelindung orang yang beriman. Dia mengeluarkan mereka dari kegelapan kepada cahaya...",
        ulamaQuote:
            "Syaikh As-Sa'di: 'Kewalian Allah kepada mukminin adalah mengaruniakan taufik dan mengeluarkan mereka dari kesesatan menuju hidayah.'",
        internalLink: "/quran/surah/2#verse-257",
        linkLabel: "Buka QS. Al-Baqarah: 257 di Quran",
    },
    57: {
        number: 57,
        latin: "Al-Hamid",
        arabic: "الْحَمِيدُ",
        meaning_idn: "Yang Maha Terpuji",
        meaning_en: "The All-Praiseworthy",
        explanation:
            "Dzat yang berhak menerima segala pujian atas kesempurnaan Dzat, sifat, dan perbuatan-Nya yang penuh karunia dan keadilan.",
        dalilRef: "QS. Ibrahim: 1",
        dalilText: "إِلَىٰ صِرَاطِ الْعَزِيزِ الْحَمِيدِ",
        dalilTrans: "...menuju jalan Tuhan Yang Mahaperkasa, Maha Terpuji.",
        ulamaQuote:
            "Ibnu Abbas: 'Al-Hamid adalah Yang dipuji oleh seluruh ciptaan dalam setiap keadaan lapang maupun sempit.'",
        internalLink: "/quran/surah/14#verse-1",
        linkLabel: "Buka QS. Ibrahim: 1 di Quran",
    },
    58: {
        number: 58,
        latin: "Al-Muhshi",
        arabic: "الْمُحْصِي",
        meaning_idn: "Yang Maha Menghitung",
        meaning_en: "The Comprehensive Reckoner",
        explanation:
            "Dzat yang mengetahui batasan, hitungan, dan rincian segala sesuatu di alam raya tanpa ada satupun yang luput dari hitungan-Nya.",
        dalilRef: "QS. Al-Jinn: 28",
        dalilText: "وَأَحْصَىٰ كُلَّ شَيْءٍ عَدَدًا",
        dalilTrans: "...dan Dia menghitung segala sesuatu satu persatu.",
        ulamaQuote:
            "Imam Ath-Thabari: 'Ilmu-Nya mencakup jumlah butir pasir, tetes hujan, helai daun, dan hembusan nafas makhluk.'",
        internalLink: "/quran/surah/72#verse-28",
        linkLabel: "Buka QS. Al-Jinn: 28 di Quran",
    },
    59: {
        number: 59,
        latin: "Al-Mubdi'",
        arabic: "الْمُبْدِئُ",
        meaning_idn: "Yang Maha Memulai Penciptaan",
        meaning_en: "The Originator",
        explanation:
            "Dzat yang memulai penciptaan seluruh makhluk dari ketiadaan tanpa memerlukan contoh atau bahan sebelumnya.",
        dalilRef: "QS. Al-Buruj: 13",
        dalilText: "إِنَّهُ هُوَ يُبْدِئُ وَيُعِيدُ",
        dalilTrans: "Sungguh, Dialah yang memulai penciptaan (makhluk) dan yang menghidupkannya kembali.",
        ulamaQuote:
            "Imam Ibnu Katsir: 'Al-Mubdi' menciptakan makhluk pada awal mulanya hanya dengan firman-Nya: Kun fayakun.'",
        internalLink: "/quran/surah/85#verse-13",
        linkLabel: "Buka QS. Al-Buruj: 13 di Quran",
    },
    60: {
        number: 60,
        latin: "Al-Mu'id",
        arabic: "الْمُعِيدُ",
        meaning_idn: "Yang Maha Mengembalikan Kehidupan",
        meaning_en: "The Restorer",
        explanation:
            "Dzat yang mengembalikan makhluk hidup menjadi hidup kembali setelah mereka mati dan hancur lebur pada Hari Kebangkitan.",
        dalilRef: "QS. Yunus: 34",
        dalilText: "قُلِ اللَّهُ يَبْدَأُ الْخَلْقَ ثُمَّ يُعِيدُهُ ۖ فَأَنَّىٰ تُؤْفَكُونَ",
        dalilTrans: "Katakanlah, 'Allah-lah yang memulai penciptaan (makhluk), kemudian mengulanginya kembali. Maka bagaimana kamu dipalingkan (dari kebenaran)?'",
        ulamaQuote:
            "Syaikh As-Sa'di: 'Mengembalikan penciptaan adalah bukti tak terbantahkan atas kekuasaan Allah membangkitkan manusia.'",
        internalLink: "/quran/surah/10#verse-34",
        linkLabel: "Buka QS. Yunus: 34 di Quran",
    },
    61: {
        number: 61,
        latin: "Al-Muhyi",
        arabic: "الْمُحْيِي",
        meaning_idn: "Yang Maha Menghidupkan",
        meaning_en: "The Giver of Life",
        explanation:
            "Dzat yang meniupkan ruh dan memberikan kehidupan kepada jasad yang mati, serta menghidupkan hati manusia dengan cahaya petunjuk iman.",
        dalilRef: "QS. Ar-Rum: 50",
        dalilText: "فَانْظُرْ إِلَىٰ آثَارِ رَحْمَتِ اللَّهِ كَيْفَ يُحْيِي الْأَرْضَ بَعْدَ مَوْتِهَا ۚ إِنَّ ذَٰلِكَ لَمُحْيِي الْمَوْتَىٰ",
        dalilTrans: "Maka perhatikanlah bekas-bekas rahmat Allah, bagaimana Dia menghidupkan bumi setelah mati (kering). Sungguh, itu berarti Dia pasti menghidupkan orang yang telah mati...",
        ulamaQuote:
            "Imam Al-Baghawi: 'Menghidupkan tanah gersang dengan hujan adalah perumpamaan nyata bagi penghidupan manusia dari kuburnya.'",
        internalLink: "/quran/surah/30#verse-50",
        linkLabel: "Buka QS. Ar-Rum: 50 di Quran",
    },
    62: {
        number: 62,
        latin: "Al-Mumit",
        arabic: "الْمُمِيتُ",
        meaning_idn: "Yang Maha Mematikan",
        meaning_en: "The Bringer of Death",
        explanation:
            "Dzat yang mencabut nyawa setiap makhluk hidup apabila telah tiba ajal yang telah ditentukan dengan hikmah dan keadilan-Nya.",
        dalilRef: "QS. Al-Hijr: 23",
        dalilText: "وَإِنَّا لَنَحْنُ نُحْيِي وَنُمِيتُ وَنَحْنُ الْوَارِثُونَ",
        dalilTrans: "Dan sungguh, Kamilah yang menghidupkan dan mematikan dan Kami (pulalah) yang mewarisi.",
        ulamaQuote:
            "Hasan Al-Bashri: 'Kematian adalah hakikat pasti yang memutus segala kelezatan duniawi dan menghadapkan manusia pada amalnya.'",
        internalLink: "/quran/surah/15#verse-23",
        linkLabel: "Buka QS. Al-Hijr: 23 di Quran",
    },
    63: {
        number: 63,
        latin: "Al-Hayy",
        arabic: "الْحَيُّ",
        meaning_idn: "Yang Maha Hidup Kekal",
        meaning_en: "The Ever-Living",
        explanation:
            "Dzat yang hidup kekal abadi sempurna tanpa permulaan dan tanpa akhir, tidak pernah mengantuk, tidur, ataupun mati.",
        dalilRef: "QS. Al-Baqarah: 255",
        dalilText: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ",
        dalilTrans: "Allah, tidak ada tuhan selain Dia. Yang Mahahidup, Yang terus-menerus mengurus (makhluk-Nya)...",
        ulamaQuote:
            "Ibnul Qayyim: 'Al-Hayy adalah pokok seluruh sifat dzatiyah Allah, sedangkan Al-Qayyum adalah pokok seluruh sifat fi'liyah-Nya.' (Zadul Ma'ad)",
        internalLink: "/quran/surah/2#verse-255",
        linkLabel: "Buka QS. Al-Baqarah: 255 di Quran",
    },
    64: {
        number: 64,
        latin: "Al-Qayyum",
        arabic: "الْقَيُّومُ",
        meaning_idn: "Yang Maha Mandiri & Mengurus Makhluk",
        meaning_en: "The Self-Sustaining & Sustainer",
        explanation:
            "Dzat yang berdiri sendiri tidak membutuhkan bantuan siapapun, dan senantiasa menegakkan serta memelihara keberlangsungan seluruh alam semesta.",
        dalilRef: "QS. Thaha: 111",
        dalilText: "وَعَنَتِ الْوُجُوهُ لِلْحَيِّ الْقَيُّومِ",
        dalilTrans: "Dan tunduklah semua muka (dengan rendah hati) di hadapan (Allah) Yang Hidup Kekal lagi senantiasa mengurus (makhluk-Nya)...",
        ulamaQuote:
            "Doa Nabi ﷺ saat gundah: 'Ya Hayyu Ya Qayyum, bi rahmatika astaghits...' (Wahai Yang Maha Hidup lagi Maha Mandiri, dengan rahmat-Mu aku memohon pertolongan). (HR. Tirmidzi 3524)",
        internalLink: "/quran/surah/20#verse-111",
        linkLabel: "Buka QS. Thaha: 111 di Quran",
    },
    65: {
        number: 65,
        latin: "Al-Wajid",
        arabic: "الْوَاجِدُ",
        meaning_idn: "Yang Maha Menemukan & Kaya",
        meaning_en: "The Perceiver & Resourceful",
        explanation:
            "Dzat yang serba ada, tidak pernah mengalami kekurangan apapun, dan dapat mewujudkan segala sesuatu yang dikehendaki-Nya.",
        dalilRef: "QS. Adh-Dhuha: 6-8",
        dalilText: "وَوَجَدَكَ عَائِلًا فَأَغْنَىٰ",
        dalilTrans: "dan Dia mendapatimu sebagai seorang yang kekurangan, lalu Dia memberikan kecukupan.",
        ulamaQuote:
            "Imam Al-Khatthabi: 'Al-Wajid adalah Yang tidak pernah kekurangan, perbendaharaan-Nya tidak pernah habis oleh pemberian-Nya.'",
        internalLink: "/quran/surah/93#verse-8",
        linkLabel: "Buka QS. Adh-Dhuha: 8 di Quran",
    },
    66: {
        number: 66,
        latin: "Al-Majid",
        arabic: "الْمَاجِدُ",
        meaning_idn: "Yang Maha Mulia & Dermawan",
        meaning_en: "The Noble & Magnificent",
        explanation:
            "Dzat yang memiliki sifat kemuliaan, kehormatan yang agung, serta kedermawanan yang tiada tara kepada para hamba-Nya.",
        dalilRef: "QS. Al-Buruj: 15",
        dalilText: "ذُو الْعَرْشِ الْمَجِيدُ",
        dalilTrans: "Pemilik 'Arsy yang Mahamulia,",
        ulamaQuote:
            "Syaikh As-Sa'di: 'Al-Majid menunjukkan kelapangan sifat kemegahan, keagungan, dan kebaikan yang tiada bertepi.'",
        internalLink: "/quran/surah/85#verse-15",
        linkLabel: "Buka QS. Al-Buruj: 15 di Quran",
    },
    67: {
        number: 67,
        latin: "Al-Wahid",
        arabic: "الْوَاحِدُ",
        meaning_idn: "Yang Maha Esa",
        meaning_en: "The One & Indivisible",
        explanation:
            "Dzat yang Maha Tunggal tanpa sekutu, tiada tandingan dalam Dzat, sifat, perbuatan, dan hak-Nya untuk diibadahi.",
        dalilRef: "QS. Al-Baqarah: 163",
        dalilText: "وَإِلَٰهُكُمْ إِلَٰهٌ وَاحِدٌ ۖ لَا إِلَٰهَ إِلَّا هُوَ الرَّحْمَٰنُ الرَّحِيمُ",
        dalilTrans: "Dan Tuhan kamu adalah Tuhan Yang Maha Esa; tidak ada tuhan selain Dia, Yang Maha Pengasih, Maha Penyayang.",
        ulamaQuote:
            "Imam Ibnu Katsir: 'Keesaan Allah menuntut pemurnian ibadah hanya untuk-Nya semata, bebas dari noda syirik.'",
        internalLink: "/quran/surah/2#verse-163",
        linkLabel: "Buka QS. Al-Baqarah: 163 di Quran",
    },
    68: {
        number: 68,
        latin: "Al-Ahad",
        arabic: "الْأَحَدُ",
        meaning_idn: "Yang Maha Tunggal / Esa Mutlak",
        meaning_en: "The Unique One",
        explanation:
            "Dzat yang Maha Tunggal secara mutlak, tidak beranak dan tidak diperanakkan, serta tidak ada satupun yang setara dengan-Nya.",
        dalilRef: "QS. Al-Ikhlas: 1",
        dalilText: "قُلْ هُوَ اللَّهُ أَحَدٌ",
        dalilTrans: "Katakanlah (Muhammad), 'Dialah Allah, Yang Maha Esa.'",
        ulamaQuote:
            "Nabi ﷺ: 'Surah Al-Ikhlas sebanding dengan sepertiga Al-Qur'an karena kandungannya memurnikan tauhid Asma' wa Sifat.' (HR. Bukhari 5013)",
        internalLink: "/quran/surah/112#verse-1",
        linkLabel: "Buka QS. Al-Ikhlas: 1 di Quran",
    },
    69: {
        number: 69,
        latin: "As-Samad",
        arabic: "الصَّمَدُ",
        meaning_idn: "Yang Maha Dibutuhkan Tempat Bergantung",
        meaning_en: "The Eternal Refuge",
        explanation:
            "Dzat yang sempurna kemuliaan dan kekuasaan-Nya, yang menjadi tumpuan harapan dan tempat bergantung seluruh makhluk dalam memenuhi segala hajat.",
        dalilRef: "QS. Al-Ikhlas: 2",
        dalilText: "اللَّهُ الصَّمَدُ",
        dalilTrans: "Allah tempat meminta segala sesuatu.",
        ulamaQuote:
            "Ibnu Abbas: 'As-Samad adalah Penguasa yang sempurna kedaulatan-Nya, Yang Maha Mulia yang sempurna kemuliaan-Nya, dan tidak berongga (tidak butuh makan/minum).'",
        internalLink: "/quran/surah/112#verse-2",
        linkLabel: "Buka QS. Al-Ikhlas: 2 di Quran",
    },
    70: {
        number: 70,
        latin: "Al-Qadir",
        arabic: "الْقَادِرُ",
        meaning_idn: "Yang Maha Berkuasa / Menentukan",
        meaning_en: "The Capable & Determiner",
        explanation:
            "Dzat yang berkuasa penuh mewujudkan apa yang dikehendaki-Nya dan tidak mewujudkan apa yang tidak dikehendaki-Nya sesuai ukuran yang tepat.",
        dalilRef: "QS. Al-An'am: 65",
        dalilText: "قُلْ هُوَ الْقَادِرُ عَلَىٰ أَنْ يَبْعَثَ عَلَيْكُمْ عَذَابًا مِنْ فَوْقِكُمْ أَوْ مِنْ تَحْتِ أَرْجُلِكُمْ",
        dalilTrans: "Katakanlah (Muhammad), 'Dialah yang berkuasa mengirimkan azab kepadamu, dari atas atau dari bawah kakimu...'",
        ulamaQuote:
            "Syaikh As-Sa'di: 'Kekuasaan Allah meliputi segala kemungkinan, tiada suatu halangan pun di bumi maupun di langit yang melemahkan-Nya.'",
        internalLink: "/quran/surah/6#verse-65",
        linkLabel: "Buka QS. Al-An'am: 65 di Quran",
    },
    71: {
        number: 71,
        latin: "Al-Muqtadir",
        arabic: "الْمُقْتَدِرُ",
        meaning_idn: "Yang Maha Berkuasa Penuh",
        meaning_en: "The Omnipotent",
        explanation:
            "Dzat yang memiliki kekuasaan mutlak yang tak terbatas, menundukkan segala sesuatu tanpa ada perlawanan dari siapapun.",
        dalilRef: "QS. Al-Qamar: 42",
        dalilText: "فَأَخَذْنَاهُمْ أَخْذَ عَزِيزٍ مُقْتَدِرٍ",
        dalilTrans: "...maka Kami azab mereka dengan azab dari Yang Mahaperkasa, Mahakuasa.",
        ulamaQuote:
            "Imam Ath-Thabari: 'Al-Muqtadir adalah Yang memiliki kekuasaan paripurna untuk melaksanakan apa saja yang telah Dia putuskan.'",
        internalLink: "/quran/surah/54#verse-42",
        linkLabel: "Buka QS. Al-Qamar: 42 di Quran",
    },
    72: {
        number: 72,
        latin: "Al-Muqaddim",
        arabic: "الْمُقَدِّمُ",
        meaning_idn: "Yang Maha Mendahulukan",
        meaning_en: "The Expediter & Advancer",
        explanation:
            "Dzat yang memajukan dan mendahulukan apa yang Dia kehendaki, baik waktu, tempat, martabat, maupun keutamaan hamba-hamba-Nya.",
        dalilRef: "QS. Qaf: 28",
        dalilText: "قَالَ لَا تَخْتَصِمُوا لَدَيَّ وَقَدْ قَدَّمْتُ إِلَيْكُمْ بِالْوَعِيدِ",
        dalilTrans: "Dia (Allah) berfirman, 'Janganlah kamu bertengkar di hadapan-Ku, dan sungguh, dahulu Aku telah menyampaikan ancaman kepadamu.'",
        ulamaQuote:
            "Doa Nabi ﷺ: 'Antal Muqaddimu wa Antal Mu'akhkhir, la ilaha illa Ant.' (Engkaulah Yang Mendahulukan dan Yang Mengakhirkan, tiada ilah selain Engkau). (HR. Bukhari 1120)",
        internalLink: "/hadith/bukhari/1120",
        linkLabel: "Buka HR. Bukhari No. 1120 di Hadits",
    },
    73: {
        number: 73,
        latin: "Al-Mu'akhkhir",
        arabic: "الْمُؤَخِّرُ",
        meaning_idn: "Yang Maha Mengakhirkan",
        meaning_en: "The Delayer & Postponer",
        explanation:
            "Dzat yang menunda atau mengakhirkan sesuatu sesuai hikmah-Nya, seperti mengakhirkan balasan dosa orang zalim hingga hari kiamat.",
        dalilRef: "QS. Ibrahim: 42",
        dalilText: "إِنَّمَا يُؤَخِّرُهُمْ لِيَوْمٍ تَشْخَصُ فِيهِ الْأَبْصَارُ",
        dalilTrans: "...Sesungguhnya Allah menangguhkan mereka sampai hari yang pada waktu itu mata (mereka) terbelalak.",
        ulamaQuote:
            "Imam Ibnu Katsir: 'Allah mengakhirkan ajal dan hukuman orang-orang zalim semata-mata sebagai bentuk istidraj dan hikmah keadilan-Nya.'",
        internalLink: "/quran/surah/14#verse-42",
        linkLabel: "Buka QS. Ibrahim: 42 di Quran",
    },
    74: {
        number: 74,
        latin: "Al-Awwal",
        arabic: "الْأَوَّلُ",
        meaning_idn: "Yang Maha Awal",
        meaning_en: "The Very First",
        explanation:
            "Dzat yang ada sebelum segala sesuatu ada, tanpa permulaan bagi wujud-Nya.",
        dalilRef: "QS. Al-Hadid: 3",
        dalilText: "هُوَ الْأَوَّلُ وَالْآخِرُ وَالظَّاهِرُ وَالْبَاطِنُ ۖ وَهُوَ بِكُلِّ شَيْءٍ عَلِيمٌ",
        dalilTrans: "Dialah Yang Awal, Yang Akhir, Yang Zahir dan Yang Batin; dan Dia Maha Mengetahui segala sesuatu.",
        ulamaQuote:
            "Nabi ﷺ menafsirkan: 'Antal Awwalu fa laisa qablaka syai' (Engkaulah Al-Awwal, maka tidak ada sesuatupun sebelum-Mu).' (HR. Muslim 2713)",
        internalLink: "/quran/surah/57#verse-3",
        linkLabel: "Buka QS. Al-Hadid: 3 di Quran",
    },
    75: {
        number: 75,
        latin: "Al-Akhir",
        arabic: "الْآخِرُ",
        meaning_idn: "Yang Maha Akhir",
        meaning_en: "The Infinite Last",
        explanation:
            "Dzat yang tetap kekal abadi setelah segala sesuatu binasa dan musnah, tanpa ada akhir bagi wujud-Nya.",
        dalilRef: "QS. Al-Hadid: 3",
        dalilText: "هُوَ الْأَوَّلُ وَالْآخِرُ",
        dalilTrans: "Dialah Yang Awal dan Yang Akhir...",
        ulamaQuote:
            "Nabi ﷺ menafsirkan: 'Wa Antal Akhiru fa laisa ba'daka syai' (Dan Engkaulah Al-Akhir, maka tidak ada sesuatupun setelah-Mu).' (HR. Muslim 2713)",
        internalLink: "/quran/surah/57#verse-3",
        linkLabel: "Buka QS. Al-Hadid: 3 di Quran",
    },
    76: {
        number: 76,
        latin: "Az-Zhahir",
        arabic: "الظَّاهِرُ",
        meaning_idn: "Yang Maha Nyata & Tinggi",
        meaning_en: "The Manifest & Supreme",
        explanation:
            "Dzat yang Maha Tinggi di atas segala sesuatu dan Maha Nyata bukti-bukti keberadaan serta keagungan-Nya di alam semesta.",
        dalilRef: "QS. Al-Hadid: 3",
        dalilText: "وَالظَّاهِرُ وَالْبَاطِنُ",
        dalilTrans: "...Yang Zahir dan Yang Batin...",
        ulamaQuote:
            "Nabi ﷺ menafsirkan: 'Wa Antazh Zhahir fa laisa fauqaka syai' (Dan Engkaulah Az-Zhahir, maka tidak ada sesuatupun di atas-Mu).' (HR. Muslim 2713)",
        internalLink: "/quran/surah/57#verse-3",
        linkLabel: "Buka QS. Al-Hadid: 3 di Quran",
    },
    77: {
        number: 77,
        latin: "Al-Bathin",
        arabic: "الْبَاطِنُ",
        meaning_idn: "Yang Maha Tersembunyi & Dekat",
        meaning_en: "The Hidden & Intimate",
        explanation:
            "Dzat yang tidak dapat dijangkau oleh pandangan mata di dunia, namun Maha Dekat dengan ilmu dan pengawasan-Nya terhadap segala rahasia batin.",
        dalilRef: "QS. Al-Hadid: 3",
        dalilText: "وَهُوَ بِكُلِّ شَيْءٍ عَلِيمٌ",
        dalilTrans: "...dan Dia Maha Mengetahui segala sesuatu.",
        ulamaQuote:
            "Nabi ﷺ menafsirkan: 'Wa Antal Bathinu fa laisa dunaka syai' (Dan Engkaulah Al-Bathin, maka tidak ada sesuatupun yang lebih tersembunyi dari-Mu).' (HR. Muslim 2713)",
        internalLink: "/quran/surah/57#verse-3",
        linkLabel: "Buka QS. Al-Hadid: 3 di Quran",
    },
    78: {
        number: 78,
        latin: "Al-Wali",
        arabic: "الْوَالِي",
        meaning_idn: "Yang Maha Memerintah & Mengatur",
        meaning_en: "The Governor & Sole Ruler",
        explanation:
            "Dzat Penguasa tunggal yang mengatur, mengelola, dan mengendalikan semua urusan makhluk serta alam raya tanpa campur tangan pihak lain.",
        dalilRef: "QS. Ar-Ra'd: 11",
        dalilText: "وَمَا لَهُمْ مِنْ دُونِهِ مِنْ وَالٍ",
        dalilTrans: "...dan tidak ada pelindung bagi mereka selain Dia.",
        ulamaQuote:
            "Imam Al-Khatthabi: 'Al-Wali adalah Pemilik kekuasaan mutlak yang menjalankan kehendak-Nya atas kerajaan-Nya.'",
        internalLink: "/quran/surah/13#verse-11",
        linkLabel: "Buka QS. Ar-Ra'd: 11 di Quran",
    },
    79: {
        number: 79,
        latin: "Al-Muta'ali",
        arabic: "الْمُتَعَالِي",
        meaning_idn: "Yang Maha Tinggi & Luhur",
        meaning_en: "The Self-Exalted",
        explanation:
            "Dzat yang Maha Tinggi dari segala sangkaan, kekurangan, fitnah orang-orang kafir, dan keserupaan dengan makhluk.",
        dalilRef: "QS. Ar-Ra'd: 9",
        dalilText: "عَالِمُ الْغَيْبِ وَالشَّهَادَةِ الْكَبِيرُ الْمُتَعَالِ",
        dalilTrans: "(Dialah) Yang Mengetahui semua yang gaib dan yang nyata; Yang Mahabesar, Mahatinggi.",
        ulamaQuote:
            "Syaikh As-Sa'di: 'Tinggi dalam kekuasaan-Nya, tinggi dalam Dzat-Nya di atas 'Arsy, dan tinggi dalam segenap kemuliaan sifat-sifat-Nya.'",
        internalLink: "/quran/surah/13#verse-9",
        linkLabel: "Buka QS. Ar-Ra'd: 9 di Quran",
    },
    80: {
        number: 80,
        latin: "Al-Barr",
        arabic: "الْبَرُّ",
        meaning_idn: "Yang Maha Dermawan & Melimpah Kebajikan",
        meaning_en: "The Source of Goodness",
        explanation:
            "Dzat yang sangat luas kebaikan dan kasih sayang-Nya, menepati janji, serta melimpahkan kenikmatan lahir batin bagi seluruh makhluk.",
        dalilRef: "QS. At-Tur: 28",
        dalilText: "إِنَّا كُنَّا مِنْ قَبْلُ نَدْعُوهُ ۖ إِنَّهُ هُوَ الْبَرُّ الرَّحِيمُ",
        dalilTrans: "Sesungguhnya kami dahulu menyembah-Nya. Sungguh, Dialah Yang Melimpahkan Kebaikan, Maha Penyayang.",
        ulamaQuote:
            "Ibnu Abbas: 'Al-Barr adalah Dzat yang sangat berlemah lembut dan berbuat kebajikan kepada hamba-hamba-Nya.'",
        internalLink: "/quran/surah/52#verse-28",
        linkLabel: "Buka QS. At-Tur: 28 di Quran",
    },
    81: {
        number: 81,
        latin: "At-Tawwab",
        arabic: "التَّوَّابُ",
        meaning_idn: "Yang Maha Penerima Taubat",
        meaning_en: "The Accepter of Repentance",
        explanation:
            "Dzat yang selalu membimbing hamba-Nya untuk bertaubat dan senantiasa menerima taubat mereka betapapun besarnya dosa yang telah diperbuat.",
        dalilRef: "QS. An-Nur: 10",
        dalilText: "وَأَنَّ اللَّهَ تَوَّابٌ حَكِيمٌ",
        dalilTrans: "...dan sungguh, Allah Maha Penerima Tobat, Mahabijaksana.",
        ulamaQuote:
            "Rasulullah ﷺ bersabda: 'Sungguh Allah lebih gembira dengan taubat hamba-Nya daripada kegembiraan seseorang yang menemukan kembali untanya yang hilang di padang pasir.' (HR. Bukhari 6309, Muslim 2747)",
        internalLink: "/hadith/bukhari/6309",
        linkLabel: "Buka HR. Bukhari No. 6309 di Hadits",
    },
    82: {
        number: 82,
        latin: "Al-Muntaqim",
        arabic: "الْمُنْتَقِمُ",
        meaning_idn: "Yang Maha Menghukum Orang Zalim",
        meaning_en: "The Just Avenger",
        explanation:
            "Dzat yang menimpakan balasan azab yang setimpal dan menghancurkan para penentang kebenaran dan orang-orang yang melampaui batas.",
        dalilRef: "QS. As-Sajdah: 22",
        dalilText: "إِنَّا مِنَ الْمُجْرِمِينَ مُنْتَقِمُونَ",
        dalilTrans: "...Sungguh, Kami akan memberikan pembalasan kepada orang-orang yang berdosa.",
        ulamaQuote:
            "Syaikh As-Sa'di: 'Pembalasan Allah berlaku bagi orang-orang yang sombong, mendustakan para rasul, dan berbuat zalim di muka bumi.'",
        internalLink: "/quran/surah/32#verse-22",
        linkLabel: "Buka QS. As-Sajdah: 22 di Quran",
    },
    83: {
        number: 83,
        latin: "Al-'Afuw",
        arabic: "الْعَفُوُّ",
        meaning_idn: "Yang Maha Pemaaf",
        meaning_en: "The Supreme Eraser of Sins",
        explanation:
            "Dzat yang menghapus catatan dosa, memaafkan kesalahan, dan menggugurkan sanksi hukum dari para hamba-Nya.",
        dalilRef: "QS. An-Nisa': 99",
        dalilText: "وَكَانَ اللَّهُ عَفُوًّا غَفُورًا",
        dalilTrans: "...dan Allah Maha Pemaaf, Maha Pengampun.",
        ulamaQuote:
            "Doa Lailatul Qadar yang diajarkan Nabi ﷺ: 'Allahumma innaka 'Afuwwun tuhibbul 'afwa fa'fu 'anni' (Ya Allah sesungguhnya Engkau Maha Pemaaf dan mencintai kemaafan, maka maafkanlah aku). (HR. Tirmidzi 3513)",
        internalLink: "/quran/surah/4#verse-99",
        linkLabel: "Buka QS. An-Nisa': 99 di Quran",
    },
    84: {
        number: 84,
        latin: "Ar-Ra'uf",
        arabic: "الرَّؤُوفُ",
        meaning_idn: "Yang Maha Belas Kasih",
        meaning_en: "The Most Compassionate",
        explanation:
            "Dzat yang memiliki kelembutan kasih sayang yang amat tinggi, tidak membebani hamba di luar kemampuannya, dan meringankan kesulitan mereka.",
        dalilRef: "QS. Al-Baqarah: 207",
        dalilText: "وَاللَّهُ رَءُوفٌ بِالْعِبَادِ",
        dalilTrans: "...dan Allah Maha Penyantun kepada hamba-hamba-Nya.",
        ulamaQuote:
            "Imam Al-Khatthabi: 'Ar-Ra'fah adalah tingkatan kasih sayang yang paling lembut dan mendalam, di atas makna rahmat biasa.'",
        internalLink: "/quran/surah/2#verse-207",
        linkLabel: "Buka QS. Al-Baqarah: 207 di Quran",
    },
    85: {
        number: 85,
        latin: "Malikul Mulk",
        arabic: "مَالِكُ الْمُلْكِ",
        meaning_idn: "Yang Maha Memiliki Kerajaan Semesta",
        meaning_en: "The Owner of All Sovereignty",
        explanation:
            "Dzat Pemilik seluruh kekuasaan mutlak di jagat raya, memberikan kekuasaan kepada siapa yang dikehendaki dan mencabutnya sesuai kehendak-Nya.",
        dalilRef: "QS. Ali 'Imran: 26",
        dalilText: "قُلِ اللَّهُمَّ مَالِكَ الْمُلْكِ تُؤْتِي الْمُلْكَ مَنْ تَشَاءُ وَتَنْزِعُ الْمُلْكَ مِمَّنْ تَشَاءُ",
        dalilTrans: "Katakanlah (Muhammad), 'Wahai Tuhan pemilik kekuasaan, Engkau berikan kekuasaan kepada siapa pun yang Engkau kehendaki, dan Engkau cabut kekuasaan dari siapa pun yang Engkau kehendaki...'",
        ulamaQuote:
            "Ibnu Katsir: 'Hanya Allah Pengatur sejati alam semesta; tiada kekuasaan makhluk yang abadi selain kekuasaan-Nya.'",
        internalLink: "/quran/surah/3#verse-26",
        linkLabel: "Buka QS. Ali 'Imran: 26 di Quran",
    },
    86: {
        number: 86,
        latin: "Dzul Jalali wal Ikram",
        arabic: "ذُو الْجَلَالِ وَالْإِكْرَامِ",
        meaning_idn: "Yang Maha Memiliki Keagungan & Kemuliaan",
        meaning_en: "The Lord of Majesty and Bounty",
        explanation:
            "Dzat Pemilik segala kebesaran yang agung serta sumber segala kemuliaan, karunia, dan kedermawanan bagi makhluk-Nya.",
        dalilRef: "QS. Ar-Rahman: 78",
        dalilText: "تَبَارَكَ اسْمُ رَبِّكَ ذِي الْجَلَالِ وَالْإِكْرَامِ",
        dalilTrans: "Mahasuci nama Tuhanmu Pemilik Keagungan dan Kemuliaan.",
        ulamaQuote:
            "Nabi ﷺ bersabda: 'Perbanyaklah berdoa dengan menyebut Ya Dzal Jalali wal Ikram.' (HR. Tirmidzi 3525)",
        internalLink: "/quran/surah/55#verse-78",
        linkLabel: "Buka QS. Ar-Rahman: 78 di Quran",
    },
    87: {
        number: 87,
        latin: "Al-Muqsith",
        arabic: "الْمُقْسِطُ",
        meaning_idn: "Yang Maha Berlaku Adil",
        meaning_en: "The Fair & Equitable",
        explanation:
            "Dzat yang menegakkan keadilan mutlak, membela orang yang teraniaya dari orang yang zalim, dan membalas setiap amal tanpa berat sebelah.",
        dalilRef: "QS. Al-A'raf: 29",
        dalilText: "قُلْ أَمَرَ رَبِّي بِالْقِسْطِ",
        dalilTrans: "Katakanlah, 'Tuhanku menyuruhku berlaku adil...'",
        ulamaQuote:
            "Imam Al-Qurthubi: 'Al-Muqsith adalah Dzat yang mengambil hak orang terzalimi dari orang yang menzaliminya secara adil sempurna.'",
        internalLink: "/quran/surah/7#verse-29",
        linkLabel: "Buka QS. Al-A'raf: 29 di Quran",
    },
    88: {
        number: 88,
        latin: "Al-Jami'",
        arabic: "الْجَامِعُ",
        meaning_idn: "Yang Maha Mengumpulkan",
        meaning_en: "The Gatherer of All",
        explanation:
            "Dzat yang menghimpun seluruh makhluk pada Hari Kiamat di Padang Mahsyar, serta menghimpun seluruh kesempurnaan pada Dzat-Nya.",
        dalilRef: "QS. Ali 'Imran: 9",
        dalilText: "رَبَّنَا إِنَّكَ جَامِعُ النَّاسِ لِيَوْمٍ لَا رَيْبَ فِيهِ ۚ إِنَّ اللَّهَ لَا يُخْلِفُ الْمِيعَادَ",
        dalilTrans: "Ya Tuhan kami, Engkaulah yang mengumpulkan manusia pada hari yang tidak ada keraguan padanya. Sungguh, Allah tidak menyalahi janji.",
        ulamaQuote:
            "Syaikh As-Sa'di: 'Al-Jami' mengumpulkan partikel jasad yang tercerai-berai untuk dihidupkan kembali di hari perjumpaan.'",
        internalLink: "/quran/surah/3#verse-9",
        linkLabel: "Buka QS. Ali 'Imran: 9 di Quran",
    },
    89: {
        number: 89,
        latin: "Al-Ghani",
        arabic: "الْغَنِيُّ",
        meaning_idn: "Yang Maha Kaya / Serba Cukup",
        meaning_en: "The Self-Sufficient",
        explanation:
            "Dzat yang Maha Kaya secara mutlak, tidak memerlukan siapapun dan apapun, sedangkan seluruh makhluk sangat fakir dan butuh kepada-Nya.",
        dalilRef: "QS. Fatir: 15",
        dalilText: "يَا أَيُّهَا النَّاسُ أَنْتُمُ الْفُقَرَاءُ إِلَى اللَّهِ ۖ وَاللَّهُ هُوَ الْغَنِيُّ الْحَمِيدُ",
        dalilTrans: "Wahai manusia! Kamulah yang memerlukan Allah; dan Allah Dialah Yang Mahakaya (tidak memerlukan sesuatu), Maha Terpuji.",
        ulamaQuote:
            "Hadits Qudsi: 'Wahai hamba-Ku, andai orang pertama hingga terakhir dari kalian bertaqwa, itu tak menambah kerajaan-Ku sedikitpun...' (HR. Muslim 2577)",
        internalLink: "/quran/surah/35#verse-15",
        linkLabel: "Buka QS. Fatir: 15 di Quran",
    },
    90: {
        number: 90,
        latin: "Al-Mughni",
        arabic: "الْمُغْنِي",
        meaning_idn: "Yang Maha Memberi Kekayaan & Kecukupan",
        meaning_en: "The Enricher",
        explanation:
            "Dzat yang menganugerahkan kekayaan materi, ketenangan hati, dan kecukupan qana'ah kepada siapa yang Dia kehendaki.",
        dalilRef: "QS. An-Najm: 48",
        dalilText: "وَأَنَّهُ هُوَ أَغْنَىٰ وَأَقْنَىٰ",
        dalilTrans: "dan sesungguhnya Dialah yang memberikan kekayaan dan kecukupan.",
        ulamaQuote:
            "Ibnu Katsir: 'Allah-lah yang mempermudah jalan rezeki dan memampukan manusia untuk hidup berkecukupan.'",
        internalLink: "/quran/surah/53#verse-48",
        linkLabel: "Buka QS. An-Najm: 48 di Quran",
    },
    91: {
        number: 91,
        latin: "Al-Mani'",
        arabic: "الْمَانِعُ",
        meaning_idn: "Yang Maha Mencegah / Menolak",
        meaning_en: "The Withholder & Protector",
        explanation:
            "Dzat yang mencegah keburukan menimpa para hamba-Nya dan menahan rezeki atau cobaan sesuai ketetapan hikmah-Nya.",
        dalilRef: "QS. Al-Mulk: 21",
        dalilText: "أَمَّنْ هَٰذَا الَّذِي يَرْزُقُكُمْ إِنْ أَمْسَكَ رِزْقَهُ",
        dalilTrans: "Atau siapakah yang dapat memberimu rezeki jika Dia menahan rezeki-Nya?...",
        ulamaQuote:
            "Doa setelah sholat Nabi ﷺ: 'Allahumma la mani'a lima a'thaita wa la mu'thiya lima mana'ta' (Ya Allah tiada yang dapat mencegah apa yang Engkau beri, dan tiada yang dapat memberi apa yang Engkau cegah). (HR. Bukhari 844, Muslim 593)",
        internalLink: "/hadith/bukhari/844",
        linkLabel: "Buka HR. Bukhari No. 844 di Hadits",
    },
    92: {
        number: 92,
        latin: "Ad-Dharr",
        arabic: "الضَّارُّ",
        meaning_idn: "Yang Maha Menentukan Kemudaratan",
        meaning_en: "The Balancer of Harm",
        explanation:
            "Dzat yang di tangan-Nya lah segala ketetapan mudarat dan ujian bagi makhluk, dan tiada satupun yang mampu menolaknya selain izin-Nya.",
        dalilRef: "QS. Al-An'am: 17",
        dalilText: "وَإِنْ يَمْسَسْكَ اللَّهُ بِضُرٍّ فَلَا كَاشِفَ لَهُ إِلَّا هُوَ",
        dalilTrans: "Dan jika Allah menimpakan suatu bencana kepadamu, maka tidak ada yang dapat menghilangkannya selain Dia...",
        ulamaQuote:
            "Ibnul Qayyim: 'Penyebutan Ad-Dharr selalu digandengkan dengan An-Nafi' untuk menunjukkan kesempurnaan hikmah dan kekuasaan-Nya.'",
        internalLink: "/quran/surah/6#verse-17",
        linkLabel: "Buka QS. Al-An'am: 17 di Quran",
    },
    93: {
        number: 93,
        latin: "An-Nafi'",
        arabic: "النَّافِعُ",
        meaning_idn: "Yang Maha Memberi Manfaat",
        meaning_en: "The Creator of Good & Benefit",
        explanation:
            "Dzat yang mendatangkan segala manfaat, kebaikan, dan kemaslahatan bagi seluruh alam semesta.",
        dalilRef: "QS. Yunus: 107",
        dalilText: "وَإِنْ يُرِدْكَ بِخَيْرٍ فَلَا رَادَّ لِفَضْلِهِ ۚ يُصِيبُ بِهِ مَنْ يَشَاءُ مِنْ عِبَادِهِ",
        dalilTrans: "...dan jika Dia menghendaki kebaikan bagimu, maka tidak ada yang dapat menolak karunia-Nya. Dia memberikan kebaikan itu kepada siapa pun yang Dia kehendaki...",
        ulamaQuote:
            "Syaikh As-Sa'di: 'Segala nikmat, keselamatan, dan keberkahan berasal semata-mata dari limpahan anugerah An-Nafi'.' (Taisirul Karimir Rahman)",
        internalLink: "/quran/surah/10#verse-107",
        linkLabel: "Buka QS. Yunus: 107 di Quran",
    },
    94: {
        number: 94,
        latin: "An-Nur",
        arabic: "النُّورُ",
        meaning_idn: "Yang Maha Pemberi Cahaya",
        meaning_en: "The Illuminating Light",
        explanation:
            "Dzat yang menerangi langit dan bumi dengan ciptaan-Nya, serta menerangi sanubari hamba-hamba-Nya dengan cahaya kitab suci dan keimanan.",
        dalilRef: "QS. An-Nur: 35",
        dalilText: "اللَّهُ نُورُ السَّمَاوَاتِ وَالْأَرْضِ",
        dalilTrans: "Allah (pemberi) cahaya (kepada) langit dan bumi...",
        ulamaQuote:
            "Ibnu Abbas: 'Allah adalah Pemberi petunjuk bagi penduduk langit dan bumi dengan cahaya-Nya.' (Tafsir Ibnu Katsir)",
        internalLink: "/quran/surah/24#verse-35",
        linkLabel: "Buka QS. An-Nur: 35 di Quran",
    },
    95: {
        number: 95,
        latin: "Al-Hadi",
        arabic: "الْهَادِي",
        meaning_idn: "Yang Maha Pemberi Petunjuk",
        meaning_en: "The Ultimate Guide",
        explanation:
            "Dzat yang membimbing seluruh makhluk menuju kelangsungan hidup mereka, dan mengaruniakan hidayah taufik ke jalan yang lurus (Sirathal Mustaqim) bagi orang beriman.",
        dalilRef: "QS. Al-Hajj: 54",
        dalilText: "وَإِنَّ اللَّهَ لَهَادِ الَّذِينَ آمَنُوا إِلَىٰ صِرَاطٍ مُسْتَقِيمٍ",
        dalilTrans: "...Dan sungguh, Allah pemberi petunjuk bagi orang-orang yang beriman kepada jalan yang lurus.",
        ulamaQuote:
            "Syaikh As-Sa'di: 'Hidayah terbagi dua: hidayah ilmu/bimbingan umum dan hidayah taufik khusus untuk beramal shalih.'",
        internalLink: "/quran/surah/22#verse-54",
        linkLabel: "Buka QS. Al-Hajj: 54 di Quran",
    },
    96: {
        number: 96,
        latin: "Al-Badi'",
        arabic: "الْبَدِيعُ",
        meaning_idn: "Yang Maha Pencipta Keindahan Tanpa Tandingan",
        meaning_en: "The Incomparable Originator",
        explanation:
            "Dzat yang menciptakan alam semesta dalam bentuk yang teramat indah, sempurna, dan menakjubkan tanpa ada contoh tandingan sebelumnya.",
        dalilRef: "QS. Al-Baqarah: 117",
        dalilText: "بَدِيعُ السَّمَاوَاتِ وَالْأَرْضِ ۖ وَإِذَا قَضَىٰ أَمْرًا فَإِنَّمَا يَقُولُ لَهُ كُنْ فَيَكُونُ",
        dalilTrans: "(Allah) pencipta langit dan bumi. Apabila Dia hendak menetapkan sesuatu, Dia hanya berkata kepadanya, 'Jadilah!' Maka jadilah sesuatu itu.",
        ulamaQuote:
            "Imam Ath-Thabari: 'Al-Badi' adalah Dzat yang mengadakan sesuatu yang belum pernah ada wujudnya sama sekali.'",
        internalLink: "/quran/surah/2#verse-117",
        linkLabel: "Buka QS. Al-Baqarah: 117 di Quran",
    },
    97: {
        number: 97,
        latin: "Al-Baqi",
        arabic: "الْبَاقِي",
        meaning_idn: "Yang Maha Kekal Abadi",
        meaning_en: "The Everlasting",
        explanation:
            "Dzat yang keberadaan-Nya kekal selamanya tanpa pernah berakhir, sementara seluruh alam raya dan ciptaan akan fana dan musnah.",
        dalilRef: "QS. Ar-Rahman: 26-27",
        dalilText: "كُلُّ مَنْ عَلَيْهَا فَانٍ وَيَبْقَىٰ وَجْهُ رَبِّكَ ذُو الْجَلَالِ وَالْإِكْرَامِ",
        dalilTrans: "Semua yang ada di bumi itu akan binasa, tetapi Wajah Tuhanmu yang memiliki kebesaran dan kemuliaan tetap kekal.",
        ulamaQuote:
            "Ibnu Katsir: 'Kekekalan Allah adalah sifat hakiki yang tidak terikat oleh waktu dan kebinasaan alam fana.'",
        internalLink: "/quran/surah/55#verse-27",
        linkLabel: "Buka QS. Ar-Rahman: 27 di Quran",
    },
    98: {
        number: 98,
        latin: "Al-Warits",
        arabic: "الْوَارِثُ",
        meaning_idn: "Yang Maha Mewarisi",
        meaning_en: "The Supreme Inheritor",
        explanation:
            "Dzat yang tetap ada dan mewarisi seluruh alam semesta setelah kepunahan seluruh makhluk, dan kepada-Nya lah tempat kembali segala urusan.",
        dalilRef: "QS. Al-Hijr: 23",
        dalilText: "وَإِنَّا لَنَحْنُ نُحْيِي وَنُمِيتُ وَنَحْنُ الْوَارِثُونَ",
        dalilTrans: "Dan sungguh, Kamilah yang menghidupkan dan mematikan dan Kami (pulalah) yang mewarisi.",
        ulamaQuote:
            "Doa Nabi Zakariya 'alaihissalam: 'Rabbi la tadzarni fardan wa Anta Khairul Waritsin' (Ya Tuhanku janganlah Engkau biarkan aku hidup seorang diri dan Engkaulah Ahli Waris yang terbaik). (QS. Al-Anbiya: 89)",
        internalLink: "/quran/surah/15#verse-23",
        linkLabel: "Buka QS. Al-Hijr: 23 di Quran",
    },
    99: {
        number: 99,
        latin: "Ar-Rasyid",
        arabic: "الرَّشِيدُ",
        meaning_idn: "Yang Maha Membimbing ke Jalan Benar",
        meaning_en: "The Guide to Righteousness",
        explanation:
            "Dzat yang seluruh perbuatan dan ketetapan-Nya tepat, bijak, dan lurus, serta membimbing para hamba-Nya menuju kebaikan dunia dan keselamatan akhirat.",
        dalilRef: "QS. Al-Kahf: 10",
        dalilText: "رَبَّنَا آتِنَا مِنْ لَدُنْكَ رَحْمَةً وَهَيِّئْ لَنَا مِنْ أَمْرِنَا رَشَدًا",
        dalilTrans: "...'Wahai Tuhan kami! Berikanlah rahmat kepada kami dari sisi-Mu dan sempurnakanlah petunjuk yang lurus bagi kami dalam urusan kami.'",
        ulamaQuote:
            "Syaikh As-Sa'di: 'Ar-Rasyid adalah Yang sempurna kebijaksanaan-Nya, mengarahkan segala takdir menuju kebaikan yang sejati.' (Taisirul Karimir Rahman)",
        internalLink: "/quran/surah/18#verse-10",
        linkLabel: "Buka QS. Al-Kahf: 10 di Quran",
    },
};

export const asmaulHusnaGeneralDalil = {
    hadith: {
        ref: "HR. Bukhari No. 2736 & Muslim No. 2677",
        arabic: "إِنَّ لِلَّهِ تِسْعَةً وَتِسْعِينَ اسْمًا، مِائَةً إِلَّا وَاحِدًا، مَنْ أَحْصَاهَا دَخَلَ الْجَنَّةَ",
        trans: "Sesungguhnya Allah memiliki 99 nama, seratus kurang satu. Barangsiapa menghafalnya (dan memahaminya serta mengamalkannya), niscaya ia masuk surga.",
        link: "/hadith/bukhari/2736",
    },
    quran: {
        ref: "QS. Al-A'raf: 180",
        arabic: "وَلِلَّهِ الْأَسْمَاءُ الْحُسْنَىٰ فَادْعُوهُ بِهَا",
        trans: "Dan Allah memiliki Asma'ul Husna (nama-nama yang terbaik), maka bermohonlah kepada-Nya dengan menyebut Asma'ul Husna itu...",
        link: "/quran/surah/7#verse-180",
    },
};
