import {
    BsBarChart,
    BsBell,
    BsBook,
    BsCalendar3,
    BsCalculator,
    BsChatDots,
    BsCircleHalf,
    BsJournalCheck,
    BsPeopleFill,
    BsStickyFill,
    BsTrophyFill,
} from 'react-icons/bs';
import { FaBrain, FaQuran } from 'react-icons/fa';
import { GiCompass, GiOpenBook, GiPrayerBeads } from 'react-icons/gi';
import { ImBook } from 'react-icons/im';
import {
    MdAccessTime,
    MdArticle,
    MdCalendarMonth,
    MdCheckBox,
    MdExplore,
    MdFlag,
    MdFormatListBulleted,
    MdMenuBook,
    MdMosque,
    MdOutlineAutoStories,
    MdOutlineContactPhone,
    MdOutlineDirectionsWalk,
    MdOutlinePlayLesson,
    MdRefresh,
    MdSelfImprovement,
    MdStar,
    MdTimeline,
} from 'react-icons/md';
import { TbApi } from 'react-icons/tb';

export const linksMenu = [
    { label: 'Quran', labelKey: 'link.quran', href: '/quran', icon: <FaQuran /> },
    { label: 'Hadith', labelKey: 'link.hadith', href: '/hadith', icon: <ImBook /> },
    { label: 'Dev', labelKey: 'link.dev', href: '/dev', icon: <TbApi /> },
    { label: 'Contact', labelKey: 'link.contact', href: '/contact', icon: <MdOutlineContactPhone /> },
];

export const linksMenuContent = [
    { label: 'Asmaul Husna', labelKey: 'link.asmaul_husna', href: '/asmaul-husna', icon: <MdStar /> },
    { label: 'Flashcard Asmaul Husna', labelKey: 'link.asmaul_flashcard', href: '/asmaul-husna/flashcard', icon: <MdStar /> },
    { label: 'Wirid Asmaul Husna', labelKey: 'link.asmaul_wirid', href: '/asmaul-husna/wirid', icon: <GiPrayerBeads /> },
    { label: 'Doa', labelKey: 'link.doa', href: '/doa', icon: <MdSelfImprovement /> },
    { label: 'Dzikir', labelKey: 'link.dhikr', href: '/dzikir', icon: <GiOpenBook /> },
    { label: 'Panduan Sholat', labelKey: 'link.prayer_guide', href: '/panduan-sholat', icon: <MdMenuBook /> },
    { label: 'Wirid Sunnah', labelKey: 'link.wird', href: '/wirid', icon: <GiOpenBook /> },
    { label: 'Wirid Pribadi', labelKey: 'link.wirid_custom', href: '/wirid-custom', icon: <GiOpenBook /> },
    { label: 'Tahlil & Yasin', labelKey: 'link.tahlil', href: '/tahlil', icon: <BsBook /> },
    { label: 'Siroh', labelKey: 'link.sirah_short', href: '/siroh', icon: <MdMenuBook /> },
    { label: 'Tokoh Tarikh', labelKey: 'link.tokoh', href: '/tokoh', icon: <BsPeopleFill /> },
    { label: 'Peta Islam', labelKey: 'link.peta', href: '/peta', icon: <MdExplore /> },
    { label: 'Blog', labelKey: 'link.blog', href: '/blog', icon: <MdArticle /> },
    { label: 'Kajian Islam', labelKey: 'link.kajian', href: '/kajian', icon: <MdOutlinePlayLesson /> },
    { label: 'Perpustakaan Ilmu', labelKey: 'link.library', href: '/library', icon: <BsBook /> },
    { label: 'Forum Diskusi', labelKey: 'link.forum', href: '/forum', icon: <BsChatDots /> },
    { label: 'Asbabun Nuzul', labelKey: 'link.asbabun_nuzul', href: '/asbabun-nuzul', icon: <MdMenuBook /> },
    { label: 'Tafsir Al-Quran', labelKey: 'link.tafsir', href: '/tafsir', icon: <MdOutlineAutoStories /> },
    { label: 'Fiqh Ringkas', labelKey: 'link.brief_fiqh', href: '/fiqh', icon: <MdOutlineAutoStories /> },
    { label: 'Kamus Arab', labelKey: 'link.arabic_dict', href: '/kamus', icon: <BsBook /> },
    { label: 'Kalender Hijriah', labelKey: 'link.hijri_calendar', href: '/hijri', icon: <MdCalendarMonth /> },
    { label: 'Jadwal Sholat', labelKey: 'link.prayer_schedule', href: '/jadwal-sholat', icon: <MdAccessTime /> },
    { label: 'Leaderboard', labelKey: 'link.leaderboard', href: '/leaderboard', icon: <BsTrophyFill /> },
    { label: 'Quiz Islami', labelKey: 'link.quiz', href: '/quiz', icon: <FaBrain /> },
    { label: 'Sejarah Islam', labelKey: 'link.islamic_history', href: '/sejarah', icon: <MdTimeline /> },
    { label: 'Manasik Haji & Umrah', labelKey: 'link.manasik', href: '/manasik', icon: <MdOutlineDirectionsWalk /> },
    { label: 'Arah Kiblat', labelKey: 'link.qibla', href: '/kiblat', icon: <GiCompass /> },
    { label: 'Imsakiyah', labelKey: 'link.imsakiyah', href: '/imsakiyah', icon: <BsCalendar3 /> },
    { label: 'Tasbih Digital', labelKey: 'link.tasbih', href: '/tasbih', icon: <GiPrayerBeads /> },
    { label: 'Kalkulator Waris', labelKey: 'link.faraidh', href: '/faraidh', icon: <BsCalculator /> },
    { label: 'Kalkulator Zakat', labelKey: 'link.zakat', href: '/zakat', icon: <BsCalculator /> },
];

const pickContentLinks = (hrefs) =>
    hrefs
        .map((href) => linksMenuContent.find((link) => link.href === href))
        .filter(Boolean);

export const linksMenuContentGroups = [
    {
        labelKey: 'nav.content_group.worship',
        items: pickContentLinks([
            '/doa',
            '/dzikir',
            '/panduan-sholat',
            '/wirid',
            '/wirid-custom',
            '/tahlil',
            '/asmaul-husna',
            '/asmaul-husna/flashcard',
            '/asmaul-husna/wirid',
        ]),
    },
    {
        labelKey: 'nav.content_group.quran_learning',
        items: pickContentLinks([
            '/tafsir',
            '/asbabun-nuzul',
            '/fiqh',
            '/kamus',
            '/quiz',
            '/library',
            '/forum',
        ]),
    },
    {
        labelKey: 'nav.content_group.history_media',
        items: pickContentLinks([
            '/siroh',
            '/sejarah',
            '/tokoh',
            '/peta',
            '/blog',
            '/kajian',
            '/manasik',
        ]),
    },
    {
        labelKey: 'nav.content_group.tools',
        items: pickContentLinks([
            '/jadwal-sholat',
            '/hijri',
            '/imsakiyah',
            '/kiblat',
            '/tasbih',
            '/faraidh',
            '/zakat',
            '/leaderboard',
        ]),
    },
];

export const linksMenuAuth = [
    { label: 'Dashboard', labelKey: 'link.dashboard', href: '/dashboard', icon: <BsBarChart /> },
    { label: 'Bookmark', labelKey: 'link.bookmarks', href: '/bookmarks' },
    { label: 'Hafalan', labelKey: 'link.memorization', href: '/hafalan' },
    { label: "Muroja'ah", labelKey: 'link.review', href: '/muroja-ah', icon: <MdRefresh /> },
    { label: 'Tilawah', labelKey: 'link.recitation', href: '/tilawah', icon: <BsJournalCheck /> },
    { label: 'Khatam Tracker', labelKey: 'link.khatam', href: '/khatam', icon: <FaQuran /> },
    { label: 'Amalan', labelKey: 'link.deeds', href: '/amalan', icon: <MdFormatListBulleted /> },
    { label: 'Sholat Tracker', labelKey: 'link.sholat_tracker', href: '/sholat-tracker', icon: <MdMosque /> },
    { label: 'Catatan', labelKey: 'link.notes', href: '/notes', icon: <BsStickyFill /> },
    { label: 'Muhasabah', labelKey: 'link.muhasabah', href: '/muhasabah', icon: <MdSelfImprovement /> },
    { label: 'Target Belajar', labelKey: 'link.goals', href: '/goals', icon: <MdFlag /> },
    { label: 'Notifikasi', labelKey: 'link.notifications', href: '/notifications', icon: <BsBell /> },
    { label: 'Profil', labelKey: 'link.profile', href: '/profile' },
];

export const listMasjidImage = [
	{
		label: 'Masjid Al-Haram',
		src: '/assets/images/masjid/Haram1.jpg',
		alt: 'Masjid Al-Haram',
	},
	{
		label: 'Masjid Al-Haram',
		src: '/assets/images/masjid/Haram3.jpg',
		alt: 'Masjid Al-Haram',
	},
	{
		label: 'Masjid Al-Haram',
		src: '/assets/images/masjid/Haram4.jpg',
		alt: 'Masjid Al-Haram',
	},
	{ label: 'Masjid', src: '/assets/images/masjid/Masjid2.jpg', alt: 'Masjid' },
	{ label: 'Masjid', src: '/assets/images/masjid/Masjid3.jpg', alt: 'Masjid' },
	{ label: 'Masjid', src: '/assets/images/masjid/Masjid4.jpg', alt: 'Masjid' },
	{
		label: 'Masjid Nabawi',
		src: '/assets/images/masjid/Nabawi1.jpg',
		alt: 'Masjid Nabawi',
	},
	{
		label: 'Masjid Nabawi',
		src: '/assets/images/masjid/Nabawi2.jpg',
		alt: 'Masjid Nabawi',
	},
	{
		label: 'Masjid Nabawi',
		src: '/assets/images/masjid/Nabawi3.jpg',
		alt: 'Masjid Nabawi',
	},
	{
		label: 'Masjid Nabawi',
		src: '/assets/images/masjid/Nabawi6.jpg',
		alt: 'Masjid Nabawi',
	},
	// { label: 'Masjid Nabawi', src: '/assets/images/masjid/Nabawi7.jpg', alt:'Masjid Nabawi' },
];

export const hadithTabList = [
	{
		label: 'Book',
		alt: 'Book',
		href: '#book',
	},
	{
		label: 'Theme',
		alt: 'Theme',
		href: '#theme',
	},
	{
		label: 'Chapter',
		alt: 'Chapter',
		href: '#chapter',
	},
	{
		label: 'Hadith',
		alt: 'Hadith',
		href: '#hadith',
	},
];

export const listTajweed = [
    {
        Type: 'hamza-wasl',
        Identifier: '[h',
        Colour: '#AAAAAA',
        CSS: 'ham_wasl',
        Arabic: 'هَمْزَةُ الْوَصْل',
        Description: 'Hamzat ul Wasl',
        TitleId: 'Hamzah Wasal',
        DescriptionId: 'Hamzah penyambung — tidak dibaca di tengah kalimat',
        DescriptionEn: 'Connecting Hamzah — not pronounced in the middle of speech',
    },
    {
        Type: 'silent',
        Identifier: '[s',
        Colour: '#AAAAAA',
        CSS: 'slnt',
        Arabic: 'حَرْفٌ سَاكِن',
        Description: 'Silent',
        TitleId: 'Huruf Sukun',
        DescriptionId: 'Huruf yang dimatikan (sukun), tidak berbunyi',
        DescriptionEn: 'Letter with sukun (sukoon) — not pronounced',
    },
    {
        Type: 'laam-shamsiyah',
        Identifier: '[l',
        Colour: '#AAAAAA',
        CSS: 'slnt',
        Arabic: 'لَامٌ شَمْسِيَّة',
        Description: 'Lam Shamsiyyah',
        TitleId: 'Lam Syamsiyah',
        DescriptionId: 'Lam diidghamkan ke huruf syamsiyah yang mengikutinya',
        DescriptionEn: 'Lam assimilated into the following shamsiyyah letter',
    },
    {
        Type: 'madda-normal',
        Identifier: '[n',
        Colour: '#537FFF',
        CSS: 'madda_normal',
        Arabic: 'مَدٌّ طَبِيعِيّ',
        Description: 'Normal Prolongation: 2 Vowels',
        TitleId: "Mad Thabi'i: 2 Harakat",
        DescriptionId: 'Mad asli / alami — dibaca 2 harakat',
        DescriptionEn: 'Natural madd — read 2 harakats',
    },
    {
        Type: 'madda-permissible',
        Identifier: '[p',
        Colour: '#4050FF',
        CSS: 'madda_permissible',
        Arabic: 'مَدٌّ جَائِز',
        Description: 'Permissible Prolongation: 2, 4, 6 Vowels',
        TitleId: 'Mad Jaiz: 2, 4, 6 Harakat',
        DescriptionId: 'Mad boleh — dibaca 2, 4, atau 6 harakat (ikhtiyar)',
        DescriptionEn: 'Optional madd — read 2, 4, or 6 harakats (ikhtiyar)',
    },
    {
        Type: 'madda-necesssary',
        Identifier: '[m',
        Colour: '#000EBC',
        CSS: 'madda_necessary',
        Arabic: 'مَدٌّ لَازِم',
        Description: 'Necessary Prolongation: 6 Vowels',
        TitleId: 'Mad Lazim: 6 Harakat',
        DescriptionId: 'Mad wajib — harus dibaca 6 harakat',
        DescriptionEn: 'Obligatory madd — must be read 6 harakats',
    },
    {
        Type: 'qalaqah',
        Identifier: '[q',
        Colour: '#DD0008',
        CSS: 'qlq',
        Arabic: 'قَلْقَلَة',
        Description: 'Qalaqah',
        TitleId: 'Qalqalah',
        DescriptionId: 'Bunyi memantul pada huruf ق ط ب ج د saat mati/waqaf',
        DescriptionEn: 'Echoing sound on letters ق ط ب ج د when stopped/paused',
    },
    {
        Type: 'madda-obligatory',
        Identifier: '[o',
        Colour: '#2144C1',
        CSS: 'madda_pbligatory',
        Arabic: 'مَدٌّ وَاجِب',
        Description: 'Obligatory Prolongation: 4-5 Vowels',
        TitleId: 'Mad Wajib: 4-5 Harakat',
        DescriptionId: 'Mad wajib muttasil — dibaca 4-5 harakat',
        DescriptionEn: 'Mad wajib muttasil — read 4-5 harakats',
    },
    {
        Type: 'ikhafa-shafawi',
        Identifier: '[c',
        Colour: '#D500B7',
        CSS: 'ikhf_shfw',
        Arabic: 'إِخْفَاءٌ شَفَوِيّ',
        Description: "Ikhafa' Shafawi - With Meem",
        TitleId: "Ikhfa' Syafawi - Dengan Mim",
        DescriptionId: "Mim sukun bertemu ba' — dibaca samar dengan dengung",
        DescriptionEn: "Meem sukun meets ba' — read softly with nasalization",
    },
    {
        Type: 'ikhafa',
        Identifier: '[f',
        Colour: '#9400A8',
        CSS: 'ikhf',
        Arabic: 'إِخْفَاء',
        Description: "Ikhafa'",
        TitleId: "Ikhfa'",
        DescriptionId: 'Nun sukun/tanwin bertemu 15 huruf ikhfa — dibaca samar',
        DescriptionEn: 'Noon sukun/tanween meets one of 15 ikhfa letters — read softly',
    },
    {
        Type: 'idgham-shafawi',
        Identifier: '[w',
        Colour: '#58B800',
        CSS: 'idghm_shfw',
        Arabic: 'إِدْغَامٌ شَفَوِيّ',
        Description: 'Idgham Shafawi - With Meem',
        TitleId: 'Idgham Syafawi - Dengan Mim',
        DescriptionId: 'Mim sukun bertemu mim — dilebur dengan dengung',
        DescriptionEn: 'Meem sukun meets meem — merged with nasalization',
    },
    {
        Type: 'iqlab',
        Identifier: '[i',
        Colour: '#26BFFD',
        CSS: 'iqlb',
        Arabic: 'إِقْلَاب',
        Description: 'Iqlab',
        TitleId: 'Iqlab',
        DescriptionId: "Nun sukun/tanwin bertemu ba' — berubah bunyi menjadi mim",
        DescriptionEn: "Noon sukun/tanween meets ba' — sound changes to meem",
    },
    {
        Type: 'idgham-with-ghunnah',
        Identifier: '[a',
        Colour: '#169777',
        CSS: 'idgh_ghn',
        Arabic: 'إِدْغَامٌ بِغُنَّة',
        Description: 'Idgham - With Ghunnah',
        TitleId: 'Idgham - Dengan Ghunnah',
        DescriptionId: 'Nun sukun/tanwin masuk ke ي ن م و — dengan dengung',
        DescriptionEn: 'Noon sukun/tanween enters ي ن م و — with nasalization',
    },
    {
        Type: 'idgham-without-ghunnah',
        Identifier: '[u',
        Colour: '#169200',
        CSS: 'idgh_w_ghn',
        Arabic: 'إِدْغَامٌ بِلَا غُنَّة',
        Description: 'Idgham - Without Ghunnah',
        TitleId: 'Idgham - Tanpa Ghunnah',
        DescriptionId: 'Nun sukun/tanwin masuk ke ل ر — tanpa dengung',
        DescriptionEn: 'Noon sukun/tanween enters ل ر — without nasalization',
    },
    {
        Type: 'idgham-mutajanisayn',
        Identifier: '[d',
        Colour: '#A1A1A1',
        CSS: 'idgh_mus',
        Arabic: 'إِدْغَامُ الْمُتَجَانِسَيْن',
        Description: 'Idgham - Mutajanisayn',
        TitleId: 'Idgham - Mutajanisain',
        DescriptionId: 'Dua huruf sejenis makhraj & sifat bertemu — dilebur',
        DescriptionEn: 'Two letters of identical makhraj & sifat meet — merged',
    },
    {
        Type: 'idgham-mutaqaribayn',
        Identifier: '[b',
        Colour: '#A1A1A1',
        CSS: 'idgh_mus',
        Arabic: 'إِدْغَامُ الْمُتَقَارِبَيْن',
        Description: 'Idgham - Mutaqaribayn',
        TitleId: 'Idgham - Mutaqaribayn',
        DescriptionId: 'Dua huruf berdekatan makhrajnya bertemu — dilebur',
        DescriptionEn: 'Two letters with close makhraj meet — merged',
    },
    {
        Type: 'ghunnah',
        Identifier: '[g',
        Colour: '#FF7E1E',
        CSS: 'ghn',
        Arabic: 'غُنَّة',
        Description: 'Ghunnah: 2 Vowels',
        TitleId: 'Ghunnah: 2 Harakat',
        DescriptionId: 'Dengung 2 harakat pada nun/mim bertasydid ( نّ / مّ )',
        DescriptionEn: 'Nasalization of 2 harakats on shadda noon/meem ( نّ / مّ )',
    },
];
