export const JAKARTA_DOMISILI = [
    "Semua Jakarta",
    "Jakarta Pusat",
    "Jakarta Selatan",
    "Jakarta Barat",
    "Jakarta Timur",
    "Jakarta Utara",
    "Bodetabek",
];

export const RADIO_DOMISILI = [
    "Semua Domisili",
    "Jakarta",
    "Bogor",
    "Depok",
    "Tangerang",
    "Bekasi",
    "Bandung",
    "Surabaya",
    "Yogyakarta",
    "Nasional / Streaming",
];

export const JAKARTA_MASJIDS = [
    {
        id: 1,
        name: "Masjid Jami' Al-Barkah (Rodja)",
        city: "Jakarta Timur",
        district: "Kramat Jati",
        address: "Jl. Raya Condet No.27, Batu Ampar, Kramat Jati, Jakarta Timur 13520",
        lat: -6.2704,
        lng: 106.8678,
        capacity: 2500,
        phone: "021-87781371",
        website: "https://radiorodja.com",
        facilities: [
            "Kajian Sunnah Rutin",
            "Live Streaming Rodja",
            "Perpustakaan Kitab",
            "Area Wudhu Luas",
            "Parkir",
        ],
        description: "Masjid utama sekaligus pusat Radio Rodja 756 AM. Siaran kajian ilmiah Islam berlandaskan Al-Qur'an dan As-Sunnah pemahaman Salafush Shalih.",
    },
    {
        id: 2,
        name: "Masjid Nur-Salma",
        city: "Jakarta Selatan",
        district: "Setiabudi",
        address: "Jl. HR. Rasuna Said Kav. B1-3, Karet Kuningan, Setiabudi, Jakarta Selatan 12940",
        lat: -6.2180,
        lng: 106.8310,
        capacity: 1500,
        phone: "021-52901234",
        website: "https://nursalma.or.id",
        facilities: [
            "Kajian Sunnah",
            "Perpustakaan Kitab Kuning",
            "Area Wudhu",
            "Kelas Tahsin & Tahfizh",
        ],
        description: "Masjid yayasan Nur-Salma yang diasuh Ustadz Dr. Erwandi Tarmizi, MA. Fokus kajian tauhid, jual-beli riba, dan hadits arbain.",
    },
    {
        id: 3,
        name: "Masjid Nurim Blok M",
        city: "Jakarta Selatan",
        district: "Kebayoran Baru",
        address: "Jl. Wolter Monginsidi No.71, Kebayoran Baru, Jakarta Selatan 12180",
        lat: -6.2440,
        lng: 106.7995,
        capacity: 1800,
        phone: "021-7206123",
        facilities: [
            "Kajian Sunnah Pekanan",
            "Kelas Bahasa Arab",
            "Wudhu & Parkir",
        ],
        description: "Masjid di pusat Blok M, pengajian rutin ahlussunnah waljama'ah yang ramai dikunjungi karyawan & mahasiswa sekitar Kebayoran.",
    },
    {
        id: 4,
        name: "Masjid Sunda Kelapa",
        city: "Jakarta Pusat",
        district: "Menteng",
        address: "Jl. Taman Sunda Kelapa No.16, Menteng, Jakarta Pusat 10310",
        lat: -6.1996,
        lng: 106.8329,
        capacity: 4000,
        phone: "021-31934261",
        website: "https://masjidsundakelapa.id",
        facilities: [
            "Kajian Rutin Sunnah",
            "Perpustakaan",
            "Aula Serbaguna",
            "Klinik Dhuafa",
            "Parkir",
        ],
        description: "Pusat dakwah dan kajian sunnah di kawasan Menteng. Dipimpin Ustadz Dudi Muttaqien dan asatidzah salaf lainnya.",
    },
    {
        id: 5,
        name: "Masjid Al-Ikhlas Cipete",
        city: "Jakarta Selatan",
        district: "Cilandak",
        address: "Jl. Cipete III No.3, Cipete Selatan, Cilandak, Jakarta Selatan 12410",
        lat: -6.2789,
        lng: 106.8042,
        capacity: 2500,
        phone: "021-7690123",
        facilities: [
            "Kajian Sunnah Rutin",
            "Streaming YouTube/Audio",
            "Perpustakaan",
            "Parkir Motor/Mobil",
        ],
        description: "Salah satu pusat kajian ilmiah dan tadabbur Qur'an teraktif di Cipete-Cilandak, salaf-affiliated.",
    },
    {
        id: 6,
        name: "Masjid Baitussalam Billy Moon",
        city: "Jakarta Timur",
        district: "Duren Sawit",
        address: "Komplek Billy Moon, Pondok Kelapa, Duren Sawit, Jakarta Timur 13450",
        lat: -6.2367,
        lng: 106.9242,
        capacity: 3000,
        phone: "021-8645123",
        facilities: [
            "Kajian Sunnah Tematik",
            "AC Dingin",
            "Perpustakaan",
            "Parkir",
        ],
        description: "Masjid kajian sunnah tematik di kawasan Duren Sawit dengan pengajian keluarga dan pemuda aktif.",
    },
    {
        id: 7,
        name: "Masjid Jami' Imam Asy-Syafi'i BSD",
        city: "Tangerang Selatan",
        district: "Serpong",
        address: "Jl. Kalimantan, BSD City, Serpong, Tangerang Selatan, Banten 15310",
        lat: -6.3039,
        lng: 106.6847,
        capacity: 2000,
        phone: "021-5371234",
        facilities: [
            "Kajian Sunnah",
            "Perpustakaan",
            "Ruang Wudhu",
            "Parkir Luas",
        ],
        description: "Masjid jami ahlussunnah di kawasan BSD City, dikenal dengan kajian hadits arbain dan fikih perbandingan madzhab.",
    },
    {
        id: 8,
        name: "Masjid Ar-Rohmah Cibubur",
        city: "Bogor",
        district: "Gunung Putri",
        address: "Komp. Kota Wisata Cibubur, Nagrak, Gunung Putri, Bogor, Jawa Barat 16968",
        lat: -6.3688,
        lng: 106.9486,
        capacity: 1500,
        phone: "021-84934567",
        facilities: [
            "Kajian Keluarga",
            "Kelas Tahfizh",
            "Wudhu",
            "Parkir",
        ],
        description: "Masjid ahlussunnah di Cibubur, pengajian keluarga dan remaja aktif dengan tema tarbiyah dan aqidah.",
    },
];

export const ISLAMIC_RADIOS = [
    {
        id: 1,
        name: "Radio Rodja 756 AM",
        frequency: "756 AM",
        frequencyType: "AM",
        city: "Jakarta",
        province: "DKI Jakarta / Jabar",
        coverageArea: "Jakarta, Bogor, Depok, Tangerang, Bekasi, Banten, Jabar Barat",
        streamUrl: "https://live2.radiorodja.com/rodja.mp3",
        website: "https://radiorodja.com",
        description: "Radio Menebar Cahaya Sunnah. Siaran kajian ilmiah Islam berlandaskan Al-Qur'an dan As-Sunnah pemahaman para sahabat Nabi (Salafush Shalih). Tanya-jawab fiqih, tafsir, aqidah, dan bahasa Arab.",
        tags: ["Kajian Sunnah", "Tafsir", "Bahasa Arab", "Tanya Jawab"],
        frequencyNotice: "Di Jakarta & sekitarnya frekuensi 756 AM adalah Radio Rodja. Di luar pulau Jawa, frekuensi AM 756 kHz dapat dialokasikan untuk siaran lain atau menggunakan pemancar relay lokal.",
    },
    {
        id: 2,
        name: "Radio Silaturahim (Rasil) 720 AM",
        frequency: "720 AM",
        frequencyType: "AM",
        city: "Jakarta",
        province: "DKI Jakarta",
        coverageArea: "Jabodetabek dan sebagian Jawa Barat",
        streamUrl: "https://ssg.streamingmurah.com:9300/;",
        website: "https://radiosilaturahim.com",
        description: "Untuk Islam yang Satu. Menyajikan kajian keislaman lintas madzhab, dialog kebangsaan, warta dunia Islam, konsultasi medis herbal, dan pembinaan keluarga sakinah.",
        tags: ["Ukhuwah", "Kajian Tematik", "Kesehatan Herbal", "Berita Islam"],
        frequencyNotice: "Frekuensi 720 AM di Jabodetabek diisi oleh Radio Silaturahim. Di kota/wilayah lain gelombang 720 AM dialokasikan untuk stasiun radio daerah berbeda.",
    },
    {
        id: 3,
        name: "Radio Fajri 99.3 FM",
        frequency: "99.3 FM",
        frequencyType: "FM",
        city: "Bogor",
        province: "Jawa Barat / Jakarta",
        coverageArea: "Bogor, Depok, Jakarta Selatan & Jakarta Timur",
        streamUrl: "https://radio.mitradio.com/listen/fajrifm/radio.mp3",
        website: "https://fajrifm.com",
        description: "Suara Kebangkitan Islam. Program dakwah keluarga islami, bimbingan tilawah, tadabbur ayat, dan kajian fiqih praktis sehari-hari.",
        tags: ["Keluarga Islami", "Kajian", "Tahsin", "Remaja"],
        frequencyNotice: "99.3 FM di kawasan Jabodetabek selatan adalah Radio Fajri. Di Bandung atau kota lain, 99.3 FM bisa merupakan radio komersial musik atau radio lokal lain.",
    },
    {
        id: 4,
        name: "Radio Muadz (Jakarta & Kendari)",
        frequency: "Digital Streaming",
        frequencyType: "Online",
        city: "Jakarta",
        province: "DKI Jakarta",
        coverageArea: "Seluruh Indonesia & Mancanegara (Aplikasi & Web)",
        streamUrl: "https://radioislamindonesia.com/radiomuadz.mp3",
        website: "https://radiomuadz.com",
        description: "Radio dakwah Ahlussunnah wal Jama'ah menyiarkan kajian fiqih, tafsir, aqidah shahihah, doa dzikir, dan murottal Al-Qur'an tartil 24 jam nonstop.",
        tags: ["Murottal", "Kajian Ilmiah", "Aqidah", "Fiqih"],
        frequencyNotice: "Siaran digital online dapat didengarkan dari mana saja tanpa interferensi frekuensi udara.",
    },
    {
        id: 5,
        name: "Radio Tarbiyah Sunnah (1476 AM)",
        frequency: "1476 AM",
        frequencyType: "AM",
        city: "Bandung",
        province: "Jawa Barat",
        coverageArea: "Bandung Raya, Priangan Timur, Jakarta & Jabar via Relay",
        streamUrl: "https://radioislamindonesia.com/tarbiyah.mp3",
        website: "https://tarbiyahsunnah.com",
        description: "Radio kajian sunnah dan pembersihan jiwa (tazkiyatun nufus) asuhan para asatidzah senior seperti Ustadz Abu Haidar As-Sundawy.",
        tags: ["Tazkiyatun Nufus", "Sunnah", "Hadits", "Aqidah"],
        frequencyNotice: "1476 AM mengudara dari Bandung. Di luar Jawa Barat, frekuensi ini tidak terjangkau gelombang darat dan memerlukan streaming digital.",
    },
    {
        id: 6,
        name: "Radio Muslim Jogja (1467 AM)",
        frequency: "1467 AM",
        frequencyType: "AM",
        city: "Yogyakarta",
        province: "DI Yogyakarta",
        coverageArea: "Yogyakarta, Sleman, Bantul, dan sekitarnya",
        streamUrl: "https://streaming.radiomuslim.com/;stream/1",
        website: "https://radiomuslim.com",
        description: "Memurnikan Aqidah Menebarkan Sunnah. Radio dakwah ilmiah yang dikelola oleh pemuda dan mahasiswa muslim di Yogyakarta.",
        tags: ["Mahasiswa", "Kajian Ilmiah", "Hadits Shahih", "Jogja"],
        frequencyNotice: "Frekuensi 1467 AM adalah stasiun Radio Muslim di Yogyakarta. Warga Jakarta mendengarkan melalui relay streaming resmi.",
    },
    {
        id: 7,
        name: "Radio Suara Al-Iman (846 AM)",
        frequency: "846 AM",
        frequencyType: "AM",
        city: "Surabaya",
        province: "Jawa Timur",
        coverageArea: "Surabaya, Sidoarjo, Gresik, Madura, Jatim",
        streamUrl: "https://radioislamindonesia.com/aliman.mp3",
        website: "https://suaraaliman.com",
        description: "Sarana Menyapa Hati dengan Sunnah. Pusat kajian ilmiah asatidzah STDI Imam Syafi'i Jember & Surabaya.",
        tags: ["Kajian Fiqih", "Hadits", "Bahasa Arab", "Surabaya"],
        frequencyNotice: "Frekuensi 846 AM berlaku di Jawa Timur. Di kota lain frekuensi ini kosong atau dipakai stasiun lokal lainnya.",
    },
    {
        id: 8,
        name: "Radio Kita 94.3 FM (Cirebon)",
        frequency: "94.3 FM",
        frequencyType: "FM",
        city: "Cirebon",
        province: "Jawa Barat",
        coverageArea: "Cirebon, Indramayu, Majalengka, Kuningan",
        streamUrl: "https://broadcast.yufid.com/listen/radio_sunnah_cirebon/kitafm",
        website: "https://radiokitafm.com",
        description: "Menebar Sunnah Membangun Umat. Radio dakwah sunnah tertua di kawasan pantura Jawa Barat.",
        tags: ["Pantura", "Kajian Sunnah", "Keluarga"],
        frequencyNotice: "94.3 FM di Cirebon adalah Radio Kita. Di Jakarta frekuensi 94.3 FM dipegang oleh radio swasta musik perkotaan.",
    },
    {
        id: 9,
        name: "Radio Hang 106.0 FM (Batam-Kepri)",
        frequency: "106.0 FM",
        frequencyType: "FM",
        city: "Batam",
        province: "Kepulauan Riau",
        coverageArea: "Batam, Tanjung Pinang, Singapura, Johor Bahru Malaysia",
        streamUrl: "https://icecast.surau.tv/hangfm",
        website: "https://hangfm.id",
        description: "Radio Dakwah Islam di batas negeri yang menjangkau pemirsa serumpun Indonesia, Singapura, dan Malaysia.",
        tags: ["Perbatasan", "Kajian", "Serumpun Melayu"],
        frequencyNotice: "106.0 FM di Batam adalah Radio Hang. Di Jakarta frekuensi 106.0 FM adalah radio umum komersial.",
    },
    {
        id: 10,
        name: "Murottal Quran 24 Jam Nonstop",
        frequency: "Live Stream 24/7",
        frequencyType: "Online",
        city: "Nasional",
        province: "Seluruh Wilayah",
        coverageArea: "Global (Internet)",
        streamUrl: "",
        description: "Siaran tilawah Al-Qur'an 30 juz 24 jam nonstop dari para Qari terkemuka: Misyari Rasyid, Sudais, Syuraim, Al-Ghamidi, Al-Hushari.",
        tags: ["Murottal", "Tilawah 30 Juz", "24 Jam", "Ketenangan Jiwa"],
        frequencyNotice: "Tersedia secara online tanpa batasan frekuensi radio terrestrial.",
    },
];

export function calculateDistanceKm(lat1, lon1, lat2, lon2) {
    if (lat1 == null || lon1 == null || lat2 == null || lon2 == null)
        return null;
    const R = 6371; // radius bumi dalam km
    const dLat = ((lat2 - lat1) * Math.PI) / 180;
    const dLon = ((lon2 - lon1) * Math.PI) / 180;
    const a =
        Math.sin(dLat / 2) * Math.sin(dLat / 2) +
        Math.cos((lat1 * Math.PI) / 180) *
            Math.cos((lat2 * Math.PI) / 180) *
            Math.sin(dLon / 2) *
            Math.sin(dLon / 2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    return Math.round(R * c * 10) / 10;
}

export function getNearbyMasjids(userLat, userLng, masjids = JAKARTA_MASJIDS) {
    if (userLat == null || userLng == null) return [];
    return masjids
        .map((m) => {
            const distance = calculateDistanceKm(
                userLat,
                userLng,
                m.lat,
                m.lng,
            );
            return {
                ...m,
                distance_km: distance,
            };
        })
        .sort((a, b) => (a.distance_km ?? 9999) - (b.distance_km ?? 9999));
}
