export const routeOverrides = {
    "/admin/blog/[id]/edit": "/admin/blog/1/edit",
    "/admin/siroh/[id]/edit": "/admin/siroh/1/edit",
    "/blog/[slug]": "/blog/sample-post",
    "/dashboard/blog/[slug]": "/dashboard/blog/sample-post",
    "/dashboard/forum/[slug]": "/dashboard/forum/sample-question",
    "/dashboard/hadith/[slug]": "/dashboard/hadith/bukhari",
    "/dashboard/hadith/[slug]/[number]": "/dashboard/hadith/bukhari/1",
    "/dashboard/hadith/theme/[slug]": "/dashboard/hadith/theme/niat",
    "/dashboard/library/[slug]": "/dashboard/library/sample-book",
    "/dashboard/perawi/[id]": "/dashboard/perawi/1",
    "/dashboard/quran/[slug]": "/dashboard/quran/Al-Fatihah",
    "/dashboard/siroh/[slug]": "/dashboard/siroh/sample-story",
    "/dashboard/tafsir/[slug]": "/dashboard/tafsir/Al-Fatihah",
    "/forum/[slug]": "/forum/sample-question",
    "/hadith/[slug]": "/hadith/bukhari",
    "/hadith/[slug]/[number]": "/hadith/bukhari/1",
    "/hadith/theme/[slug]": "/hadith/theme/niat",
    "/hadits/[slug]/[number]": "/hadits/bukhari/1",
    "/library/[slug]": "/library/sample-book",
    "/perawi/[id]": "/perawi/1",
    "/quran/[...slug]": "/quran/surah/Al-Fatihah",
    "/siroh/[id]": "/siroh/1",
    "/tafsir/[slug]": "/tafsir/Al-Fatihah",
};

export const dashboardRedirectRoutes = [
    "/amalan",
    "/bookmarks",
    "/goals",
    "/hafalan",
    "/muhasabah",
    "/muroja-ah",
    "/notifications",
    "/sholat-tracker",
    "/stats",
    "/tilawah",
];

export const publicRoutes = [
    "/",
    "/amalan",
    "/asbabun-nuzul",
    "/asmaul-husna",
    "/asmaul-husna/flashcard",
    "/auth/login",
    "/auth/register",
    "/blog",
    "/contact",
    "/dev",
    "/doa",
    "/dzikir",
    "/faraidh",
    "/fiqh",
    "/goals",
    "/hadith",
    "/hafalan",
    "/hijri",
    "/imsakiyah",
    "/jadwal-sholat",
    "/kajian",
    "/kamus",
    "/khatam",
    "/kiblat",
    "/leaderboard",
    "/manasik",
    "/muhasabah",
    "/muroja-ah",
    "/notes",
    "/panduan-sholat",
    "/perawi",
    "/quran",
    "/quran/page-mushaf",
    "/quiz",
    "/search",
    "/sejarah",
    "/sholat-tracker",
    "/siroh",
    "/stats",
    "/tafsir",
    "/tahlil",
    "/tasbih",
    "/tilawah",
    "/wirid",
    "/wirid-custom",
    "/zakat",
];

export const dashboardRoutes = [
    "/dashboard",
    "/dashboard/achievements",
    "/dashboard/amalan",
    "/dashboard/asbabun-nuzul",
    "/dashboard/asmaul-husna",
    "/dashboard/asmaul-husna/flashcard",
    "/dashboard/asmaul-husna/wirid",
    "/dashboard/belajar",
    "/dashboard/belajar/lessons",
    "/dashboard/blog",
    "/dashboard/blog/[slug]",
    "/dashboard/bookmarks",
    "/dashboard/doa",
    "/dashboard/dzikir",
    "/dashboard/faraidh",
    "/dashboard/feed",
    "/dashboard/fiqh",
    "/dashboard/forum",
    "/dashboard/forum/ask",
    "/dashboard/forum/[slug]",
    "/dashboard/goals",
    "/dashboard/hadith",
    "/dashboard/hadith/[slug]",
    "/dashboard/hadith/[slug]/[number]",
    "/dashboard/hadith/theme/[slug]",
    "/dashboard/hafalan",
    "/dashboard/hijri",
    "/dashboard/imsakiyah",
    "/dashboard/jadwal-sholat",
    "/dashboard/kajian",
    "/dashboard/kamus",
    "/dashboard/khatam",
    "/dashboard/kiblat",
    "/dashboard/komunitas",
    "/dashboard/leaderboard",
    "/dashboard/library",
    "/dashboard/library/[slug]",
    "/dashboard/manasik",
    "/dashboard/masjid",
    "/dashboard/muhasabah",
    "/dashboard/muroja-ah",
    "/dashboard/notes",
    "/dashboard/notifications",
    "/dashboard/panduan-sholat",
    "/dashboard/perawi",
    "/dashboard/perawi/[id]",
    "/dashboard/peta",
    "/dashboard/profile",
    "/dashboard/quran",
    "/dashboard/quran/page-mushaf",
    "/dashboard/quran/[slug]",
    "/dashboard/quiz",
    "/dashboard/radio-islamic",
    "/dashboard/reports",
    "/dashboard/search",
    "/dashboard/sejarah",
    "/dashboard/settings",
    "/dashboard/sholat-tracker",
    "/dashboard/siroh",
    "/dashboard/siroh/[slug]",
    "/dashboard/stats",
    "/dashboard/tafsir",
    "/dashboard/tafsir/[slug]",
    "/dashboard/tasbih",
    "/dashboard/tilawah",
    "/dashboard/tokoh",
    "/dashboard/wirid",
    "/dashboard/wirid-custom",
    "/dashboard/zakat",
    "/dashboard/zakat/history",
];

export function concretizeRoute(route) {
    if (routeOverrides[route]) return routeOverrides[route];
    return route
        .replace("[...slug]", "sample")
        .replace("[slug]", "sample")
        .replace("[id]", "1")
        .replace("[number]", "1");
}

export function getConcreteDashboardRoutes() {
    return dashboardRoutes.map(concretizeRoute);
}

export function getConcretePublicRoutes() {
    return publicRoutes.map(concretizeRoute);
}
