const testCases = [
    {
        id: "tab-home",
        name: "Tab Beranda",
        type: "tab",
        tab: "home",
        deepLink: "thullaabulilmi://home",
        actions: [
            { type: "swipe", x1: 540, y1: 1500, x2: 540, y2: 600, duration: 250 },
            { type: "swipe", x1: 540, y1: 600, x2: 540, y2: 1500, duration: 250 },
            { type: "wait", ms: 300 },
        ],
        assertTexts: ["Beranda"],
    },
    {
        id: "tab-quran",
        name: "Tab Al-Quran",
        type: "tab",
        tab: "quran",
        deepLink: "thullaabulilmi://quran",
        actions: [
            { type: "type", placeholder: "Cari surah...", text: "Baqarah" },
            { type: "wait", ms: 500 },
            { type: "tap", text: "Al-Baqarah" },
            { type: "wait", ms: 800 },
        ],
        assertTexts: ["Al-Baqarah", "Sapi Betina"],
    },
    {
        id: "tab-hadith",
        name: "Tab Hadis",
        type: "tab",
        tab: "hadith",
        deepLink: "thullaabulilmi://hadith",
        actions: [
            { type: "tap", text: "Bukhari" },
            { type: "wait", ms: 400 },
            { type: "tap", text: "Muslim" },
            { type: "wait", ms: 400 },
            { type: "tap", text: "Abu Daud" },
            { type: "wait", ms: 400 },
            { type: "tap", text: "Bukhari" },
            { type: "wait", ms: 400 },
        ],
        assertTexts: ["Shahih Bukhari"],
    },
    {
        id: "tab-ibadah",
        name: "Tab Ibadah",
        type: "tab",
        tab: "ibadah",
        deepLink: "thullaabulilmi://ibadah",
        assertTexts: ["Ibadah", "Kiblat"],
    },
    {
        id: "tab-belajar",
        name: "Tab Belajar",
        type: "tab",
        tab: "belajar",
        deepLink: "thullaabulilmi://belajar",
        actions: [
            { type: "swipe", x1: 540, y1: 1600, x2: 540, y2: 600, duration: 250 },
            { type: "swipe", x1: 540, y1: 600, x2: 540, y2: 1600, duration: 250 },
        ],
        assertTexts: ["Belajar"],
    },
    {
        id: "feature-doa",
        name: "Doa Harian & Pilihan",
        type: "feature",
        featureKey: "doa",
        deepLink: "thullaabulilmi://belajar/doa",
        actions: [
            { type: "type", placeholder: "Cari", text: "tidur" },
            { type: "wait", ms: 400 },
            { type: "tap", text: "Sebelum Tidur" },
            { type: "wait", ms: 400 },
        ],
        assertTexts: ["Doa", "Tidur"],
    },
    {
        id: "feature-zakat",
        name: "Kalkulator Zakat",
        type: "feature",
        featureKey: "zakat",
        deepLink: "thullaabulilmi://belajar/zakat",
        actions: [
            { type: "tap", text: "pill-Fitrah", attr: "resource-id" },
            { type: "wait", ms: 300 },
            { type: "tap", text: "pill-Dagang", attr: "resource-id" },
            { type: "wait", ms: 300 },
            { type: "tap", text: "pill-Tani", attr: "resource-id" },
            { type: "wait", ms: 300 },
            { type: "tap", text: "pill-Emas", attr: "resource-id" },
            { type: "wait", ms: 300 },
            { type: "tap", text: "pill-Maal", attr: "resource-id" },
            { type: "wait", ms: 300 },
            { type: "swipe", x1: 540, y1: 1400, x2: 540, y2: 600, duration: 250 },
            { type: "swipe", x1: 540, y1: 600, x2: 540, y2: 1400, duration: 250 },
        ],
        assertTexts: ["Zakat", "Maal", "Fitrah", "Harga emas"],
    },
    {
        id: "feature-dzikir",
        name: "Dzikir",
        type: "feature",
        featureKey: "dzikir",
        deepLink: "thullaabulilmi://belajar/dzikir",
        actions: [
            { type: "swipe", x1: 540, y1: 1400, x2: 540, y2: 600, duration: 250 },
            { type: "swipe", x1: 540, y1: 600, x2: 540, y2: 1400, duration: 250 },
        ],
        assertTexts: ["Dzikir"],
    },
    {
        id: "feature-wirid",
        name: "Wirid Rutin",
        type: "feature",
        featureKey: "wirid",
        deepLink: "thullaabulilmi://belajar/wirid",
        assertTexts: ["Wirid"],
    },
    {
        id: "feature-user-wird",
        name: "Wirid Saya",
        type: "feature",
        featureKey: "user-wird",
        deepLink: "thullaabulilmi://belajar/user-wird",
        assertTexts: ["Wirid"],
    },
    {
        id: "feature-asmaul-wirid",
        name: "Wirid Asmaul Husna",
        type: "feature",
        featureKey: "asmaul-wirid",
        deepLink: "thullaabulilmi://belajar/asmaul-wirid",
        assertTexts: ["Asmaul Husna"],
    },
    {
        id: "feature-amalan",
        name: "Amalan Harian",
        type: "feature",
        featureKey: "amalan",
        deepLink: "thullaabulilmi://belajar/amalan",
        assertTexts: ["Amalan"],
    },
    {
        id: "feature-asmaul-husna",
        name: "Asmaul Husna List",
        type: "feature",
        featureKey: "asmaul-husna",
        deepLink: "thullaabulilmi://belajar/asmaul-husna",
        actions: [
            { type: "type", placeholder: "Cari nama Allah", text: "Rahman" },
            { type: "wait", ms: 400 },
        ],
        assertTexts: ["Asmaul Husna", "الرَّحْمَنُ"],
    },
    {
        id: "feature-asmaul-flashcard",
        name: "Flashcard Asmaul Husna",
        type: "feature",
        featureKey: "asmaul-flashcard",
        deepLink: "thullaabulilmi://belajar/asmaul-flashcard",
        actions: [
            { type: "tap", text: "web-app-asmaul-flashcard-card", attr: "resource-id" },
            { type: "wait", ms: 400 },
            { type: "tap", text: "Sembunyikan" },
            { type: "wait", ms: 400 },
            { type: "tap", text: "Selanjutnya" },
            { type: "wait", ms: 400 },
            { type: "tap", text: "Acak" },
            { type: "wait", ms: 400 },
        ],
        assertTexts: ["Flashcard", "Asmaul Husna"],
    },
    {
        id: "feature-tafsir",
        name: "Tafsir Al-Quran",
        type: "feature",
        featureKey: "tafsir",
        deepLink: "thullaabulilmi://belajar/tafsir",
        assertTexts: ["Tafsir"],
    },
    {
        id: "feature-asbabun-nuzul",
        name: "Asbabun Nuzul",
        type: "feature",
        featureKey: "asbabun-nuzul",
        deepLink: "thullaabulilmi://belajar/asbabun-nuzul",
        assertTexts: ["Asbabun Nuzul"],
    },
    {
        id: "feature-panduan-sholat",
        name: "Panduan Sholat",
        type: "feature",
        featureKey: "panduan-sholat",
        deepLink: "thullaabulilmi://belajar/panduan-sholat",
        actions: [
            { type: "type", placeholder: "Cari tata cara", text: "Wudhu" },
            { type: "wait", ms: 400 },
            { type: "tap", text: "Wudhu", attr: "content-desc" },
            { type: "wait", ms: 400 },
            { type: "tap", text: "Sholat", attr: "content-desc" },
            { type: "wait", ms: 400 },
            { type: "tap", text: "Sunnah", attr: "content-desc" },
            { type: "wait", ms: 400 },
            { type: "tap", text: "Dzikir", attr: "content-desc" },
            { type: "wait", ms: 400 },
            { type: "tap", text: "Umum", attr: "content-desc" },
            { type: "wait", ms: 400 },
            { type: "swipe", x1: 540, y1: 1400, x2: 540, y2: 600, duration: 250 },
            { type: "swipe", x1: 540, y1: 600, x2: 540, y2: 1400, duration: 250 },
        ],
        assertTexts: ["Panduan Sholat", "Niat", "Takbiratul Ihram", "Wudhu", "Sholat", "Sunnah", "Dzikir", "Umum"],
    },
    {
        id: "feature-siroh",
        name: "Siroh Nabawiyah",
        type: "feature",
        featureKey: "siroh",
        deepLink: "thullaabulilmi://belajar/siroh",
        assertTexts: ["Siroh"],
    },
    {
        id: "feature-tokoh",
        name: "Tokoh Tarikh",
        type: "feature",
        featureKey: "tokoh",
        deepLink: "thullaabulilmi://belajar/tokoh",
        assertTexts: ["Tokoh"],
    },
    {
        id: "feature-sejarah",
        name: "Sejarah Islam",
        type: "feature",
        featureKey: "sejarah",
        deepLink: "thullaabulilmi://belajar/sejarah",
        assertTexts: ["Sejarah"],
    },
    {
        id: "feature-historical-map",
        name: "Peta Islam Interaktif",
        type: "feature",
        featureKey: "historical-map",
        deepLink: "thullaabulilmi://belajar/historical-map",
        assertTexts: ["Peta", "Sejarah"],
    },
    {
        id: "feature-masjid",
        name: "Direktori Masjid",
        type: "feature",
        featureKey: "masjid",
        deepLink: "thullaabulilmi://belajar/masjid",
        assertTexts: ["Masjid"],
    },
    {
        id: "feature-radio-islamic",
        name: "Radio Islam",
        type: "feature",
        featureKey: "radio-islamic",
        deepLink: "thullaabulilmi://belajar/radio-islamic",
        assertTexts: ["Radio"],
    },
    {
        id: "feature-fiqh",
        name: "Fiqh Ringkas",
        type: "feature",
        featureKey: "fiqh",
        deepLink: "thullaabulilmi://belajar/fiqh",
        assertTexts: ["Fiqh"],
    },
    {
        id: "feature-manasik",
        name: "Manasik Haji & Umrah",
        type: "feature",
        featureKey: "manasik",
        deepLink: "thullaabulilmi://belajar/manasik",
        assertTexts: ["Manasik"],
    },
    {
        id: "feature-community-feed",
        name: "Feed Komunitas",
        type: "feature",
        featureKey: "community-feed",
        deepLink: "thullaabulilmi://belajar/community-feed",
        assertTexts: ["Komunitas"],
    },
    {
        id: "feature-komunitas",
        name: "Obrolan Komunitas",
        type: "feature",
        featureKey: "komunitas",
        deepLink: "thullaabulilmi://belajar/komunitas",
        assertTexts: ["Komunitas"],
    },
    {
        id: "feature-kajian",
        name: "Kajian",
        type: "feature",
        featureKey: "kajian",
        deepLink: "thullaabulilmi://belajar/kajian",
        assertTexts: ["Kajian"],
    },
    {
        id: "feature-lessons",
        name: "Modul & Kelas",
        type: "feature",
        featureKey: "lessons",
        deepLink: "thullaabulilmi://belajar/lessons",
        assertTexts: ["Wudhu"],
    },
    {
        id: "feature-library",
        name: "Perpustakaan Kitab",
        type: "feature",
        featureKey: "library",
        deepLink: "thullaabulilmi://belajar/library",
        assertTexts: ["Perpustakaan"],
    },
    {
        id: "feature-blog",
        name: "Artikel & Blog",
        type: "feature",
        featureKey: "blog",
        deepLink: "thullaabulilmi://belajar/blog",
        assertTexts: ["Artikel"],
    },
    {
        id: "feature-perawi",
        name: "Perawi Hadis",
        type: "feature",
        featureKey: "perawi",
        deepLink: "thullaabulilmi://belajar/perawi",
        actions: [
            { type: "tap", text: "Bagan" },
            { type: "wait", ms: 400 },
            { type: "tap", text: "Daftar" },
            { type: "wait", ms: 400 },
            { type: "tap", text: "web-app-perawi-tabaqah-sahabat", attr: "resource-id" },
            { type: "wait", ms: 400 },
            { type: "tap", text: "web-app-perawi-tabaqah-tabiin", attr: "resource-id" },
            { type: "wait", ms: 400 },
            { type: "tap", text: "web-app-perawi-tabaqah-all", attr: "resource-id" },
            { type: "wait", ms: 400 },
            { type: "tap", text: "web-app-perawi-card", attr: "resource-id" },
            { type: "wait", ms: 500 },
            { type: "key", keycode: 4 },
            { type: "wait", ms: 400 },
        ],
        assertTexts: ["Perawi", "Daftar", "Bagan"],
    },
    {
        id: "feature-jarh-tadil",
        name: "Jarh wa Ta'dil",
        type: "feature",
        featureKey: "jarh-tadil",
        deepLink: "thullaabulilmi://belajar/jarh-tadil",
        assertTexts: ["Jarh"],
    },
    {
        id: "feature-forum",
        name: "Forum Tanya Jawab",
        type: "feature",
        featureKey: "forum",
        deepLink: "thullaabulilmi://belajar/forum",
        assertTexts: ["Forum"],
    },
    {
        id: "feature-kamus",
        name: "Kamus Arab-Indonesia",
        type: "feature",
        featureKey: "kamus",
        deepLink: "thullaabulilmi://belajar/kamus",
        actions: [
            { type: "type", placeholder: "Cari kata Arab", text: "iman" },
            { type: "wait", ms: 800 },
        ],
        assertTexts: ["Kamus", "إيمان"],
    },
    {
        id: "feature-quiz",
        name: "Quiz Islami",
        type: "feature",
        featureKey: "quiz",
        deepLink: "thullaabulilmi://belajar/quiz",
        actions: [
            { type: "swipe", x1: 540, y1: 1400, x2: 540, y2: 600, duration: 250 },
            { type: "swipe", x1: 540, y1: 600, x2: 540, y2: 1400, duration: 250 },
        ],
        assertTexts: ["Quiz"],
    },
    {
        id: "feature-hijri",
        name: "Kalender Hijri",
        type: "feature",
        featureKey: "hijri",
        deepLink: "thullaabulilmi://belajar/hijri",
        assertTexts: ["Hijri"],
    },
    {
        id: "feature-imsakiyah",
        name: "Jadwal Imsakiyah",
        type: "feature",
        featureKey: "imsakiyah",
        deepLink: "thullaabulilmi://belajar/imsakiyah",
        assertTexts: ["Imsak"],
    },
    {
        id: "feature-tasbih",
        name: "Tasbih Digital",
        type: "feature",
        featureKey: "tasbih",
        deepLink: "thullaabulilmi://belajar/tasbih",
        actions: [
            { type: "wait", ms: 800 },
            { type: "tap", text: "web-app-tasbih-counter", attr: "resource-id", fast: true },
            { type: "tap", text: "web-app-tasbih-counter", attr: "resource-id", fast: true },
            { type: "tap", text: "web-app-tasbih-counter", attr: "resource-id", fast: true },
            { type: "tap", text: "Reset" },
            { type: "tap", text: "Getar: On" },
        ],
        assertTexts: ["Tasbih", "Subhanallah", "/ 33"],
    },
    {
        id: "feature-faraidh",
        name: "Kalkulator Faraidh Waris",
        type: "feature",
        featureKey: "faraidh",
        deepLink: "thullaabulilmi://belajar/faraidh",
        assertTexts: ["Faraidh", "Waris"],
    },
    {
        id: "feature-sholat-tracker",
        name: "Sholat Tracker",
        type: "feature",
        featureKey: "sholat-tracker",
        deepLink: "thullaabulilmi://belajar/sholat-tracker",
        actions: [
            { type: "tap", text: "Subuh" },
            { type: "wait", ms: 300 },
            { type: "tap", text: "Dzuhur" },
            { type: "wait", ms: 300 },
            { type: "tap", text: "Ashar" },
            { type: "wait", ms: 300 },
            { type: "tap", text: "Maghrib" },
            { type: "wait", ms: 300 },
            { type: "tap", text: "Isya" },
            { type: "wait", ms: 300 },
            { type: "swipe", x1: 540, y1: 1500, x2: 540, y2: 600, duration: 250 },
            { type: "swipe", x1: 540, y1: 600, x2: 540, y2: 1500, duration: 250 },
        ],
        assertTexts: ["Sholat", "Subuh", "Dzuhur", "Ashar", "Maghrib", "Isya"],
    },
    {
        id: "feature-bookmarks",
        name: "Bookmark Tersimpan",
        type: "feature",
        featureKey: "bookmarks",
        deepLink: "thullaabulilmi://belajar/bookmarks",
        assertTexts: ["Bookmark"],
    },
    {
        id: "feature-notes",
        name: "Catatan Pribadi",
        type: "feature",
        featureKey: "notes",
        deepLink: "thullaabulilmi://belajar/notes",
        assertTexts: ["Catatan"],
    },
    {
        id: "feature-notifications",
        name: "Pusat Notifikasi",
        type: "feature",
        featureKey: "notifications",
        deepLink: "thullaabulilmi://belajar/notifications",
        assertTexts: ["Notifikasi"],
    },
    {
        id: "feature-goals",
        name: "Target Belajar",
        type: "feature",
        featureKey: "goals",
        deepLink: "thullaabulilmi://belajar/goals",
        assertTexts: ["Target"],
    },
    {
        id: "feature-muhasabah",
        name: "Jurnal Muhasabah",
        type: "feature",
        featureKey: "muhasabah",
        deepLink: "thullaabulilmi://belajar/muhasabah",
        assertTexts: ["Muhasabah"],
    },
    {
        id: "feature-hafalan",
        name: "Progress Hafalan",
        type: "feature",
        featureKey: "hafalan",
        deepLink: "thullaabulilmi://belajar/hafalan",
        assertTexts: ["Hafalan"],
    },
    {
        id: "feature-murojaah",
        name: "Jadwal Murojaah",
        type: "feature",
        featureKey: "murojaah",
        deepLink: "thullaabulilmi://belajar/murojaah",
        assertTexts: ["Murojaah"],
    },
    {
        id: "feature-tilawah",
        name: "Log Tilawah",
        type: "feature",
        featureKey: "tilawah",
        deepLink: "thullaabulilmi://belajar/tilawah",
        assertTexts: ["Tilawah"],
    },
    {
        id: "feature-stats",
        name: "Statistik Belajar",
        type: "feature",
        featureKey: "stats",
        deepLink: "thullaabulilmi://belajar/stats",
        assertTexts: ["Statistik"],
    },
    {
        id: "feature-leaderboard",
        name: "Leaderboard Streak",
        type: "feature",
        featureKey: "leaderboard",
        deepLink: "thullaabulilmi://belajar/leaderboard",
        assertTexts: ["Leaderboard"],
    },
];

module.exports = { testCases };
